### ISSUE TITLE
feat(security): add default Content-Security-Policy

### ISSUE THREAD

**Issue by Manouchehri** [langfuse/langfuse#1018]
### Describe the bug

Would it be possible to set a default `Content-Security-Policy`? :) 

### To reproduce

N/A

**Comment by marcklingen** [comment]
Great suggestion, apparently easy to add ([docs](https://nextjs.org/docs/pages/building-your-application/configuring/content-security-policy#without-nonces)). I'll give this a try and check whether there are unexpected consequences
