### ISSUE TITLE
bug: `Expires` doesn't actually delete files off S3

### ISSUE THREAD

**Issue by Manouchehri** [langfuse/langfuse#1046]
### Describe the bug

The `Expires` header in S3's PutObject is meant to indicate to clients (e.g. Chrome) when the file should no longer be cached.

https://github.com/langfuse/langfuse/blob/b86eab9e04e9039160ac0fe34d7a712060fdcd38/src/server/api/routers/generations.ts#L479

https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html#API_PutObject_RequestSyntax

If you want to auto-delete the files, setting up a lifecycle rule on the bucket is the correct solution. Personally, I do _not_ want langfuse to automatically attempt to modify lifecycle rules; if the bucket gets too big, I'll enable that myself. =) 

### To reproduce

N/A

**Comment by Manouchehri** [comment]
I would recommend doing this:

```
Expires: new Date(31536000),
CacheControl: "immutable, max-age=31536000, s-maxage=31536000"
```

This enables caching for up to a year (the max of what many clients and proxies support).

**Comment by marcklingen** [comment]
Agree, will remove this. For Langfuse Cloud we also use lifecycle rules to make this a temporary bucket.
