### ISSUE TITLE
[LF-657] feat: POST Completion request to langfuse

### ISSUE THREAD

**Issue by ishaan-jaff** [langfuse/langfuse#105]
### Describe the feature you'd like to request

I'm trying to make a callback to send data to langfuse. C
This will allow me to use langfuse with other tools like promptlayer, helicone etc 

### Describe the solution you'd like to see

Can you expose an API endpoint that allows me to pass langfuse the ChatCompletion() kwargs, response etc ? 

<sub>[LF-657](https://linear.app/langfuse/issue/LF-657/feat-post-completion-request-to-langfuse)</sub>

**Comment by ishaan-jaff** [comment]
I want to use the OpenAI sdk for my completion call and then post the input/output to langfuse. Looked at the docs and it seems like I can't do that :https://langfuse.com/docs/integrations/api 

let me know if i missed something

**Comment by ishaan-jaff** [comment]
makes sense so I need to use this code snippet to post data to langfuse ? 
```

from datetime import datetime
from langfuse.model import InitialGeneration, Usage
 
generationStartTime = datetime.now()
 
# call to an LLM API
 
langfuse.generation(InitialGeneration(
    name="summary-generation",
    startTime=generationStartTime,
    endTime=datetime.now(),
    model="gpt-3.5-turbo",
    modelParameters={"maxTokens": "1000", "temperature": "0.9"},
    prompt=[{"role": "system", "content": "You are a helpful assistant."}, {"role": "user", "content": "Please generate a summary of the following documents \nThe engineering department defined the following OKR goals...\nThe marketing department defined the following OKR goals..."}],
    completion="The Q3 OKRs contain goals for multiple teams...",
    usage=Usage(promptTokens=50, completionTokens = 49),
    metadata={"interface": "whatsapp"}
))
```

**Comment by marcklingen** [comment]
@MasterPtatoknerrichmckenzie is this done? please comment and close

**Comment by maxdeichmann** [comment]
> makes sense so I need to use this code snippet to post data to langfuse ?
> 
> ```
> 
> from datetime import datetime
> from langfuse.model import InitialGeneration, Usage
>  
> generationStartTime = datetime.now()
>  
> # call to an LLM API
>  
> langfuse.generation(InitialGeneration(
>     name="summary-generation",
>     startTime=generationStartTime,
>     endTime=datetime.now(),
>     model="gpt-3.5-turbo",
>     modelParameters={"maxTokens": "1000", "temperature": "0.9"},
>     prompt=[{"role": "system", "content": "You are a helpful assistant."}, {"role": "user", "content": "Please generate a summary of the following documents \nThe engineering department defined the following OKR goals...\nThe marketing department defined the following OKR goals..."}],
>     completion="The Q3 OKRs contain goals for multiple teams...",
>     usage=Usage(promptTokens=50, completionTokens = 49),
>     metadata={"interface": "whatsapp"}
> ))
> ```

Exactly :) If you have further questions, feel free to open an issue or reach out on Discord: https://langfuse.com/discord
