### ISSUE TITLE
feat(docker): set cache-control headers on `_next/static/*`

### ISSUE THREAD

**Issue by Manouchehri** [langfuse/langfuse#1056]
### Describe the bug

Our auto-scaling of Langfuse is based on CPU/memory load, _and_ incoming requests. Because visiting the Langfuse web UI (understandably) causes a lot of requests for JS, CSS, and HTML resources, we end up accidentally spinning up like 4-5 containers every day for a few seconds just to load the web interface. =P

This should be pretty easy to improve  by adjusting the Cache-Control header on `/_next/static/*`. Everything in that folder is hashed (e.g. `/_next/static/chunks/1501-4cd7e1308f7fc8a4.js`), so it's safe to cache forever.

I'd recommend setting these headers on `/_next/static/*`:

```
Cache-Control: public, immutable, max-age=31536000, s-maxage=31536000
Expires: Fri, 31 Dec 9999 23:59:59 GMT
```

I see you are already doing this on `https://cloud.langfuse.com/_next/static/*`. =) 

### To reproduce

N/A

### Additional information

Similar ish to #1023.

**Comment by marcklingen** [comment]
Thanks for the suggestion, open for PRs on this.

Context
- The Langfuse UI is a NextJS project exporting to static files using `export`, docs here: https://nextjs.org/docs/pages/building-your-application/deploying/static-exports
- next.config.js might be the right place to configure the headers, but testing is needed to verify that this actually also applies the headers to static files served by the nodejs server (dockerized): https://nextjs.org/docs/pages/api-reference/next-config-js/headers

**Comment by Manouchehri** [comment]
After looking at this more, I think it was our cache configuration on Cloudflare that was incorrect configured. I do see `public, max-age=31536000, immutable` now.

**Comment by marcklingen** [comment]
> After looking at this more, I think it was our cache configuration on Cloudflare that was incorrectly configured. I do see `public, max-age=31536000, immutable` now.

perfect, thanks for confirming

**Comment by Manouchehri** [comment]
Sorry about that!

**Comment by marcklingen** [comment]
no worries
