### ISSUE TITLE
bug: The LLM call will be recorded without model name

### ISSUE THREAD

**Issue by mdavidkeyrus** [langfuse/langfuse#1069]
### Describe the bug

LlamaCpp not have model or model_name attributes.
Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name. 

### To reproduce

```
# Initialize Langfuse handler
from langfuse.callback import CallbackHandler
handler = CallbackHandler("YOUR KEY", "YOUR KEY")

from os.path import expanduser
from os.path import expanduser

# Importation des éléments de langchain_community
from langchain_community.llms import LlamaCpp

# Importation des éléments de langchain_experimental
from langchain_experimental.chat_models import Llama2Chat

# Importations supplémentaires de langchain (ajuster selon les noms exacts)
from langchain.chains import LLMChain
from langchain.memory import ConversationBufferMemory

from langchain.prompts.chat import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    MessagesPlaceholder,
)
from langchain.schema import SystemMessage

template_messages = [
    SystemMessage(content="You are a helpful assistant."),
    MessagesPlaceholder(variable_name="chat_history"),
    HumanMessagePromptTemplate.from_template("{text}"),
]
prompt_template = ChatPromptTemplate.from_messages(template_messages)



model_path = expanduser(llama-2-7b-chat.Q2_K.gguf")

llm = LlamaCpp(
    model_path=model_path,
    streaming=False,
)
model = Llama2Chat(llm=llm)

memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)
chain = LLMChain(llm=model, prompt=prompt_template, memory=memory, callbacks=[handler])

print(
    chain.run(
        text="What can I see in Vienna? Propose a few locations. Names only, no details.",
        callbacks=[handler]
    )
)

print(chain.run(text="Tell me more about #2.", callbacks=[handler]))
```

### Additional information

WARNING:langfuse:Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name. Please create an issue so we can fix your integration: https://github.com/langfuse/langfuse/issues/new/choose
ERROR:langfuse:2 validation errors for SdkLogEvent
timestamp
  str type expected (type=type_error.str)
body
  field required (type=value_error.missing)
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/langchain/lib/python3.10/site-packages/langfuse/callback.py", line 680, in __on_llm_action
    self._report_error(
  File "/home/user/anaconda3/envs/langchain/lib/python3.10/site-packages/langfuse/callback.py", line 818, in _report_error
    event = SdkLogEvent(id=str(uuid4()), data=error, timestamp=_get_timestamp())
  File "/home/user/anaconda3/envs/langchain/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 2 validation errors for SdkLogEvent
timestamp
  str type expected (type=type_error.str)
body
  field required (type=value_error.missing)

**Comment by omarcevi** [comment]
Hello, i have solved the issue regarding detecting and parsing llamacpp in langfuse and i would like to contribute with a PR if possible. :)

**Comment by aiseei** [comment]
Hi @omarcevi!
Thats great - could you explain how you did it? Having the same issue. 

Thanks!

**Comment by marcklingen** [comment]
> Hi @omarcevi! Thats great - could you explain how you did it? Having the same issue.
> 
> Thanks!

which model is not detected? Please raise a new issue for this, we'd love to get this fixed
