### ISSUE TITLE
feat(python-sdk): support for custom httpx.client

### ISSUE THREAD

**Issue by brandonkzw** [langfuse/langfuse#1072]
### Discussed in https://github.com/orgs/langfuse/discussions/1071

<div type='discussions-op-text'>

<sup>Originally posted by **brandonkzw** February  5, 2024</sup>
Current version of Langfuse Python SDK (2.7.6) does not support custom httpx.client, i.e. for developers that are dealing with self-signed certificate, this may cause an issue for https connection.

Will be creating a PR for this feat.</div>

Implemented in Fork and Commit https://github.com/brandonkzw/langfuse-python/commit/053a07ffc60e5cda6d999ff7902feb348a17ea52

**Comment by brandonkzw** [comment]
Created PR https://github.com/langfuse/langfuse-python/pull/329

**Comment by maxdeichmann** [comment]
@brandonkzw thanks a lot for the contribution. I just merged this.

**Comment by brandonkzw** [comment]
@maxdeichmann my pleasure, found a bug while looking through the pytests.  This should fix the task_manager test failure

Fix available here https://github.com/langfuse/langfuse-python/commit/bd746b193bf1ad820966124d0bf9186c8620ffd5

**Comment by marcklingen** [comment]
> @maxdeichmann my pleasure, found a bug while looking through the pytests. This should fix the task_manager test failure
> 
> Fix available here [langfuse/langfuse-python@bd746b1](https://github.com/langfuse/langfuse-python/commit/bd746b193bf1ad820966124d0bf9186c8620ffd5)

awesome, can you create a PR for this?

**Comment by marcklingen** [comment]
Let's get this and https://github.com/langfuse/langfuse-python/pull/330 in before the release
