### ISSUE TITLE
feat: delete prompt versions

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#1079]
Add delete to prompt versions and prompts

Considerations:
- cascade to generations if they are linked to prompt
- warning as application could depend on prompt, alert() is enough for v1

**Comment by khareyash05** [comment]
Hey @marcklingen Just a doubt, I am confused as to what path should be followed if a prompt version is being used in production is about to be deleted. Here are 2 things we can do.
1. Migrate the production prompt implicitly to the below version
2. Ask user implicitly to select another prompt to be shifted to production

Or maybe some another methods. I think second option will be better as of now. As first option is an overwhelming issue in itself and will require close monitoring. WDYT?

**Comment by marcklingen** [comment]
I'd simplify this to show a warning no matter whether it is a production prompt or not. A prompt can also be pinned by version and thus lead to consequences when deleted.
