### ISSUE TITLE
feat(auth): post-login redirect to initial url

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#1093]
Deeplinks to traces are a popular feature. Currently if a user is unauthenticated, the deep link does not work as expected as it is not persisted when redirecting an unauthed user to the login page (see layout.tsx).

Steps

- [ ] Add target url to auth page as url param in redirect (layout.tsx)
- [ ] Persist target url while signing in (managed by AuthJS/NextAuth)
- [ ] Add e2e test for this behavior (playwright)

**Comment by Dharshan-K** [comment]
Hi @marcklingen, Can I take this issue?

**Comment by marcklingen** [comment]
Sure, assigning it to you. Let me know if you have questions, hope the notes make sense.

**Comment by Dharshan-K** [comment]
Hi @marcklingen, Can you provide me an example of Deeplink to traces.

**Comment by marcklingen** [comment]
Generally, these can be any links that get redirected to the authentication page within layout.tsx

**Comment by Dharshan-K** [comment]
Hi @marcklingen, after ```npm db:migrate``` why dummy data is not appearing in UI. I have persisted the URL but without trace data the page directly goes to the project main page after sign-in.
![Screenshot from 2024-02-15 22-42-26](https://github.com/langfuse/langfuse/assets/76818013/e6e39d69-80c3-44b7-8588-ad847dbf7cd6)

**Comment by marcklingen** [comment]
Please read the contributing.md for information on how to run the seeder

**Comment by Dharshan-K** [comment]
I saw demo login in the db with username: Demo User emailId: demo@langfuse.com. Do I need to login with the demo user to access the dummy data? if that's the case, the password for the demo user is not in the docs? could you provide the password for the demo account?

**Comment by khareyash05** [comment]
> I saw demo login in the db with username: Demo User emailId: [demo@langfuse.com](mailto:demo@langfuse.com). Do I need to login with the demo user to access the dummy data? if that's the case, the password for the demo user is not in the docs? could you provide the password for the demo account?

Hey @Dharshan-K  Please go through the contributing docs again! the email will be `demo@langfuse.com` and the password will be `password`. Seeding is designed to work only on the demo id. Try logging the same. If any queries I can help out. Reach out to me on discord.
Also lets not clutter the issue here. Instead use the discord channel mentioned. Thanks
