### ISSUE TITLE
bug: Hosted version fails when submitting feedback

### ISSUE THREAD

**Issue by aablsk** [langfuse/langfuse#1144]
### Describe the bug

The self-hosted version fails to submit feedback with a 400 HTTP error.

### To reproduce

1. Setup self-hosted langfuse 
2. Sign up on the web interface
3. Create a project
4. Click on Feedback button
5. Fill in text in feedback box
6. Click 'Submit'

Observed behavior:
- `{}` below the input box turns red
- request fails with `Failed to load resource: the server responded with a status of 400 ()` to `cloud.langfuse.com/api/feedback`

Expected behavior:
- feedback is submitted successfully

**Comment by marcklingen** [comment]
Thank you for reporting this! I have fixed it and will release the fix in a few minutes.

**Comment by aablsk** [comment]
That was lightning fast ⚡ Thank you, Marc! 🙇

**Comment by marcklingen** [comment]
Super curious to get your feedback :) This is the most important api endpoint 🙏
