### ISSUE TITLE
bug: No number_of_consumers in Langfuse Constructor

### ISSUE THREAD

**Issue by jatin1760** [langfuse/langfuse#1155]
### Describe the bug

Error occurred while connecting to Langfuse Server. Error: Langfuse.__init__() got an unexpected keyword argument 'number_of_consumers'

### To reproduce

langfuse = Langfuse(number_of_consumers=1)

# Ref: https://langfuse.com/docs/sdk/python

### Additional information

I've used langfuse==2.11.0 (client) and latest containers as well.

I think that "number_of_consumers" should be "threads", as per the constructor of Langfuse

**Comment by marcklingen** [comment]
Thanks for reporting, just fixed this in https://github.com/langfuse/langfuse-docs/commit/72f03e7b30e9d421a88c067e69158371c6048bb2
