### ISSUE TITLE
bug: Latency, usage, and cost not shown for historical generations

### ISSUE THREAD

**Issue by Stadly** [langfuse/langfuse#1188]
### Describe the bug

When ingesting generations from the past (I'm migrating data from PromptLayer to Langfuse), the latency, usage, and cost is not shown correctly in the traces overview. It seems like the data is correctly shown for generations that are less than 14 days old, but not older ones:

![image](https://github.com/langfuse/langfuse/assets/7263579/ec014626-ad1c-4ed8-bc6c-c550a74088e4)

When looking at the trace details, however, the data is correctly shown:
![image](https://github.com/langfuse/langfuse/assets/7263579/42d5fa9d-2e79-4f86-813d-90bb9d8d887f)
![image](https://github.com/langfuse/langfuse/assets/7263579/e7696a74-925d-4aab-95f6-77eec67316f2)

### To reproduce

```ts
langfuse.generation({
  input: "a",
  output: "b",
  startTime: new Date(2024, 1, 2, 0, 0, 0),
  endTime: new Date(2024, 1, 2, 0, 0, 5),
  model: "gpt-4",
  name: "Generation 2024-02-02",
});

langfuse.generation({
  input: "a",
  output: "b",
  startTime: new Date(2024, 1, 3, 0, 0, 0),
  endTime: new Date(2024, 1, 3, 0, 0, 5),
  model: "gpt-4",
  name: "Generation 2024-02-03",
});
```

**Comment by marcklingen** [comment]
Thanks for sharing, have not encountered this issue before. Are you self-hosting Langfuse? If yes, are you on the latest version?

**Comment by Stadly** [comment]
Self-hosting, yes. I was on version 2.3.0. I've now updated to version 2.5.1. The behavior is the same.

**Comment by Stadly** [comment]
I think I know the reason! By default, the filter is set to only fetch traces for the two last weeks. The traces get timestamped today, so they are fetched. But the generations that are older than that are not fetched, and hence there is no data for calculating latency, usage, and cost.

I have not tested this, but it seems plausible.

Maybe a solution is to fetch all data related to the traces? The filter should apply to the traces, not the data related to a trace.

**Comment by Stadly** [comment]
Because I was ingesting historical data. With the new `trace.timestamp` it shouldn't be much of an issue anymore.

**Comment by marcklingen** [comment]
Perfect, thanks for confirming that trace.timestamp has solved this for you. If you are on Langfuse Cloud and want me to batch-delete some traces, ping me: marc at langfuse com
