### ISSUE TITLE
bug: Impossible to select input and output text in trace

### ISSUE THREAD

**Issue by Stadly** [langfuse/langfuse#1189]
### Describe the bug

When the text is long, it is expanded/collapsed when clicked. This makes it impossible to make selections.

![Untitled video - Made with Clipchamp](https://github.com/langfuse/langfuse/assets/7263579/c2e578ca-a3a5-4fb2-8c9b-ee774a86bdae)

### To reproduce

Drag to make a selection. When you release the mouse button, the text expands/collapses and the selection is cleared.

**Comment by marcklingen** [comment]
Thanks for reporting this, just created an issue to discuss with the maintainer of the json editor that we used here whether this is something we can add upstream or override in Langfuse

**Comment by marcklingen** [comment]
Just released the fix for this yesterday: https://github.com/langfuse/langfuse/releases/tag/v2.7.2
