### ISSUE TITLE
Langfuse was not able to parse the LLM model. 

### ISSUE THREAD

**Issue by clarkebishop** [langfuse/langfuse#1197]
Got the following message:

WARNING langfuse: Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name. Please create an issue so we can fix your integration:

I'm using LangChain with LangGraph. Basically, my code looks like the following. There are multiple LLM calls and each points to the LangFuse callback handler.

local_llm = "mistral:latest"

llm = ChatOllama(model=local_llm, temperature=0)

# Chain
rag_chain = prompt | llm | StrOutputParser()

**Comment by marcklingen** [comment]
Thanks for reporting this!

**Comment by aldrinjenson** [comment]
Hi, 

Is there any further update on this? 🤞 

I'm facing the same issue with mistral model in ChatOllama

**Comment by Fares-Tabet** [comment]
Getting the same issue with langchain and  Anthropic models (ChatAnthropic) :

```
errors
    model_name = _extract_model_name(serialized, **kwargs)
...
Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name.
```

**Comment by marcklingen** [comment]
are you on the latest sdk version? if yes, please open a new issue for this
