### ISSUE TITLE
potential bug or miss use of langfuse documentation: impossible to show input/output in the main Trace 

### ISSUE THREAD

**Issue by Frikha1S** [langfuse/langfuse#1200]
### Describe the bug

Hello it was imposible for us to show input/output in the main trace, we tried with conversationalChain and with LCEL chain you can see the screenshots for both methods and the issue behind : 
![image](https://github.com/langfuse/langfuse/assets/160147389/2a7ce389-7138-4fd1-b9f4-1f34be450717)
![image](https://github.com/langfuse/langfuse/assets/160147389/0a35ffa8-2683-476c-9ef8-293b5cfa6fab)

### To reproduce

#For conversational chain : code snippet :  
result = chain(
            {
                "question": question.content,
                "chat_history": chat_history,
            } ,callbacks=[handler]
        )
# For LCEL runnable chains : 
rag_chain_1 = rag_chain_1 = (
            _inputs_1 | retriever| answer
        )
result = rag_chain_1.invoke(
            inputs, config={"callbacks": [ConsoleCallbackHandler(), handler]}

**Comment by destri84** [comment]
same issue here, please help

**Comment by Frikha1S** [comment]
issue solved after updating langfuse to 2.14.0 version
