### ISSUE TITLE
bug: cannot bump langfuse-python with recent python version

### ISSUE THREAD

**Issue by backmask** [langfuse/langfuse#1222]
### Describe the bug

Langfuse-python recently constrainted the python version to be <3.12 (change made in https://github.com/langfuse/langfuse-python/pull/384). It makes langfuse-python incompatible with the latest version (3.12.2)

I am not sure if the constraint is warranted, so maybe it can be relaxed. If it cannot, bear in mind that some users may be unable to use the latest features 😊

### To reproduce

Try to install langfuse-python with python 3.12.2
```
The current project's supported Python range (>=3.12.1,<3.13.0) is not compatible with some of the required packages Python requirement:
  - langfuse requires Python >=3.8.1,<3.12, so it will not be satisfied for Python >=3.12.1,<3.13.0
```

**Comment by maxdeichmann** [comment]
@backmask thanks for raising this! I will have this fixed asap.

**Comment by maxdeichmann** [comment]
@backmask i just fixed this (here)[https://github.com/langfuse/langfuse-python/releases/tag/v2.15.1]. Let me know, if you run into issues.

**Comment by backmask** [comment]
I confirm the fix is working. Thanks!
