### ISSUE TITLE
bug: npm script for `infra:dev:up` and `infra:dev:down` 

### ISSUE THREAD

**Issue by khareyash05** [langfuse/langfuse#1243]
### Describe the bug

the npm commands for infra dev up and down needs a refactoring 
Ex - `docker-compose -f ./docker-compose.dev.yml up -d` instead of `../docker-compose.dev.yml up -d`

### To reproduce

`npm run infra:dev:up`

**Comment by marcklingen** [comment]
thx for spotting this, we are currently making some migrations to the structure of the repo, @maxdeichmann will fix this

**Comment by maxdeichmann** [comment]
Thanks, fixing it here: https://github.com/langfuse/langfuse/pull/1251
