### ISSUE TITLE
bug: An empty trace is created during file upload operation (embedding + indexing) due to usage of threads 

### ISSUE THREAD

**Issue by jatin1760** [langfuse/langfuse#1270]
### Describe the bug

 
  An empty trace is created during file upload operation (embedding + indexing) due to the usage of threads.
  No issue found, if no thread is used.

### To reproduce

1. Set the threads to 4
    langfuse = Langfuse(threads=4)
2. Perform a file upload operation
    Use PyPDFLoader => RecursiveCharacterTextSplitter => embedding operation => create indexes using FAISS and save it
 3. An empty trace is generated in langfuse in addition to a trace where the above whole operation is captured.

**Comment by marcklingen** [comment]
Hi @jatin1760, which integration do you use?

**Comment by marcklingen** [comment]
Would love to help here or fix this, can you share more details?

**Comment by jatin1760** [comment]
Sure...Thanks for helping

1. We have deployed a server where the langfuse containers are running using podman
2. We have another server where our api container is running which also consists of the langfuse client so as to push data to the langfuse server
3. In out API container, we are using FastAPI, wher one of the api is upload_doc api.
    Here, set the threads to 4 e.g. langfuse = Langfuse(threads=4)
    Here, you can upload a pdf file and use the below flow
    Use PyPDFLoader => RecursiveCharacterTextSplitter => embedding operation => create indexes using FAISS and save it
4. An empty trace is generated in langfuse in addition to a trace where the above whole operation is captured.
5. Used below versions in the API Container
   fastAPI  == 0.98.0
   openai == 1.12.0
   uvicorn == 0.22.0
   langchain == 0.1.2
   faiss-cpu == 1.7.4
   PyPDF2==3.0.1
   pypdf==4.0.0
   langfuse==2.0.1
   langchain-openai==0.0.3
   langchain-community==0.0.14

**Comment by jatin1760** [comment]
Hi @marcklingen, 

Thank you for resolving our issues/doubts related to Langfuse.

Can you please help with the below doubts as well.

A) With ref to the architecture we are using (mentioned in the above comment), I also wanted to ask you another query regarding our api server going down.
   In some of the events/span for input/output, a large amount of data was getting streamed to Langfuse Server from our api server, due to which our api server was down with the below logs.
   
   Logs:
   connectionpool.py connectionpool 292 DEBUG 01/30/2024 03:40:37 PM Resetting dropped connection: 172.27.220.83
   connectionpool.py connectionpool 546 DEBUG 01/30/2024 03:40:37 PM http://172.27.220.83:4000 "POST /api/public/ingestion HTTP/1.1" 207 204

   Note: Here, langfuse server is deployed at 172.27.220.83:4000
   
   Temporarily, we have truncated the data being sent to Langfuse Server.
   
   Can you please suggest anything to resolve this?
   
B) In our api, we are using the below steps:
   Step1: Create a langfuse obj and then create a trace obj from it.
   Step2: Bussiness Logic i.e. any LLM call or document embedding etc and update the trace as well 
   Step3: Use langfuse.flush()
   Step4: Send the API Response
   
   Need your suggestions/views for Step3 i.e. using langfuse.flush() before sending the API Response.

**Comment by marcklingen** [comment]
Let's have a look at this together: https://cal.com/marc-kl/15

**Comment by marcklingen** [comment]
closing this for now, feel free to reopen in case upgrading the container and sdks has not fixed this
