### ISSUE TITLE
bug: Package dependency incompatibilities

### ISSUE THREAD

**Issue by pamelafox** [langfuse/langfuse#1285]
### Describe the bug

Getting pip incompatibility errors when installing langfuse into my project:

langfuse 2.18.2 requires httpx<0.26.0,>=0.15.4, but you have httpx 0.27.0 which is incompatible.
langfuse 2.18.2 requires wrapt==1.14, but you have wrapt 1.16.0 which is incompatible.

2.18.2 is the latest on pypi, so I think we're up to date with your releases:
https://pypi.org/project/langfuse/

### To reproduce

Install in https://github.com/Azure-Samples/azure-search-openai-demo/ alongside app/backend/requirements.txt

**Comment by marcklingen** [comment]
thanks for reporting, we'll look into this

**Comment by maxdeichmann** [comment]
@pamelafox thanks for raising this. We just fixed it here: https://github.com/langfuse/langfuse-python/releases/tag/v2.18.3

Let me know if you run into any issues :)
