### ISSUE TITLE
bug: CallbackHandler.get_langchain_run_name() now returns the last character of the name

### ISSUE THREAD

**Issue by sammypbaird** [langfuse/langfuse#1292]
### Describe the bug

Looks like this was a simple mistake made when refactoring the code. This bug was introduced in version 2.11.0.

This commit introduced the bug: https://github.com/langfuse/langfuse-python/commit/bc63674f576bd8b36691d146a74e9ccc1be07671
See line 205.

It changed from:
`serialized.get("name", serialized.get("id", ["<unknown>"])[-1])`

to:
`serialized.get("name", serialized.get("id", ["<unknown>"]))[-1]`

The result is instead of returning a name like "AzureChatOpenAI", it now returns a name of "I"

### To reproduce

The serialized dict needs to have a name on it to exercise this bug.

**Comment by sammypbaird** [comment]
![image](https://github.com/langfuse/langfuse/assets/24234787/af11e272-a254-47b1-91a3-520501449799)
Notice that the generations only have a single letter for their name

**Comment by maxdeichmann** [comment]
@sammypbaird thanks for raising this! Which python sdk version are you using? I fixed this [here](https://github.com/langfuse/langfuse-python/commit/112168daafb3160cb7035f6d78077168df95b994)

If you upgrade to the latest version, this should be fixed.
