### ISSUE TITLE
bug: AsyncAzureOpenAI does not exist for early version of OpenAI

### ISSUE THREAD

**Issue by yzliao-zip** [langfuse/langfuse#1318]
### Describe the bug

The python sdk imports `AsyncAzureOpenAI`, which is not available for the early version of OpenAI Python SDK (e.g., pre 1.0 versions).

### To reproduce

1. `pip install openai==0.28.1`
2. `pip install langfuse`
3. login into python shell and run `from langfuse.openai import openai`. The error is `ImportError: cannot import name 'AsyncAzureOpenAI' from 'openai'`

**Comment by maxdeichmann** [comment]
Hi @yzliao-zip thanks for raising this. We are looking into this.

**Comment by marcklingen** [comment]
Thanks for reporting, this is a regression introduced by a recent change. We have drafted a fix and will merge soon when having tested it
https://github.com/langfuse/langfuse-python/pull/483

**Comment by maxdeichmann** [comment]
@yzliao-zip we just released a fix for this: https://github.com/langfuse/langfuse-python/releases/tag/v2.20.3

Let me know, if this works for you.
