### ISSUE TITLE
bug: trace table does not load in case of large inputs/outputs

### ISSUE THREAD

**Issue by arvinxx** [langfuse/langfuse#1352]
### Describe the bug

<img width="1901" alt="image" src="https://github.com/langfuse/langfuse/assets/28616219/908a3dd3-73cb-4db3-8f50-d092f2071b75">

### To reproduce

You can dm me to add member to my project

**Comment by marcklingen** [comment]
We're working on a fix for this. This is related to comparatively large trace inputs/outputs.

In the meantime, you can just reduce the number of rows per page to be able to use the table.

**Comment by maxdeichmann** [comment]
@arvinxx thanks a lot for raising this. We just released a fix for this.
