### ISSUE TITLE
Support parsing LLM model for ChatOllama

### ISSUE THREAD

**Issue by kleebaum** [langfuse/langfuse#1377]
Thanks for the great product!

Currently, the model name is not recorded for ChatOllama models. Deserialization seems to be "not_implemented" yet. 
The error message is: Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name.

Could you please **support parsing the LLM model for ChatOllama or Ollama**?

![grafik](https://github.com/langfuse/langfuse/assets/5443645/5e91f4a4-5407-43e1-8fa3-e248a66c477e)

Thank you!

**Comment by marcklingen** [comment]
Thanks for the ping on this, we'll ping you once we get to adding chatollama. Open for PR on this in case you want to contribute

**Comment by marcklingen** [comment]
To verify, do you use langchain python?

**Comment by Dev-Khant** [comment]
Hi @marcklingen I would like to get started on this. Could you briefly guide me on how can I start with integrating Ollama or ChatOllama?

**Comment by marcklingen** [comment]
> Hi @marcklingen I would like to get started on this. Could you briefly guide me on how can I start with integrating Ollama or ChatOllama?

You could add it here, but you'd need to test this extensively locally: https://github.com/langfuse/langfuse-python/blob/ed36978beee8278d80cabaefe73c68ff2bbbe0c6/langfuse/extract_model.py

we're looking into solutions to solve this problem in a more generic way

**Comment by Dev-Khant** [comment]
> > Hi @marcklingen I would like to get started on this. Could you briefly guide me on how can I start with integrating Ollama or ChatOllama?
> 
> You could add it here, but you'd need to test this extensively locally: https://github.com/langfuse/langfuse-python/blob/ed36978beee8278d80cabaefe73c68ff2bbbe0c6/langfuse/extract_model.py
> 
> we're looking into solutions to solve this problem in a more generic way

Alright I'll make changes there and test out locally.

**Comment by marcklingen** [comment]
As stated above, we aim for a generalizable solution. Follow #1920 to understand more of the context and get updates on this. I'm sorry for the inconvenience. Please reopen in case this throws an exception instead of just logging a warning in your case.
