### ISSUE TITLE
bug: Unable to parse the LLM model (Anthropic + Langchain).

### ISSUE THREAD

**Issue by dee-walia20** [langfuse/langfuse#1424]
### Langfuse was not able to parse the LLM model (Anthropic + Langchain).

**Token usage is not getting recorded with Langchain + Anthropic Models.**

Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name. Please create an issue so we can fix your integration: https://github.com/langfuse/langfuse/issues/new/choose
ERROR:langfuse:'token_usage'
Traceback (most recent call last):
  File "c:\Users\deewa\anaconda3\envs\myenv\lib\site-packages\langfuse\callback\langchain.py", line 676, in on_llm_end
    or not response.llm_output["token_usage"]
KeyError: 'token_usage'

### To reproduce

```python
from dotenv import load_dotenv
import os
from langchain_anthropic import ChatAnthropic
from langfuse.callback import CallbackHandler
from langchain_core.prompts import ChatPromptTemplate
load_dotenv()

anthropic_key = os.getenv("ANTHROPIC_KEY")
langfuse_secret_key = os.getenv("LANGFUSE_SECRET_KEY")
langfuse_public_key = os.getenv("LANGFUSE_PUBLIC_KEY")

chat = ChatAnthropic(model="claude-3-sonnet-20240229", anthropic_api_key=anthropic_key, temperature=0.1)
langfuse_handler = CallbackHandler(
    public_key=langfuse_public_key,
    secret_key=langfuse_secret_key,
    host="https://cloud.langfuse.com"
)

system = (
    "You are a helpful assistant that translates {input_language} to {output_language}."
)
human = "{text}"
prompt = ChatPromptTemplate.from_messages([("system", system), ("human", human)])

chain = prompt | chat
chain.invoke(
    {
        "input_language": "English",
        "output_language": "Korean",
        "text": "I love Python"
    }, 
    config={"callbacks":[langfuse_handler]}
)
```

**Comment by maxdeichmann** [comment]
@dee-walia20 thanks for raising this. I just published a fix here: https://github.com/langfuse/langfuse-python/releases/tag/v2.20.4 

Feel free to re-open if the issue persists.
