### ISSUE TITLE
bug: mistral-AI cost and tokens usage not displayed

### ISSUE THREAD

**Issue by mogupta** [langfuse/langfuse#1430]
### Describe the bug

mistral-AI cost and tokens usage not displayed

### To reproduce

I used Flowise's Mistral AI node to run

**Comment by marcklingen** [comment]
Mistral models can be run on many different infrastructure providers, thus there is no one pricing to support in Langfuse. When token counts are collected by the integration, you can define the pricing model for your mistral usage in the `models` tab to get USD costs in Langfuse: https://langfuse.com/docs/model-usage-and-cost#custom-model-definitions

**Comment by marcklingen** [comment]
Good question here though, are tokens tracked? If not, token usage tracking could be extended to Mistral models

**Comment by mogupta** [comment]
No, tokens are not tracked
