### ISSUE TITLE
bug: Langfuse was not able to parse the LLM model (BedrockChat, anthropic.claude-3-sonnet-20240229-v1:0)

### ISSUE THREAD

**Issue by rpgeddam** [langfuse/langfuse#1464]
### Describe the bug

> Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name. Please create an issue so we can fix your integration: https://github.com/langfuse/langfuse/issues/new/choose

### To reproduce

```
from langchain_community.chat_models import BedrockChat

llm = BedrockChat(
            streaming=True,
            client=bedrock_client,
            model_id="anthropic.claude-3-sonnet-20240229-v1:0",
        )
```

**Comment by maxdeichmann** [comment]
Hi @rpgeddam thanks for reporting this. We will look into this. Which Langchain + Langfuse versions are you using?

**Comment by rpgeddam** [comment]
```
langchain = "0.1.12"
langchain-community = "^0.0.28"
langfuse = "^2.21.0"
```

**Comment by joshmcqueen** [comment]
I'm seeing the same issue.  However, I'm using a Flowise chatflow with Langfuse enabled. 

<img width="1418" alt="image" src="https://github.com/langfuse/langfuse/assets/10521798/bb07f45a-bca5-4682-842d-9921910767f5">

All the other providers I tested work fine (OpenAI, Anthropic, Ollama) -- it's just the Bedrock ones that aren't coming back 

<img width="486" alt="image" src="https://github.com/langfuse/langfuse/assets/10521798/2e0f3585-282a-4f9d-9765-d6d8ccd305da">

**Comment by aunitt** [comment]
I'm also seeing the same issue with Bedrock models (which had been working in the past for me).

I'm currently using:
```
langchain==0.1.16
langchain_community==0.0.34
langchain_core==0.1.45
langfuse==2.27.0
```

I believe it was working with:
```
langchain==0.1.14
langchain_community==0.0.31
langchain_core==0.1.39
langfuse==2.21.3
```

**Comment by marcklingen** [comment]
We aim for a generalizable solution here. Follow #1920 to understand more of the context and get updates on this. I'm sorry for the inconvenience. Please reopen in case this throws an exception instead of just logging a warning in your case.

**Comment by maxdeichmann** [comment]
@aunitt, @joshmcqueen, @rpgeddam: I just released a fix for this. Please re-open if this persists for you: https://github.com/langfuse/langfuse-python/releases/tag/v2.29.1

**Comment by marcklingen** [comment]
> Man, langchain does not like to make things easy huh. Thanks for the fix @maxdeichmann !

Thanks @rpgeddam! All frameworks move fast and break interfaces every now and then. @maxdeichmann luckily is quite good at keeping up with the changes :)
