### ISSUE TITLE
bug:  can't connect to SMTP - `SMTP_CONNECTION_URL` cannot handle special chars (limitation of connection string)

### ISSUE THREAD

**Issue by zoltan-fedor** [langfuse/langfuse#1517]
### Describe the bug

There was a PR merged recently to introduce the `SMTP_CONNECTION_URL` as a replacement for the configuration object-based authentication for SMTP.

The problem is that the connection string does NOT work when the connection string contains special chars (like #, + , \, etc), which are typical in auto-generated SMTP service user passwords.

As such, now there is no option to use SMTP for those needing to authenticate against an SMTP server and their password includes any of those special chars.

See below about how the owners of the `nodemailer` package recommend the use of the configuration object instead of the connection string for special chars: https://github.com/nodemailer/nodemailer/issues/1332

The connection url parsing happens at https://github.com/langfuse/langfuse/pull/574/files#diff-e3dc7edb613d7623d9e870267bab78170c6951e6dc98114ca3d2bba4621f8481R18

### To reproduce

Try out an  `SMTP_CONNECTION_URL`  value with a special char, like `smtps://no-reply@ciao.in:Gitw50#2@cloud.ciao.it?pool=true`

### Additional information

In general the use of connection urls are NOT a full replacement for object based connection, they are almost always introduce some limitations, so in general it is not recommended to solely rely on connection urls.

**Comment by marcklingen** [comment]
docs: https://nodemailer.com/extras/smtp-connection/

Thanks for raising this, what's your suggested fix, does a stringified `options` object work as an alternative env?

**Comment by zoltan-fedor** [comment]
Yes, I think that could work, as long as the stringification can handle all special chars (sorry, I am not a node.js developer, but a Python one, so not quite sure how that might work in node.js)
.
Also that stringification of the `options` should allow getting the whole string or parts of that string from a secrets store (as the SMTP password will need to be considered a protected resource). But that is likely solve-able as long as that stringified `options` can be provided from either as an env or a startup param to the app (sorry, not sure what other options are available to provide the stringified `options` to the app in node.js).

**Comment by zoltan-fedor** [comment]
Sorry, Just read the https://nodemailer.com/extras/smtp-connection/ more closely.
It seems the `options` does not include the username and the password, so it doesn't solve the root of the problem - that these usernames and password can contain special characters - ones that cannot be used in the a connection url string.

As such it seems the stringified `options` from https://nodemailer.com/extras/smtp-connection/ will not solve this, as it does not allow us to supply the SMTP username and the password.

**Comment by zoltan-fedor** [comment]
Actually I have figured out that if you url-encode the username and the password, then `nodemailer` will handle it right!

Closing this ticket

**Comment by marcklingen** [comment]
awesome, thanks for sharing

**Comment by guillaumemeyer** [comment]
I know this issue is closed @zoltan-fedor . But as a good practice, using multiple environment variables instead of one single connection string is more reliable and less prone to errors. The same applies to `DATABASE_URL` I guess.
Having to pre-url-encode environment variables is problematic in some DevOps environments.

**Comment by marcklingen** [comment]
@guillaumemeyer, agree, open for contributions on this!

We already added this for `DATABASE_URL` ([docs](https://langfuse.com/docs/deployment/self-host#configuring-environment-variables))
> Instead of DATABASE_URL, you can also use DATABASE_HOST, DATABASE_USERNAME, DATABASE_PASSWORD and DATABASE_NAME.
