### ISSUE TITLE
bug: Scores section broken after upgrade to 2.14.x

### ISSUE THREAD

**Issue by fgiuba** [langfuse/langfuse#1529]
### Describe the bug

After updating to 2.14.1 (same for 2.14.4), I see an error when I try to open the  `score` section:
Application error: a client-side exception has occurred (see the browser console for more information).

### To reproduce

- Upgraded from 2.11.3 to 2.14.1
- Open `scores` section

### Additional information

Console logs:
![Screenshot from 2024-03-28 13-02-48](https://github.com/langfuse/langfuse/assets/17831955/058fae18-6564-4a54-88b0-b3c00ea9175d)

**Comment by marcklingen** [comment]
Thanks for reporting. @maxdeichmann is working on a fix

**Comment by maxdeichmann** [comment]
@fgiuba pushing a release right now which resolves the issue. Let me know if this persists.

**Comment by fgiuba** [comment]
@maxdeichmann it works. Thank you for the (really!) quick fix.

**Comment by maxdeichmann** [comment]
Thanks for the feedback :)
