### ISSUE TITLE
feat: Disable user sign up based on environment variable

### ISSUE THREAD

**Issue by molntamas** [langfuse/langfuse#153]
### Describe the feature you'd like to request

I would like to self host langfuse in the cloud on a public URL and limit who can log in to langfuse.
Currently if the system/URL is public, anybody could sign up and log in.

### Describe the solution you'd like to see

I'm not sure what a good solution would be for this.

An example solution I can think off:
- having a setting to disable sign up

Then first I would deploy while sign up is enabled and create an account. 
Then I disable sign up and deploy again

Usage:
```
docker run --name langfuse \
-e DATABASE_URL=...
...
SIGN_UP_DISABLED=TRUE
ghcr.io/langfuse/langfuse:latest
```

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
Agree @molntamas, that would be useful.

Thoughts on implementation:
- Add optional environment flag `SIGN_UP_DISABLED=TRUE`
- If enabled
  - Hide link to signup on login page
  - Block user creation in `/src/features/auth/lib/emailPassword.ts`

**Comment by marcklingen** [comment]
@molntamas done, use `NEXT_PUBLIC_SIGN_UP_DISABLED=true`
