### ISSUE TITLE
Trace input is null when passing in nodes, or Documents with transformations to VectorStoreIndex constructor

### ISSUE THREAD

**Issue by mwertheim-zco** [langfuse/langfuse#1551]
### Discussed in https://github.com/orgs/langfuse/discussions/1538

<div type='discussions-op-text'>

<sup>Originally posted by **mwertheim-zco** March 28, 2024</sup>
I am creating an instance of llama_index VectoreStoreIndex using the class method `from_documents`. 
If I pass in a list of Documents, the trace appears normal with input showing document metadata.
If I pass in a list of TextNodes, or a list of Documents with a list of transformations (to produce text nodes inside the constructor) the input shows null.
Is this normal and expected behavior?
langfuse v2.21.1
python v3.10.13
llama-index v0.10.20

works as intended, showing screenshot below as result
`

          langfuse_callback_handler = LlamaIndexCallbackHandler()
                  langfuse_callback_handler.set_trace_params(
                      name= 'foo',
                      user_id='bar',
                  )
           Settings.callback_manager = CallbackManager([langfuse_callback_handler])
           Settings.llm = OpenAIEmbedding(model=LLM_MODEL)
          vector_store = WeaviateVectorStore(
                      weaviate_client=weaviate_client,
                      index_name="Document",
                      text_key='content'
                  )
          storage_context = StorageContext.from_defaults(vector_store=vector_store)
          VectorStoreIndex.from_documents(
                      documents=documents,
                      storage_context=storage_context, 
                      show_progress=True
                  )
`

This is the trace using a list of Documents and no transformations. It appears detailed.
<img width="1297" alt="Screenshot 2024-03-28 at 6 22 28 PM" src="https://github.com/langfuse/langfuse/assets/147201130/81a6ae80-660f-4fee-9e07-f0b86b28aa75">

Shows input: null and produces screenshot below

`

          langfuse_callback_handler = LlamaIndexCallbackHandler()
                  langfuse_callback_handler.set_trace_params(
                      name= 'foo',
                      user_id='bar',
                  )
           Settings.callback_manager = CallbackManager([langfuse_callback_handler])
           Settings.llm = OpenAIEmbedding(model=LLM_MODEL)
          vector_store = WeaviateVectorStore(
                      weaviate_client=weaviate_client,
                      index_name="Document",
                      text_key='content'
                  )
          storage_context = StorageContext.from_defaults(vector_store=vector_store)
          nodes=run_llama_index_ingestion_pipeline(documents)
          VectorStoreIndex(
                      nodes=nodes,
                      storage_context=storage_context, 
                      show_progress=True
                  )

           [OR]

          transformers=get_transform_components()

          VectorStoreIndex.from_documents(
            documents=documents,
            storage_context=storage_context, 
            show_progress=True,
            transformations=transformers
        )
`

This is the trace using either a list of Nodes OR a list of Documents AND a list of transformations.
<img width="1318" alt="Screenshot 2024-03-28 at 6 23 06 PM" src="https://github.com/langfuse/langfuse/assets/147201130/e2d56038-84e8-4914-93b3-702dac71adf3">

</div>

**Comment by mwertheim-zco** [comment]
I was able to get more data in `Input` by changing this: 
`langfuse_callback_handler = LlamaIndexCallbackHandler()
              langfuse_callback_handler.set_trace_params(
                  name= 'foo',
                  user_id='bar',
              )
       Settings.callback_manager = CallbackManager([langfuse_callback_handler])`


to this:

`langfuse_callback_handler = langfuse_context.get_current_llama_index_handler()
        langfuse_context.update_current_trace(
            name= 'foo',
            user_id='bar',
        )
        Settings.callback_manager = CallbackManager([langfuse_callback_handler])`

![image](https://github.com/langfuse/langfuse/assets/147201130/49950815-3984-4099-a772-8f57da18aebe)


I'm happy with this solution. However, if you feel the original code should work then feel free to keep the issue open. Thanks!

**Comment by marcklingen** [comment]
Thanks for the update @mwertheim-zco! Much appreciated as we'll get to this soon

**Comment by hassiebp** [comment]
We have just shipped a major improvement to the LlamaIndex instrumentation integration that should address your issue. Please upgrade and check out our docs in how to enable the integration via the `LlamaIndexInstrumentor` and let us know your feedback here! 🙏🏾 

- [Release](https://github.com/langfuse/langfuse-python/releases/tag/v2.52.0)
- [Docs](https://langfuse.com/docs/integrations/llama-index/get-started#beta-observability-based-on-llamaindex-instrumentation-module)
- [Cookbook](https://langfuse.com/docs/integrations/llama-index/example-python-instrumentation-module)
