### ISSUE TITLE
bug: import issue when using pydantic v1.10.15, AttributeError: module 'pydantic.v1' has no attribute 'json'

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#1581]
### Describe the bug

When I need to use pydantic@1 due to other dependencies, the latest update (v1.10.15) leads to the following issue:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-2-612513d4cfc7>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from langfuse import Langfuse

8 frames
[/usr/local/lib/python3.10/dist-packages/langfuse/api/core/jsonable_encoder.py](https://localhost:8080/#) in <module>
     40 
     41 encoders_by_class_tuples = generate_encoders_by_class_tuples(
---> 42     pydantic.json.ENCODERS_BY_TYPE
     43 )
     44 

AttributeError: module 'pydantic.v1' has no attribute 'json'
```

### To reproduce

```
pip install pydantic==1.10.15 langfuse
```

```python
from langfuse import Langfuse
```

### Additional information

Issue can be fixed until upstream fix is available by pinning the previous version: `pip install pydantic==1.10.14 langfuse`

**Comment by ishaan-jaff** [comment]
Is there a fix for this? Trying to pin to `pydantic==1.10.14` and seeing if that fixes it

**Comment by liamvdv** [comment]
+1

**Comment by clemra** [comment]
Thanks, both. You can fix it for now by pinning the previous version: pip install pydantic==1.10.14 langfuse

We'll update you here in a bit!

**Comment by maxdeichmann** [comment]
Hi all, i just published a fix here: https://github.com/langfuse/langfuse-python/releases/tag/v2.21.3

Please let me know if the issue persists.
