### ISSUE TITLE
feat(scores): Add a score value filter to api

### ISSUE THREAD

**Issue by Hacky-DH** [langfuse/langfuse#1614]
### Discussed in https://github.com/orgs/langfuse/discussions/1613

<div type='discussions-op-text'>

<sup>Originally posted by **Hacky-DH** April  8, 2024</sup>
### Describe the feature or potential improvement

I add a score value filter with two params to api/public/scores?operator=&value=

`operator` supports [">", "<", ">=", "<=", "!=", "="]

### Additional information

_No response_</div>

**Comment by marcklingen** [comment]
sounds good to me! Important here is that the `operator` and `value` are validated (zod input schema is enough) to make sure that no unsafe sql is executed.

**Comment by Hacky-DH** [comment]
@marcklingen Yes, I check them. So I will pull request later, please review.

**Comment by Hacky-DH** [comment]
@marcklingen I pull a request https://github.com/langfuse/langfuse/pull/1655
