### ISSUE TITLE
bug: wrong redirect after signing up (local install)

### ISSUE THREAD

**Issue by lightningRalf** [langfuse/langfuse#1618]
### Describe the bug

After I signed up. I got redirected to localhost:3000 instead of localhost:3100

### To reproduce

fresh install. (from within superagent) 
docker compose up -d
in browser: localhost:3100
sign up for new account
redirected to localhost:3000

**Comment by marcklingen** [comment]
Thanks for reporting this, added a pr to superagent which should fix this issue

**Comment by marcklingen** [comment]
Did you use the template .env for langfuse?

**Comment by lightningRalf** [comment]
There was an .env.example that I copied as per their instructions:
https://docs.superagent.sh/overview/logging/langfuse

**Comment by marcklingen** [comment]
Ok thanks for confirming, make sure to use port 3100 as NEXTAUTH_URL. I created a PR to fix the template within the superagent repo

**Comment by marcklingen** [comment]
What fixed this issue for you?

**Comment by marcklingen** [comment]
Did changing the .env to point to 3100 fix this for you?
