### ISSUE TITLE
bug: current batch size limiting of python SDK does not work in all cases, http 413 (request entity too large) api response

### ISSUE THREAD

**Issue by abhimasand** [langfuse/langfuse#1631]
### Describe the bug

Giving up execute_task_with_backoff(...) after 3 tries (langfuse.request.APIError: <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
 (413): None)
ERROR:backoff:Giving up execute_task_with_backoff(...) after 3 tries (langfuse.request.APIError: <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
 (413): None)
ERROR:langfuse:error uploading: <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
 (413): None
Traceback (most recent call last):
  File "/Users/abhimasand/miniconda3/lib/python3.11/site-packages/langfuse/request.py", line 103, in _process_response
    payload = res.json()
              ^^^^^^^^^^
  File "/Users/abhimasand/miniconda3/lib/python3.11/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abhimasand/miniconda3/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abhimasand/miniconda3/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abhimasand/miniconda3/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### To reproduce

I have a singular rag chain with query reformulation, decomposition into n queries, separate retrieval for each of those, and reranking and using top-k to generate an answer. I believe because of this singular large chain, it is giving this request entity too large. 

However, I don't return more than 10 documents in each query, a total of around 30k tokens probably, I don't know if that should trigger this error, and what I can do to mitigate it. 

I'm using langchain-specific handler directly with LCEL so I don't know how can I even control how much data am I sending to langfuse to avoid this error.

**Comment by marcklingen** [comment]
Sorry for the inconvenience here. Can you add a code example which helps to reproduce this issue?

**Comment by fhrzn** [comment]
hey, any update on this? I got the same issue recently

**Comment by marcklingen** [comment]
> hey, any update on this? I got the same issue recently

can you share an example to reproduce this issue?

**Comment by marcklingen** [comment]
related to #1676

**Comment by maxdeichmann** [comment]
@abhimasand are you self-hosting langfuse or are you using our cloud product?

**Comment by abhimasand** [comment]
I'm self hosting it on kubernetes

**Comment by abhimasand** [comment]
I wasn't able to make a reproducible code, since  the request too large is dependent on the amount of data coming in from the vector store

**Comment by maxdeichmann** [comment]
Ok, are you somehow using nginx in kubernetes? I fear that nginx denied the request (https://docs.nginx.com/nginx-management-suite/acm/how-to/policies/request-body-size-limit/#about-the-policy)

We allow bodies of up to 2.5 mb: https://github.com/langfuse/langfuse-python/blob/fbd04266a9de6d936af6f82d268cf0c5c31f226b/langfuse/task_manager.py#L34

Can you try to configure nginx to make that work?

**Comment by maxdeichmann** [comment]
@fhrzn are you self-hosting as well?
