### ISSUE TITLE
bug: Langfuse run not found in on_chain_ned with LangChain AgentExecutor

### ISSUE THREAD

**Issue by slassau** [langfuse/langfuse#1658]
### Describe the bug

I am using Langfuse to monitor a LangChain AgentExecutor using AzureOpenAI model.
An error catch and logged by `langfuse.callback.CallbackHandler.on_chain_end`:

```
ERROR:langfuse:run not found
Traceback (most recent call last):
  File ".../lib/python3.12/site-packages/langfuse/callback/langchain.py", line 323, in on_chain_end
    raise Exception("run not found")
Exception: run not found
```

I expect the handler to not raise an error and have knowledge of the current `run_id`.

### To reproduce

Minimal example:

```python
import os

import langfuse.callback

from langchain.agents import AgentExecutor, create_react_agent
from langchain.prompts import PromptTemplate
from langchain.tools import tool
from langchain_openai import AzureChatOpenAI


os.environ["OPENAI_API_VERSION"] = "2023-12-01-preview"
os.environ["AZURE_OPENAI_ENDPOINT"] = "..."
os.environ["AZURE_OPENAI_API_KEY"] = "..."

prompt = PromptTemplate.from_template("""
Answer the following questions as best you can. You have access to the following tools:

{tools}

Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [{tool_names}]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can repeat N times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question

Begin!

Question: {input}
Thought:{agent_scratchpad}
""")

langfuse_callback = langfuse.callback.CallbackHandler()

llm = AzureChatOpenAI(
    azure_deployment= "gpt35",
    model_name= "gpt-35-turbo",
)

@tool
def get_word_length(word: str) -> int:
    """Returns the length of a word."""
    return len(word)

tools = [get_word_length]
agent = create_react_agent(llm, tools, prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

agent_executor.invoke({"input": "what is the length of the word LangFuse?"}, config={"callbacks": [langfuse_callback]})
```

### Additional information

This issues occurs only on newer version of langfuse `>=2.22.0`. No error is raised on python-langfuse `2.21.x`.
Maybe introduced by langfuse/langfuse-python@752e40c993168b2255532670042e932784544459?

I don't have the issue when using the LLM directly. This only seems to be a problem for AgentExecutor.

Weirdly enough, I didn't saw any differences in the traces (on Langfuse interface) when running the example two version of Langfuse (one with the error and one without)

LangChain version details:

| Packages | Version |
| -- | -- |
| langchain | 0.1.14 |
| langchain-community | 0.0.31 |
| langchain-core | 0.1.37 |
| langchain-openai | 0.0.8 |

**Comment by marcklingen** [comment]
Thanks for reporting and the steps to reproduce, we'll have a look as this is clearly a regression added by the change that was necessary to enable async/batch

**Comment by marcklingen** [comment]
This was released here: https://github.com/langfuse/langfuse-python/releases/tag/v2.25.0

Let us know if it does not work as expected 🙏

**Comment by ret2libc** [comment]
Even with 2.26.3 i'm still receiving a very similar error with the react-based prompt.

```
Traceback (most recent call last):
  File "/.venv/lib/python3.10/site-packages/langfuse/callback/langchain.py", line 522, in on_tool_end
    raise Exception("run not found")
Exception: run not found
Traceback (most recent call last):
  File "/.venv/lib/python3.10/site-packages/langchain/agents/agent.py", line 1166, in _iter_next_step
    output = self.agent.plan(
  File "/.venv/lib/python3.10/site-packages/langchain/agents/agent.py", line 397, in plan
    for chunk in self.runnable.stream(inputs, config={"callbacks": callbacks}):
  File "/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2875, in stream
    yield from self.transform(iter([input]), config, **kwargs)
  File "/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2862, in transform
    yield from self._transform_stream_with_config(
  File "/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1880, in _transform_stream_with_config
    chunk: Output = context.run(next, iterator)  # type: ignore
  File "/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2826, in _transform
    for output in final_pipeline:
  File "/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1300, in transform
    yield from self.stream(final, config, **kwargs)
  File "/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 808, in stream
    yield self.invoke(input, config, **kwargs)
  File "/.venv/lib/python3.10/site-packages/langchain_core/output_parsers/base.py", line 169, in invoke
    return self._call_with_config(
  File "/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1625, in _call_with_config
    context.run(
  File "/.venv/lib/python3.10/site-packages/langchain_core/runnables/config.py", line 347, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
  File "/.venv/lib/python3.10/site-packages/langchain_core/output_parsers/base.py", line 170, in <lambda>
    lambda inner_input: self.parse_result(
  File "/.venv/lib/python3.10/site-packages/langchain_core/output_parsers/base.py", line 221, in parse_result
    return self.parse(result[0].text)
  File "/.venv/lib/python3.10/site-packages/langchain/agents/output_parsers/react_single_input.py", line 75, in parse
    raise OutputParserException(
langchain_core.exceptions.OutputParserException: Could not parse LLM output: `I'm sorry, but I can't assist with this request.`

```

**Comment by marcklingen** [comment]
> Even with 2.26.3 i'm still receiving a very similar error with the react-based prompt.
> 
> ```
> Traceback (most recent call last):
>   File "/.venv/lib/python3.10/site-packages/langfuse/callback/langchain.py", line 522, in on_tool_end
>     raise Exception("run not found")
> Exception: run not found
> Traceback (most recent call last):
>   File "/.venv/lib/python3.10/site-packages/langchain/agents/agent.py", line 1166, in _iter_next_step
>     output = self.agent.plan(
>   File "/.venv/lib/python3.10/site-packages/langchain/agents/agent.py", line 397, in plan
>     for chunk in self.runnable.stream(inputs, config={"callbacks": callbacks}):
>   File "/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2875, in stream
>     yield from self.transform(iter([input]), config, **kwargs)
>   File "/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2862, in transform
>     yield from self._transform_stream_with_config(
>   File "/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1880, in _transform_stream_with_config
>     chunk: Output = context.run(next, iterator)  # type: ignore
>   File "/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2826, in _transform
>     for output in final_pipeline:
>   File "/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1300, in transform
>     yield from self.stream(final, config, **kwargs)
>   File "/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 808, in stream
>     yield self.invoke(input, config, **kwargs)
>   File "/.venv/lib/python3.10/site-packages/langchain_core/output_parsers/base.py", line 169, in invoke
>     return self._call_with_config(
>   File "/.venv/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1625, in _call_with_config
>     context.run(
>   File "/.venv/lib/python3.10/site-packages/langchain_core/runnables/config.py", line 347, in call_func_with_variable_args
>     return func(input, **kwargs)  # type: ignore[call-arg]
>   File "/.venv/lib/python3.10/site-packages/langchain_core/output_parsers/base.py", line 170, in <lambda>
>     lambda inner_input: self.parse_result(
>   File "/.venv/lib/python3.10/site-packages/langchain_core/output_parsers/base.py", line 221, in parse_result
>     return self.parse(result[0].text)
>   File "/.venv/lib/python3.10/site-packages/langchain/agents/output_parsers/react_single_input.py", line 75, in parse
>     raise OutputParserException(
> langchain_core.exceptions.OutputParserException: Could not parse LLM output: `I'm sorry, but I can't assist with this request.`
> ```

do you pass the handler to the invoke/ainvoke? can you share code to reproduce this issue?

**Comment by ret2libc** [comment]
@marcklingen sorry for the delay. Here's a reproducer:
```python
import os

import langfuse.callback

from langchain.agents import AgentExecutor, create_react_agent
from langchain.prompts import PromptTemplate
from langchain_core.runnables import RunnableConfig, RunnablePassthrough
from langchain.tools import tool
from langchain_openai import ChatOpenAI


prompt = PromptTemplate.from_template("""
Answer the following questions as best you can. You have access to the following tools:

{tools}

Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [{tool_names}]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can repeat N times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question

Begin!

Question: {input}
Thought:{agent_scratchpad}
""")

langfuse_callback = langfuse.callback.CallbackHandler()

llm = ChatOpenAI(
    model_name= "gpt-4-turbo",
)

@tool
def get_word_length(word: str) -> int:
    """Returns the length of a word."""
    return len(word)

tools = [get_word_length]
agent = create_react_agent(llm, tools, prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

agent_executor = agent_executor.with_config(RunnableConfig(callbacks=[langfuse_callback]))

# This works well
# agent_executor.invoke({"input": "what is the length of the word LangFuse?"})

# This generates a lot of 'run not found' exceptions, but the program still works
chain = {"input": RunnablePassthrough()} | agent_executor
print(chain.invoke("what is the length of the word LangFuse?"))

# This just works, no problems
prompt = PromptTemplate.from_template("My name is {name}, ciao!")
chain = {"name": RunnablePassthrough()} | prompt | llm
print(chain.invoke("Riccardo"))
```

**Comment by Altaf-Axway** [comment]
Hello All,

We are currently facing some similar issue, We are using langfuse 2.33.0 version 

Chat bot code



```python
from langchain_elasticsearch import ElasticsearchStore
from langfuse.callback import CallbackHandler
from langfuse.decorators import langfuse_context, observe
from llm_integrations import get_llm
from elasticsearch_client import (
    elasticsearch_client,
    get_elasticsearch_chat_message_history,
)
from flask import render_template, stream_with_context, current_app
import json
import os


INDEX = os.getenv("ES_INDEX", "workplace-app-docs")
INDEX_CHAT_HISTORY = os.getenv(
    "ES_INDEX_CHAT_HISTORY", "workplace-app-docs-chat-history"
)
ELSER_MODEL = os.getenv("ELSER_MODEL", ".elser_model_2")
SESSION_ID_TAG = "[SESSION_ID]"
SOURCE_TAG = "[SOURCE]"
DONE_TAG = "[DONE]"

store = ElasticsearchStore(
    es_connection=elasticsearch_client,
    index_name=INDEX,
    strategy=ElasticsearchStore.SparseVectorRetrievalStrategy(model_id=ELSER_MODEL),
)


@stream_with_context
@observe()
def ask_question(question, session_id):
    yield f"data: {SESSION_ID_TAG} {session_id}\n\n"
    current_app.logger.debug("Chat session ID: %s", session_id)
    
    #langfuse_context.get_current_langchain_handler()

    langfuse_context.update_current_trace(
        name="test1",
        session_id=session_id,
    )
    #langfuse_context.get_current_langchain_handler()
    langfuse_handler = langfuse_context.get_current_langchain_handler()
    langfuse_handler = CallbackHandler(
    public_key="<pub_key>",
    secret_key="<secret_key>",
    host="https://cloud.langfuse.com",
    session_id=session_id
    )
    
    # langfuse_context.get_current_langchain_handler()

    chat_history = get_elasticsearch_chat_message_history(
        INDEX_CHAT_HISTORY, session_id
    )

    if len(chat_history.messages) > 0:
        # create a condensed question
        condense_question_prompt = render_template(
            "condense_question_prompt.txt",
            question=question,
            chat_history=chat_history.messages,
        )
        condensed_question = get_llm().invoke(condense_question_prompt, config={"callbacks": [langfuse_handler]}).content
    else:
        condensed_question = question

    current_app.logger.debug("Condensed question: %s", condensed_question)
    current_app.logger.debug("Question: %s", question)

    docs = store.as_retriever().invoke(condensed_question, config={"callbacks": [langfuse_handler]})
    for doc in docs:
        doc_source = {**doc.metadata, "page_content": doc.page_content}
        current_app.logger.debug(
            "Retrieved document passage from: %s", doc.metadata["name"]
        )
        yield f"data: {SOURCE_TAG} {json.dumps(doc_source)}\n\n"

    qa_prompt = render_template(
        "rag_prompt.txt",
        question=question,
        docs=docs,
        chat_history=chat_history.messages,
    )

    answer = ""
    for chunk in get_llm().stream(qa_prompt, config={"callbacks": [langfuse_handler]}):
        content = chunk.content.replace("\n\n", "\n").replace(
            "\n", " "
        )  # the stream can get messed up with newlines
        yield f"data: {content}\n\n"
        answer += chunk.content


    yield f"data: {DONE_TAG}\n\n"
    current_app.logger.debug("Answer: %s", answer)

    chat_history.add_user_message(question)
    chat_history.add_ai_message(answer)

``` 

in the console we see the below errors populating 

```
2024-05-25 18:35:19,765 WARNING werkzeug:  * Debugger is active!
2024-05-25 18:35:19,785 INFO werkzeug:  * Debugger PIN: 259-812-146
2024-05-25 18:35:19,893 INFO werkzeug: 127.0.0.1 - - [25/May/2024 18:35:19] "OPTIONS /api/chat HTTP/1.1" 200 -
2024-05-25 18:35:19,947 INFO werkzeug: 127.0.0.1 - - [25/May/2024 18:35:19] "POST /api/chat HTTP/1.1" 200 -
2024-05-25 18:35:19,947 DEBUG app: Chat session ID: 0e48b67c-33a7-4f55-8d30-2de8f47b80cd
/Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2024-05-25 18:35:21,554 DEBUG app: Condensed question: steps to create grafana alerts
2024-05-25 18:35:21,554 DEBUG app: Question: steps to create grafana alerts
2024-05-25 18:35:21,562 ERROR langfuse: parent run not found
Traceback (most recent call last):
  File "/Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 518, in on_retriever_start
    raise Exception("parent run not found")
Exception: parent run not found
/Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2024-05-25 18:35:21,861 ERROR langfuse: run not found
Traceback (most recent call last):
  File "/Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 544, in on_retriever_end
    raise Exception("run not found")
Exception: run not found
2024-05-25 18:35:21,862 DEBUG app: Retrieved document passage from: Steps to create grafana alerts
2024-05-25 18:35:21,862 DEBUG app: Retrieved document passage from: How to create Grafana Alerts for IICS team
2024-05-25 18:35:21,862 DEBUG app: Retrieved document passage from: What is Grafana Alerts
2024-05-25 18:35:21,862 DEBUG app: Retrieved document passage from: Grafana Overview
/Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2024-05-25 18:35:57,037 DEBUG app: Answer: To create Grafana alerts, follow these steps:

Step 1 - Create the CTP for observability team to create your team contact point and notification policy in Grafana.
Step 2 - Create a name and select a folder and group for the alert.
Step 3 - Add queries and expressions to evaluate, and then select the alert condition.
Step 4 - Define the alert condition, evaluation time, and Configure No data and error handling.
Step 5 - Add the details for your alert.
Step 6 - Validate you alert.

SOURCES: Steps to create grafana alerts, How to create Grafana Alerts for IICS team, What is Grafana Alerts, Grafana Overview
/Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2024-05-25 18:38:39,443 INFO werkzeug:  * Detected change in '/Users/ahossain/Desktop/WIP/elasticsearch-labs/example-apps/chatbot-rag-app/api/chat.py', reloading
2024-05-25 18:38:40,658 INFO werkzeug:  * Restarting with stat
``` 


Hence in the langfuse traces we don't see the tree structure for the trace with the name "test1" that we set in the context

**Comment by marcklingen** [comment]
> Hello All,
> 
> We are currently facing some similar issue, We are using langfuse 2.33.0 version
> 
> Chat bot code
> 
> ```python
> from langchain_elasticsearch import ElasticsearchStore
> from langfuse.callback import CallbackHandler
> from langfuse.decorators import langfuse_context, observe
> from llm_integrations import get_llm
> from elasticsearch_client import (
>     elasticsearch_client,
>     get_elasticsearch_chat_message_history,
> )
> from flask import render_template, stream_with_context, current_app
> import json
> import os
> 
> 
> INDEX = os.getenv("ES_INDEX", "workplace-app-docs")
> INDEX_CHAT_HISTORY = os.getenv(
>     "ES_INDEX_CHAT_HISTORY", "workplace-app-docs-chat-history"
> )
> ELSER_MODEL = os.getenv("ELSER_MODEL", ".elser_model_2")
> SESSION_ID_TAG = "[SESSION_ID]"
> SOURCE_TAG = "[SOURCE]"
> DONE_TAG = "[DONE]"
> 
> store = ElasticsearchStore(
>     es_connection=elasticsearch_client,
>     index_name=INDEX,
>     strategy=ElasticsearchStore.SparseVectorRetrievalStrategy(model_id=ELSER_MODEL),
> )
> 
> 
> @stream_with_context
> @observe()
> def ask_question(question, session_id):
>     yield f"data: {SESSION_ID_TAG} {session_id}\n\n"
>     current_app.logger.debug("Chat session ID: %s", session_id)
>     
>     #langfuse_context.get_current_langchain_handler()
> 
>     langfuse_context.update_current_trace(
>         name="test1",
>         session_id=session_id,
>     )
>     #langfuse_context.get_current_langchain_handler()
>     langfuse_handler = langfuse_context.get_current_langchain_handler()
>     langfuse_handler = CallbackHandler(
>     public_key="<pub_key>",
>     secret_key="<secret_key>",
>     host="https://cloud.langfuse.com",
>     session_id=session_id
>     )
>     
>     # langfuse_context.get_current_langchain_handler()
> 
>     chat_history = get_elasticsearch_chat_message_history(
>         INDEX_CHAT_HISTORY, session_id
>     )
> 
>     if len(chat_history.messages) > 0:
>         # create a condensed question
>         condense_question_prompt = render_template(
>             "condense_question_prompt.txt",
>             question=question,
>             chat_history=chat_history.messages,
>         )
>         condensed_question = get_llm().invoke(condense_question_prompt, config={"callbacks": [langfuse_handler]}).content
>     else:
>         condensed_question = question
> 
>     current_app.logger.debug("Condensed question: %s", condensed_question)
>     current_app.logger.debug("Question: %s", question)
> 
>     docs = store.as_retriever().invoke(condensed_question, config={"callbacks": [langfuse_handler]})
>     for doc in docs:
>         doc_source = {**doc.metadata, "page_content": doc.page_content}
>         current_app.logger.debug(
>             "Retrieved document passage from: %s", doc.metadata["name"]
>         )
>         yield f"data: {SOURCE_TAG} {json.dumps(doc_source)}\n\n"
> 
>     qa_prompt = render_template(
>         "rag_prompt.txt",
>         question=question,
>         docs=docs,
>         chat_history=chat_history.messages,
>     )
> 
>     answer = ""
>     for chunk in get_llm().stream(qa_prompt, config={"callbacks": [langfuse_handler]}):
>         content = chunk.content.replace("\n\n", "\n").replace(
>             "\n", " "
>         )  # the stream can get messed up with newlines
>         yield f"data: {content}\n\n"
>         answer += chunk.content
> 
> 
>     yield f"data: {DONE_TAG}\n\n"
>     current_app.logger.debug("Answer: %s", answer)
> 
>     chat_history.add_user_message(question)
>     chat_history.add_ai_message(answer)
> ```
> 
> in the console we see the below errors populating
> 
> ```
> 2024-05-25 18:35:19,765 WARNING werkzeug:  * Debugger is active!
> 2024-05-25 18:35:19,785 INFO werkzeug:  * Debugger PIN: 259-812-146
> 2024-05-25 18:35:19,893 INFO werkzeug: 127.0.0.1 - - [25/May/2024 18:35:19] "OPTIONS /api/chat HTTP/1.1" 200 -
> 2024-05-25 18:35:19,947 INFO werkzeug: 127.0.0.1 - - [25/May/2024 18:35:19] "POST /api/chat HTTP/1.1" 200 -
> 2024-05-25 18:35:19,947 DEBUG app: Chat session ID: 0e48b67c-33a7-4f55-8d30-2de8f47b80cd
> /Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
>   warnings.warn(
> /Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
>   warnings.warn(
> 2024-05-25 18:35:21,554 DEBUG app: Condensed question: steps to create grafana alerts
> 2024-05-25 18:35:21,554 DEBUG app: Question: steps to create grafana alerts
> 2024-05-25 18:35:21,562 ERROR langfuse: parent run not found
> Traceback (most recent call last):
>   File "/Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 518, in on_retriever_start
>     raise Exception("parent run not found")
> Exception: parent run not found
> /Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
>   warnings.warn(
> 2024-05-25 18:35:21,861 ERROR langfuse: run not found
> Traceback (most recent call last):
>   File "/Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 544, in on_retriever_end
>     raise Exception("run not found")
> Exception: run not found
> 2024-05-25 18:35:21,862 DEBUG app: Retrieved document passage from: Steps to create grafana alerts
> 2024-05-25 18:35:21,862 DEBUG app: Retrieved document passage from: How to create Grafana Alerts for IICS team
> 2024-05-25 18:35:21,862 DEBUG app: Retrieved document passage from: What is Grafana Alerts
> 2024-05-25 18:35:21,862 DEBUG app: Retrieved document passage from: Grafana Overview
> /Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
>   warnings.warn(
> 2024-05-25 18:35:57,037 DEBUG app: Answer: To create Grafana alerts, follow these steps:
> 
> Step 1 - Create the CTP for observability team to create your team contact point and notification policy in Grafana.
> Step 2 - Create a name and select a folder and group for the alert.
> Step 3 - Add queries and expressions to evaluate, and then select the alert condition.
> Step 4 - Define the alert condition, evaluation time, and Configure No data and error handling.
> Step 5 - Add the details for your alert.
> Step 6 - Validate you alert.
> 
> SOURCES: Steps to create grafana alerts, How to create Grafana Alerts for IICS team, What is Grafana Alerts, Grafana Overview
> /Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
>   warnings.warn(
> /Users/ahossain/Desktop/WIP/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
>   warnings.warn(
> 2024-05-25 18:38:39,443 INFO werkzeug:  * Detected change in '/Users/ahossain/Desktop/WIP/elasticsearch-labs/example-apps/chatbot-rag-app/api/chat.py', reloading
> 2024-05-25 18:38:40,658 INFO werkzeug:  * Restarting with stat
> ```
> 
> Hence in the langfuse traces we don't see the tree structure for the trace with the name "test1" that we set in the context

can you open a new issue for this?

**Comment by Altaf-Axway** [comment]
@marcklingen We have created the new issue for the same https://github.com/langfuse/langfuse/issues/2149

**Comment by marcklingen** [comment]
thanks

**Comment by jaiswalvineet** [comment]
I am still facing this issue with langfuse==2.45.0

`2024-09-12 20:39:05 - langfuse - ERROR - run not found
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 377, in on_chain_end
    raise Exception("run not found")
Exception: run not found
2024-09-12 20:39:05 - langfuse - ERROR - run not found
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 377, in on_chain_end
    raise Exception("run not found")`

**Comment by itsthisjustin** [comment]
Also getting the same error but traces show up fine in the dashboard

**Comment by marcklingen** [comment]
Are you on the latest langchain versions? the other issue mentions that this issue was fixed in langchain

**Comment by itsthisjustin** [comment]
I'm on the latest langfuse-aws which is what I'm using

**Comment by marcklingen** [comment]
@hassiebp any idea what might be happening here?

**Comment by steliyan-g** [comment]
I am also getting the below with:

> Run not found, see docs what to do in this case.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/langfuse/callback/langchain.py", line 822, in on_llm_end
    raise Exception("Run not found, see docs what to do in this case.")

My versions are:

> langchain = "^0.3.3"
langchain-aws = "^0.2.2"
langfuse = "^2.51.0"

The error doesn't seem to do any harm. It is just flooding the logs.

**Comment by hassiebp** [comment]
@steliyan-g Could you please share an example chain for which you see those logs?

**Comment by hassiebp** [comment]
Closing this as stale. Please reopen if issue persists.

**Comment by ragrawal** [comment]
I am also observing the above issue
**Environment**
langchain                                0.3.4
langchain-chroma                         0.1.4
langchain-community                      0.3.3
langchain-core                           0.3.12
langchain-openai                         0.2.1
langchain-text-splitters                 0.3.0
langfuse                                 2.53.1
langsmith                                0.1.131

**Test Code**
```
from langchain_openai import AzureChatOpenAI
from loguru import logger


from langfuse.callback import CallbackHandler
langfuse_handler = CallbackHandler()

llm = AzureChatOpenAI(
    deployment_name="gpt-4o-2024-08-06",
    model_name="gpt-4o-2024-08-06",
    streaming=True
)

llm.invoke('hello', config={"callbacks":[langfuse_handler]})
```

**Error**
```
AIMessage(content='Hello! How can I assist you today?', additional_kwargs={}, response_metadata={'finish_reason': 'stop', 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_d54531d9eb'}, id='run-5fbe1988-f8bf-4ac5-bcb0-bff1d1a526eb-0')
>>> Unexpected error occurred. Please check your request and contact support: https://langfuse.com/support.
>>> Unexpected error occurred. Please check your request and contact support: https://langfuse.com/support.
```

The above log doesn't say that the `run not found` but when I use the above code in my application I can se that in logs.

**Comment by hassiebp** [comment]
@ragrawal Could you please create a new issue with a repro example? 🙏🏾

**Comment by sergeyklay** [comment]
We are currently facing some similar issue. It is tricky to provide repro as it is a big, enterprise-level app, but I have to say "run not found" message does not help to understand what happens. Could someone from maintainers team take a look at this issue pleas and make error reporting more descriptive, including providing more useful message, stacktrace, etc.

**Comment by hassiebp** [comment]
@sergeyklay are you on the latest SDK version? 

Without a repro example / detailed debug logs it will be hard for us to get to the bottom of this issue for you.

**Comment by sergeyklay** [comment]
Hey @hassiebp!

> Without a repro example / detailed debug logs it will be hard for us to get to the bottom of this issue for you.

I plan to allocate some time to this issue next week. I'll keep you informed if something goes wrong and I can't figure it out. Thank you for the reply!
