### ISSUE TITLE
[LFC-167] bug: after changing Rows per page, the page number is not increasing

### ISSUE THREAD

**Issue by DIWAKARKASHYAP** [langfuse/langfuse#173]
### Describe the bug

In pagination, when we change the 'rows per page' option, ideally the page number should change, but it's not happening

![image](https://github.com/langfuse/langfuse/assets/94478026/c255f066-4ab6-4132-8263-5620df1215d8)
![image](https://github.com/langfuse/langfuse/assets/94478026/bf186895-78c4-4d75-b9eb-6963e8e6a2ec)

page number should increase

### To reproduce

try to change the "rows per page" in traces pagination 

<sub>[LFC-167](https://linear.app/langfuse/issue/LFC-167/bug-after-changing-rows-per-page-the-page-number-is-not-increasing)</sub>

**Comment by marcklingen** [comment]
Thanks for reporting

**Comment by marcklingen** [comment]
Fixed in https://github.com/langfuse/langfuse/commit/999b1867e0866dc4e5f4b1264effa4e0b9bfaba7
