### ISSUE TITLE
bug:  When using multiple query with llama index sub query engine

### ISSUE THREAD

**Issue by aman-vink** [langfuse/langfuse#1753]
### Describe the bug

In **python sdk** while running multiple queries (llamaindex)

usage=usage or None,
UnboundLocalError: local variable 'usage' referenced before assignment

`langfuse\llama_index\llama_index.py`

### To reproduce

`        s_engine = SubQuestionQueryEngine.from_defaults(
            query_engine_tools=query_engine_tools, verbose=True, use_async=True
        )
        
        questions = [
            "What is the core business of Microsoft?",
            "What are the main revenue streams of Microsoft?",
            "What strategic priorities or growth areas has Microsoft identified for the upcoming year?",
            "How has Microsoft's revenue and profit margin trended over the past year?",
            "What significant investments or capital expenditures has Microsoft made recently?",
            "What operational achievements or milestones has Microsoft highlighted?",
            "What challenges does Microsoft face, and how are they planning to address them?",
            "What insights does the report provide about industry trends and the competitive landscape?",
            "How does Microsoft position itself within the industry landscape?",
            "What investments in technology or innovation has Microsoft made?",
            "Are there any notable sustainability initiatives or commitments mentioned for Microsoft?",
            "What can be understood about Microsoft's leadership philosophy or any recent executive changes?",
            "What Corporate Social Responsibility (CSR) initiatives has Microsoft undertaken?"
        ]
        for question in questions:
            s_engine.query(question)`
            
            
 i am using with llamaindex

**Comment by marcklingen** [comment]
Thanks for reporting! This seems to be an issue with concurrency which is currently not handled well by the Llamaindex Callbacks (known issue). We hope that this issue is resolved when moving to Llamaindex instrumentation: https://docs.llamaindex.ai/en/stable/examples/instrumentation/basic_usage/

**Comment by marcklingen** [comment]
Thanks for reporting! This seems to be an issue with concurrency which is currently not handled well by the Llamaindex Callbacks (known issue). We hope that this issue is resolved when moving to Llamaindex instrumentation:
https://docs.llamaindex.ai/en/stable/examples/instrumentation/basic_usage/

**Comment by hassiebp** [comment]
We have just shipped a major improvement to the LlamaIndex instrumentation integration that should address your issue. Please upgrade and check out our docs in how to enable the integration via the `LlamaIndexInstrumentor` and let us know your feedback here! 🙏🏾 

- [Release](https://github.com/langfuse/langfuse-python/releases/tag/v2.52.0)
- [Docs](https://langfuse.com/docs/integrations/llama-index/get-started#beta-observability-based-on-llamaindex-instrumentation-module)
- [Cookbook](https://langfuse.com/docs/integrations/llama-index/example-python-instrumentation-module)
