### ISSUE TITLE
bug: KeyError: 'message' on raising APIErrors in python sdk

### ISSUE THREAD

**Issue by noxan** [langfuse/langfuse#1754]
### Describe the bug

the `message` key does not exist on the response from the server, but the python sdk expects it to be present.

langfuse/request.py in _process_response at line 97:
```
APIError(error["status"], error["message"], error["error"])
```

but the response payload from the server looks as follows:
```
{
error: "Internal Server Error",
id: "<uuid>",
status: 500
}
```

not sure what causes the server error in the first place, happy to help investigate.

### To reproduce

not sure, seems to be raised from `Giving up execute_task_with_backoff(...) after 3 tries (KeyError: 'message')
`, guess something with the request payload. happy to share the payload privately.

**Comment by marcklingen** [comment]
Thanks for reporting this! I'll fix the `APIError(error["status"], error["message"], error["error"])` issue.

Can you share payload? marc at langfuse com

**Comment by marcklingen** [comment]
https://github.com/langfuse/langfuse-python/releases/tag/v2.26.3
