### ISSUE TITLE
bug: Validation Error in get_trace(trace_id) 

### ISSUE THREAD

**Issue by nathan-vo810** [langfuse/langfuse#1758]
### Describe the bug

When trying to get trace info, ValidationError are raised because of missing htmlPath and totalCost. The two fields are not presented in the trace either!

ValidationError: 2 validation errors for ParsingModel[TraceWithFullDetails]
__root__ -> htmlPath
  field required (type=value_error.missing)
__root__ -> totalCost
  field required (type=value_error.missing)

<img width="956" alt="Screenshot 2024-04-17 at 13 53 09" src="https://github.com/langfuse/langfuse/assets/14048514/5a276987-b346-4b09-9e63-13b60a5e30a0">

### To reproduce

1. Create a trace 
2. Obtain the `trace_id`
3. Use Langfuse client to `get_trace(trace_id)`

**Comment by marcklingen** [comment]
Do you host langfuse yourself? Are you on the latest container version?
