### ISSUE TITLE
bug: There is no exit button on the homepage

### ISSUE THREAD

**Issue by secsilm** [langfuse/langfuse#1787]
### Describe the bug

![image](https://github.com/langfuse/langfuse/assets/8894643/121637bc-a3aa-4e84-9c35-f4179872398f)

### To reproduce

Register a new user.

**Comment by marcklingen** [comment]
good one @secsilm, this happens on the onboarding screen when not having access to any project yet. open for contributions on this

**Comment by mini2809** [comment]
@marcklingen I am looking to make contributions but this looks as per design.

Another scenario: Create a project to complete onboarding, delete that project, refresh to home screen -> user will again land up on this screen as user dont have access to any project. 

What should be expected here as exit button? "Skip to dashboard" or "Signout" ?

**Comment by marcklingen** [comment]
fixed this, the intention here was to focus on the next step during Langfuse onboarding (create project) but I understand that this leads to undesired outcomes (cannot sign out). easiest fix here was to just always show the menu
