### ISSUE TITLE
bug: Traces count seems to be incorrect

### ISSUE THREAD

**Issue by secsilm** [langfuse/langfuse#1791]
### Describe the bug

⬇️ Under the default view, there are 453 traces for 0420:
![image](https://github.com/langfuse/langfuse/assets/8894643/8a300883-ae07-4c43-9fa5-359e0278d3f5)

⬇️ but after selecting the last 24 hours as the date range, the number of traces for 0420 is definitely more than 453:
![image](https://github.com/langfuse/langfuse/assets/8894643/abfd651e-1e08-43b9-9331-459804aec4f0)

### To reproduce

None

**Comment by secsilm** [comment]
This seems to be a time conversion issue, using UTC time under the default view, while using local time (GMT+8 in my case) when manually selecting the date range.

**Comment by marcklingen** [comment]
Hi, we made many updates to the dashboard logic in the last releases. Is this still an ongoing issue for you?

**Comment by marcklingen** [comment]
Closing this as stale, please reopen in case this is still an issue after upgrading to the latest version
