### ISSUE TITLE
bug: self-host langfuse get 502 bad gateway if client behind http proxy

### ISSUE THREAD

**Issue by zhaolj** [langfuse/langfuse#1792]
### Describe the bug

I set up a self-host langfuse refer to the instructions:
```shell
# Clone the Langfuse repository
git clone https://github.com/langfuse/langfuse.git
cd langfuse
 
# Start the server and database
docker compose up
```
I tried "curl http://[my.host]:3000/api/public/health" in my client host, I got "502 bad gateway" response.
My client is behind a local http proxy: http://127.0.0.1:8889 .
If I remove the http proxy, it works.

My local http proxy works fine with other site.

### To reproduce

Here is the detail info:
```shell
$ curl http://[my.host]:3000/api/public/health --verbose
* Uses proxy env variable http_proxy == 'http://127.0.0.1:8889'
*   Trying 127.0.0.1:8889...
* Connected to 127.0.0.1 (127.0.0.1) port 8889 (#0)
> GET http://[my.host]:3000/api/public/health HTTP/1.1
> Host: [my.host]:3000
> User-Agent: curl/8.1.2
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 502 Bad Gateway
< Connection: keep-alive
< Keep-Alive: timeout=4
< Proxy-Connection: keep-alive
< Content-Length: 0
< 
* Connection #0 to host 127.0.0.1 left intact
```

If I remove the local proxy, I will get the correct response:
```shell
$ no_proxy=[my.host] curl http://[my.host]:3000/api/public/health --verbose
* Uses proxy env variable no_proxy == '[my.host]'
*   Trying [IP.to.MY.HOST]:3000...
* Connected to [my.host] ([IP.to.MY.HOST]) port 3000 (#0)
> GET /api/public/health HTTP/1.1
> Host: [my.host]:3000
> User-Agent: curl/8.1.2
> Accept: */*
> 
< HTTP/1.1 200 OK
< x-frame-options: SAMEORIGIN
< X-Content-Type-Options: nosniff
< Referrer-Policy: strict-origin-when-cross-origin
< Permissions-Policy: autoplay=*, fullscreen=*, microphone=*
< Vary: Origin, Accept-Encoding
< Content-Type: application/json; charset=utf-8
< ETag: "10kadd2rskey"
< Content-Length: 34
< Date: Sat, 20 Apr 2024 03:50:06 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
* Connection #0 to host [my.host] left intact
{"status":"OK","version":"2.30.2"}% 
```

**Comment by marcklingen** [comment]
thanks for sharing, does it work if you use langfuse on port 3000 behind the proxy? (trying to understand what the issue here really is)

**Comment by kondera** [comment]
I have the same problem (using openai on Azure to which to connect I need to set proxy). When proxy is set, every connection to local langfuse returns 502 errors.

But I successfully created a bit hacky solution that can connect (at least in python):
```{python}
import httpx
from langfuse import Langfuse
from langfuse.callback import CallbackHandler

# before setting proxy, create client and pass it in langfuse and pass it to callback handler
client = httpx.Client()
langfuse = Langfuse(httpx_client=client)
langfuse_handler = CallbackHandler()
langfuse_handler.langfuse = langfuse

# set proxy from .env
from dotenv import load_dotenv
load_dotenv()

# check connection
assert langfuse.auth_check()
```

**Comment by FrostScent** [comment]
Just set `HOSTNAME` to `0.0.0.0`.

I had the same problem.
My environment is Docker Swarm cluster, traefik proxy. 
service and proxy has no problem, and i got `bad gateway` too.

I solved this problem with this [trouble shooting guide](https://langfuse.com/docs/deployment/self-host#troubleshooting)

**Comment by marcklingen** [comment]
thanks @FrostScent for sharing that this point included in the troubleshooting guide resolved this issue for you. Feel free to reopen in case this does not work for you @zhaolj.
