### ISSUE TITLE
bug: Unable to parse the LLM model - Groq

### ISSUE THREAD

**Issue by jayaveer** [langfuse/langfuse#1798]
### Describe the bug

Langfuse was not able to parse the LLM model - Groq (ChatGroq). The LLM call will be recorded without model name.

### To reproduce

```
pip install langchain-groq

from langchain_core.prompts import ChatPromptTemplate
from langchain_groq import ChatGroq

chat = ChatGroq(temperature=0, groq_api_key="YOUR_API_KEY", model_name="mixtral-8x7b-32768")

system = "You are a helpful assistant."
human = "{text}"
prompt = ChatPromptTemplate.from_messages([("system", system), ("human", human)])

chain = prompt | chat
chain.invoke({"text": "Explain the importance of low latency LLMs."})
```

**Comment by marcklingen** [comment]
Thanks for reporting this issue, we aim for a generalizable solution. Follow #1920 to understand more of the context and get updates on this. I'm sorry for the inconvenience. Please reopen in case this throws an exception instead of just logging a warning in your case.

**Comment by maxdeichmann** [comment]
@jayaveer I just released a fix for this. Please re-open if this persists for you: https://github.com/langfuse/langfuse-python/releases/tag/v2.29.1
