### ISSUE TITLE
bug: Disable debug output in public apis

### ISSUE THREAD

**Issue by Lunik** [langfuse/langfuse#1804]
### Describe the bug

As of right now, each time a trace is recorded to Langfuse, a debug log is displayed to the stdout. This is a security issue because it can leak sensitive information (input/ouput completion)

### To reproduce

Launch a Languse instance and make a trace with completion

### Additional information

A boolean to enable or disable this behaviour should be enought

**Comment by hookenful** [comment]
There is `LANGFUSE_DEBUG` environment variable or callback's param 'debug' depends whether you use full SDK or callbacks

**Comment by marcklingen** [comment]
to confirm, @Lunik you suggest to toggle this behavior on the langfuse api, not on the sdks as @hookenful suggested?

**Comment by tmyjoe** [comment]
I have also come across the same issue. To illustrate, the log output on this particular line is an example of the concern: https://github.com/langfuse/langfuse/blob/7c5a49b4eea0c36350af2eee51809f9e594207eb/web/src/pages/api/public/ingestion.ts#L260
It would be beneficial to introduce a configuration option that toggle this log output ON or OFF.

**Comment by tmyjoe** [comment]
The log has been reduced in 2.37.3, but it seems that the Input is still being outputted in cases where there is no Output yet.
Additionally, a similar problem was found in this location as well:
https://github.com/langfuse/langfuse/blob/v2.37.3/web/src/pages/api/public/traces.ts#L59

**Comment by marcklingen** [comment]
thanks for the feedback! will try to address this in one of the upcoming releases

**Comment by afonsomatos** [comment]
how do I turn this off entirely? there is no environment variable for this?

**Comment by marcklingen** [comment]
@Steffen911 added support for configuring log levels and format via environment variables (`LANGFUSE_LOG_LEVEL`, `LANGFUSE_LOG_FORMAT`) today. See docs here: https://langfuse.com/docs/deployment/self-host#configuring-environment-variables

**Comment by pashok3d** [comment]
@marcklingen `LANGFUSE_LOG_LEVEL` and `LANGFUSE_LOG_FORMAT` can be used to control logs level and format, but it would be nice to have an option to completely turn off Langfuse logs.

**Comment by marcklingen** [comment]
> @marcklingen `LANGFUSE_LOG_LEVEL` and `LANGFUSE_LOG_FORMAT` can be used to control logs level and format, but it would be nice to have an option to completely turn off Langfuse logs.

`LANGFUSE_LOG_LEVEL=fatal` will disable almost all logs, did you try this already?

**Comment by talrejanikhil** [comment]
Actually what worked for me was this:

```
from langfuse.logger import langfuse_logger
import logginglangfuse_logger.setLevel(logging.FATAL)
```

I am using langfuse SDK 3.5.1
