### ISSUE TITLE
bug: Parent run not found when using Callbacks with langchain EnsembleRetriever

### ISSUE THREAD

**Issue by nathan-vo810** [langfuse/langfuse#1818]
### Describe the bug

When trying to pass Langfuse callbacks into EnsembleRetriever, Exception was raised.

<img width="1006" alt="Screenshot 2024-04-23 at 19 28 32" src="https://github.com/langfuse/langfuse/assets/14048514/5816ab3a-8597-48a4-a8e6-e7ee6c67dbe3">

### To reproduce

```
from langfuse.callback import CallbackHandler
from langchain.retrievers import BM25Retriever, EnsembleRetriever

question = ""
    
vector_db_client_provider = PGVectorClient()
vectorstore = vector_db_client_provider.get_client("user")

docs = vectorstore.similarity_search(query=question, k=1)
bm25_retriever = BM25Retriever.from_documents(documents=docs)
vector_retriever = vectorstore.as_retriever()

ensemble_retriever = EnsembleRetriever(retrievers=[vector_retriever, bm25_retriever], weights=[0.5, 0.5])

relevant_docs = ensemble_retriever.get_relevant_documents(question, callbacks=[CallbackHandler()])
```

**Comment by nathan-vo810** [comment]
I use that as a standalone for my RAG pipeline. Rather than incorporating with Langchain, I built separated components and finally link them together.

**Comment by nathan-vo810** [comment]
Ah yes, I did pass `langfuse_context.get_current_langchain_handler()` to my EnsembleRetriever. But the result is as above exception. 

Thanks for providing such a great tool and I look forward to the solution!

**Comment by marcklingen** [comment]
> Ah yes, I did pass `langfuse_context.get_current_langchain_handler()` to my EnsembleRetriever. But the result is as above exception.
> 
> Thanks for providing such a great tool and I look forward to the solution!

👍 awesome, I was worried that the docs were not clear enough on how this works

probably decorating a function that wraps the `get_relevant_documents` and just passing all kwargs is the best workaround until this is fixed. thereby you at least can track the inputs/outputs/timings of this within your larger context.

**Comment by marcklingen** [comment]
Merging this into #1927 to collect all instances of this error
