### ISSUE TITLE
bug: Public and secret keys should not be required at build time

### ISSUE THREAD

**Issue by Stadly** [langfuse/langfuse#1829]
### Describe the bug

The public key and secret key are required when building the application with Vite. I think they should only be required at runtime, so the build system does not need to know the keys used when running the application.

### To reproduce

https://stackblitz.com/edit/sveltejs-kit-template-default-qeurfm?file=src%2Froutes%2F%2Bpage.server.js

Run `npm run build` in the terminal. You'll get the error

```
publicKey is required, but was not provided. It can be provided as an argument or as an environment variable LANGFUSE_PUBLIC_KEY.
```

### Additional information

I'm using the JS/TS SDK.

**Comment by Stadly** [comment]
I'm concerned that silently disabling Langfuse will trip up people when setting up the project. I guess there should be a way to require an env var during runtime but not during build time? Sounds like a common problem to encounter.

**Comment by marcklingen** [comment]
I'd suggest logging a single warning ("langfuse environment variables not set, tracing disabled"). I think I have seen this behavior with Sentry, Betterstack, Posthog, …

**Comment by Stadly** [comment]
Yes, that sounds reasonable 👍

**Comment by marcklingen** [comment]
Moved this to #1910 as there was another user requesting this
