### ISSUE TITLE
[LFC-178] feat: delete project

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#186]
### Describe the feature you'd like to request

Add delete project button to project settings

### Describe the solution you'd like to see

* dialog
  * use shadcn ui button component
  * modal to confirm deletion
* trpc route for deletion
* project:delete as new scope only granted to project owners
  * hide button in frontend if not owner
  * enforce in trpc route that user needs to be owner to delete project
* cascading deletion of observation/traces/scores/memberships in db

### Additional information

*No response*

### Contribute

* [ ] Yes, I can implement this and raise a PR

<sub>From [SyncLinear.com](https://synclinear.com) | [LFC-178](https://linear.app/langfuse/issue/LFC-178/feat-delete-project)</sub>

**Comment by DIWAKARKASHYAP** [comment]
i am working on this

**Comment by maxdeichmann** [comment]
> Currently, i am working on this

Thanks a lot for picking this up :)
