### ISSUE TITLE
bug: Unable to parse the LLM model with Langchain `ChatAnthropic`

### ISSUE THREAD

**Issue by Doma1204** [langfuse/langfuse#1868]
### Describe the bug

Anthropic Model cannot be parsed, so the Langfuse trace are logged without a model name.

```
Traceback (most recent call last):
  File "/home/joseph/anaconda3/envs/lf_err/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 627, in _parse_model_and_log_errors
    model_name = _extract_model_name(serialized, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joseph/anaconda3/envs/lf_err/lib/python3.11/site-packages/langfuse/extract_model.py", line 287, in _extract_model_name
    model = _extract_model_by_pattern("ChatAnthropic", serialized, "model")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joseph/anaconda3/envs/lf_err/lib/python3.11/site-packages/langfuse/extract_model.py", line 342, in _extract_model_by_pattern
    extracted = _extract_model_with_regex(pattern, serialized["repr"])
                                                   ~~~~~~~~~~^^^^^^^^
KeyError: 'repr'
Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name. Please create an issue so we can fix your integration: https://github.com/langfuse/langfuse/issues/new/choose
```

### To reproduce

```python
from langchain_core.runnables import RunnableConfig
from langchain_anthropic import ChatAnthropic
from langfuse.callback import CallbackHandler as LangfuseCallbackHandler

config: RunnableConfig = {
    "callbacks": [LangfuseCallbackHandler()],
}

model = ChatAnthropic(
    model="claude-3-haiku-20240307",
    temperature=0,
    max_tokens=1,
)

print(model.invoke("hello", config=config))
```

Package Dependency:
```
langchain==0.1.16
langchain-anthropic==0.1.11
langfuse==2.27.0
```

### Additional information

I've tried different versions of `langchain-anthropic` while keeping other dependencies the same, and I found out that the error is raised with the version above `0.1.9`.

Here's the versions I've tried:
- `0.1.6` - `0.1.8`: No error
- `0.1.9` - `0.1.11`: Error raised

**Comment by kdcokenny** [comment]
I get this error as well. Downgrading to 0.1.8 also shows no error. That'll work as a temporary fix for me.

**Comment by MarkEdmondson1234** [comment]
I have this as well

**Comment by marcklingen** [comment]
Thanks for reporting this issue, we aim for a generalizable solution. Follow #1920 to understand more of the context and get updates on this. I'm sorry for the inconvenience. Please reopen in case this throws an exception instead of logging the warning/stack-trace in your case.

In this case I assume that the key changed in which anthropic models in Langchain include the model name.

**Comment by maxdeichmann** [comment]
@Doma1204, @MarkEdmondson1234, @kdcokenny i just released a fix for this. Please re-open if this persists for you: https://github.com/langfuse/langfuse-python/releases/tag/v2.29.1
