### ISSUE TITLE
[LFC-179] [Python-SDK] OpenAI SDK Wrapper/Integration

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#187]
Issue is related to the Python SDK: [https://github.com/langfuse/langfuse-python](https://github.com/langfuse/langfuse-python)

For users who just want to log OpenAI calls to Langfuse, getting started with Langfuse could be as simple as:

```
# openai
from openai import openai

# openai with langfuse logging
from langfuse.openai import openai
```

<sub>From [SyncLinear.com](https://synclinear.com) | [LFC-179](https://linear.app/langfuse/issue/LFC-179/[python-sdk]-openai-sdk-wrapperintegration)</sub>

**Comment by Dev-Khant** [comment]
Can I pick this up @marcklingen?

**Comment by marcklingen** [comment]
@Dev-Khant sure, PR welcome on this
