### ISSUE TITLE
bug: Langfuse was not able to parse the LLM model.

### ISSUE THREAD

**Issue by marco-introvigne** [langfuse/langfuse#1873]
### Describe the bug

I’ve encountered a persistent issue with the latest versions of langchain, langchain-core, and langchain community. The problem arises when the system fails to recognize the model, which results in the following warning message:

`WARNING:langfuse:Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name. Please create an issue so we can fix your integration.`

This issue prevents the correct tracing of model usage and pricing on Langfuse.

Interestingly, when I revert to older versions of the packages (langchain v0.1.13, langchain community v0.0.31, and langchain-core v0.1.39), the warning no longer appears, and Langfuse operates as expected.

### To reproduce

For more details on the error and the context in which it occurs, please refer to the attached screenshot.
![Screenshot 2024-04-26 at 09 26 22](https://github.com/langfuse/langfuse/assets/162149734/b1b34b77-9fa5-4cac-9f76-f90e13627006)

**Comment by marcklingen** [comment]
Which mdoel do you use?

**Comment by marcklingen** [comment]
Follow #1920 to understand more of the context and get updates on this. I'm sorry for the inconvenience. Please reopen in case this throws an exception instead of just logging a warning in your case.

**Comment by maxdeichmann** [comment]
@marco-introvigne I just released a fix for this. Please re-open if this persists for you: https://github.com/langfuse/langfuse-python/releases/tag/v2.29.1
