### ISSUE TITLE
bug: Langfuse was not able to parse the LLM model.

### ISSUE THREAD

**Issue by marco-introvigne** [langfuse/langfuse#1874]
### Describe the bug

I’ve encountered a persistent issue with the latest versions of langchain, langchain-core, and langchain community. The problem arises when the system fails to recognize the model, which results in the following warning message:

`WARNING:langfuse:Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name. Please create an issue so we can fix your integration.`

This issue prevents the correct tracing of model usage and pricing on Langfuse.

Interestingly, when I revert to older versions of the packages (langchain v0.1.13, langchain community v0.0.31, and langchain-core v0.1.39), the warning no longer appears, and Langfuse operates as expected.

### To reproduce

For more details on the error and the context in which it occurs, please refer to the attached screenshot.
![Screenshot 2024-04-26 at 09 26 22](https://github.com/langfuse/langfuse/assets/162149734/7aa1ed8e-c6e5-4ba5-89a9-93889ad625a7)

**Comment by ajram23** [comment]
Same. This langchain version adds support for tool calling in groq so please fix ASAP.

**Comment by luiscastejon-aily** [comment]
Same error here.

**Comment by marcklingen** [comment]
Thanks for reporting this issue, we aim for a generalizable solution. Follow #1920 to understand more of the context and get updates on this. I'm sorry for the inconvenience. Please reopen in case this throws an exception instead of just logging a warning in your case.

**Comment by maxdeichmann** [comment]
@luiscastejon-aily and @marco-introvigne, can you share the models + packages you are using?

**Comment by ajram23** [comment]
@maxdeichmann happy to give you one. I am use LLama3-70B-8192 from Groq (ChatGroq) for instance. Let me know if you need anything else.

**Comment by luiscastejon-aily** [comment]
@maxdeichmann hey! Thanks for your reply. I am using Claude 2.1 from Bedrock.

**Comment by maxdeichmann** [comment]
@marco-introvigne , @ajram23, @luiscastejon-aily: I just released a fix for this. Please re-open if this persists for you: https://github.com/langfuse/langfuse-python/releases/tag/v2.29.1
