### ISSUE TITLE
bug: While doing with LangChain+Ollama(self-hosts chat models) , it can not record the price and useage

### ISSUE THREAD

**Issue by ShaunDeng** [langfuse/langfuse#1877]
### Describe the bug

I use LangChain to integrate with Langfuse, which call the llms run on Ollama(self-hosts), after the chain completed, I can see the traces records but without price/useage info. Below is the error I found in the console of my IDE:

`Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name. Please create an issue so we can fix your integration: https://github.com/langfuse/langfuse/issues/new/choose`

Appreciate for your assistence

### To reproduce

Please see my code snippet:

... ...

langfuse = Langfuse()
langfuse_prompt = langfuse.get_prompt(name='mytemplate')
code_gen_prompt = ChatPromptTemplate.from_messages(langfuse_prompt.get_langchain_prompt())

chat_model_handler = self._get_chat_model_handler()
chat_model = chat_model_handler.get_chat_model() #here will return a Ollama hosted model

output_parser = StrOutputParser()

chain = setup_and_retrieval | code_gen_prompt | chat_model | output_parser

langfuse_handler = CallbackHandler(user_id=self.user_id, session_id=self.session_id, release=VERSION, version=VERSION,
								   trace_name='ChatWithAWS')
chain.stream({"question": self.input}, config={"callbacks":[langfuse_handler]})

... ...

### Additional information

Below is about how LangChain integrated with Ollama:

[](https://python.langchain.com/docs/integrations/llms/ollama/)

and the raw API responses from ollama NOT inculdes prices and useages, please check below:

POST http://ollama_host/api/chat
REQUEST BODY:
{
  "model": "mistral:latest",
  "messages": [
    { "role": "user", "content": "why is the sky blue?" }
  ],
  "stream": false
}
RESPONSE BODY:
{
    "model": "mistral:latest",
    "created_at": "2024-04-26T10:23:11.865836488Z",
    "message": {
        "role": "assistant",
        "content": " The color of the sky appears blue due to a phenomenon called Rayleigh scattering. When sunlight reaches the Earth's atmosphere, it interacts with different gases and particles in the air. Blue light has a shorter wavelength and gets scattered more easily than other colors because it travels in smaller waves. This scattered blue light is what we observe when looking up at the sky."
    },
    "done": true,
    "total_duration": 1986140878,
    "load_duration": 979758722,
    "prompt_eval_count": 15,
    "prompt_eval_duration": 89812000,
    "eval_count": 77,
    "eval_duration": 916087000
}

**Comment by ShaunDeng** [comment]
Hi I notice the code snippet in CallbackHandler class.


```
def _parse_usage(response: LLMResult):
    # langchain-anthropic uses the usage field
    llm_usage_keys = ["token_usage", "usage"]
    llm_usage = None
    if response.llm_output is not None:
        for key in llm_usage_keys:
            if key in response.llm_output and response.llm_output[key]:
                llm_usage = _parse_usage_model(response.llm_output[key])
                break

    return llm_usage
```

so if it's possible to calculate the token directly rather than only get it from the model APIs(or while there's response from model API)?

For example, use tiktoken? I think that will be quick to implement all usage info first.

**Comment by marcklingen** [comment]
Thanks for reporting this issue, we aim for a generalizable solution. Follow #1920 to understand more of the context and get updates on this. I'm sorry for the inconvenience. Please reopen in case this throws an exception instead of just logging a warning in your case.

**Comment by marcklingen** [comment]
> Hi I notice the code snippet in CallbackHandler class.
> 
> ```
> def _parse_usage(response: LLMResult):
>     # langchain-anthropic uses the usage field
>     llm_usage_keys = ["token_usage", "usage"]
>     llm_usage = None
>     if response.llm_output is not None:
>         for key in llm_usage_keys:
>             if key in response.llm_output and response.llm_output[key]:
>                 llm_usage = _parse_usage_model(response.llm_output[key])
>                 break
> 
>     return llm_usage
> ```
> 
> so if it's possible to calculate the token directly rather than only get it from the model APIs(or while there's response from model API)?
> 
> For example, use tiktoken? I think that will be quick to implement all usage info first.

Langfuse uses tiktoken to derive token counts in cases where they are not reported by the model. See more details here: https://langfuse.com/docs/model-usage-and-cost

**Comment by marcklingen** [comment]
https://github.com/langfuse/langfuse/issues/1920

**Comment by maxdeichmann** [comment]
@ShaunDeng i just released a fix for this. Please re-open if this persists for you: https://github.com/langfuse/langfuse-python/releases/tag/v2.29.1
