### ISSUE TITLE
[LFC-180] [Python-SDK] Llamaindex integration via callback handler

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#188]
Learn more: [https://gpt-index.readthedocs.io/en/latest/end_to_end_tutorials/one_click_observability.html](https://gpt-index.readthedocs.io/en/latest/end_to_end_tutorials/one_click_observability.html)

Implementation similar to existing Langchain callback handler that we have built on top of the Python SDK

<sub>From [SyncLinear.com](https://synclinear.com) | [LFC-180](https://linear.app/langfuse/issue/LFC-180/llamaindex-integration-via-callback-handler)</sub>

**Comment by Dev-Khant** [comment]
Marc, can you give more clarity on how the structure should be?

**Comment by Dev-Khant** [comment]
@marcklingen Can I pick this up?

**Comment by marcklingen** [comment]
Duplicate of #828
