### ISSUE TITLE
bug: Dependency issues python sdk, `backoff`

### ISSUE THREAD

**Issue by ajram23** [langfuse/langfuse#1917]
### Describe the bug

Between Langfuse, Posthog & ChromaDB (opentelemetry), there seems to be an dependency conflict:

The user requested backoff<3.0.0 and >=2.2.1
    langfuse 2.27.3 depends on backoff<3.0.0 and >=2.2.1
    posthog 3.5.0 depends on backoff>=1.10.0
    opentelemetry-exporter-otlp-proto-grpc 1.11.1 depends on backoff<2.0.0 and >=1.10.0
    The user requested backoff<3.0.0 and >=2.2.1
    langfuse 2.27.3 depends on backoff<3.0.0 and >=2.2.1
    posthog 3.5.0 depends on backoff>=1.10.0
    opentelemetry-exporter-otlp-proto-grpc 1.11.0 depends on backoff<2.0.0 and >=1.10.0
    The user requested backoff<3.0.0 and >=2.2.1
    langfuse 2.27.3 depends on backoff<3.0.0 and >=2.2.1
    posthog 3.5.0 depends on backoff>=1.10.0
    opentelemetry-exporter-otlp-proto-grpc 1.10.0 depends on backoff~=1.10.0
    The user requested backoff<3.0.0 and >=2.2.1
    langfuse 2.27.3 depends on backoff<3.0.0 and >=2.2.1
    posthog 3.5.0 depends on backoff>=1.10.0
    opentelemetry-exporter-otlp-proto-grpc 1.9.1 depends on backoff~=1.10.0
    The user requested backoff<3.0.0 and >=2.2.1
    langfuse 2.27.3 depends on backoff<3.0.0 and >=2.2.1
    posthog 3.5.0 depends on backoff>=1.10.0
    opentelemetry-exporter-otlp-proto-grpc 1.9.0 depends on backoff~=1.10.0
    The user requested backoff<3.0.0 and >=2.2.1
    langfuse 2.27.3 depends on backoff<3.0.0 and >=2.2.1
    posthog 3.5.0 depends on backoff>=1.10.0
    opentelemetry-exporter-otlp-proto-grpc 1.8.0 depends on backoff~=1.10.0
    The user requested backoff<3.0.0 and >=2.2.1
    langfuse 2.27.3 depends on backoff<3.0.0 and >=2.2.1
    posthog 3.5.0 depends on backoff>=1.10.0
    opentelemetry-exporter-otlp-proto-grpc 1.7.1 depends on backoff~=1.10.0
    The user requested backoff<3.0.0 and >=2.2.1
    langfuse 2.27.3 depends on backoff<3.0.0 and >=2.2.1
    posthog 3.5.0 depends on backoff>=1.10.0
    opentelemetry-exporter-otlp-proto-grpc 1.7.0 depends on backoff~=1.10.0
    The user requested backoff<3.0.0 and >=2.2.1
    langfuse 2.27.3 depends on backoff<3.0.0 and >=2.2.1
    posthog 3.5.0 depends on backoff>=1.10.0
    opentelemetry-exporter-otlp-proto-grpc 1.6.2 depends on backoff~=1.10.0
    The user requested backoff<3.0.0 and >=2.2.1
    langfuse 2.27.3 depends on backoff<3.0.0 and >=2.2.1
    posthog 3.5.0 depends on backoff>=1.10.0
    opentelemetry-exporter-otlp-proto-grpc 1.6.1 depends on backoff~=1.10.0
    The user requested backoff<3.0.0 and >=2.2.1
    langfuse 2.27.3 depends on backoff<3.0.0 and >=2.2.1
    posthog 3.5.0 depends on backoff>=1.10.0
    opentelemetry-exporter-otlp-proto-grpc 1.6.0 depends on backoff~=1.10.0
    The user requested backoff<3.0.0 and >=2.2.1
    langfuse 2.27.3 depends on backoff<3.0.0 and >=2.2.1
    posthog 3.5.0 depends on backoff>=1.10.0
    opentelemetry-exporter-otlp-proto-grpc 1.5.0 depends on backoff~=1.10.0
    The user requested backoff<3.0.0 and >=2.2.1
    langfuse 2.27.3 depends on backoff<3.0.0 and >=2.2.1
    posthog 3.5.0 depends on backoff>=1.10.0
    opentelemetry-exporter-otlp-proto-grpc 1.4.1 depends on backoff~=1.10.0
    The user requested backoff<3.0.0 and >=2.2.1
    langfuse 2.27.3 depends on backoff<3.0.0 and >=2.2.1
    posthog 3.5.0 depends on backoff>=1.10.0
    opentelemetry-exporter-otlp-proto-grpc 1.4.0 depends on backoff~=1.10.0
    The user requested backoff<3.0.0 and >=2.2.1
    langfuse 2.27.3 depends on backoff<3.0.0 and >=2.2.1
    posthog 3.5.0 depends on backoff>=1.10.0
    opentelemetry-exporter-otlp-proto-grpc 1.3.0 depends on backoff~=1.10.0
    The user requested backoff<3.0.0 and >=2.2.1
    langfuse 2.27.3 depends on backoff<3.0.0 and >=2.2.1
    posthog 3.5.0 depends on backoff>=1.10.0
    opentelemetry-exporter-otlp-proto-grpc 1.2.0 depends on backoff~=1.10.0

### To reproduce

A app that that uses ChromaDB and has integration between langfuse & posthog.

### Additional information

Any help/suggestion to resolve this would be greatly appreciated.

**Comment by marcklingen** [comment]
@maxdeichmann any chance we can also use >=1.10.0 or even >= 1.2.0?

**Comment by maxdeichmann** [comment]
@ajram23 thanks for raising this! I just deployed a fix for that. Please let me know if this did not work for you.

**Comment by ajram23** [comment]
Thank you @maxdeichmann @marcklingen. This fixed this issue!
