### ISSUE TITLE
bug: Langchain Python Dataset run has `null` trace I/O

### ISSUE THREAD

**Issue by nimbusaeta** [langfuse/langfuse#1919]
### Describe the bug

In the VUI, in the Dataset run view, the inputs of each view appear as null, but in the Dataset Item view, the input is populated with the expected text.

### To reproduce

The run was created following the [Datasets Cookbook](https://langfuse.com/docs/datasets/python-cookbook#langchain-application) (the Langchain application part).

**Comment by marcklingen** [comment]
Thanks for creating this issue. We'll try to push a fix soon.

More context:

- item.get_langchain_handler() creates a trace under the hood
- if the handler is then passed to a langchain agent/chain, it does not update the trace (this is generally the desired behavior as multiple runs could be grouped into the same trace).

**Comment by pckim93** [comment]
Is this still an issue? I'm running into this as well (with some paths adjusted for privacy):
```
.../eval.py 
Traceback (most recent call last):
  File ".../eval.py", line 191, in <module>
    main()
  File ".../eval.py", line 100, in main
    handler = item.get_langchain_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/langfuse/client.py", line 2553, in get_langchain_handler
    self.link(
  File ".venv/lib/python3.11/site-packages/langfuse/client.py", line 2518, in link
    self.langfuse.client.dataset_run_items.create(
  File ".venv/lib/python3.11/site-packages/langfuse/api/resources/dataset_run_items/client.py", line 127, in create
    raise NotFoundError(pydantic_v1.parse_obj_as(typing.Any, _response.json()))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
langfuse.api.resources.commons.errors.not_found_error.NotFoundError: status_code: 404, body: {'message': 'Trace not found'}
```

**Comment by marcklingen** [comment]
> Is this still an issue? I'm running into this as well (with some paths adjusted for privacy):
> 
> ```
> .../eval.py 
> Traceback (most recent call last):
>   File ".../eval.py", line 191, in <module>
>     main()
>   File ".../eval.py", line 100, in main
>     handler = item.get_langchain_handler(
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File ".venv/lib/python3.11/site-packages/langfuse/client.py", line 2553, in get_langchain_handler
>     self.link(
>   File ".venv/lib/python3.11/site-packages/langfuse/client.py", line 2518, in link
>     self.langfuse.client.dataset_run_items.create(
>   File ".venv/lib/python3.11/site-packages/langfuse/api/resources/dataset_run_items/client.py", line 127, in create
>     raise NotFoundError(pydantic_v1.parse_obj_as(typing.Any, _response.json()))  # type: ignore
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> langfuse.api.resources.commons.errors.not_found_error.NotFoundError: status_code: 404, body: {'message': 'Trace not found'}
> ```

do you self-host Langfuse? If yes, do you run the latest version?

**Comment by pckim93** [comment]
@marcklingen Sorry about that. This is no longer an issue. I am self-hosting and I didn't update the container correctly. My apologies.

**Comment by marcklingen** [comment]
thanks for sharing!
