### ISSUE TITLE
feat: rewrite llamaindex integration to be based on `instrumentation` module

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#1931]
Docs: https://docs.llamaindex.ai/en/stable/module_guides/observability/instrumentation/

The current implementation is based on LlamaIndex callbacks. The new instrumentation module seems to be very promising and might resolve llamaIndex tracing issues.

**Comment by siquick** [comment]
Any update on this one? We use a multistep retrieval-then-query process and only getting traces of the retrieval stage. Would love to use Langfuse. Even any workarounds would be great.

**Comment by hassiebp** [comment]
Hi @siquick - we have just released an [experimental integration](https://github.com/langfuse/langfuse-python/releases/tag/v2.44.0) for the LlamaIndex instrumentation module. Feel free to check it out! It is still under active development and behavior / interfaces may change in coming releases. [Link to our docs](https://langfuse.com/docs/integrations/llama-index/get-started#%EF%B8%8F-beta-observability-based-on-llamaindex-instrumentation-module).

**Comment by zkhan93** [comment]
is the related bug fixed ? I'm having issue with concurrent requests. langfuse becomes unresponsive with only ~30 concurrent requests

**Comment by hassiebp** [comment]
We have just shipped a major improvement to the LlamaIndex instrumentation integration. Please check out our docs in how to enable the integration via the `LlamaIndexInstrumentor` and let us know your feedback! 🙏🏾 

- [Release](https://github.com/langfuse/langfuse-python/releases/tag/v2.52.0)
- [Docs](https://langfuse.com/docs/integrations/llama-index/get-started#beta-observability-based-on-llamaindex-instrumentation-module)
- [Cookbook](https://langfuse.com/docs/integrations/llama-index/example-python-instrumentation-module)

**Comment by SinghCoder** [comment]
Hey @hassiebp , thanks for this integration.
The earlier callback manager allowed setting global <tags, metadata> at instantiation time itself which get attached to every trace.. (helpful in experimentation time)
Do you folks plan to have that feature here too?

**Comment by hassiebp** [comment]
@SinghCoder - Thanks a lot for your feedback! Yes, we can add back setting global trace params on `LlamaIndexInstrumentor` instantiation. Feel free to subscribe to [this issue](https://github.com/langfuse/langfuse/issues/3731) to track progress on this 👍🏾
