### ISSUE TITLE
feat: add docker images for `arm64` to build pipeline

### ISSUE THREAD

**Issue by bidva** [langfuse/langfuse#1954]
### Describe the bug

Getting exec /usr/local/bin/docker-entrypoint.sh: exec format error on running arm64

### To reproduce

# Clone the Langfuse repository
git clone https://github.com/langfuse/langfuse.git
cd langfuse
 
# Start the server and database
docker compose up

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Currently we do not publish official ARM images. However, you can build your own ARM images using the Dockerfile in the Langfuse repository

To make this easy, we added this docker compose file: https://github.com/langfuse/langfuse/blob/main/docker-compose.build.yml

**Comment by marcklingen** [comment]
reopening this issue as an arm built of Langfuse would be helpful for many. Contributions welcome!

**Comment by marcklingen** [comment]
First version to include arm image was just released: https://github.com/langfuse/langfuse/releases/tag/v2.58.0
Thanks again @rennokki for the contribution

**Comment by tan-yong-sheng** [comment]
Still got this issue on Oracle server, below is the architecture:
- Linux instance-20240630-1207 5.15.0-1062-oracle #68~20.04.1-Ubuntu SMP Tue Jun 18 12:47:52 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

<img width="399" alt="image" src="https://github.com/langfuse/langfuse/assets/64836390/3c786c7e-dd7a-4ac8-8b18-7623473ede59">

**Comment by marcklingen** [comment]
@tan-yong-sheng, might be related to this: https://github.com/langfuse/langfuse/pull/2541

The fix was just merged and will be included in next release. You could try the dev-build (`langfuse/langfuse:main`) which is currently building ([pipeline](https://github.com/langfuse/langfuse/actions/runs/9828226297/job/27131985936)) to verify whether this solved your issue.

**Comment by tan-yong-sheng** [comment]
Hi @marcklingen, I see, thanks. I tried to rebuild it again with latest image and now it's working.

**Comment by marcklingen** [comment]
Awesome. Thanks for confirming. The next release will have proper arm builds then as well. I’d recommend to switch to langfuse/langfuse:2 at that point
