### ISSUE TITLE
Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name.

### ISSUE THREAD

**Issue by paolotamag** [langfuse/langfuse#1972]
### Describe the bug

I used a langchain sequential chain, the first chain was with Claude, the second with GPT4.
As I executed the chain with the callback to langfuse cloud API, I get the following error..

`'repr'
Traceback (most recent call last):
  File "C:\Users\paolo\.conda\envs\langchain-test\Lib\site-packages\langfuse\callback\langchain.py", line 626, in _parse_model_and_log_errors
    model_name = _extract_model_name(serialized, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\.conda\envs\langchain-test\Lib\site-packages\langfuse\extract_model.py", line 287, in _extract_model_name
    model = _extract_model_by_pattern("ChatAnthropic", serialized, "model")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paolo\.conda\envs\langchain-test\Lib\site-packages\langfuse\extract_model.py", line 342, in _extract_model_by_pattern
    extracted = _extract_model_with_regex(pattern, serialized["repr"])
                                                   ~~~~~~~~~~^^^^^^^^
KeyError: 'repr'
Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name. Please create an issue so we can fix your integration: https://github.com/langfuse/langfuse/issues/new/choose
`

### To reproduce

```
langchain                 0.1.17                   pypi_0    pypi
langchain-anthropic       0.1.11                   pypi_0    pypi
langchain-community       0.0.36                   pypi_0    pypi
langchain-core            0.1.48                   pypi_0    pypi
langchain-text-splitters  0.0.1                    pypi_0    pypi
langfuse                  2.28.2                   pypi_0    pypi
langsmith                 0.1.52                   pypi_0    pypi
```


```
from langchain.chains import LLMChain
chain_one = LLMChain(llm=chat_Claude, prompt=prompt_template, output_key="second_input")

chain_two = LLMChain(llm=chat_GPT4, prompt=prompt_template, output_key="output")


from langchain.chains import SequentialChain
double_chain = SequentialChain(chains=[chain_one , chain_two],
                               input_variables = ['text','style','format_instructions'],
                               output_variables = ['second_input','output'],
                               verbose=True
                              )
from langfuse.callback import CallbackHandler
langfuse_handler = CallbackHandler(
    secret_key="xxxxxxxxxxxxxxxxxxx",
    public_key="xxxxxxxxxxxxxxxxxxx",
    host="https://cloud.langfuse.com", # 🇪🇺 EU region
  # host="https://us.cloud.langfuse.com", # 🇺🇸 US region
)


output_all = double_chain(all_params, callbacks=[langfuse_handler])

```

### SDK and container versions

_No response_

### Additional information

_No response_

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Thanks for reporting. How do you instantiate the two chat models?

**Comment by paolotamag** [comment]
You mean on LangChain side right?

```
from langchain_anthropic import ChatAnthropic
claude_key = "xxxxxxxxxxxxxxxxxxxxxxxxx"
chat_Claude = ChatAnthropic(model="claude-3-sonnet-20240229", temperature=0.2, max_tokens=1024, api_key=claude_key)
```

and

```
from langchain.chat_models import ChatOpenAI
key = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
llm_model = "gpt-4"
chat_GPT4 = ChatOpenAI(temperature=0.0, model=llm_model, openai_api_key=key)
```

I tried to add the key on your cloud langfuse platform for anthropic too but i could not find it in the dropdown..

<img width="647" alt="image" src="https://github.com/langfuse/langfuse/assets/11270852/8f9d50ee-0a96-4c2e-a0f7-2a917d657a14">

was i supposed to do more on the langfuse side to properly link your platform to my langchain traces?

**Comment by marcklingen** [comment]
Thanks for sharing, I was interested in the ChatAnthropic and ChatOpenAI imports. Storing the LLM API key is only necessary to use evaluation in Langfuse, your regular LLM calls directly use the model providers and get logged to langfuse only asynchronously in the background.

**Comment by marcklingen** [comment]
We aim for a generalizable solution. Follow https://github.com/langfuse/langfuse/issues/1920 to understand more of the context and get updates on this. I'm sorry for the inconvenience. Please reopen in case this throws an exception instead of just logging a warning in your case.

**Comment by maxdeichmann** [comment]
@paolotamag, I just released a fix for this. Please re-open if this persists for you: https://github.com/langfuse/langfuse-python/releases/tag/v2.29.1

**Comment by paolotamag** [comment]
Hi thanks,
I received a similar error running OLlama with LLama3

'''
Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name. Please create an issue so we can fix your integration: https://github.com/langfuse/langfuse/issues/new/choose
'''

This was the code from LangChain

'''
from langchain_community.llms import Ollama

llama = Ollama(model="llama3")

chain_creates_quiz = LLMChain(llm=llama, prompt=prompt_template, output_key="quiz")
chain_parses_quiz = LLMChain(llm=llama, prompt=prompt, output_key="parsed_quiz")

double_chain = SequentialChain(chains=[chain_creates_quiz, chain_parses_quiz],
                               input_variables = ['text','style','format_instructions'],
                               output_variables = ['quiz','parsed_quiz'],
                               verbose=True
                              )

all_params = {}
all_params['style'] = system_message_style
all_params['text'] = text_to_quiz
all_params['format_instructions'] = format_instructions

output_all = double_chain(all_params, callbacks=[langfuse_handler])
'''

Will that be fixed too?

**Comment by paolotamag** [comment]
updated package on pip, issue is gone now
llama3 and claude appeared on the dashboard :)

<img width="559" alt="2024-05-07_13h16_00" src="https://github.com/langfuse/langfuse/assets/11270852/078f60ae-c12a-4d6b-ba10-2448801a98f8">


thank you! you guys are so quick!

**Comment by maxdeichmann** [comment]
@paolotamag thanks a lot for the feedback. Yes, ollama should be working as well. Let me know if you run into issues.
