### ISSUE TITLE
bug: TypeError: observe() fails if output is a type container including a generator function

### ISSUE THREAD

**Issue by liamvdv** [langfuse/langfuse#1977]
### Describe the bug

Please refer to https://github.com/langfuse/langfuse/issues/1855. The current implementation fails to handle the case that a output is a container (tuple, list), which contains a generator function item.

### To reproduce

```py
from langfuse.decorators import observe

anything = None

def gen():
    for i in range(10):
        yield i

@observe()
def myfunc(g):
    return (g,)   # fails if wrapped in any container type, tuple being a common one
    # or return [g]
    # or return (g, anything)
    # ....

myfunc(gen())
```

### SDK and container versions

2.28.2, following the 'fix' for #1855 which solved it for the non-container type.

### Additional information

It's a common pattern to wrap generators and pass secondary metadata in a tuple. Please correctly handle wrapping containers, at minimum for a single level of wrapping.

<img width="1009" alt="image" src="https://github.com/langfuse/langfuse/assets/62619917/bb3f93d9-ae86-4574-965c-b12fe903f388">

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks for reporting this 🙏

**Comment by foragerr** [comment]
I noticed a similar issue with function args. It is easy to introduce function args of types that aren't fully handled by lanfuse-python's [serializer](https://github.com/langfuse/langfuse-python/blob/main/langfuse/serializer.py#L24). In my case it was a `slack_sdk` class. langfuse-python logs a `ValueError` and the server returns a `400:Not Valid JSON`

I suppose a workaround is to set one or both capture flags to `False` and supply custom inputs and output vaules.
```
@observe(capture_input=False, capture_output=False)
```

```
    langfuse_context.update_current_observation(
        input="Table?", output="Tennis!"
    )
```
