### ISSUE TITLE
[LFC-192] OpenTelemetry

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#199]
OTel as (1) additional data source for more execution details, and (2) alternative integration to replace current SDKs

<sub>[LFC-192](https://linear.app/langfuse/issue/LFC-192/open-telemetry)</sub>

**Comment by pamelafox** [comment]
Did you all make a decision regarding OTel integration? My team at Microsoft is curious (since Azure Monitor brings in OTel traces).

**Comment by marcklingen** [comment]
Currently we see otel to be promising for some of our users (just monitor/log production traffic), whereas it does not work for others (also want to quickly iterate locally / in batches / in notebooks). Thus, we cannot yet shift all of our tracing/ingestion to OTel.

The best way forward here is most likely to build an OTel compatible receiver/processor as an alternative way to ingest data into langfuse for those who want it for their production deployments.

As generally building integrations for Langfuse is very simple, we are very open to collab on this, right now, there are higher impact features to ship for most of our users especially with a focus on evaluation and testing of LLM applications.

**Comment by pamelafox** [comment]
Okay, that makes sense. I don't have a strong opinion currently, I'll look out for feedback from our Microsoft customers.

**Comment by gingters** [comment]
I would also love to see support of OpenTelemetry ingestion.
My specific reason would be to enable observablity of [Semantic Kernel](https://github.com/microsoft/semantic-kernel) based applications in langfuse. It would be awesome if we could see the single steps of SK applications in the same way we can currently see langchain-based application traces.

**Comment by benjamincudi** [comment]
I'd also love to see support in some kind for this - in particular, I'd love to be able to incorporate (or leverage) Langfuse tracing as part of broader application tracing, and send those traces through an OpenTelemetry Collector rather than directly to `LANGFUSE_HOST`

Is this something that has been tested or attempted previously with any success?

**Comment by athewsey** [comment]
Also interested in this feature - my (customers') use-case would be similar to the above: Integrate Langfuse's traces with those from other microservices/apps in AWS X-Ray for end-to-end debugging & visibility.

**Comment by johnson-liang** [comment]
When it comes to Langfuse ingesting OpenTelemetry, I think it is more straightforward to implement an [OpenTelemetry exporter](https://opentelemetry.io/ecosystem/registry/?component=exporter) that calls Langfuse SDK for each OpenTelemetry trace.

**Comment by marcklingen** [comment]
Merging this into the discussion here: https://github.com/orgs/langfuse/discussions/2509
