### ISSUE TITLE
feat: archive evaluation template via the ui

### ISSUE THREAD

**Issue by manu2022** [langfuse/langfuse#1994]
### Describe the bug

Once you have your template created, you can set it as active or inactive, but it is not possible to delete

### To reproduce

Just log in to the page and check the feature :)

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks for adding this. I adapted the issue in order to archive instead of delete. Deletion is risky here due the features that depend on templates being immutable.
