### ISSUE TITLE
bug: Found broken /docs/evals link.

### ISSUE THREAD

**Issue by johnnydevriese** [langfuse/langfuse#2018]
### Describe the bug

<img width="437" alt="image" src="https://github.com/langfuse/langfuse/assets/29763777/57862dfb-1e9c-4d08-800c-fbf48d5a29a0">

the info link on Eval Templates is just a placeholder.

### To reproduce

Go to Langfuse cloud dashboard -> Evaluation -> Templates -> click on info tip on `Eval Templates`. 

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks for reporting, fixed here https://github.com/langfuse/langfuse/commit/d2d10893e1ffc0e171b495c87291f6e0bfe13544

we'll release this later today
