### ISSUE TITLE
feat: Add metadata to manually created spans / observations

### ISSUE THREAD

**Issue by l4b4r4b4b4** [langfuse/langfuse#202]
### Describe the feature you'd like to request

Would love to be able to set metadata fields on manually created spans:

### Describe the solution you'd like to see

```python
langfuse_handler.setNextSpan(next_span_id, metadata_field_1="foo",metadata_field_2="bar")
```

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
Not needed, can use metadata field on Langchain objects. Langfuse callback handler automatically adds these to Langfuse objects.
