### ISSUE TITLE
docs: Self-host GCP Cloud Run / Cloud SQL instructions missing steps

### ISSUE THREAD

**Issue by justinwiley** [langfuse/langfuse#2044]
### Describe the bug

The instructions describe setting up Cloud Run and Cloud SQL, but leave off granting 'Cloud SQL Client' permissions to the service accounts necessary to connect, resulting in the error `Error 403: boss::NOT_AUTHORIZED: Not authorized to access resource. Possibly missing permission cloudsql.instances.connect` when deploying the Laangfuse container.

After creating cloud run, users will need to:

- search for and select Service Accounts from the Google Cloud search box
- find the service <your project>@appspot.gserviceaccount.com <some number>-compute@developer.gserviceaccount.com
- search for and select IAM & Admin in the search box
- click "Grant Access", then Add Principals
- enter the first service account name
- Select the "Cloud SQL Client" role and save
- repeat for the second service account role

https://langfuse.com/docs/deployment/self-host

### To reproduce

Follow the instructions in self-host -> Google Cloud Platform (Cloud Run & Cloud SQL) -> Option 1: UI Deployment

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks again, added this here: https://github.com/langfuse/langfuse-docs/pull/809
