### ISSUE TITLE
feat: render markdown in input/output fields

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#2109]
### Discussed in https://github.com/orgs/langfuse/discussions/2097

<div type='discussions-op-text'>

<sup>Originally posted by **hburrichter** May 18, 2024</sup>
### Describe the feature or potential improvement

It would be great to see the rendered Markdown of a trace input/output or other observations in the Langfuse UI. 

This would greatly improve the readability of Markdown elements like tables and images. Currently, we need to copy and open image links manually to view and check them.

Perhaps a "Markdown" option could be added to the existing "Pretty | Json" button group in Langfuse?

### Additional information

_No response_</div>

**Comment by marcklingen** [comment]
great idea, @hburrichter do you use ChatML (rendered in "pretty" mode) or plain text?

**Comment by hburrichter** [comment]
Thanks Marc for the fast response!

The input/output of our traces are just two strings, the user and assistant message content. So we not even have this option/button group (Pretty | Json) in the trace view.

Within our traces, we use Pretty/ChatML for quickly checking the list of messages, and JSON for more detailed evaluations. For instance, we pass messages and a tools as one large JSON as the input of certain observations and the ChatML view shows us the nicely formatted list of messages and the JSON view lets us check the tool definitions that were passed alongside the messages to GPT. This works really well for us.

**Comment by marliessophie** [comment]
Markdown is now supported in Pretty mode for trace input/output. See [changelog post](https://langfuse.com/changelog/2024-07-15-render-markdown-trace-preview)
