### ISSUE TITLE
feat: prompt "draft mode" which allows for edits without creating a new `version`

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#2110]
## Suggested change

- Adding a draft mode to prompt management
- Draft prompts can be edited
- Draft prompts have their own reserved label to pull via SDKs ("draft")
- Draft prompts can be saved as a new version (which then includes a proper version number and can be assigned other labels than the "draft")
- If no "draft" prompt exists, the "latest" prompt version is returned by the api when fetching "draft"

**Comment by ajram23** [comment]
I am assuming prompts in draft mode can be fetched and used.
