### ISSUE TITLE
bug: Total Cost For Claude Models Not Working Right

### ISSUE THREAD

**Issue by samitugal** [langfuse/langfuse#2116]
### Describe the bug

In my project, I am using Claude models for code generation. While tracking traces during usage, there is a significant inconsistency in usage despite using the same models and token usage. I think there is a bug for this situation.

![image](https://github.com/langfuse/langfuse/assets/57317518/c1d6c584-b61a-4b34-bb60-3e5a10aec524)

### To reproduce

I am using Claude3 Sonnet as the Claude model. I have not made any additional configuration settings

### Are you interested to contribute a fix for this bug?

No

**Comment by samitugal** [comment]
Hi, I have integrated Langfuse with Python. I am adding tokens, user information, and session ID information to Langfuse from Python. 
![image](https://github.com/langfuse/langfuse/assets/57317518/6cd0d857-7ad0-41b3-a5f3-8fe4d9ed960c)

**Comment by haris-crewlogix** [comment]
I am facing the same issue.

Did anyone find the solution to this?

**Comment by alex-stoica** [comment]
I have not noticed any problem, nor inconsistencies. My code is 

`from langfuse.decorators import observe, langfuse_context
import anthropic
 
anthropic_client = anthropic.Anthropic()
 
@observe(as_type="generation")
def anthropic_completion(**kwargs):
  kwargs_clone = kwargs.copy()
  input = kwargs_clone.pop('messages', None)
  model = kwargs_clone.pop('model', None)
  langfuse_context.update_current_observation(
      input=input,
      model=model,
      metadata=kwargs_clone
  )
 
  return anthropic_client.messages.create(**kwargs).content[0].text
 
@observe()
def main(content):
  return anthropic_completion(
      model="claude-3-opus-20240229",
      max_tokens=1024,
      messages=[
          {"role": "user", "content": content}
      ]
  )
 
main(content)`

Which is mostly the same as in the official example

**Comment by usersina** [comment]
I also saw the same behavior, albeit on `v2.93.4 EE`. I've been using `@langchain/openai`'s `ChatOpenAI` with LiteLLM (tweaking the base url and api key to point to my proxy's).

![image](https://github.com/user-attachments/assets/5bb65189-ac6d-478e-945b-a0818b848b6e)
![image](https://github.com/user-attachments/assets/def44b80-0465-48c1-8600-cc55b65f6ed3)
![image](https://github.com/user-attachments/assets/0c2a3948-769e-4cd1-a6a6-506ac4379d00)

My team will be migrating to `v3` soon... Once that's taken care of, I will be updating this thread.
