### ISSUE TITLE
bug: Are Dataset Item IDs are expected to be unique across accounts/projects?

### ISSUE THREAD

**Issue by harikv** [langfuse/langfuse#2167]
### Describe the bug

We've been encountering 500 Internal Server Errors when using the LangFuse Python SDK to insert/upsert dataset_items. Our use cases requires us to have unique (but reproducible) IDs for every item in a dataset as the expected_outputs should be allowed to evolve over time and hence updated as necessary.

### To reproduce

1. Create a dataset_item using:
`langfuse.create_dataset_item(
            dataset_name=...,
            input=input,
            expected_output=expected_output,
            metadata=metadata,
            id=<a deterministic id>)`

2. Try to do the same thing with the same ID for a different dataset. Ideally we should expect this to get created, but this fails with an opaque `langfuse.api.core.api_error.ApiError: status_code: 500, body: {'error': 'Internal Server Error'}`

3. Try to do the same with the same ID for a different account, and that also fails with the same error

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks for raising this. We expect ids to be unique (most teams uuids). Can you prefix your <a deterministic id> with the dataset name or id in order to make it unique?

**Comment by marcklingen** [comment]
Fixed in https://github.com/langfuse/langfuse/releases/tag/v2.66.0
