### ISSUE TITLE
bug: Trace is not created with Llama Cpp models

### ISSUE THREAD

**Issue by omarcevi** [langfuse/langfuse#2214]
### Describe the bug

Traces are not being detected after version 2.6.3 in langfuse when using llama.cpp as a model. previously the model was not being detected. but even after the latest updates the traces are still not being detected

I'm not getting any kind of error message after the latest updates but the traces are not shown.

logs show that the chain is being detected however no trace is sent to the server.

### To reproduce

Use langfuse => 2.6.3 with llama.cpp model 

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
How do you run this application? I assume it is locally when using llama.cpp. If the execution terminates, traces might not have been sent correctly. You can force this by using the flush method of the respective integration. More typical debugging steps here: https://langfuse.com/faq/all/missing-traces

If you keep having this issue, please share a short snippet to reproduce it and we'll have a look

**Comment by omarcevi** [comment]
I do run the application locally using llama.cpp, and yes we do use the flush method according to the documentation

heres a snippet of the run function:
```
def run(query, memory, chain, metadata={}, **kwargs):
    logging.info(f"ask llm running: {query}")
    try:
        trace = langfuse.trace(id=id, user_id=user_id, metadata=metadata)
        lf_handler = trace.get_langchain_handler()
        lf_handler.setNextSpan(kwargs.get(...))
        result = chain.invoke(
            {"input": query, "chat_history": memory},
            config={"callbacks": [lf_handler]},
        )
    except Exception as e:
        logging.error(f"REPLY error {e}")
        result = str(e)
    else:
        logging.info(f"LLM replied: {result}")
    finally:
        langfuse.flush()
    return result
```

and at 2.6.3 this is the resulting chain
<img width="403" alt="image" src="https://github.com/langfuse/langfuse/assets/63335393/8bf71298-52b2-49ec-9b78-9268af76864d">

with the latest version of langfuse:
<img width="406" alt="image" src="https://github.com/langfuse/langfuse/assets/63335393/40b8636f-3a30-49e4-bd32-60f935da0a49">

the trace is created but no chain 

versions that are used
```
langchain==0.1.16
langchain-community==0.0.34
langfuse==2.6.3 # for first photo
langfuse==2.36.1 # for second photo
llama-cpp-python[server]==0.2.75
celery==5.3.6
redis==4.0.2
```

**Comment by cereniyim** [comment]
@marcklingen I am having a similar issue, did you have a chance to look into this bug? Thank you 🤗

**Comment by marcklingen** [comment]
> @marcklingen hey no worries thank you for checking back.
> 
> yeah as you said, implementing the solution you recommended solved it for me. there was no error message stating that `lf_handler.setNextSpan` was depecrated when using newer versions.
> 
> Thank you again for your help.

perfect, glad to hear this. I've just added deprecation warnings to these methods ([PR](https://github.com/langfuse/langfuse-python/pull/775))
