### ISSUE TITLE
Add devcontainers / GitHub Codespaces for this repo

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#2247]
This would make contributing to Langfuse so much easier.

Setup steps (see [contributing.md](https://github.com/langfuse/langfuse/blob/main/CONTRIBUTING.md))
- run infra command with docker-in-docker to spin up redis and postgres instances: `pnpm run infra:dev:up`
- create env if it does not exist: `[ ! -f .env ] && cp .env.dev.example .env`
- run dx to install dependencies and reset/migrate/seed the db: `pnpm run dx`

**Comment by 4t8dd** [comment]
let me do this.

**Comment by marcklingen** [comment]
sure, let me know if you have any questions

**Comment by 4t8dd** [comment]
Actually there are two ways: docker in docker and docker compose.
But it took a little longer for docker compose way. Because it does some building stuff to build the environment.

Well, for docker in docker, it may take 2-3 min before your can get access the UI.
