### ISSUE TITLE
[LFC-196] [Python-SDK] Haystack Integration

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#227]
Callback handler for haystack
https://github.com/deepset-ai/haystack

Chainlit integration with haystack might be a good reference implementation
https://docs.chainlit.io/integrations/haystack

<sub>[LFC-196](https://linear.app/langfuse/issue/LFC-196/[python-sdk]-haystack-integration)</sub>

**Comment by ilkersigirci** [comment]
I have recently discovered `langfuse` and loved it. But I want to use it with `haystack`. Will there be a haystack 2.x integration?

**Comment by marcklingen** [comment]
Hi @ilkersigirci, I've just added a potential Haystack integration to the idea list in GitHub disucssions, feel free to add your +1: https://github.com/orgs/langfuse/discussions/1221

Currently no immediate plans to build the integration it but I am very open for contributions or to discuss with the Haystack authors.
