### ISSUE TITLE
[LFC-199] Pydantic dependency

### ISSUE THREAD

**Issue by maxdeichmann** [langfuse/langfuse#228]
**Current behavior**

* Our package requires Pydantic version < 2.0.0. We have some who would like to run it with > 2.0.0.
* Fern has an issue on how to make changes in their code to support both versions: [https://github.com/fern-api/fern-python/issues/288](https://github.com/fern-api/fern-python/issues/288)

**Expected behaviror**

* Make our SDK agnostic to Pydantic major versions
* Find a way with e.g. poetry dependency groups to test the different environments

<sub>From [SyncLinear.com](https://synclinear.com) | [LFC-199](https://linear.app/langfuse/issue/LFC-199/pydantic-dependency)</sub>

**Comment by prayashm** [comment]
We hit this today, when were releasing an app which uses supabase.
Switching to directly calling the APIs for the time being.

**Comment by maxdeichmann** [comment]
Thanks for the feedback. We are currently thinking about how to solve that.

**Comment by jasonm** [comment]
+1 - evaluating this in an app with Supabase and running into the conflict with langfuse requiring pydantic<2.0 (LMK if +1s are not helpful - thanks for releasing langfuse! 😄)

**Comment by marcklingen** [comment]
@jasonm helpful, thanks for adding your +1. We consider removing the dependency on Pydantic when rebuilding our ingestion API. Will keep you updated here

**Comment by Bl4ckEnd** [comment]
hi there, we also use pydantic 2.4 and would like try langfuse, which is currently not possible with our setup.

**Comment by maxdeichmann** [comment]
Hi all, we fixed this issue in version `1.1.3` of our package. Please re-open if there are any issues.
