### ISSUE TITLE
bug: langfuse_context.configure not working

### ISSUE THREAD

**Issue by bgreal5** [langfuse/langfuse#2291]
### Describe the bug

trying to update the host, public_key, and secret_key via the langfuse_context.configure method does not work

### To reproduce

do not set the LANGFUSE_HOST, LANGFUSE_PUBLIC_KEY, LANGFUSE_PRIVATE_KEY env variables and try to connect to a self hosted langfuse instance. Your traces will not appear in the instance. Only the env vars seem to work

### SDK and container versions

langfuse==2.33.0

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
can you share a snippet to reproduce this issue? We run CI tests for this configure command and would like to add additional tests to cover this issue that you are having

**Comment by bgreal5** [comment]
This is the code snippet I'm using (printed the tokens going in to verify they are correct)

  @observe()
  def _call_model(self, input, langfuse_id):
      print("- " + colored("INPUT:", 'blue') + f" {input}")
      if langfuse_id is not None:
          print("Setting LangFuse context.")

          # Add our auth context
          langfuse_context.configure(
              secret_key=LANGFUSE_SECRET_KEY,
              public_key=LANGFUSE_PUBLIC_KEY,
              host=LANGFUSE_HOST
          )
          # Set the langfuse context to the testing ID
          langfuse_context.update_current_trace(
              tags=[langfuse_id]
          )
      result = self.model.run(input)

      langfuse_context.flush()
      
      print("- " + colored("OUTPUT:", 'green') + f" {result}")
      return result

**Comment by bgreal5** [comment]
also `update_current_trace` with the tags doesn't seem to be actually adding the tag I specified

**Comment by bgreal5** [comment]
Upon further review of y'alls docs, i can see that I was supposed to configure at the top of the application.

Although my issue with the update_current_trace method still persists

**Comment by bgreal5** [comment]
Closing this because I was passing in tags as a list of lists instead of just a list of strings to the `update_current_trace` method. This was causing it to silently fail
