### ISSUE TITLE
feat: dual-axis on dashboard score timeseries chart

### ISSUE THREAD

**Issue by charlieviettq** [langfuse/langfuse#2295]
### Discussed in https://github.com/orgs/langfuse/discussions/2282

<div type='discussions-op-text'>

<sup>Originally posted by **charlieviettq** June 10, 2024</sup>
### Describe the feature or potential improvement

- Use a dual-axis bar chart to update the score chart, including the number of score records in the right column. 
   This enhancement will clarify the data and make it more useful for monitoring evaluation results.

### Additional information

_No response_</div>

**Comment by marcklingen** [comment]
Cancelling this issue as stale, the use case has been mostly solved by the new charts for scores at the bottom of the dashboard: [https://langfuse.com/changelog/2024-08-19-score-analytics](https://langfuse.com/changelog/2024-08-19-score-analytics)
