### ISSUE TITLE
[LFC-201] [SDKs] Use env vars to configure the Langfuse Client

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#232]
Currently the Python and JS/TS SDK expect a private and secret key in their respective constructor. It would be nice to set these via environment variables, e.g. for use in staging and CI:

Envs

* `LANGFUSE_PUBLIC_KEY`, in JS also check `NEXT_PUBLIC_LANGFUSE_PUBLIC_KEY` as there are many users using Next.JS for their applications
* `LANGFUSE_SECRET_KEY`
* `LANGFUSE_HOST`

This will lead to not requiring these params in the constructors. Log info to console that Langfuse is disabled if public key or secret key are missing.

**Edit**: envs should be an alternative way to set public/secret key and host. We need to support constructor arguments for backwards compatibility. Thus, they become optional.

* [X] Python SDK
* [ ] JS SDK

<sub>From [SyncLinear.com](https://synclinear.com) | [LFC-201](https://linear.app/langfuse/issue/LFC-201/[sdks]-use-env-vars-to-configure-the-langfuse-client)</sub>

**Comment by marcklingen** [comment]
Python (wip): https://github.com/langfuse/langfuse/issues/232

**Comment by Dev-Khant** [comment]
@marcklingen This is completed for Python SDK.

**Comment by marcklingen** [comment]
Thanks @Dev-Khant, updated the issue accordingly

**Comment by DIWAKARKASHYAP** [comment]
@marcklingen , please check pr langfuse/langfuse-js#40

**Comment by khareyash05** [comment]
Due to long inactivity on this issue , I worked upon a PR. @marcklingen Requesting a review

**Comment by georgegebbett** [comment]
In my experience, SDKs reading env vars directly has always led to pain when that behaviour is not desired (for example two different configs of the same SDK) - if this is implemented it should always be disableable and the env vars should not be used over and above constructor parameters (all these are behaviours that I have run into in the wild...)
