### ISSUE TITLE
bug: Local LLMs (Ollama) are supposed to be free/$0 but price is incrementing based on the output tokens

### ISSUE THREAD

**Issue by timoa** [langfuse/langfuse#2382]
## Versions
I'm using Open WebUI + the Pipelines Langfuse filter + Ollama with Llama3:latest.
Langfuse is the v2.55.1

## Issue
I have created a new custom model price with CHARACTERS and price at $0:
![Screenshot 2024-06-20 at 16 20 54](https://github.com/langfuse/langfuse/assets/1432989/12bf84c9-7702-41d3-90b0-1cdca166b0f7)

The price is supposed to stay at $0, but incrementing for each tokens output (not for input tokens):
![Screenshot 2024-06-20 at 16 21 12](https://github.com/langfuse/langfuse/assets/1432989/98a9c011-1dc5-4cba-b3fb-f0ce517c083e)

![Screenshot 2024-06-20 at 16 22 51](https://github.com/langfuse/langfuse/assets/1432989/39cefa14-4ae6-4bf4-8620-5bdae94f9746)

### To reproduce

Create a new model with CHARACTERS or TOKENS to $0 and run a local LLM like llama3:latest plugged to Langfuse (Python script for ex.):

![Screenshot 2024-06-20 at 16 32 01](https://github.com/langfuse/langfuse/assets/1432989/b73c459d-f109-4a39-a373-d6920fd5f192)

### SDK and container versions

Container version: 2.55.1
SDK: 2.36.1

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Langfuse does not come with default pricing for llama3, do you have another llama3 model configuration which includes a price?

**Comment by timoa** [comment]
Thanks for your quick reply! No, I deployed Langfuse (K8S), connected OpenWebUI + Pipelines, and showed a price for the first traces.

Since you said there is no price by default, I checked the OpenWebUI Pipeline and think this is where the issue is.
There is a kind of calculation of the total cost at the end of the script:

```python
# Update usage cost based on the length of the input and output messages
# Below does not reflect the actual cost of the API
# You can adjust the cost based on your requirements
generation.end(
    output=generated_message,
    usage={
        "totalCost": (len(user_message) + len(generated_message)) / 1000,
        "unit": "CHARACTERS",
    },
    metadata={"interface": "open-webui"},
)
```

https://github.com/open-webui/pipelines/blob/a0ec0103b06a380f20044049908aa8e7fda271dc/examples/filters/langfuse_filter_pipeline.py#L123C9-L133C10

I will use my version of this Python script and send the total cost to 0.

Thanks again for your reply!

**Comment by marcklingen** [comment]
awesome, thanks for confirming that this works as expected
