### ISSUE TITLE
bug: Trace timeline doesn't take into account nested generations

### ISSUE THREAD

**Issue by Manouchehri** [langfuse/langfuse#2384]
### Describe the bug

When the first generation is collapsed, it should be the total time of all the generations, including nested ones.

<img width="1110" alt="image" src="https://github.com/langfuse/langfuse/assets/7232674/27143a4e-9fd3-453d-ad0a-ee7dd24d9120">

<img width="1107" alt="image" src="https://github.com/langfuse/langfuse/assets/7232674/a430ae37-f3b9-45ee-a52b-32acd27f3f60">

### To reproduce

See screenshots above.

### SDK and container versions

v2.55.1

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
cc @marliessophie
