### ISSUE TITLE
bug: new prompt text lost when switching between Chat/Text tabs

### ISSUE THREAD

**Issue by canadaduane** [langfuse/langfuse#2430]
### Describe the bug

Text typed into the "System" prompt section of a new prompt goes missing when you switch back-and-forth between Text/Chat tabs.

### To reproduce

1. Click Prompts -> New Prompt to go to the new prompt page
2. Click the "Chat" tab (under the "Prompt" subheading)
3. Type something into the "Enter a system message here" text input box
4. Click the "Text" tab (under the "Prompt" subheading)
5. Click the "Chat" tab (under the "Prompt" subheading)

The text typed at step 3 will be missing.

### Are you interested to contribute a fix for this bug?

Yes

**Comment by marcklingen** [comment]
Agree that it would be nice if this text persisted when switching between prompt types.

1. This would be easy to achieve when switching between chat (with just a system message) and text.
2. If the chat prompt includes more than a system message, we would need to stringify to text and then parse again into ChatML.

I'm not sure if case 2 is worth the added complexity. And if we do not add case 2, then I'm unsure if case 1 is worth it, as this will work inconsistently. What do you think?

**Comment by marcklingen** [comment]
> I'm not sure if case 2 is worth the added complexity. And if we do not add case 2, then I'm unsure if case 1 is worth it, as this will work inconsistently. What do you think?

thought about this again, not worth the complexity. Please reopen or add comments, would love to get your opinion on this
