### ISSUE TITLE
feat: Allow for custom OAuth scopes when self-hosing

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#2458]
### Discussed in https://github.com/orgs/langfuse/discussions/2376

<div type='discussions-op-text'>

<sup>Originally posted by **0x77dev** June 20, 2024</sup>
### Describe the feature or potential improvement

Extend this to include custom OAuth scopes using env variable: https://github.com/langfuse/langfuse/blob/main/packages/shared/src/server/auth.ts#L68C40-L68C60

For example, Clerk does not allow the `openid` scope, and `profile` is sufficient for auth.js.

### Additional information

- https://clerk.com/docs/advanced-usage/clerk-idp#use-clerk-as-an-o-auth-2-provider
- https://next-auth.js.org/configuration/providers/oauth#using-a-custom-provider
- https://langfuse.com/docs/deployment/self-host#sso</div>

**Comment by 0x77dev** [comment]
Hey @marcklingen, thank you so much for this one, there is still a need to configure additional options. For example, the `idToken` is not supported by Clerk and is currently hardcoded: https://github.com/langfuse/langfuse/blob/main/packages/shared/src/server/auth/customSsoProvider.ts#L20C1-L20C19

It would be beneficial to have the ability to modify anything in the OAuth provider, as described in the Next.js Auth documentation: https://next-auth.js.org/configuration/providers/oauth

If you'd like, I can create a pull request to address this.
