### ISSUE TITLE
bug: custom model pricing is not picked 

### ISSUE THREAD

**Issue by sourabhsinha396** [langfuse/langfuse#2491]
### Describe the bug

Langfuse comes with predefined model for gemini-1.5-flash. This model is neither editable nor delectable. 
I added custom model and its pricing. The title and regex is same as pre-definied model. But my custom user defined pricing is not picked.
![image](https://github.com/langfuse/langfuse/assets/43882893/41e303ae-f1a1-4a9f-a5c3-9b22edb3043e)

### To reproduce

Add custom pricing for gemini-1.5-flash. 

### SDK and container versions

Langfuse : langfuse/langfuse:2
Agent: Litellm

### Are you interested to contribute a fix for this bug?

Yes

**Comment by sourabhsinha396** [comment]
Had there been an option to edit the models or delete it. My custom model would have worked. 
Also, if gemini API pricing varies if we use context caching of if our input token is  > 128K.

So, it makes sense to me to keep the models editable.

Price (input)
$0.35 / 1 million tokens (for prompts up to 128K tokens)
$0.70 / 1 million tokens (for prompts longer than 128K)

Context caching
$0.0875 / 1 million tokens (for prompts up to 128K tokens)
$0.175 / 1 million tokens (for prompts longer than 128K)
$1.00 / 1 million tokens per hour (storage)

**Comment by marcklingen** [comment]
You can delete the model pricing on the far-right of the table (sorry for bad UX right now, this is on our list to make this easier to edit/maintain). We just released a change which will soon allow for more complex pricing logic to account for Gemini pricing as well

**Comment by marcklingen** [comment]
Can you share an example trace (using share publicly on the top right)? Would love to look into this to understand why your model price is not picked up correctly.

**Comment by sourabhsinha396** [comment]
Hey @marcklingen Thanks for the prompt reply. 
I tried to delete the mode by going to the far right. But built-in models can not be deleted. 
![image](https://github.com/langfuse/langfuse/assets/43882893/64cfe998-ce2a-4491-995f-76dd11ee4116)

**Comment by marcklingen** [comment]
> Hey @marcklingen Thanks for the prompt reply. I tried to delete the mode by going to the far right. But built-in models can not be deleted. ![image](https://private-user-images.githubusercontent.com/43882893/346270114-64cfe998-ce2a-4491-995f-76dd11ee4116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0Mjg0NTgsIm5iZiI6MTcyMDQyODE1OCwicGF0aCI6Ii80Mzg4Mjg5My8zNDYyNzAxMTQtNjRjZmU5OTgtY2UyYS00NDkxLTk5NWYtNzZkZDExZWU0MTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA4NDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZDk1NTgzZTYxOTE4ODY5YWFiMTAzNDdkZjMxMGQwYWIxZTBkNWRlYjUwNTI4N2E2NDdhNTM2MjMxODdkMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3-vvA1TQCvCswcVbLJhxCOjKczuD8M6ZWLvfj9Z2Q1c)

You can override the price though by creating an own model definition with the same name. We will make improvements to the UI for this/

**Comment by yusuke-intern** [comment]
@marcklingen @sourabhsinha396 
Do we have specific reason why showing cost of Gemini models are not available officially on Langfuse?

**Comment by yusuke-intern** [comment]
I really need this visualisation.

**Comment by cikalT** [comment]
> > Hey @marcklingen Thanks for the prompt reply. I tried to delete the mode by going to the far right. But built-in models can not be deleted. ![image](https://private-user-images.githubusercontent.com/43882893/346270114-64cfe998-ce2a-4491-995f-76dd11ee4116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0Mjg0NTgsIm5iZiI6MTcyMDQyODE1OCwicGF0aCI6Ii80Mzg4Mjg5My8zNDYyNzAxMTQtNjRjZmU5OTgtY2UyYS00NDkxLTk5NWYtNzZkZDExZWU0MTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA4NDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZDk1NTgzZTYxOTE4ODY5YWFiMTAzNDdkZjMxMGQwYWIxZTBkNWRlYjUwNTI4N2E2NDdhNTM2MjMxODdkMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3-vvA1TQCvCswcVbLJhxCOjKczuD8M6ZWLvfj9Z2Q1c)
> 
> You can override the price though by creating an own model definition with the same name. We will make improvements to the UI for this.

<img width="1405" alt="Screenshot 2024-07-10 at 18 28 43" src="https://github.com/langfuse/langfuse/assets/35053051/5930317f-c097-4fbc-aa08-009bcc1cbc20">

I also experienced something similar. I have made a custom model to suit the pricing of Google Gemini, especially the 1.5 pro and 1.5 flash (by calculating the price myself and using tokenizer from openai chatgpt 3.5), and have been using it for the last 3 months. But today Langfuse stopped tracing. In the dashboard, identified models section it also stops showing Google Gemini.

**Comment by marcklingen** [comment]
@cikalT do you use Langfuse Cloud? Did you update the models or SDK versions? Would love to understand what is happening here. Maybe it's easiest if you create a new issue with the full context of this issue and we can reference this issue in case they are related

**Comment by marcklingen** [comment]
Closing this as stale. We plan to make configuring custom models easier soon, however I am unable to replicate this specific issue.
