### ISSUE TITLE
Unable to get Azure GPT cost when using dspy framework

### ISSUE THREAD

**Issue by Aaryaveerkrishna23** [langfuse/langfuse#2496]
### Describe the bug

![image](https://github.com/langfuse/langfuse/assets/86841659/67f8ce41-24d9-442b-9f11-5765a6a7698b)

### To reproduce

Code is proprietary , but Please look into how can we display models connected via DSPY on langfuse traces or dashboard . As DSPY is already been connected to various frameworks including langchain , Milvus.

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Thanks for reporting this. Can you provide a brief example how you integrated DSPy with Langfuse? This would help a ton to reproduce and improve this!

**Comment by marcklingen** [comment]
I fully understand that you cannot share your proprietary code

**Comment by Aaryaveerkrishna23** [comment]
> I fully understand that you cannot share your proprietary code

I was simply using the @observe decorator , the traces were visible but not the model's cost .I was using azure gpt-35-turbo

**Comment by marcklingen** [comment]
> > I fully understand that you cannot share your proprietary code
> 
> I was simply using the @observe decorator , the traces were visible but not the model's cost .I was using azure gpt-35-turbo

Can you share an example trace or code privately? my email: marc at langfuse

**Comment by marcklingen** [comment]
For future reference, this is how to report token counts/cost to Langfuse when using the decorator: [https://langfuse.com/docs/sdk/python/decorators#log-any-llm-call](https://langfuse.com/docs/sdk/python/decorators#log-any-llm-call)<br><br>In the meantime, more native support to track llm calls made via dspy in langfuse has been added to dspy: [https://github.com/stanfordnlp/dspy/pull/1186](https://github.com/stanfordnlp/dspy/pull/1186)<br><br>Closing this now as this has been stale for a while
