### ISSUE TITLE
feat: PR template for contributions

### ISSUE THREAD

**Issue by Dev-Khant** [langfuse/langfuse#250]
### Describe the feature you'd like to request

I suggest having a proper template for PRs. When a person contributes and makes a PR if the information needs to be filled like a description of the feat/bug, which issue it resolves etc.

### Describe the solution you'd like to see

A template for PR like : 

`Description`
Describe what changes you made.

`Issue Resolved` # (issue)

`Checks`
- My code passes all tests
- I have formatted the code
- It generates no new warnings
- Have written documentation or added comments for it

### Contribute

- [X] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
@Dev-Khant sounds good, do you want to contribute this? Happy to get it merged

**Comment by Dev-Khant** [comment]
@marcklingen I have made the PR. Please do have a look. Thanks

**Comment by Dev-Khant** [comment]
Similarly if you want then I can add to langfuse-python as well.

**Comment by marcklingen** [comment]
@Dev-Khant this would be great across all repos if you'd like to add it

**Comment by marcklingen** [comment]
Thank you
