### ISSUE TITLE
feat: add non-numeric scores via sdks

### ISSUE THREAD

**Issue by xinyiqin** [langfuse/langfuse#2514]
### Describe the bug

why scores can be set as categorical type by user annotations, but cannot be set in python SDK？
all scores are NUMERIC type now.

### To reproduce

langfuse.score(
          id=id,
          name="intent",
          trace_id=generation.trace_id,
          observation_id=[generation.id](http://generation.id),
          data_type='CATEGORICAL',
          value=0,
          string_value=str(intent_lst),
          comment=str(intent_lst),
        )

### SDK and container versions

*No response*

### Additional information

*No response*

### Are you interested to contribute a fix for this bug?

```
langfuse.score(
   name='intent', 
   trace_id='1234', 
   data_type='Categorical' # new 
   value='correct' # new, value: float -> value: float | string  
   configId='4566' # new 
```

**Comment by marcklingen** [comment]
Thanks for reporting. Yes, this is a current limitation. We will release new APIs and SDK versions to support non-numeric score ingestion. ETA: this week
