### ISSUE TITLE
feat: JavaScript/TypeScript Support in LangFuse and LangChain for Dataset Experimentation

### ISSUE THREAD

**Issue by guidev** [langfuse/langfuse#2515]
## Is your feature request related to a problem?

Currently, there is no support for running experiments on datasets using LangChain in JavaScript/TypeScript environments.

## Describe the solution you'd like

I would like to see a JavaScript/TypeScript implementation similar to the following Python functionality:

```
dataset = langfuse.get_dataset("<dataset_name>")

for item in dataset.items:
    # Langchain callback handler that automatically links the execution trace to the dataset item
    handler = item.get_langchain_handler(run_name="<run_name>")
    
    # Execute application and pass custom handler
    my_langchain_chain.run(item.input, callbacks=[handler])
```

## Related sub-libraries

- [ ] All of them
- [ ] langfuse
- [ ] langfuse-node

#### *Thank you* for your feature request – we love each and every one!

**Comment by camwardy** [comment]
+1 for this feature please

**Comment by camwardy** [comment]
Is there a workaround in the time being for this?

**Comment by marcklingen** [comment]
> Is there a workaround in the time being for this?

Yes, you can use the [interoperability with the regular SDK](https://langfuse.com/docs/integrations/langchain/tracing#interoperability) to achieve this. This should work:

```typescript
const dataset = await langfuse.getDataset("<dataset_name>");
 
for (const item of dataset.items) {
  const trace = langfuse.trace();
  const langfuse_handler = new CallbackHandler({
    root: trace,
    updateRoot: true,
  });
  const output = chain.invoke({"input": "<user_input>"}, config={"callbacks": [langfuse_handler]})
 
  // link the execution trace to the dataset item and give it a run_name
  await item.link(trace, "<run_name>", {
    description: "My first run", // optional run description
    metadata: { model: "llama3" }, // optional run metadata
  });
 
  // optionally, evaluate the output to compare different runs more easily
  trace.score({
    name: "<score_name>",
    value: myEvalFunction(item.input, output, item.expectedOutput),
    comment: "This is a comment", // optional, useful to add reasoning
  });
}
 
// Flush the langfuse client to ensure all data is sent to the server at the end of the experiment run
await langfuse.flushAsync();
```

Hope this helps! Let me know if you have any questions.

**Comment by hassiebp** [comment]
Tracking progress here: https://github.com/langfuse/langfuse/issues/1970

**Comment by hassiebp** [comment]
Hi @guidev - this has been released 👍🏾 Please upgrade your [Langfuse JS SDK](https://github.com/langfuse/langfuse-js/releases/tag/v3.27.0) and [check out our docs on how to get started (see tab Langchain (JS/TS))](https://langfuse.com/docs/datasets/overview#run-experiment-on-a-dataset)

**Comment by camwardy** [comment]
Amazing! Really appreciate the speed on getting this implemented, thank you! 🙏 @hassiebp @marcklingen
