### ISSUE TITLE
feat: Request to Add Get list of traces Functionality to langfuse-js SDK

### ISSUE THREAD

**Issue by guidev** [langfuse/langfuse#2516]
## Is your feature request related to a problem?

I've noticed that while there is a REST API available for getting the list of traces (GET /api/public/traces), this functionality is not yet available in the SDK.

To retrieve a list of traces, we currently need to directly interact with the REST API, which involves handling HTTP requests and responses manually. This is not as efficient and seamless as using the SDK functions.

## Describe the solution you'd like

It would be highly beneficial to include a function in the langfuse-js SDK that encapsulates this API call. This addition would streamline development by reducing the need for boilerplate code and by providing a more consistent and simplified interface.

## Related sub-libraries

- [ ] All of them
- [ ] langfuse
- [ ] langfuse-node

#### *Thank you* for your feature request – we love each and every one!

**Comment by marcklingen** [comment]
forgot to close this issue here, I added `fetch_*` methods to the JS SDK: https://langfuse.com/changelog/2024-07-04-query-traces-via-sdks

```typescript
import { Langfuse } from "langfuse";
const langfuse = new Langfuse();
 
// Fetch list of traces, supports filters and pagination
const traces = await langfuse.fetchTraces();
 
// Fetch a single trace by ID
const trace = await langfuse.fetchTrace("traceId");
 
// Fetch list of observations, supports filters and pagination
const observations = await langfuse.fetchObservations();
 
// Fetch a single observation by ID
const observation = await langfuse.fetchObservation("observationId");
 
// Fetch list of sessions
const sessions = await langfuse.fetchSessions();
```

**Comment by guidev** [comment]
Hi, thank you... 
Can you add a `fetchSession("sessionId")` method? 
https://api.reference.langfuse.com/#get-/api/public/sessions/-sessionId-

**Comment by marcklingen** [comment]
> Hi, thank you... Can you add a `fetchSession("sessionId")` method? https://api.reference.langfuse.com/#get-/api/public/sessions/-sessionId-

@guidev, I'd recommend to use fetchTraces instead with `sessionId` as an argument as the GET session api is a legacy api that is not paginated.
