### ISSUE TITLE
feat(rbac): add scope for projects:create to restrict viewers from creating own projects

### ISSUE THREAD

**Issue by superpoussin22** [langfuse/langfuse#2517]
### Describe the bug

as project reader (view-only) , I think a user shouldn't be able to create new project in particular because even an admin can't see the created project unless querying the database 

### To reproduce

creat ea project
add someone as project reader
ask the project reader to try to create a new project in langfuse 

### Are you interested to contribute a fix for this bug?

Yes

**Comment by marcklingen** [comment]
Instead of creating a new issue for this, I edited the title to be able to keep track of this change as it is implemented

**Comment by marcklingen** [comment]
You can now restrict users from creating projects with the new organizations released this week: https://langfuse.com/docs/rbac

+ we added a new flag to maintain an allowlist of users who can create organizations on an instance
