### ISSUE TITLE
bug: in python, GET /api/public/traces does not return input and output

### ISSUE THREAD

**Issue by GTimothee** [langfuse/langfuse#2540]
### Describe the bug

Using langfuse==2.37.0
I successfully retrieve my traces using GET /api/public/traces
I don't see any "input" or "output" key in the traces.
According to https://api.reference.langfuse.com/#get-/api/public/traces it is supposed to be under trace_list["data"].

### To reproduce

```
import os
import requests

my_tags = <tags_list>
url = f"{os.getenv('LANGFUSE_HOST')}/api/public/traces/"
r = requests.get(
    url,
    headers=headers,
    params={'page': i, 'tags': my_tags}
)
traces = r.json()
print(traces['data'][0].keys())
```

### Are you interested to contribute a fix for this bug?

Eventually

**Comment by marcklingen** [comment]
can you use `get_traces()`?

**Comment by GTimothee** [comment]
thanks for your answer, input is there this time, but its value is "None" every time

**Comment by marcklingen** [comment]
do the same traces have input/output when viewing them in the UI?

**Comment by GTimothee** [comment]
Yes I can see the input and output in the traces. 

here is what I get from my script for example: 
outputs = [(trace.id, trace.output) for trace in traces.data]
[('28af9f31-d6a2-4b14-b0fb-bb8f375f2785', None), ...]

On the UI I see: 
![errorCapture](https://github.com/langfuse/langfuse/assets/39728445/faff3014-bb85-4444-9cdd-7ebd2361faaa)

My version of langfuse server is v2.7.0, could it be the problem ?

**Comment by marcklingen** [comment]
yes! that's why the bug report form asks for these versions. please upgrade and try again

**Comment by GTimothee** [comment]
ok sorry, I keep you in touch

**Comment by marcklingen** [comment]
no worries

**Comment by marcklingen** [comment]
closing for now, please reopen in case this issue persisted on the latest version

**Comment by GTimothee** [comment]
Sorry I took time to come back, it works ;)

**Comment by marcklingen** [comment]
awesome, no worries, thanks for confirming!
