### ISSUE TITLE
bug: can not start docker container on arm64 ubuntu

### ISSUE THREAD

**Issue by sideef5ect** [langfuse/langfuse#2556]
### Describe the bug

```bash
docker run -it --rm langfuse/langfuse:2 
exec /usr/local/bin/docker-entrypoint.sh: exec format error

docker run -it --rm langfuse/langfuse:2 sh
exec /usr/local/bin/docker-entrypoint.sh: exec format error

docker run -it --rm --entrypoint /bin/sh langfuse/langfuse:main -c "ls"
exec /bin/sh: exec format error
```

> The "exec format error" typically indicates that the executable you are trying to run is not compatible with the architecture of the system you are running the container on. This can happen for a few reasons:
> Architecture Mismatch: The image you are trying to run may be built for a different CPU architecture than the one your host machine uses. For example, if you are running on an ARM-based system (like a Raspberry Pi) but the image is built for x86_64, you might see this error.
> Corrupted or Misconfigured Image: The image might be corrupted or incorrectly configured, leading to the entrypoint not being executable.

### To reproduce

OS: ubuntu arm64
```
uname -a
Linux ubuntu 5.15.0-41-generic #44-Ubuntu SMP Thu Jun 23 11:20:13 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

### SDK and container versions

docker container langfuse/langfuse:2

### Are you interested to contribute a fix for this bug?

No

**Comment by sideef5ect** [comment]
```bash
docker image inspect langfuse/langfuse:2
...
        "Architecture": "arm64",
        "Os": "linux",
```

**Comment by jtha** [comment]
@sideef5ect I think the pre-built arm64 images were only available recently. You could just go with langfuse:latest, or peruse yourself which versions have the arm64 image here: https://hub.docker.com/r/langfuse/langfuse/tags

**Comment by marcklingen** [comment]
Thanks for reporting. Will most likely resolved by this change: https://github.com/langfuse/langfuse/pull/2541

**Comment by sideef5ect** [comment]
Thanks for the prompt response, I am building the image on my local machine and it works.
