### ISSUE TITLE
Weird Output for scores when using fetch_traces()

### ISSUE THREAD

**Issue by kevinpkaria** [langfuse/langfuse#2617]
### Discussed in https://github.com/orgs/langfuse/discussions/2616

<div type='discussions-op-text'>

<sup>Originally posted by **kevinpkaria** July 11, 2024</sup>
Upon using the fetch_trace() function and thne printing the scores, I receive an array of IDs instead of the score values. Why so?
An array of proper scores and not unhelpful IDs would be helpful.
<img width="1512" alt="Screenshot 2024-07-11 at 6 06 15 PM" src="https://github.com/langfuse/langfuse/assets/89715638/24137f27-aef6-4e72-b4d1-f6ffc0f7ab2b">
<img width="1512" alt="Screenshot 2024-07-11 at 6 07 41 PM" src="https://github.com/langfuse/langfuse/assets/89715638/034bfec3-3066-478d-b832-f25b523d9065">

</div>

**Comment by marcklingen** [comment]
Happy to help here and thanks for sharing your thoughts on this.

Please do not open a Github discussion thread, issue, and Discord thread. Let's stick to one of the above :) Closing this here in favor of the discussion thread and will copy my response from discord to the thread: https://github.com/orgs/langfuse/discussions/2616

**Comment by kevinpkaria** [comment]
Sure!
