### ISSUE TITLE
bug:  Cost and Avg Latency Not Displayed in Dataset Run Overview with Langfuse Integration in Python and Langchain

### ISSUE THREAD

**Issue by ollesve** [langfuse/langfuse#2621]
### Describe the bug

Hello!

Im using langfuse (currently locally) together with python and langchain and have two issues when it comes to dataset runs.

1. The cost doesn't show up in the dataset run (see attached picture). The cost does how ever show up in the trace connected to the dataset item run and I have specified the model in the run metadata. Any ideas of what might be wrong here?
2. The latency is shown per dataset item in the run view (see attached picture) but in the overview of all test runs the avg latency isn't shown.

Thanks for the help!

No total cost but latency in dataset run
<img width="621" alt="image" src="https://github.com/user-attachments/assets/ade8a01a-4051-4090-938a-7569cdfc9395">

Total cost in trace
<img width="860" alt="image" src="https://github.com/user-attachments/assets/b61f0d00-4583-4315-96d1-8df7cb930371">

No latency in dataset overview
<img width="1200" alt="image" src="https://github.com/user-attachments/assets/826b0d46-a48f-4471-9b09-f15649677a3d">

### To reproduce

Code to run test
```
dataset = langfuse.get_dataset(DATASET_NAME)
    test_run_name = f"test_run_{datetime.now()}"
    evaluation_model = create_eval_model()

    for item in dataset.items:
        with item.observe(
            run_name=test_run_name,
            run_metadata={"model": "gpt-4o-2024-05-13"},
        ) as trace_id:
            agent_answer = ask_question(item.input, show_logs=False)

            result = evaluation_model.invoke(
                {
                    "answer_ground_truth": item.expected_output,
                    "user_question": item.input,
                    "agent_answer": agent_answer,
                }
            )

            item.langfuse.score(
                trace_id=trace_id,
                name="eval_chain",
                value=result.get("evaluation"),
                comment=result.get("comment"),
            )

    langfuse.flush()
```
    

Code to run agent:    
```
    @observe()
def ask_question(question: str, show_logs: bool = True) -> str:
    user_input = {"input": question}
    langfuse_context.update_current_trace(
        name="ask_question",
        session_id=get_git_revision_short_hash(),
        tags=["dev"],
    )
    langfuse_context.update_current_observation(
        input=question,
    )
    agent_tools = get_agent_tools()
    agent_executor = create_agent_executor(agent_tools, show_logs)

    response = agent_executor.invoke(
        user_input,
        config={"callbacks": [langfuse_context.get_current_langchain_handler()]},
    )
    if "Final Answer:" in response["output"]:
        return response["output"].split("Final Answer:")[-1]
    else:
        return "Förlåt jag kan inte svara på din fråga"
```

### SDK and container versions

Self-hosted version: 2.61.1
Python SDK version: 2.39.0

### Are you interested to contribute a fix for this bug?

No

**Comment by giogvn** [comment]
I am having a similar issue when using the method `observe_llama_index` for a dataset item. All the cost information shows up in the dataset item's corresponding Trace, but it is not shown in the Dataset section

**Comment by yevkim** [comment]
Same error using Python (Decorator) - cost is displayed in Traces but not in Dataset view.

**Comment by micahstairs** [comment]
@marcklingen is there an ETA for the fix? This is also affecting us.

**Comment by marcklingen** [comment]
Thanks for the ping, I just aggregated a couple of reports related to this issue and we will prioritize a fix for this

**Comment by rodrigobdz** [comment]
This issue of cost in experiment runs not showing seems to be happening in self-hosted OS version v3.173.0. 

The first row of the experiment run shows "Cost $0.00"

<img width="654" height="172" alt="Image" src="https://github.com/user-attachments/assets/a0f8258b-66ed-4633-b639-fe75ef6a9a8e" />

but clicking on the trace button, cost is shown for this trace:

<img width="1077" height="193" alt="Image" src="https://github.com/user-attachments/assets/c65450fa-7921-4c0e-8924-00dd24dffb77" />
