### ISSUE TITLE
bug: in python, GET /api/public/scores does not return the data

### ISSUE THREAD

**Issue by GTimothee** [langfuse/langfuse#2639]
### Describe the bug

Sorry I am back again with the same kind of error than last time... 

My goal is to retrieve the traces and the scores and merge them in a dataframe for later analysis (evolution through time, etc.). 

Using the Python low level SDK client object I can now retrieve the traces with input, output and score id. When I call the scores/ endpoint, however, it only returns the metadata. I am using the API to retrieve the scores data because I did not find a way to retrieve the scores using the Python SDK.

When I look in the developer tools I can see the whole data that is returned in the Response object. It starts like this: 
```
   {
        "result": {
            "data": {
                "json": {
                    "scores": [
                        {
```
So I don't understand how the data is lost between what is returned by the server and what I get.

### To reproduce

Here is the call:
```python
r = requests.get(
    url = f"{os.getenv('LANGFUSE_HOST')}/api/public/scores",
    headers=headers
)
print(f"scores: {r.content}")
```

Here is the output I get:
```scores: b'{"data":[],"meta":{"page":1,"limit":50,"totalItems":11,"totalPages":1}}'```

### SDK and container versions

Version of the langfuse library: 2.37.0
Version of the server: 2.60.1

### Are you interested to contribute a fix for this bug?

Yes

**Comment by marcklingen** [comment]
thanks for sharing! can you share the server logs as well?

**Comment by marcklingen** [comment]
the devtools call that you see is another api (we use trpc to power the front-end), the public api that can be used directly or via the SDKs has another schema: https://api.reference.langfuse.com/#get-/api/public/scores

**Comment by marliessophie** [comment]
Hey Timothee, thanks for reporting this! 

You are currently on langfuse version 2.60.1 correct? Could you please confirm if your issue persists if you upgrade to version [2.60.3](https://github.com/langfuse/langfuse/releases/tag/v2.60.3) or higher? We had an issue with GET /api/public/scores in v2.60.0 that was fixed in v2.60.3. Apologies for the inconvenience

**Comment by GTimothee** [comment]
Thanks, we will try that ! 
Sorry I took time to get back to you I don't have directly access to the server so I had to ask to someone at my company. The only thing he found in the logs was "Request to route  Get Scores projectId  clxbvafaj4z97x5vog5vsw422 with query  {} and body  {}" apparently so not very useful... 
We will try upgrading the server, I keep you in touch

**Comment by marcklingen** [comment]
thanks @GTimothee

**Comment by marcklingen** [comment]
closing for now as we verified the fix on langfuse cloud, let's reopen in case this is still an issue on the latest version

**Comment by GTimothee** [comment]
Hello :) Sorry for the delay. Just to confirm the fix works 👍

**Comment by marcklingen** [comment]
thank you
