### ISSUE TITLE
bug: JavaScript langfuse-langchain missing support for Bedrock

### ISSUE THREAD

**Issue by tomi-bigpi** [langfuse/langfuse#2659]
### Describe the bug

The JavaScript library for langfuse-langchain does not correctly recognize models or token usage when using AWS Bedrock.

### To reproduce

Use Bedrock with langfuse-langchain. Observe that no pricing or token usage is recorded.

### SDK and container versions

```
    "langfuse-core": "~3.16.1",
    "langfuse-langchain": "~3.16.1",
```

### Additional information

I've opened a PR https://github.com/langfuse/langfuse-js/pull/304 to resolve both issues.

### Are you interested to contribute a fix for this bug?

Yes

**Comment by tomi-bigpi** [comment]
Any updates on getting this reviewed and the PR merged?

**Comment by marcklingen** [comment]
Sorry for moving so slowly, I tagged @maxdeichmann who will have a look

**Comment by hassiebp** [comment]
Thanks for raising this, @tomi-bigpi ! I have linked a PR that fixes this issue once merged and released 👍🏾
