### ISSUE TITLE
bug: Whitespace doesn't display correctly in the web UI

### ISSUE THREAD

**Issue by iuliaturc** [langfuse/langfuse#2660]
### Describe the bug

Neither the "Pretty" nor the "JSON" version preserves white spaces in the Langfuse UI.
It's inconvenient especially when it's important that the inputs are properly formatted (e.g. when inputs are code)

### To reproduce

Log a call with input that contains tabs or newlines.

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Thanks for raising this!

I used the following snippet to reproduce this issue:

````python
from langfuse import Langfuse
langfuse = Langfuse()

example_text = """text code

trace = langfuse.trace(name="github-issue-2660-whitespaces")
trace.generation(
    name="example-generation",
    input=example_text
)
print(trace.get_trace_url())
"""

example_md = """md code

```python
trace = langfuse.trace(name="github-issue-2660-whitespaces")
trace.generation(
    name="example-generation",
    input=example_text
)
print(trace.get_trace_url())
```
"""


trace = langfuse.trace(name="github-issue-2660-whitespaces")
trace.generation(
    name="example-generation",
    input=example_text,
    output=example_md
)
print(trace.get_trace_url())

langfuse.flush()
````

Example trace: https://cloud.langfuse.com/project/cloramnkj0002jz088vzn1ja4/traces/76fff05f-298d-42cf-83bf-7c63c872ec41?observation=c1b86a3d-1079-43e2-b6ae-fe48b42b32ab

---

Whitespaces get stripped when string is collapsed. When string is uncollapsed, it looks good

https://github.com/user-attachments/assets/6df2006f-d2b5-4fdb-8636-4acab8f4ad67

Langfuse Markdown viewer renders codeblocks within markdown correctly, but strips newlines/tabs when rendering code that is outside of a markdown code block

![CleanShot 2024-07-18 at 00 24 13](https://github.com/user-attachments/assets/7792751a-97ca-4aa5-9bdd-c1d0464052b3)

**Comment by marcklingen** [comment]
> Whitespaces get stripped when string is collapsed. When string is uncollapsed, it looks good

Fixed: #2662

**Comment by iuliaturc** [comment]
Phenomenal turnaround time! Thanks Marc.

**Comment by marcklingen** [comment]
Sure, thanks again for reporting this @iuliaturc!

@marliessophie had a quick look into preserving whitespace within markdown outside of code-blocks. This is not straightforward and usually stripped in Markdown (e.g. on GitHub). Thus, we'd keep the behavior as it is right now.
