### ISSUE TITLE
bug: Docker build is failing for web with OOM error

### ISSUE THREAD

**Issue by MomenNano** [langfuse/langfuse#2673]
### Describe the bug

I'm encounter this error whenever I'm trying to build `server` image in `docker-compose.build.yml` file.

After digging deep into this issue it turns out it was failing when it tried to execute below step in docker file
```sh
RUN turbo prune --scope=web --docker
```
which after that will trigger the build step in `package.json` file inside the web folder, and in their it basically runs `next build`.

Below is the error message that I was getting
```sh
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

To resolve this I had to specify and add `NODE_OPTIONS=\"--max-old-space-size=4096\" ` in the same build command to increase the heap size of it. and it works for me.

### To reproduce

```sh
docker compose -f docker-compose.build.yml build server
```

### Are you interested to contribute a fix for this bug?

Yes

**Comment by marcklingen** [comment]
@maxdeichmann are you aware of this issue across the build pipelines? I was able to reproduce this locally

**Comment by MomenNano** [comment]
Also worth mentioning that I was using colima on macos. and noticed a wired behaviour due to the dynamic way that node.js uses to determine the heap size it should use.

so whenever I'm doing `colima start --memory 4` or any value that is less than 16 it's going to choose 2GB as a default heap size, and if you ask colima to use 16GB of memory in that case node.js container will automatically choose 4GB as a default heap in I was not getting that error in this case without any need to increase the heap size using above mentioned command.

But because I normally give less resources to my docker service to use 8GB of memory and 4 cpu cores, I faced this issue.

**Comment by MomenNano** [comment]
I'm happpy to raise a PR if we agree on the solution

**Comment by marcklingen** [comment]
I have no experience with colima, let's wait for @maxdeichmann to chime in here

**Comment by Heucles** [comment]
@MomenNano the adjustment that you've made, you've made on the package.json? 

something on the likes of: 
```js
  "scripts": {
    "preinstall": "npx only-allow pnpm",
    "infra:dev:up": "docker compose -f ./docker-compose.dev.yml up -d",
    "infra:dev:down": "docker compose -f ./docker-compose.dev.yml down",
    "db:generate": "turbo run db:generate",
    "db:migrate": "turbo run db:migrate",
    "db:seed": "turbo run db:seed",
    "db:seed:examples": "turbo run db:seed:examples",
    "nuke": "bash ./scripts/nuke.sh",
    "dx": "pnpm i && pnpm run infra:dev:up && pnpm --filter=shared run db:reset && pnpm --filter=shared run db:seed:examples && pnpm run dev",
    "dx-f": "pnpm i && pnpm run infra:dev:up && pnpm --filter=shared run db:reset -f && pnpm --filter=shared run db:seed:examples && pnpm run dev",
    "build": "NODE_OPTIONS='--max-old-space-size=8192' turbo run build",
    ...
 ```
 ???

**Comment by MomenNano** [comment]
@Heucles 

You need to replace build command on package.json that exists inside **web** folder, I think you're referring to the root package.json here in your example. 

```json
"build": "INLINE_RUNTIME_CHUNK=false NODE_OPTIONS=\"--max-old-space-size=5096\" dotenv -e ../.env -- next build >> log.txt 2>&1",
```

**Comment by marcklingen** [comment]
thanks again for reporting this. I added this to the dockerfile as this only affected docker builds, will be part of the next release

Fixed in https://github.com/langfuse/langfuse/pull/3217
