### ISSUE TITLE
bug: Incorrect name for text-embedding-3-large in models page 

### ISSUE THREAD

**Issue by georgeherby** [langfuse/langfuse#2688]
### Describe the bug

<img width="1268" alt="image" src="https://github.com/user-attachments/assets/cfae2f6b-5cec-47ab-a32c-93e93216a521">

I assume the second `text-embedding-ada-002-v2` should be `text-embedding-3-large`

### To reproduce

Go to Models on local or cloud. 
Go to page 2
Search for text-embedding-3-large

### SDK and container versions

2.64.0

### Are you interested to contribute a fix for this bug?

Yes

**Comment by touhi99** [comment]
is it still fixed? anyone knows how can I modify it in my local instance?

**Comment by marcklingen** [comment]
Thanks again for reporting this, fixed in #2941
