### ISSUE TITLE
bug(ui): Huge markdown prompts cause web UI to hang

### ISSUE THREAD

**Issue by Manouchehri** [langfuse/langfuse#2690]
### Describe the bug

Huge input prompts with markdown seem to cause Langfuse to basically hang the browser tab for several seconds.

<img width="1038" alt="image" src="https://github.com/user-attachments/assets/a665858b-1c8c-46d8-9be5-87e1bb0c801a">

This is a new problem. We should probably automatically turn off markdown if the prompt is beyond a certain size, if it's gonna be this slow.

### To reproduce

Log a huge prompt that uses markdown and json.

### SDK and container versions

v2.64.0

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
We'll look into optimizing performance, this should not be this slow. Thanks for sharing! You can disable markdown rendering  and your setting will be persisted. We will post an update here.

Options to explore:
- improve markdown rendering performance
- collapse output of markdown component similar to json viewer to improve performance when transitioning between different observations with large markdown content

**Comment by marcklingen** [comment]
> I'm using an M1 Max as well, so not a slow machine. :)

can't expect this to require a maxxed out machine to render some text :)

**Comment by marliessophie** [comment]
Thanks again for reporting this issue! We've created a [feature](https://github.com/langfuse/langfuse/issues/3514) to truncate/collapse markdown by default which should be a good way to optimise for performance here.
