### ISSUE TITLE
bug: Invalid Request Data Error in Haystack Integration

### ISSUE THREAD

**Issue by LastRemote** [langfuse/langfuse#2737]
## Description:
While using the [Haystack integration](https://langfuse.com/docs/integrations/haystack/get-started), I encountered a consistent error when one of my customized components returned a `List[sqlglot.Expression]` output. The error message is as follows:
```
Received 400 error by Langfuse server, not retrying: {'message': 'Invalid request data', 'errors': ['Expected object, received string']}
```

## Expected Result:
The pipeline should process the List[sqlglot.Expression] output without errors.

## Actual Result:
The Langfuse server returns a 400 error with the message indicating invalid request data.

Currently I managed to circumvent the issue by casting `sqlglot.Expression` to a string. I am not sure what is the cause of this server-side error, but I am looking forward to seeing the root cause and how to resolve it. Thank you.

## Steps to Reproduce:

Use the Haystack integration.
Configure a customized component to return a List[sqlglot.Expression] output.
Trace the pipeline to observe the error.

For security reasons I am not allowed to paste my own implementation of the component, but I traced down the batch that is causing this error below.

### SDK and container versions

langfuse-2.39.3 langfuse-haystack-0.2.0 haystackai-2.3.0

## Debugging Information:
The error occurs consistently at [task_manager.py#L229](https://github.com/langfuse/langfuse-python/blob/main/langfuse/task_manager.py#L229) when sending the following batch:
```
{'id': 'ebeccc6c-bdab-4f44-9b93-a47fc2f63e19', 'type': 'span-update', 'body': {'traceId': '3533d1ad-878e-4a0c-b347-29d051ea4c5e', 'output': {'sql_responses': [Select(
  expressions=[
    Alias(
      this=Case(
        ifs=[
          If(
            this=Like(
              this=Column(
                this=Identifier(this=REDACTED, quoted=True)),
              expression=Literal(this=REDACTED, is_string=True)),
            true=Literal(this=REDACTED, is_string=True)),
          If(
            this=Like(
              this=Column(
                this=Identifier(this=REDACTED, quoted=True)),
              expression=Literal(this=%REDACTED%, is_string=True)),
            true=Literal(this=REDACTED, is_string=True))]),
      alias=Identifier(this=keyword_group, quoted=False)),
    Sum(
      this=Column(
        this=Identifier(this=REDACTED, quoted=True))),
    Sum(
      this=Column(
        this=Identifier(this=REDACTED, quoted=True)))],
  from=From(
    this=Table(
      this=Identifier(this=REDACTED, quoted=True))),
  where=Where(
    this=And(
      this=And(
        this=And(
          this=EQ(
            this=Column(
              this=Identifier(this=REDACTED, quoted=True)),
            expression=Literal(this=REDACTED, is_string=False)),
          expression=EQ(
            this=Column(
              this=Identifier(this=REDACTED, quoted=True)),
            expression=Literal(this=REDACTED, is_string=True))),
        expression=Like(
          this=Column(
            this=Identifier(this=REDACTED, quoted=True)),
          expression=Literal(this=REDACTED, is_string=True))),
      expression=EQ(
        this=Column(
          this=Identifier(this=REDACTED, quoted=True)),
        expression=Column(
          this=Identifier(this=REDACTED, quoted=False))))),
  group=Group(
    expressions=[
      Column(
        this=Identifier(this=keyword_group, quoted=False)),
      Column(
        this=Identifier(this=REDACTED, quoted=True))]),
  order=Order(
    expressions=[
      Ordered(
        this=Column(
          this=Identifier(this=REDACTED, quoted=True)),
        nulls_first=True)]))]}, 'id': 'edb99230-81bb-4c6b-8265-6120d4d9efe2'}, 'timestamp': datetime.datetime(2024, 7, 25, 8, 27, 25, 4296, tzinfo=datetime.timezone.utc)}
```

### Are you interested to contribute a fix for this bug?

Yes, but I have limited knowledge of telemetry and tracing.

**Comment by hassiebp** [comment]
This is likely due to some non-serializable object in the request data. We have recently merged improvements for this. Please upgrade Langfuse and if issue persists, please open an issue in the haystack repo that is maintaining this integration.
