### ISSUE TITLE
bug: assistant tab is not displaying for completion when stream is enabled

### ISSUE THREAD

**Issue by ss-kumar** [langfuse/langfuse#2742]
### Describe the bug

Assistant section does not appear for completion when the stream is enabled until the next request is posted. The context is flushed immediately after the call to the method decorated with @observe. This issue occurs only after deployment and works fine locally.

```python
@observe(name="Conversation")
async def conversation_with_search_results(request):

response = await conversation_with_search_results(request)
langfuse_context.flush()
langfuse.flush()
```

Assistant section is displayed after another request is posted as shown in the image
![image](https://github.com/user-attachments/assets/a933185b-3583-4701-a6e2-285a10d0cf23)

### To reproduce

Call the completion stream and look for assistant section in langfuse after deployment to Azure app service

```python
@observe(as_type="generation",name="Stream Completion")
def get_completion_stream(messages,session_id,**kwargs):
    prompt = None
    try:
        prompt = langfuse.get_prompt("SYSTEM_MESSAGE")
    except Exception as e:
        print(f"Error retrieving prompt: {e}")

    if prompt is not None:
        langfuse_context.update_current_observation(name="Stream Completion", session_id=session_id, prompt=prompt)
    else:
        langfuse_context.update_current_observation(name="Stream Completion", session_id=session_id)

    return openai_client.chat.completions.create(
        name="stream-completion",
        model=AZURE_OPENAI_MODEL,
        messages = messages,
        temperature=float(AZURE_OPENAI_TEMPERATURE),
        max_tokens=int(AZURE_OPENAI_MAX_TOKENS),
        top_p=float(AZURE_OPENAI_TOP_P),
        stop=AZURE_OPENAI_STOP_SEQUENCE.split("|") if AZURE_OPENAI_STOP_SEQUENCE else None,
        stream=SHOULD_STREAM,
        seed=int(AZURE_OPENAI_SEED)
    )
```

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Thanks for reporting, the issue here is that serverless deployments might fail to send the logs to Langfuse before halting the execution of the API (when finishing the streamed response). Overall, your implementation looks good.

where do you call `get_completion_stream`? Could you flush after the stream is finished?

**Comment by hassiebp** [comment]
Hi @ss-kumar, this sounds like your execution environment in production does not continue flushing between requests, but only delivers events to Langfuse on the next request to your server, assuming the instance is still 'hot'. In order to add a flush _after_ the stream finished but _before_ the environment pauses, could you please wrap your completion stream in a generator function?

```python
@observe(as_type="generation",name="Stream Completion")
def get_completion_stream(messages,session_id,**kwargs):
    prompt = None
    try:
        prompt = langfuse.get_prompt("SYSTEM_MESSAGE")
    except Exception as e:
        print(f"Error retrieving prompt: {e}")

    if prompt is not None:
        langfuse_context.update_current_observation(name="Stream Completion", session_id=session_id, prompt=prompt)
    else:
        langfuse_context.update_current_observation(name="Stream Completion", session_id=session_id)

    stream = openai_client.chat.completions.create(
        name="stream-completion",
        model=AZURE_OPENAI_MODEL,
        messages = messages,
        temperature=float(AZURE_OPENAI_TEMPERATURE),
        max_tokens=int(AZURE_OPENAI_MAX_TOKENS),
        top_p=float(AZURE_OPENAI_TOP_P),
        stop=AZURE_OPENAI_STOP_SEQUENCE.split("|") if AZURE_OPENAI_STOP_SEQUENCE else None,
        stream=SHOULD_STREAM,
        seed=int(AZURE_OPENAI_SEED)
    )

    for chunk in stream:
        yield chunk
    
    langfuse_context.flush()

**Comment by hassiebp** [comment]
Closing this as stale, please reopen if issue persists.
