### ISSUE TITLE
bug: Continuation of patching of cost not working

### ISSUE THREAD

**Issue by atrik-das-razer** [langfuse/langfuse#2754]
### Describe the bug

Hi @marcklingen,

I am opening a new issue because the one I had opened previously was closed prematurely. This issue is a continuation of https://github.com/langfuse/langfuse/issues/2702. 

I tried running the script again and this time I didn't face any dependency issues which was great but I did face this typing error:
![351644432-1e993a0a-91f2-42fa-97b2-123bf4b3cdbc](https://github.com/user-attachments/assets/7104a1ea-fb0c-4a23-bc10-fb57569c9817)

I fixed it by editing the file in web/node_modules/@langfuse/shared/src/features/ingestion/types.ts with the following code:

```
.superRefine((data, ctx) => {
  // Type guard to help TypeScript with type narrowing
    function isOfType<T extends { dataType?: string }>(d: T, type: string): d is T & { dataType: string } {
      return d.dataType === type;
    }

    if (isOfType(data, "CATEGORICAL") && typeof data.value === "number") {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `Value must be a string for data type ${data.dataType}`,
      });
    } else if (isOfType(data, "NUMERIC") && typeof data.value === "string") {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `Value must be a number for data type ${data.dataType}`,
      });
    } else if (isOfType(data, "BOOLEAN") && typeof data.value === "string") {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `Value must number equal to either 0 or 1 for data type ${data.dataType}`,
      });
    }
  });
```

After this change, the script ran just fine and seemed to have updated the historical token usage for all my traces however my cost is still showing as $0.00:
![351646866-a5a09e09-f688-4c1a-a777-a779944d45c0](https://github.com/user-attachments/assets/5a3cf496-09b5-46fe-b6a9-1499d93b02c0)

Shouldn't the cost also be updated accordingly?

### To reproduce

Run the exact same commands as mentioned in https://langfuse.com/docs/deployment/self-host#migrate-models

### Are you interested to contribute a fix for this bug?

No

**Comment by marliessophie** [comment]
Hey @atrik-das-razer - thanks so much for reporting the type errors! Seems like you were on a more recent TS version than me which is why we had missed this initially. Your fix of course works, but we also ensured there should be no TS errors across versions via [this change](https://github.com/langfuse/langfuse/commit/484ef3fcacfef2a9d716a2054c93958ee661865f). 

Please let us know in case you have any more questions/thoughts/feedback

**Comment by atrik-das-razer** [comment]
@hassiebp Here are some examples of a relevant row from the generations tab containing the missing cost and usage fields:
![image](https://github.com/user-attachments/assets/b3ee3ef9-cc7f-4059-b4d4-e4526ff68053)

**Comment by atrik-das-razer** [comment]
@marliessophie thanks for the quick fix, just pulled your change and tested it and the typing issues are gone. However, the migration script still doesn't work as it should as per the image above.

**Comment by atrik-das-razer** [comment]
Hi @hassiebp I am running v2.64.0 which contains the latest gpt-4o pricing as maintained by Langfuse. Here are the model definitions that I have in my models table:
![image](https://github.com/user-attachments/assets/efcb172e-64ff-4f98-9a8d-5653d6c91597)

**Comment by hassiebp** [comment]
Hi @atrik-das-razer - unfortunately this looks quite tricky to debug from afar. Could you please share the exact logs when running the script? Is the input / output field populated for all the generations?

**Comment by hassiebp** [comment]
Closing this as stale.
