### ISSUE TITLE
bug: Langchain - @chain decorator with abatch/batch dumps all batch runs into same trace 

### ISSUE THREAD

**Issue by jpmin7** [langfuse/langfuse#2777]
### Describe the bug

Using the Langchain-@chain decorator while using abatch/batch leads to langfuse dumping all batch runs into one trace instead of seperate traces for each batch call. The batch tracking works when using the "older" pipe chain structure.  

Also when using the @chain decorator cost or token data are missing in langfuse.

### To reproduce

Running a chain with the chain decorator in batch will reproduce this behavior. 

```
from langchain_core.runnables import chain
from langfuse import Langfuse
from langfuse.decorators import langfuse_context, observe

@chain
def raumbuch_chain(input: str):
    documents = docsRerankCohere(input)
    prompt_raumbuch = prompt.invoke({"input": input, "context": documents})
    output_raumbuch = model.invoke(prompt_raumbuch)
    raumbuch = output_parser.invoke(output_raumbuch)
    return raumbuch
    

 langfuse_handler = langfuse_context.get_current_langchain_handler()
    
batch_result = await raumbuch_chain.with_config(config= {'callbacks': [langfuse_handler]}).abatch(queries)
```

### SDK and container versions

langserve = ">=0.0.22"
python sdk 

### Are you interested to contribute a fix for this bug?

No

**Comment by itssimon** [comment]
We're also hitting this issue.

**Comment by marcklingen** [comment]
thanks for reporting this @jpmin7 & @itssimon

**Comment by hassiebp** [comment]
Closing this as stale.
