### ISSUE TITLE
bug: Self-hosted langfuse crashes after ingesting a trace where an exception has been thrown

### ISSUE THREAD

**Issue by jamesc601** [langfuse/langfuse#2806]
### Describe the bug

We are self-hosting Langfuse in an Azure app service. When the application sending traces etc. throws an exception, we see a large spike in Langfuse's CPU usage and the application crashes.

### To reproduce

We seem to be able to reproduce this every time an exception is thrown.

The size of some objects passed as arguments to some of the functions that are observed by Langfuse (using the observe decorator) are quite large. We are avoiding capturing this input in Langfuse using `capture_input` as including these in our traces are not particularly useful and ingesting them causes performance Langfuse performance issues. If I was to take a guess at what is causing this, I would say that the exception is causing our capture_input to not work, causing large events to be sent to Langfuse which causes the performance issues. I don't have information that backs this up though.

### SDK and container versions

Langfuse Python SDK = 2.33.1
Langfuse container 2.65.0

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Thanks for sharing this, do you use some sort of load balancer? We for example enforce limits regarding api payloads on a load balancer level on Langfuse cloud, more on this here: https://langfuse.com/faq/all/api-limits

**Comment by marcklingen** [comment]
Closing this for now as stale, happy to reopen in case this is still an issue

**Comment by adithya-dinesh** [comment]
Hi @marcklingen 
We are encountering the same issue. We have deployed Langfuse on Kubernetes, and since all calls are internal within the cluster, we do not have a dedicated load balancer for Langfuse.

Is there a way to reject requests that exceed the recommended payload size before the call is made, while allowing all other calls to proceed as expected?

**Comment by marcklingen** [comment]
That's currently not supported as the langfuse client sdk all limit payload size automatically, thus, this should not happen. Can you share more details?
