### ISSUE TITLE
bug: Langfuse was not able to parse the LLM model for Azure gpt-4o-mini

### ISSUE THREAD

**Issue by SathinduGA** [langfuse/langfuse#2816]
### Describe the bug

I'm using AzureChatOpenAI model from `langchain_openai ` and using `gpt-4o-mini` model. I'm getting `Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name. Please create an issue so we can fix your integration: https://github.com/langfuse/langfuse/issues/new/choose` error message for all of my LLM calls.

I've used other models such as GPT-4o, Llama 3.1, Claude 3.5 Sonnet and not getting this issue. **Also if I'm using gpt-4o-mini from OpenAI endpoints, I'm not getting this one.**

This is the one I'm using with `@observe` decorator.
```
AzureChatOpenAI(
    openai_api_version="2024-06-01",
    azure_deployment="****",
    temperature=0.7,
)
```

<img width="1495" alt="Screenshot 2024-08-02 at 8 31 53 PM" src="https://github.com/user-attachments/assets/fdaa1edf-f8e1-45cd-8355-a9aa06b928ce">

### To reproduce

Invoke Azure OpenAI deployment with Langchain's AzureChatOpenAI class for gpt-4o-mini

### SDK and container versions

Langfuse Server: `v2.67.0`
Langfuse Python SDK: `2.40.0`

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
can you add an additional `model` property, otherwise the model name might be inconsistent in Langfuse?

**Comment by hassiebp** [comment]
Closing as stale. We have also released improvements to model name parsing for Langchain for Langfuse Python SDK version >=2.51.1 . When using Azure, adding the `model` parameter helps hinting Langchain/Langfuse to what OpenAI model corresponds with the deployment, thus improving model name detection.
