### ISSUE TITLE
bug: Error When Using Langfuse Callback Handler with Groq API in create-llama

### ISSUE THREAD

**Issue by cloud-ray** [langfuse/langfuse#2836]
### Describe the bug

When using the [Langfuse Callback Handler](https://docs.llamaindex.ai/en/stable/examples/observability/LangfuseCallbackHandler) with the Groq API in the [create-llama project](https://github.com/run-llama/create-llama), an error occurs during the parsing of the usage event payload. 

The error message indicates that a ChatCompletionChunk object has no attribute get. Despite the error, traces still appear on the Langfuse dashboard.

**Expected Behavior**

I expected the Langfuse Callback Handler to correctly parse the usage information from the event payload without raising any errors, similar to how it presumably functions when using the OpenAI API.

### To reproduce

1. Set up the `create-llama` project using the `Groq API` found in: 
- _(project_name/backend/app/settings.py)_
- _(project_name/backend/.env)_

3. Add the Langfuse Callback Handler to _backend/main.py_ using either of the following options:

   **Option 1: Set global LlamaIndex handler**

   ```python
   from llama_index.core import global_handler, set_global_handler

   set_global_handler("langfuse")
   langfuse_callback_handler = global_handler
   ```

   **Option 2: Use Langfuse callback directly**

   ```python
   from llama_index.core import Settings
   from llama_index.core.callbacks import CallbackManager
   from langfuse.llama_index import LlamaIndexCallbackHandler

   langfuse_callback_handler = LlamaIndexCallbackHandler()
   Settings.callback_manager = CallbackManager([langfuse_callback_handler])
   ```

### SDK and container versions

- **Python**: ^3.11, <3.12
- **FastAPI**: ^0.109.1
- **python-dotenv**: ^1.0.0
- **aiostream**: ^0.5.2
- **llama-index**: 0.10.58
- **cachetools**: ^5.3.3
- **llama-index-llms-groq**: ^0.1.4
- **llama-index-embeddings-fastembed**: ^0.1.7
- **langfuse**: ^2.41.0
- **graphsignal**: ^0.15.5
- **llama-index-callbacks-langfuse**: ^0.1.4

These are the package versions I'm using, installed via Poetry, which may be relevant to the issue.

### Additional information

Upon further investigation, I modified the `_parse_usage_from_event_payload` function in the Langfuse code to use `getattr` instead of `get`, which resolved the issue.

Find in:
_project_name/backend/.venv/lib/python3.11/site-packages/langfuse/llama_index/llama_index.py_

```python
def _parse_usage_from_event_payload(self, event_payload: Dict):
    model = usage = None

    if not (
        EventPayload.MESSAGES in event_payload
        and EventPayload.RESPONSE in event_payload
    ):
        return model, usage

    response = event_payload.get(EventPayload.RESPONSE)

    # Debugging statement to inspect response.raw
    if hasattr(response, "raw"):
        print("response.raw:", response.raw)
    
    if hasattr(response, "raw") and response.raw is not None:
        model = getattr(response.raw, "model", None)
        token_usage = getattr(response.raw, "usage", None)

        if token_usage:
            usage = {
                "input": getattr(token_usage, "prompt_tokens", None),
                "output": getattr(token_usage, "completion_tokens", None),
                "total": getattr(token_usage, "total_tokens", None),
            }

    return model, usage
```

This adjustment allows the code to correctly handle responses from the `Groq API`. I hope this information helps in addressing the issue. Please let me know if further details or testing are needed.

### Are you interested to contribute a fix for this bug?

Yes

**Comment by hassiebp** [comment]
Closing as stale.
