### ISSUE TITLE
Feat (ui): Move columns

### ISSUE THREAD

**Issue by marctorsoc** [langfuse/langfuse#2880]
### Discussed in https://github.com/orgs/langfuse/discussions/2850

<div type='discussions-op-text'>

<sup>Originally posted by **marctorsoc** August  7, 2024</sup>
### Describe the feature or potential improvement

First, some appreciation for release this open source. This is heavily increasing my productivity 👏 

It'd be great to move columns in the trace tables as desired. Some of the columns are less important but still useful. This is low priority, but probably not very hard either (I think?)

### Additional information

_No response_</div>

**Comment by marctorsoc** [comment]
oh, now I see [this](https://github.com/orgs/langfuse/discussions/829). Sorry for the spam

**Comment by marcklingen** [comment]
No worries! Let's keep this issue open. I'm happy to support if you're interested in contributing.

**Comment by marctorsoc** [comment]
nice! I actually opened 3 discussions in the recent days (just started using langfuse). 
- Move columns: https://github.com/orgs/langfuse/discussions/2850
- Collapse sidebar by default: https://github.com/orgs/langfuse/discussions/2881
- Allow not sorting tags: https://github.com/orgs/langfuse/discussions/2848

which one you think is more priority? for me the order is
1. 2881 
2. 2850
3. 2880

WDYT @marcklingen

**Comment by marcklingen** [comment]
thanks for sharing your feedback!<br><br>Are you interested in contributing these changes? If yes, I agree that 2881 is a great to one to prioritize first

**Comment by marctorsoc** [comment]
Happy that we're aligned. Sure, I'd be happy to contribute, but I'm not at all a seasoned FE developer. I'll look into it and come back if I get blocked. But if you (or anyone) has hints / advice, more than welcome

**Comment by ubaish01** [comment]
Hi @marctorsoc , I am a seasoned FE developer(New to open source) would love work with on this issue.
