### ISSUE TITLE
bug: LANGFUSE_CSP_ENFORCE_HTTPS doesn't work

### ISSUE THREAD

**Issue by dpetrecki** [langfuse/langfuse#2900]
### Describe the bug

When setting up the environment variable LANGFUSE_CSP_ENFORCE_HTTPS = true, I expect Langfuse to handle HTTPS connections. Unfortunately, it still works with HTTP only.
The error when trying to use HTTPS is ERR_SSL_PROTOCOL_ERROR.

### To reproduce

1. Clone repo
2. Set  LANGFUSE_CSP_ENFORCE_HTTPS=true as en environment variable in docker-compose.yml
3. Run docker-compose up
4. Try to open https://localhost:3000

The same issue occurs when hosting Langfuse on AWS ECS - the load balancer's target group has to use HTTP, as HTTPS fails with the same error.

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
This environment variable will configure Langfuse to add Content Security Policy (CSP) headers that will enforce the use of HTTPS in most browsers. Langfuse does not handle HTTPS termination, so you need to configure this within the load balancer, such as on AWS. Then, route the traffic to Langfuse on port 3000, which can be customized via the `PORT` environment variable.

This configuration works as expected. We considered performing the HTTPS termination within the Langfuse application container, but this would complicate things for everyone who manages their own SSL/TLS certificates.

I do not fully understand the specific issues you are facing with the ECS + load balancer setup. I set up a similar configuration with a team last week without any problems. Can you share more details? Happy to help.

**Comment by dpetrecki** [comment]
Hi, thank you for your answer. My load balancer is listening for HTTPS requests on 443 port.
![image](https://github.com/user-attachments/assets/d2b20c9a-22c3-43b6-b2be-062c76060d3e)
Then there is a target group configured as **HTTP**.
![image](https://github.com/user-attachments/assets/2f147309-3b44-4685-9cd0-a58641e9898f)
I would like to encrypt the traffic between the load balancer and Langfuse, but I need Langfuse to handle HTTPS connections. When I configure the target group as HTTPS, it doesn't work - the error is ERR_SSL_PROTOCOL_ERROR.
![image](https://github.com/user-attachments/assets/c7a0af6d-e43c-460f-a3d8-0328d2aa4faf)
I'd expect Langfuse to be able to handle HTTPS calls and with `LANGFUSE_CSP_ENFORCE_HTTPS = true` - to handle HTTPS requests only.
So I've started digging. In my local setup LANGFUSE_CSP_ENFORCE_HTTPS doesn't change anything. I can connect via http://localhost:3000 only and there is no way to use any encryption.
Is it an expected behaviour? Do I need to use a nginx as a sidecar task in ECS to encrypt traffic (inet -> ELB via HTTPS, then ELB -> nginx via HTTPS, then nginx -> langfuse via http on localhost)?

**Comment by marcklingen** [comment]
I understand what you are trying to achieve. As mentioned Langfuse can only add a CSP header to help enforce https client-side and prevent any non-https resources to be fetched by the client from within the Langfuse UI.<br><br>You idea to e.g. use nginx as a sidecar to encrypt traffic sounds reasonable, this is however up to you (based on your preferences).
