### ISSUE TITLE
bug: metadata doesn't seem to be merged in python

### ISSUE THREAD

**Issue by nonlocalStream** [langfuse/langfuse#2906]
### Describe the bug

I'm testing langfuse locally (2.69.0) and found that calling `update_current_trace` with metadata wipes out the old metadata while the inline docs says that metadata should be merged.

### To reproduce

I have this in one of the code block (outside this observe I have another observe, not sure if relevant to this issue)
```
@observe()
def function():
	langfuse_context.update_current_trace(
	    metadata={"comment": "first comment", "test": "first test"},
	)
	langfuse_context.update_current_trace(
	    metadata={"comment": "second comment"},
	)
    ...
```
I expected to get the final metadata to be {"comment": "second comment", "test": "first test"} but instead I get:
![Screenshot 2024-08-12 at 5 37 41 PM](https://github.com/user-attachments/assets/f4b9e72d-5ca3-423a-818c-849dc00e3df9)

### SDK and container versions

I followed this https://langfuse.com/docs/deployment/local and made sure I'm on latest version by doing
```
docker compose down
git pull
docker-compose pull
docker compose up
```

I'm on python 3.11.3

### Additional information

Also curious, are tagged supposed to be merged as well? (currently the old tags get wiped out for me as well)

### Are you interested to contribute a fix for this bug?

Yes

**Comment by nonlocalStream** [comment]
@hassiebp just to clarify, are you saying this is because I'm calling update_current_trace inside the decorated function? 

Does that mean if I call the low-level apis like `langfuse.trace` and `trace.update` directly without decorators, then metadata should be merged?

**Comment by nonlocalStream** [comment]
@hassiebp @marcklingen could you help with the follow up clarification? 🙏  I can open a new issue if that works better

**Comment by marcklingen** [comment]
> Does that mean if I call the low-level apis like langfuse.trace and trace.update directly without decorators, then metadata should be merged? I can't figure out anyway to structure the code where metadata can be automatically merged, which seems to contract the documenation
(I could trickle down the full metadata dict in all call site but could be quite tedious to implement)

That's right.

We will change the bahavior of update_current_trace which will then also be in line with the docs, sorry for the confusion

**Comment by nonlocalStream** [comment]
@marcklingen @hassiebp 

> That's right.

Even with just the low-level apis, I can't seem to get the metadata merged. Is this expected or did I miss anything? (See last code example above)

> We will change the bahavior of update_current_trace which will then also be in line with the docs, sorry for the confusion

Do we have an ETA for this? Will this be part of langfuse v3?

**Comment by hassiebp** [comment]
Hi @nonlocalStream - no ETA yet on when this will be available directly via `langfuse_context.update_current_trace`. Meanwhile, here's a workaround:

```python
    def test_update_metadata_inside_decorated_func():
        from langfuse import Langfuse
        from langfuse.decorators import langfuse_context, observe

        mock_trace_id = create_uuid()
        langfuse_client = Langfuse()

        @observe()
        def main(**kwargs):
            trace_id = langfuse_context.get_current_trace_id()
            trace_client = langfuse_client.trace(id=trace_id).update(metadata={"a": 1})
            trace_client.update(metadata={"b": 2})

            return "function response"

        result = main(langfuse_observation_id=mock_trace_id)
        langfuse_context.flush()
        langfuse_client.flush()

        assert result == "function response"

        trace_data = get_api().trace.get(mock_trace_id)

        assert trace_data.metadata == {"a": 1, "b": 2}
```

[Link to resulting trace](https://staging.langfuse.com/project/7a88fb47-b4e2-43b8-a06c-a5ce950dc53a/traces/3035f9a8-5986-430e-9b01-1856cc59fadd).

**Comment by nonlocalStream** [comment]
Thanks for the code snippet @hassiebp! 

Combined with your answer, I found that the main issue with my original code snippet (when I used @observer and the low-level sdk) is that I was doing `langfuse_client.trace(id=trace_id, metadata={"a": 1})` instead of `langfuse_client.trace(id=trace_id).update(metadata={"a": 1})` . 

After I switch to the right api, I was able to make it work:
```
@observe()
def test_langfuse_outer(input1: str) -> str:
    logging.warning("[DEBUGG] Running outer")
    trace_id = langfuse_context.get_current_trace_id()
    langfuse.trace(id=trace_id).update(
        metadata={"first_key": "first_value"},
        tags=["first_tag"],
    )

    return test_langfuse_inner(input1, trace_id) * 3


def test_langfuse_inner(input2: str, trace_id: str) -> str:
    logging.warning("[DEBUGG] Running inner")
    langfuse.trace(id=trace_id).update(
        metadata={"second_key": "second_value"}, tags=["second_tag"]
    )
    return "inner:" + input2
```
This works the best for me since it allows me to add nested @observe if I want and merge the metadata and tags

Thank you so much for helping me on this!

**Comment by marcklingen** [comment]
Glad that you made it work @nonlocalStream, thanks for confirming/sharing your solution here!

**Comment by hassiebp** [comment]
This is fixed in https://github.com/langfuse/langfuse-python/releases/tag/v2.57.12 . Please upgrade and let us know if all works well now 🙏🏾

**Comment by nonlocalStream** [comment]
Awesome! Super excited for it!
