### ISSUE TITLE
bug: batch output not appearing 

### ISSUE THREAD

**Issue by salmanmashayekh** [langfuse/langfuse#2940]
### Describe the bug

When I call a langchain runnable in the batch mode, the outputs either don't appear for individual traces, or only appear for the last call in the batch. 

### To reproduce

Here is a minimum example:

```
from os import environ

from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import PromptTemplate
from langchain_openai.chat_models import AzureChatOpenAI
from langfuse import Langfuse
from langfuse.callback.langchain import LangchainCallbackHandler


llm = AzureChatOpenAI(
    azure_deployment=environ["AZURE_DEPLOYMENT"],
    api_version=environ["AZURE_API_VERSION"],
    api_key=environ["AZURE_API_KEY"],
    azure_endpoint=environ["AZURE_ENDPOINT"],
)

callback = LangchainCallbackHandler()

batch_inputs = ["lion", "tiger", "elephant", "giraffe"]
chain = PromptTemplate.from_template("Tell me a joke about {topic}") | llm | StrOutputParser()
batch_outputs = chain.batch(batch_inputs, config={"callbacks": [callback]})
print(batch_outputs)

Langfuse().flush()
```

When I run it without the flush, I don't get any outputs (each trace is complete and have the generation and parsing inputs/outputs, but it is missing the trace output). 
When I run it with the flush, the output appears only for the last call, i.e. `giraffe`. 

### SDK and container versions

container version: v2.70.1
sdk version: 2.43.3
![Screenshot 2024-08-14 at 12 51 47 PM](https://github.com/user-attachments/assets/f18c80cb-0261-4079-bd60-b32b30d87166)
![Screenshot 2024-08-14 at 12 54 01 PM](https://github.com/user-attachments/assets/6b15d5e9-4763-440f-9799-b51bf37952f1)

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
If you run this locally or in a short-lived environment, can you try to replace the flush method with `callback.flush()`? The callback handler creates its own langfuse instance under the hood to flush events to langfuse

**Comment by salmanmashayekh** [comment]
It does not make a difference @marcklingen , I still get the output only for one of the items in the batch.

**Comment by salmanmashayekh** [comment]
I did some debugging and here is where things go wrong:
https://github.com/langfuse/langfuse-python/blob/main/langfuse/callback/langchain.py#L813

The trace id is only the same as the run_id for the last item in the batch. So it does not update the output of the trace in line 815. Now I don't know why that condition is expected to be met and is not!

**Comment by salmanmashayekh** [comment]
If I run the batch above with only the first items `lion` and `tiger`, here are some logs I get:

```
starting chain with no parent, run_id: a22169ca-5b23-4d3d-9629-f14a90f2d897, input: lion
starting chain with no parent, run_id: 39b5634b-e70a-4c17-b748-e430c8f36255, input: tiger
ending chain with no parent, run_id: a22169ca-5b23-4d3d-9629-f14a90f2d897
calling `_update_trace_and_remove_state` method in a trace with no parent, trace id: 39b5634b-e70a-4c17-b748-e430c8f36255, run_id: a22169ca-5b23-4d3d-9629-f14a90f2d897, output: Why don't lions like...
ending chain with no parent, run_id: 39b5634b-e70a-4c17-b748-e430c8f36255
calling `_update_trace_and_remove_state` method in a trace with no parent, trace id: 39b5634b-e70a-4c17-b748-e430c8f36255, run_id: 39b5634b-e70a-4c17-b748-e430c8f36255, output: Why don't tigers lik...
```

**Comment by salmanmashayekh** [comment]
I tried commenting out the `self.trace.id == run_id` line to get passed the if and call the `trace.update` with the `output`. But still, I don't get the output for the first trace!

**Comment by salmanmashayekh** [comment]
I ran the MWE with 2 items in the batch in the debug mode and here are the detailed logs, I hope that helps. 
[batch_call.log](https://github.com/user-attachments/files/16705771/batch_call.log)

**Comment by salmanmashayekh** [comment]
@hassiebp can you offer any help for this?

**Comment by hassiebp** [comment]
Hi @salmanmashayekh - thanks for your report. I've created a PR with a fix, please try again once that is merged & released 👍🏾

**Comment by salmanmashayekh** [comment]
Thank you so much for the prompt fix @hassiebp
