### ISSUE TITLE
bug(sdk-python): Pydantic dict deprecated, switch to  model_dump warning

### ISSUE THREAD

**Issue by miguelvalente** [langfuse/langfuse#2946]
### Describe the bug

Any usage of the `.dict() `method on Pydantic models will output the following VERY annoying message:
```
PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.7/migration/
  warnings.warn('The `dict` method is deprecated; use `model_dump` instead.', category=PydanticDeprecatedSince20)
```

### To reproduce

Use langfuse

### SDK and container versions

langfuse==2.43.

### Additional information

Please for the love of god replace .dict() with model_dump()

### Are you interested to contribute a fix for this bug?

Yes

**Comment by miguelvalente** [comment]
Just to be clear this is happening on the langfuse-python repo.

**Comment by marcklingen** [comment]
thank you for raising this, do you feel comfortable raising a PR to quickly fix this?

**Comment by hassiebp** [comment]
Fix released here, please upgrade and try again :) https://github.com/langfuse/langfuse-python/releases/tag/v2.53.5
