### ISSUE TITLE
feat: Avoid type errors on Create* pydantic models

### ISSUE THREAD

**Issue by hubert-springbok** [langfuse/langfuse#295]
### Describe the feature you'd like to request

Currently, the Create* models, e.g. `CreateGeneration` declare all arguments as required to the static type checking. This is unhelpful, because most of them accept `None` as the default value and work fine.
![Example error message from VSCode](https://github.com/langfuse/langfuse/assets/115166625/0e65ca51-29da-4a8a-9160-05617844cb4c)

I think the core confusion is around `typing.Optional` used in the models. It means the field can be set to `None`, but the field is still considered required, unless there is a default provided.

### Describe the solution you'd like to see

Here's a minimal example to consider. The current code looks like this:

```python
from pydantic import BaseModel
from typing import Optional
class Model(BaseModel):
   field:  Optional[str]

r = Model()  # error, the field is required
r = Model(field=None)  # OK
r = Model(field="fool)  # OK
```

It could be changed to this instead:
```python
class Model(BaseModel):
    field: Opitional[str] = None

r = Model() # OK
r = Model(field=None)  # OK, same result
```

### Contribute

- [X] Yes, I can implement this and raise a PR

**Comment by maxdeichmann** [comment]
Hi @hubert-springbok, thanks for raising the issue! This is indeed a confusing experience! We are currently using Fern (https://github.com/fern-api/fern) to generate these pydantic models for us based on API descriptions here: https://github.com/langfuse/langfuse/tree/main/fern
Feel free to look into the Fern docs and see whether it is possible to improve the situation.

**Comment by ilyannn** [comment]
@maxdeichmann Yes, I believe the option is `"require_optional_fields": False` introduced in https://github.com/fern-api/fern-python/pull/329

**Comment by maxdeichmann** [comment]
Hi @ilyannn and @hubert-springbok, we already use the feature `"require_optional_fields": False` by fern: https://github.com/langfuse/langfuse/blob/9b1ead2bd37b84be711a3f68c56ceab4fff548a5/fern/apis/server/generators.yml#L21-L22

With the latest SDK version all fields should not be required, but have default values. Feel free to re-open if you have any issues around this.
