### ISSUE TITLE
Unexpected event format when using `ibm-watsonx-ai` with LangChain extension

### ISSUE THREAD

**Issue by barvhaim** [langfuse/langfuse#2979]
### Discussed in https://github.com/orgs/langfuse/discussions/2978

<div type='discussions-op-text'>

<sup>Originally posted by **barvhaim** August 20, 2024</sup>
### Describe the feature or potential improvement

I'm able to partly use Langfuse with `ibm-watsonx-ai` with LangChain extension, I do see the traces in Langfuse but it's missing some values, and I get this error message.

```
Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name. Please create an issue so we can fix your integration: https://github.com/langfuse/langfuse/issues/new/choose
Unexpected event format: No trace id found in event
Usage object must have either {input, output, total, unit} or {promptTokens, completionTokens, totalTokens}
Traceback (most recent call last):
  File ".venv/lib/python3.11/site-packages/langfuse/client.py", line 2473, in update
    "usage": _convert_usage_input(usage) if usage is not None else None,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/langfuse/utils/__init__.py", line 101, in _convert_usage_input
    raise ValueError(
ValueError: Usage object must have either {input, output, total, unit} or {promptTokens, completionTokens, totalTokens}
```

### Additional information

 I am trying to debug to get further information.</div>

**Comment by barvhaim** [comment]
This is the usage input looks like 
![image](https://github.com/user-attachments/assets/f0bcdd9b-a154-4d28-8751-bef946251ebe)

**Comment by barvhaim** [comment]
update - in the event I do see ID, it's not called traceId but just`id`
![image](https://github.com/user-attachments/assets/fa3cb17b-f273-4ca7-9bde-744d9617e7f8)

I'll try to add it

**Comment by barvhaim** [comment]
I had to add this to make it works
![image](https://github.com/user-attachments/assets/e2496b76-03b9-4ad6-89c5-ae7376b0066e)

I'll contribute that to the lib

**Comment by marcklingen** [comment]
awesome, thanks for the contribution, I'll merge this once you create a pr

**Comment by barvhaim** [comment]
@marcklingen it worked but the model params on llm invocation are in different format, not sure how to make it generic, as you can see in the debug screen, the params are in another dict in the invocation params -
![image](https://github.com/user-attachments/assets/4b6d9775-ba0e-4028-88da-349212aa835e)

**Comment by marcklingen** [comment]
you could add these params if you want to also to the model_parameters dict, up to you

**Comment by marcklingen** [comment]
thank you by the way!

**Comment by barvhaim** [comment]
@marcklingen I wasn't sure how to handle the params, it's like looking into kwargs["invocation_params"].get('x') but my params are in another level, I can't change the __on_llm_action because others using it, any suggestion? Sorry I'm new to this lib, I might miss something

**Comment by barvhaim** [comment]
I had to flatten the params and add new params

![image](https://github.com/user-attachments/assets/408e133e-5188-42eb-8892-fa2384ff4363)

<img width="1033" alt="image" src="https://github.com/user-attachments/assets/d8f58c31-e4b5-4811-bcec-8a8e8875d492">

**Comment by maxdeichmann** [comment]
For context, here is the PR: https://github.com/langfuse/langfuse-python/pull/874
