### ISSUE TITLE
bug: can't find prompt in the playground langfuse view

### ISSUE THREAD

**Issue by ssoto** [langfuse/langfuse#2989]
### Describe the bug

I am having a extrange behaviour in langfuse server (a cloud insatnce managed by langfuse). 

The use case definition is: update an existing prompt from playground.

A more detailed use case definition: I open a saved prompt in the playground, after to do changes I want to updated the existing prompt but I can't find the existing prompt in this search input:
<img width="1571" alt="Sin título 6" src="https://github.com/user-attachments/assets/42c86fe6-7654-4762-a654-440c0f59fd54">

### To reproduce

Following the bug description steps.

### Are you interested to contribute a fix for this bug?

Yes

**Comment by marcklingen** [comment]
I have added some hints in the UI to make this clearer. Thank you for raising this issue.
