### ISSUE TITLE
bug: No scrollbar in Dataset Item page "hides" the 'Save changes' button

### ISSUE THREAD

**Issue by christos-bsq** [langfuse/langfuse#3047]
### Describe the bug

On Dataset Item pages (cloud.langfuse.com/project/{project-id}/datasets/{dataset-id}/items/{item-id}) there is no scroll bar.

As a result, if the input or output is long, the "Save changes" button, as well as the Runs section are not visible. The only way to access those hidden elements is to reduce the browser's zoom level. 

Below is a screenshot from a 24" screen from the Dataset Item page. 
- "Save changes" is not visible
- No _page_ sidebar

![image](https://github.com/user-attachments/assets/3f00beb6-2827-4f93-9b2c-0e658c2d11bb)

### To reproduce

Go to an existing Dataset Item (or create one) and place a long text in the Input or Expected Output fields.

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks for reporting this!

**Comment by ubaish01** [comment]
Hi @marcklingen , if its not fixed yet i can pick this up.

**Comment by christos-bsq** [comment]
This bug is fixed 🎉 
- The page is now split in two. 
- The top part (where users edit the Dataset item) has a scrollbar, making the 'Save changes' button always accessible

![image](https://github.com/user-attachments/assets/47209ca0-9398-4806-92d4-bf0fe0dddc98)

I'm therefore closing this Issue
