### ISSUE TITLE
bug: prompt variables and json in the same prompt

### ISSUE THREAD

**Issue by jonnyforsterMSG** [langfuse/langfuse#3054]
### Describe the bug

From the docs variables should be added with {{}} braces and this works fine expect when I have json in my prompt. In this scenario if the json is wrapped in single curly braces I get this messgae - "detail": "Expected mapping type as input to PromptTemplate. Received <class 'str'>."

To get this to work I need to double wrap the json in {{}} and leave the variable with a single curly brace {}

### To reproduce

create a prompt with a variable. Add some json to the prompt for example The output should be a JSON object with the following structure:
{
"AgentName": "The name of the agent receiving the call"
}

### SDK and container versions

self host 2.71

### Additional information

the prompt is being used in a Langchain chain and retrieved like this 

`langfuse_prompt = prompt_manager.get_prompt(
        prompt_name,
        fallback=fallback_prompt,
   )
prompt = PromptTemplate.from_template(langfuse_prompt.get_langchain_prompt())`

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks for sharing!

**Comment by jonnyforsterMSG** [comment]
Hi thanks for the reply that is what we're doing atm but it doesn't match your docs and then doesn't show the variables in the portal 
![image](https://github.com/user-attachments/assets/f6a1241a-e655-4b2e-9a82-0eae73adb14c)

**Comment by hassiebp** [comment]
Hi @jonnyforsterMSG - thanks for your report. The following prompt works as expected when consumed via Python SDK and as a Langchain prompt: 

```
    {{
        "AgentName": "{{agent_name}}"
    }}
```

Example code:
```python
    from langfuse import Langfuse
    from langchain.prompts import PromptTemplate

    langfuse = Langfuse()
    prompt_name = "curly-prompt"

    prompt = """
    {{
        "AgentName": "{{agent_name}}"
    }}
    """

    langfuse.create_prompt(name=prompt_name, prompt=prompt, labels=["production"])

    prompt_client = langfuse.get_prompt(prompt_name)
    langchain_prompt = PromptTemplate.from_template(
        prompt_client.get_langchain_prompt()
    )

    print(langchain_prompt.format(agent_name="Agent 47"))
```

This prints: 
```
 {
        "AgentName": "Agent 47"
 }
```

You are correct to mention that the parsing in the UI fails for this case. I'll create a task for us to fix that.

**Comment by imaxmelnyk** [comment]
@hassiebp, even tho the solution you proposed (using double curly brackets in json) works fine, why can't we properly fix it and allow having jsons with with single curly brackets? Open for contribution?

**Comment by hassiebp** [comment]
@imaxmelnyk Happy to review your contribution on this! Please keep in mind that the change must be backwards compatible for users that have escaped json open und closing tags with an additional curly brace already.

**Comment by gmyrianthous** [comment]
@hassiebp Assuming that only `{{agent_name}}` is the actual variable, attempting to print `prompt.variables` will give you both the agent name as well as the full JSON, which is incorrect.

**Comment by MaxBrosky** [comment]
@marcklingen 
I've got a similar problem, the following piece of text in a prompt causes errors:
  response_example: {
      "AgentName": "Name of the agent"
  }

Gives the error: "Single '}' in template."
We fixed it by doing this:
  response_example: {{
      "AgentName": "Name of the agent"
  }}

We use LangFuse with LangChain in Typescript.
However double brackets cause issues when connecting this to promptfoo and retrieving the prompt there:
[ERROR] Error: Unclosed tag at 709

Is this an issue that has been seen before and is there is a known fix for?
