### ISSUE TITLE
bug: LlamaIndex integration does not capture usage and cost of standalone components

### ISSUE THREAD

**Issue by hieu-cove** [langfuse/langfuse#3096]
### Describe the bug

When using the LlamaIndex integration, whether using the [beta instrumentation module](https://langfuse.com/docs/integrations/llama-index/get-started#%EF%B8%8F-beta-observability-based-on-llamaindex-instrumentation-module) or the existing [callback manager solution](https://langfuse.com/docs/integrations/llama-index/get-started#interoperability-with-langfuse-sdk), Langfuse neither capture the usage data nor the cost of standalone components.

### To reproduce

Below, I've adapted the given [Python example](https://langfuse.com/docs/integrations/llama-index/example-python) to illustrate my point using just a `SimpleSummarize` component.
```
from typing import cast

import llama_index.core.instrumentation as instrument
from langfuse.decorators import langfuse_context, observe
from langfuse.llama_index import LlamaIndexCallbackHandler, LlamaIndexSpanHandler
from llama_index.core import Document, Settings
from llama_index.core.callbacks import CallbackManager
from llama_index.core.response_synthesizers import SimpleSummarize
from llama_index.core.schema import NodeWithScore
from llama_index.llms.openai import OpenAI

USE_INSTRUMENTATION = True

if USE_INSTRUMENTATION:
    langfuse_span_handler = LlamaIndexSpanHandler()
    instrument.get_dispatcher().add_span_handler(langfuse_span_handler)


Settings.llm = OpenAI("gpt-4o-mini")

doc1 = Document(
    text="""
Maxwell "Max" Silverstein, a lauded movie director, screenwriter, and producer, was born on October 25, 1978, in Boston, Massachusetts. A film enthusiast from a young age, his journey began with home movies shot on a Super 8 camera. His passion led him to the University of Southern California (USC), majoring in Film Production. Eventually, he started his career as an assistant director at Paramount Pictures. Silverstein's directorial debut, “Doors Unseen,” a psychological thriller, earned him recognition at the Sundance Film Festival and marked the beginning of a successful directing career.
"""
)
doc2 = Document(
    text="""
Throughout his career, Silverstein has been celebrated for his diverse range of filmography and unique narrative technique. He masterfully blends suspense, human emotion, and subtle humor in his storylines. Among his notable works are "Fleeting Echoes," "Halcyon Dusk," and the Academy Award-winning sci-fi epic, "Event Horizon's Brink." His contribution to cinema revolves around examining human nature, the complexity of relationships, and probing reality and perception. Off-camera, he is a dedicated philanthropist living in Los Angeles with his wife and two children.
"""
)
documents = [doc1, doc2]


@observe()
def main(query):
    if not USE_INSTRUMENTATION:
        langfuse_handler = langfuse_context.get_current_llama_index_handler()
        Settings.callback_manager = CallbackManager([langfuse_handler])  # type: ignore

    summarizer = SimpleSummarize()
    nodes = [NodeWithScore(node=doc) for doc in documents]
    summary = cast(
        str,
        summarizer.synthesize(
            query=query,
            nodes=nodes,
        ).response,  # type: ignore
    )
    langfuse_context.flush()
    return summary


if __name__ == "__main__":
    main("What did Maxwell Silverstein do growing up?")
```

### SDK and container versions

SDK version: langfuse==2.44.1
LlamaIndex version: llama-index==0.11.1
Container versions: v2.67.0

### Additional information

From the above example, below are the captured traces:
![image](https://github.com/user-attachments/assets/cf788ece-bf84-457e-9e34-af80f8a11ce7)

The first trace is using the beta instrumentation module, and the second trace is using the callback manager.

Instrumentation trace in detail:
![image](https://github.com/user-attachments/assets/90187985-15c6-4554-b352-7565d573c83a)

Callback manager trace in detail:
![image](https://github.com/user-attachments/assets/e4126f20-73d4-4d2b-9950-67ead3e249d0)

### Are you interested to contribute a fix for this bug?

Yes

**Comment by hassiebp** [comment]
Hi @hieu-cove - many thanks for your report and the detailed writeup! 

Missing token usage (and thus missing cost) are currently a known limitation of the beta instrumentation module integration and will be added soon. I'll update this issue once released.

**Comment by hieu-cove** [comment]
Hey @hassiebp thanks for the reply. Just to make it clear, it did also observe this issue in the current `CallbackManager` implementation.
Does this mean that this issue will not be fixed in the current callback manager implementation?

**Comment by hassiebp** [comment]
We are prioritizing the LlamaIndex instrumentation module as the main way of integrating Langfuse in LlamaIndex. Token counts and cost should be captured correctly once the instrumentation module integration leaves beta in the coming weeks 👍🏾

**Comment by hassiebp** [comment]
We have just shipped a major improvement to the LlamaIndex instrumentation integration that should address your issue. Please upgrade and check out our docs in how to enable the integration via the `LlamaIndexInstrumentor` and let us know your feedback here! 🙏🏾 

- [Release](https://github.com/langfuse/langfuse-python/releases/tag/v2.52.0)
- [Docs](https://langfuse.com/docs/integrations/llama-index/get-started#beta-observability-based-on-llamaindex-instrumentation-module)
- [Cookbook](https://langfuse.com/docs/integrations/llama-index/example-python-instrumentation-module)

**Comment by hassiebp** [comment]
Closing this as stale. Please reopen if issue persists.
