### ISSUE TITLE
bug: Cannot access Analytics report

### ISSUE THREAD

**Issue by gyliu513** [langfuse/langfuse#310]
### Describe the bug

When click `Analytics` on the live demo, the `Usage`, `Latency`, `Scores` tab always reporting `Please sign in to your Google account, then reload this page to view this report`, but I have alraedy logged in to my Google account, am I missing anything?

### To reproduce

- Login to Langfuse
- navigate to `langfuse-docs` project
- click `Analytics`, you will see the message

**Comment by gyliu513** [comment]
it works with my chrome now

**Comment by marcklingen** [comment]
Happy that it works now, we will migrate all charts to the main dashboard soon
