### ISSUE TITLE
bug: Segmentation fault in langfuse-server

### ISSUE THREAD

**Issue by jasonm** [langfuse/langfuse#311]
### Describe the bug

Hello! I am trying out langfuse locally via Docker on macOS, sending data from a Python app that uses Langchain. One time while running this, I got a segfault in the langfuse-server process. Logs below.

### Server logs with segfaul + Python code

Please see the excerpt of Python code I'm using to send data, as well as the langfuse-server logs from docker-compose here: https://gist.github.com/jasonm/55de1b90e9710d1e733386f63fbbe8bf

### Versions and environment

Langfuse from main:

```
 ~/dev/langfuse $ git show-ref HEAD
03495e05271fcf86e154e8be431003dd4a51bb8f refs/remotes/origin/HEAD
```

Host: Apple M2 Max, macOS 13.5.2 (22G91):
```
$ uname -a  # mac host
Darwin JasonMorrisonMacbookPro.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020 arm64
```

Docker runner: https://orbstack.dev/ Version 1.0.0 (16230). From inside langfuse-server docker container:

```
~/dev/langfuse $ which docker
/Users/jason/bin/docker
~/dev/langfuse $ docker --version
Docker version 24.0.6, build ed223bc
~/dev/langfuse $ docker compose version
Docker Compose version v2.21.0
~/dev/langfuse $ docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d
(...)
~/dev/langfuse $ docker compose exec langfuse-server /bin/sh -c "uname -a"
Linux 130197d0b741 6.4.16-orbstack-00105-g14094bfeec09 #1 SMP Mon Sep 18 21:45:38 UTC 2023 x86_64 Linux
```

### To reproduce

I was using a CLI-based Python application for LLM invocation (Python 3.11.3 on macOS installed via pyenv) and the langchain server segfaulted. Not sure exactly what caused it, but sharing the logs in case this is helpful.

### Additional information

LMK if any additional information is useful!

**Comment by jasonm** [comment]
Hmm... I had not seen this before, but maybe relevant?

```
(base) 10s [main] ~/dev/langfuse $ dc -f docker-compose.yml -f docker-compose.dev.yml up -d
[+] Running 4/4
 ✔ Network langfuse_default                                                                                                                                       Created                                                                                                 0.0s
 ✔ Container langfuse-db-1                                                                                                                                        Started                                                                                                 0.0s
 ✔ Container langfuse-langfuse-server-1                                                                                                                           Started                                                                                                 0.0s
 ! langfuse-server The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                                                                         0.0s
```

**Comment by maxdeichmann** [comment]
> Hmm... I had not seen this before, but maybe relevant?
> 
> ```
> (base) 10s [main] ~/dev/langfuse $ dc -f docker-compose.yml -f docker-compose.dev.yml up -d
> [+] Running 4/4
>  ✔ Network langfuse_default                                                                                                                                       Created                                                                                                 0.0s
>  ✔ Container langfuse-db-1                                                                                                                                        Started                                                                                                 0.0s
>  ✔ Container langfuse-langfuse-server-1                                                                                                                           Started                                                                                                 0.0s
>  ! langfuse-server The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                                                                         0.0s
> ```

@jasonm thanks for reporting the issue! I just had the same issue executing the dc command with two files. When you execute `dc -f docker-compose.yml up -d`, everything shoudl work just fine.

**Comment by maxdeichmann** [comment]
> ### Describe the bug
> Hello! I am trying out langfuse locally via Docker on macOS, sending data from a Python app that uses Langchain. One time while running this, I got a segfault in the langfuse-server process. Logs below.
> 
> ### Server logs with segfaul + Python code
> Please see the excerpt of Python code I'm using to send data, as well as the langfuse-server logs from docker-compose here: https://gist.github.com/jasonm/55de1b90e9710d1e733386f63fbbe8bf
> 
> ### Versions and environment
> Langfuse from main:
> 
> ```
>  ~/dev/langfuse $ git show-ref HEAD
> 03495e05271fcf86e154e8be431003dd4a51bb8f refs/remotes/origin/HEAD
> ```
> 
> Host: Apple M2 Max, macOS 13.5.2 (22G91):
> 
> ```
> $ uname -a  # mac host
> Darwin JasonMorrisonMacbookPro.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020 arm64
> ```
> 
> Docker runner: https://orbstack.dev/ Version 1.0.0 (16230). From inside langfuse-server docker container:
> 
> ```
> ~/dev/langfuse $ which docker
> /Users/jason/bin/docker
> ~/dev/langfuse $ docker --version
> Docker version 24.0.6, build ed223bc
> ~/dev/langfuse $ docker compose version
> Docker Compose version v2.21.0
> ~/dev/langfuse $ docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d
> (...)
> ~/dev/langfuse $ docker compose exec langfuse-server /bin/sh -c "uname -a"
> Linux 130197d0b741 6.4.16-orbstack-00105-g14094bfeec09 #1 SMP Mon Sep 18 21:45:38 UTC 2023 x86_64 Linux
> ```
> 
> ### To reproduce
> I was using a CLI-based Python application for LLM invocation (Python 3.11.3 on macOS installed via pyenv) and the langchain server segfaulted. Not sure exactly what caused it, but sharing the logs in case this is helpful.
> 
> ### Additional information
> LMK if any additional information is useful!

@jasonm i just looked into that. We have never seen that before. Is that happening consistently for you?

**Comment by jasonm** [comment]
Hi @maxdeichmann thanks! No, it's quite rare, and usually it runs just fine.

**Comment by maxdeichmann** [comment]
> Hi @maxdeichmann thanks! No, it's quite rare, and usually it runs just fine.

Thanks a lot for letting me know! We have not seen that so far with anyone else, but I'll try to reproduce it.

**Comment by maxdeichmann** [comment]
Hey, we have not been able to reproduce it. Hence will close it for now. Feel free to re-open if the issue persists.

**Comment by jasonm** [comment]
Thanks for taking a look! ☺️
