### ISSUE TITLE
bug: @observe() on lambda_handler not getting a trace

### ISSUE THREAD

**Issue by ifndefdefine** [langfuse/langfuse#3119]
### Describe the bug

I'm writing a lambda on AWS with logging into Langfuse (2.30.0).  The lambda handler function is the entrypoint into the code and is decorated with @observe(), as well as several sub-functions that represent LLM generations.  The sub-functions get traces created without issue, but the main handler doesn't get a trace, and also any langfuse_context calls in there (where I'm trying to add metadata and a session_id) get ignored.  I've tried creating a global langfuse object at the beginning of the file to ensure that langfuse exists, but that hasn't helped.  Maybe lambda is somehow getting into the handler code before langfuse is initialized?

### To reproduce

sample code below.  This will correctly log a trace for `foo` and will log the below warnings, but will fail to log a trace for the handler

`[ERROR]	Failed to prepare observation: Expecting value: line 1 column 1 (char 0)`
`[WARNING]	No trace found in the current context`
`[WARNING]	No trace found in the current context`
`[ERROR]	Failed to finalize observation: No observation found in the current context`

```import json
from langfuse.decorators import langfuse_context, observe



@observe()
def foo():
    return "Hello World, this is a test"

@observe()
def lambda_handler(event, context):
    res = foo()
    langfuse_context.update_current_trace(session_id="123", metadata=res)
    langfuse_context.flush()
    return {
        'statusCode': 200,
        'body': json.dumps('Hello from Lambda!')
    }
```

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks for sharing!

as a workaround, can you call one main function from the lamda_handler function that you can then decorate?

**Comment by hassiebp** [comment]
Closing this as stale. Please reopen if issue persists.
