### ISSUE TITLE
bug: filtering doesn't refresh page

### ISSUE THREAD

**Issue by mrdrprofuroboros** [langfuse/langfuse#3121]
### Describe the bug

filtering + pagination is broken, see below

### To reproduce

- In traces/scores UI table go to page 2
- Filter traces to get really few rows (e.g. by trace ID to get just one)
- You'll see an empty page cause you're on page 2 of 1 available pages

### SDK and container versions

2.71.0

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks for sharing! please jump back to page 1 in the meantime when filtering, will try to fix this asap

**Comment by marcklingen** [comment]
resolved, will release this tomorrow

**Comment by mrdrprofuroboros** [comment]
awesome, thank you!
