### ISSUE TITLE
feat: support for completionStartedAt when using new vercel ai sdk integration based on `start response` event

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#3141]
Currently the `start response` event is recorded as a separate event via the `langfuse-vercel` integration.

This event can be used to set the correct `completionStartedAt` on its parent generation.

**Comment by hassiebp** [comment]
Vercel just released a few new telemetry features (and renamed some telemetry properties).

Highlights include:
- send response id, response model, response timestamp
- time to first chunk, time to finish, an avg completion tokens per second for streamText

https://sdk.vercel.ai/docs/ai-sdk-core/telemetry

Can be leveraged to populate time to first token directly (and others).
