### ISSUE TITLE
docs/feat: usage pattern for adding metadata/userId/sessionId/... at runtime when using new llamaindex integration (instrumentation module)

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#3187]
### Discussed in https://github.com/orgs/langfuse/discussions/3168

<div type='discussions-op-text'>

<sup>Originally posted by **erik-squared** August 30, 2024</sup>
sorry if i'm asking an obvious question, but trying to figure out correct usage pattern for llamaindex usage:

i see that the basic using model is:
```   
langfuse_span_handler = LlamaIndexSpanHandler()
instrument.get_dispatcher().add_span_handler(langfuse_span_handler)
```

llamaindex operations then subsequently generate traces/spans to langfuse.

if i wanted to add a userid to the trace, i see that `LlamaIndexSpanHandler()` constructor accepts a `user_id` as a parameter. 

```   
langfuse_span_handler = LlamaIndexSpanHandler(user_id="someuser")
instrument.get_dispatcher().add_span_handler(langfuse_span_handler)
```

but if i am running this code as part of a backend and would like to capture an inbound user_id for each request, i don't see how to do that. 

thanks in advance!
</div>

## Options

- Wrap via langfuse decorator to set metadata via `langfuse_context`.
- Native llamaindex metadatafields that can be extracted. Risk of setting trace-level metadata via span metadata when used as part of larger application.

**Comment by marcklingen** [comment]
Using the decorator here would be my preferred solution as it also makes this integration interoperable with other Langfuse integrations for Python and reduces complexity in the llamaindex specific integration code.

**Comment by marcklingen** [comment]
This is not yet supported. As mentioned above I agree that using the decorator is probably the best way to harmonize this new integration (still experimental) and make it interoperable with all Langfuse platform features

**Comment by hassiebp** [comment]
@erik-squared We have just shipped a major improvement to the LlamaIndex instrumentation integration that should address your root-setting issue. Please upgrade and check out our docs in how to enable the integration via the `LlamaIndexInstrumentor` and let us know your feedback here! 🙏🏾 

- [Release](https://github.com/langfuse/langfuse-python/releases/tag/v2.52.0)
- [Docs](https://langfuse.com/docs/integrations/llama-index/get-started#beta-observability-based-on-llamaindex-instrumentation-module)
- [Cookbook](https://langfuse.com/docs/integrations/llama-index/example-python-instrumentation-module)
