### ISSUE TITLE
bug: Langchain python integration does not support bedrock model names

### ISSUE THREAD

**Issue by AnnaZaharova** [langfuse/langfuse#3192]
### Describe the bug

I want to integrate langfuse to my python project, but I'm getting an error:

`Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name.`

Bedrock model id = **"anthropic.claude-v2"**

Imports:
```
from langchain_aws import BedrockLLM
from langfuse.callback import CallbackHandler
```

### To reproduce

bedrock_llm.ainvoke("question") -> traces exist, but no pricing info

### SDK and container versions

langfuse=2.45.1
langchain_aws=0.1.17

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment]
Thanks for reporting this! We will take a look and prioritize a fix.

**Comment by hassiebp** [comment]
Thanks for reporting this @AnnaZaharova ! We have just released improvements to model name parsing for Langchain. Could you please upgrade to Langfuse Python SDK version >=2.51.1 and try again? 🙏🏾

**Comment by hassiebp** [comment]
Closing this as stale. Please reopen if issue persists.
