### ISSUE TITLE
bug(ui): Dataset run description and metadata should not be fixed on the page

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#3213]
### Discussed in https://github.com/orgs/langfuse/discussions/3212

<div type='discussions-op-text'>

<sup>Originally posted by **justinas-kazanavicius** September  3, 2024</sup>
### Describe the feature or potential improvement

Description and metadata are always fixed on the page (they cannot be scrolled out of view), so if the description or metadata are long enough, there won't be enough space to see the dataset run items at all. It is possible to collapse the metadata to give more real estate to the dataset rows, but that is unintuitive and also even after doing that, there might still be enough space if the screen size is not big enough. For example, on my colleague's laptop with a smaller screen, he could only see a single row even after collapsing the metadata.

**Solution**: dataset run description and metadata elements should not be fixed, so that when scrolling down the page they would not be visible anymore, giving more space to see the dataset run items.

### Additional information

_No response_</div>

**Comment by justinas-kazanavicius** [comment]
to add on, it is also currently impossible to scroll inside the metadata field

**Comment by ricepoutine** [comment]
Hi, I am still having this issue in self-hosted solution (local docker container). My metadata is quite large and not scrollable, so the dataset items cannot be seen at the bottom.

**Comment by ricepoutineNT** [comment]
In the item tab of a dataset. When in the runs tab it is scrollable.

**Comment by marcklingen** [comment]
Which version do you run?
