### ISSUE TITLE
bug: python langchain retriever - parent run not found

### ISSUE THREAD

**Issue by djo10** [langfuse/langfuse#3223]
### Describe the bug

When invoking standalone langchain retriever getting parent run not found error, thus no traces

```
parent run not found
Traceback (most recent call last):
  File ".../langfuse/callback/langchain.py", line 525, in on_retriever_start
    raise Exception("parent run not found")
Exception: parent run not found
run not found
Traceback (most recent call last):
  File ".../langfuse/callback/langchain.py", line 551, in on_retriever_end
    raise Exception("run not found")
Exception: run not found
```

### To reproduce

```
retriever = my_retriever.as_retriever()
retriever.invoke('what is langfuse', config={"callbacks": [langfuse = CallbackHandler()]})
```

### SDK and container versions

python
langfuse                 2.45.1

### Additional information

https://github.com/langfuse/langfuse/issues/1927

### Are you interested to contribute a fix for this bug?

Yes

**Comment by marcklingen** [comment]
Are you on the latest langchain version? afaik this is an upstream problem in langchain which seems to fixed as reports for this issue went down a lot

**Comment by djo10** [comment]
langchain                0.2.15
langchain-community      0.2.15
langchain-core           0.2.37
langfuse                 2.45.1

**Comment by Meteord** [comment]
I encounter the same problem
```
by using vectorstore.as_retriever(...)
```

langchain==0.2.16
langchain-community==0.2.16
langchain-core==0.2.38
langfuse==2.48.0

**Comment by Meteord** [comment]
I think i found a fix. I will try to make an pr tomorrow.

**Comment by Meteord** [comment]
I have an pr for this problem: https://github.com/langfuse/langfuse-python/pull/925

Here is a workaround:
```python
retriever =  RunnableParallel({"retriever": vectorstore.as_retriever(...)}) 
retriever.invoke(input=query, config={"callbacks": [langfuse_handler]})["retriever"]
```

**Comment by hassiebp** [comment]
Thanks for the report and the PR! Could you please try upgrading langchain to ^0.3 and the Langfuse Python SDK to latest? I could not reproduce the issue any longer.

**Comment by Meteord** [comment]
Thanks for your reply! I am still getting the error:
```
 in on_retriever_start
    raise Exception("parent run not found")
```
with the following package versions:

```
langchain==0.3.0
langfuse==2.50.3
```

Here is  an example by just using the vector store as an retriever:

```python

import faiss
from langchain_community.docstore.in_memory import InMemoryDocstore
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import FakeEmbeddings
from langchain_core.documents import Document
from langfuse.callback import CallbackHandler

embeddings = FakeEmbeddings(size=1352)
index = faiss.IndexFlatL2(len(embeddings.embed_query("hello world")))

vector_store = FAISS(
    embedding_function=embeddings,
    index=index,
    docstore=InMemoryDocstore(),
    index_to_docstore_id={},
)

document_1 = Document(
    page_content="I had chocalate chip pancakes and scrambled eggs for breakfast this morning.",
    metadata={"source": "tweet"},
)

document_2 = Document(
    page_content="The weather forecast for tomorrow is cloudy and overcast, with a high of 62 degrees.",
    metadata={"source": "news"},
)
vector_store.add_documents([document_1, document_2])

retriever = vector_store.as_retriever().with_config({"run_name": "RetrieverChain"})

langfuse_handler = CallbackHandler(debug=True)

retriever.invoke(input="How is the weather forecast for tomorrow?", config={"callbacks": [langfuse_handler]})

langfuse_handler.flush()
```

**Comment by hassiebp** [comment]
Ah got it @Meteord - the issue is that no enclosing chain leads to missing parent_run when only the retriever is executed.

Thanks a lot also for your PR, lgtm!
