### ISSUE TITLE
bug:  Error During Evaluation Flow Setup with Deepbricks ChatGPT API in Langfuse

### ISSUE THREAD

**Issue by yyipkei123** [langfuse/langfuse#3225]
### Describe the bug

I am trying to set up the evaluation flow in Langfuse using the Deepbricks ChatGPT API. I've tried different configurations and models, but I keep encountering errors during in the evaluation process. Could you let me know if the Deepbricks ChatGPT API is supported for this, or if there's something else I need to configure?

Error Message:
Failed to fetch LLM completion: Error: No function_call in message [{"message":{"lc":1,"type":"constructor","id":["langchain_core","messages","AIMessage"],"kwargs":{"content":"Score: 1\nReasoning: The generation directly repeats the information provided in the query without adding any unnecessary details, making it a concise response.","tool_calls":[],"invalid_tool_calls":[],"additional_kwargs":{},"response_metadata":{"tokenUsage":{"completionTokens":30,"promptTokens":385,"totalTokens":415},"finish_reason":"stop"}}},"text":"Score: 1\nReasoning: The generation directly repeats the information provided in the query without adding any unnecessary details, making it a concise response."}]

### To reproduce

Langfuse version:v2.77.0 with cloud version

![image](https://github.com/user-attachments/assets/ad22eea4-9a67-4839-8df7-20c8dcbfce99)
![image](https://github.com/user-attachments/assets/8c773b87-f844-490b-873d-33c37cf51db6)

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
this is expected as Langfuse uses tool_calls for the evaluation feature. does Deepbricks offer an api/model that supports function calling via the openai api schema?
