### ISSUE TITLE
bug: latency (avg) always shown as 0.00s for dataset runs

### ISSUE THREAD

**Issue by justinas-kazanavicius** [langfuse/langfuse#3226]
### Describe the bug

Latency (avg) always shown as 0.00s for dataset runs even though individual runs have varying latencies.
<img width="738" alt="Screenshot 2024-09-04 at 13 15 17" src="https://github.com/user-attachments/assets/79e89983-c1ec-47b4-90d2-440e13f4a907">
<img width="441" alt="Screenshot 2024-09-04 at 13 17 17" src="https://github.com/user-attachments/assets/f3850e41-828d-4133-a90c-4e94ef411ad8">

### To reproduce

make a dataset run

### Additional information

One of the dataset run items has no latency (fake trace used only for updating the metadata), not sure if this has something to do with it.

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks for reporting this, I'll have a look!
