### ISSUE TITLE
bug(ui): scores column cannot be hidden if no scores were ever added

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#3231]
### Discussed in https://github.com/orgs/langfuse/discussions/3215

<div type='discussions-op-text'>

<sup>Originally posted by **marctorsoc** September  3, 2024</sup>
### Describe the feature or potential improvement

For some reason, the column "scores" cannot be hidden in the Traces UI, in contrast to all other columns. There's also the ID column that cannot be hidden, but that I could accept. If I'm not logging any scores, why I cannot hide such column? 

Happy to work on this if approved

### Additional information

_No response_</div>

## Options

- hide by default as it is useless if no scores were ever added
- allow hiding it

**Comment by marctorsoc** [comment]
thanks @marliessophie. This is great 👏

**Comment by marliessophie** [comment]
Glad to hear it's helpful 🙌
