### ISSUE TITLE
bug: page supports export function

### ISSUE THREAD

**Issue by l19930105** [langfuse/langfuse#3236]
### Describe the bug

page supports export function

### To reproduce

page supports export function

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Can you please share more details on this issue? Which export functionality do you mean?

**Comment by marcklingen** [comment]
Dataset exports?

**Comment by l19930105** [comment]
是的 需要支持数据集的导出功能 尤其是中文命名的数据集
