### ISSUE TITLE
bug: Python Langfuse SDK returns a Pydantic validation error when fetching a trace that uses the response_format model parameter

### ISSUE THREAD

**Issue by anatolec** [langfuse/langfuse#3241]
### Describe the bug

We are relying heavily on OpenAI's JSON mode to retrieve guaranteed JSONs from their API. But the corresponding traces cannot be fetched from Langfuse using the Python SDK

### To reproduce

1. Create a trace that uses the model parameter `response_format={"type": "json_object"}`
2. Try fetching it using the langfuse python lib : `langfuse.fetch_trace(<TRACE_ID>)`
3. You get below error:
```
4 validation errors for ParsingModel[TraceWithFullDetails]
__root__ -> observations -> 0 -> modelParameters -> response_format
  str type expected (type=type_error.str)
__root__ -> observations -> 0 -> modelParameters -> response_format
  value is not a valid integer (type=type_error.integer)
__root__ -> observations -> 0 -> modelParameters -> response_format
  value could not be parsed to a boolean (type=type_error.bool)
__root__ -> observations -> 0 -> modelParameters -> response_format
  value is not a valid list (type=type_error.list)
Traceback (most recent call last):
  File "/Users/anatolecallies/PycharmProjects/dagster-patientid-iterations/.venv/lib/python3.11/site-packages/langfuse/client.py", line 560, in fetch_trace
    trace = self.client.trace.get(id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatolecallies/PycharmProjects/dagster-patientid-iterations/.venv/lib/python3.11/site-packages/langfuse/api/resources/trace/client.py", line 86, in get
    return pydantic_v1.parse_obj_as(TraceWithFullDetails, _response.json())  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatolecallies/PycharmProjects/dagster-patientid-iterations/.venv/lib/python3.11/site-packages/pydantic/v1/tools.py", line 38, in parse_obj_as
    return model_type(__root__=obj).__root__
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatolecallies/PycharmProjects/dagster-patientid-iterations/.venv/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 4 validation errors for ParsingModel[TraceWithFullDetails]
__root__ -> observations -> 0 -> modelParameters -> response_format
  str type expected (type=type_error.str)
__root__ -> observations -> 0 -> modelParameters -> response_format
  value is not a valid integer (type=type_error.integer)
__root__ -> observations -> 0 -> modelParameters -> response_format
  value could not be parsed to a boolean (type=type_error.bool)
__root__ -> observations -> 0 -> modelParameters -> response_format
  value is not a valid list (type=type_error.list)
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "/Users/anatolecallies/PycharmProjects/dagster-patientid-iterations/.venv/lib/python3.11/site-packages/langfuse/client.py", line 564, in fetch_trace
    raise e
  File "/Users/anatolecallies/PycharmProjects/dagster-patientid-iterations/.venv/lib/python3.11/site-packages/langfuse/client.py", line 560, in fetch_trace
    trace = self.client.trace.get(id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatolecallies/PycharmProjects/dagster-patientid-iterations/.venv/lib/python3.11/site-packages/langfuse/api/resources/trace/client.py", line 86, in get
    return pydantic_v1.parse_obj_as(TraceWithFullDetails, _response.json())  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatolecallies/PycharmProjects/dagster-patientid-iterations/.venv/lib/python3.11/site-packages/pydantic/v1/tools.py", line 38, in parse_obj_as
    return model_type(__root__=obj).__root__
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatolecallies/PycharmProjects/dagster-patientid-iterations/.venv/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 4 validation errors for ParsingModel[TraceWithFullDetails]
__root__ -> observations -> 0 -> modelParameters -> response_format
  str type expected (type=type_error.str)
__root__ -> observations -> 0 -> modelParameters -> response_format
  value is not a valid integer (type=type_error.integer)
__root__ -> observations -> 0 -> modelParameters -> response_format
  value could not be parsed to a boolean (type=type_error.bool)
__root__ -> observations -> 0 -> modelParameters -> response_format
  value is not a valid list (type=type_error.list)
```

### SDK and container versions

2.46.0

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks for reporting, can you share a public link to an example trace that causes this issue?

**Comment by anatolec** [comment]
Hey @marcklingen,
Here you are : `c8897c47-adfd-48bb-8a1a-86aadbcd38ab`

**Comment by marcklingen** [comment]
> Hey @marcklingen, Here you are : `c8897c47-adfd-48bb-8a1a-86aadbcd38ab`

Can you share a URL?

**Comment by anatolec** [comment]
> > Hey @marcklingen, Here you are : `c8897c47-adfd-48bb-8a1a-86aadbcd38ab`
> 
> Can you share a URL?

Yes : https://cloud.langfuse.com/project/clxa944qk00028vsi7dp495m7/traces/c8897c47-adfd-48bb-8a1a-86aadbcd38ab?observation=87462772-8037-4f30-8171-b2f282e99714

**Comment by anatolec** [comment]
Though, it seems to depend :
Here is a trace that can be fetched without any error, that I just created using your Python OpenAI replacement : https://cloud.langfuse.com/project/clxa944qk00028vsi7dp495m7/traces/fe03cb3d-5a02-4871-8ec1-625aa48af90e?observation=b5e27c8e-4919-4c0f-80a7-760dd8aa36b9
The only difference is that here, the response_format appears in the trace metadata, rather than the model parameters.

But in the former trace (https://cloud.langfuse.com/project/clxa944qk00028vsi7dp495m7/traces/c8897c47-adfd-48bb-8a1a-86aadbcd38ab?observation=87462772-8037-4f30-8171-b2f282e99714), which was created in our product codebase, using your JS OpenAI replacement it appears in the model parameters.

I am available for a call if that helps.

**Comment by hassiebp** [comment]
Thanks for your report @anatolec ! Since [this commit](https://github.com/langfuse/langfuse-js/commit/1156a32507f354add9fb98bfc20298dcb03be8e6) we are logging the response_format as metadata and no longer as model parameters for our JS OpenAI integration. Upgrading to our latest JS SDK version should fix this issue.

**Comment by elliottower** [comment]
Unrelated to this issue, but did you find dagster and langfuse to work well together? @anatolec  Considering using langfuse for tracing / capturing LLM calls / annotation and dagster for scheduling analytics jobs / aggregating data from other sources

**Comment by anatolec** [comment]
@elliottower not really. I ended up not using Dagster to retrieve Langfuse data. Instead, I created a connector using the no-code builder of Airbyte. Now we have all our langfuse data (traces, scores) in our data warehouse and can build analytics with all the rest of our data.

**Comment by district10** [comment]
I have similar issue, when turn on fields filtering, e.g. `client.api.trace.list(fields='core')`, will throw error at:

```python
# /root/miniconda/lib/python3.12/site-packages/langfuse/api/resources/trace/client.py
class TraceClient:
    def list(...):
        ...
        try:
            if 200 <= _response.status_code < 300:
                return pydantic_v1.parse_obj_as(Traces, _response.json()) <---------- here at parse_obj_as
```

I guess `_response.json()` misses some fields TraceWithDetails expects.
Seems a logic error.
