### ISSUE TITLE
bug: Langfuse increases consumed memory from about 250MB to 500MB on AWS Lambda

### ISSUE THREAD

**Issue by shure-dev** [langfuse/langfuse#3242]
### Describe the bug

Our AWS Lambda function’s memory usage has significantly increased when integrating Langfuse. Initially, the function consumed around 250MB, but after incorporating Langfuse, it now spikes up to 500MB. 

We also have this error code:
`langfuse.request.APIError: 429 - rate limit exceeded (429):`

I will add more detail later...

### To reproduce

Our Lambda is invoked very frequently, which might contribute to the issue. 

### Additional information

Our Lambda is invoked very frequently, which might contribute to the issue. 
My team is concerned that Langfuse’s memory usage is too high for our production environment.

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Can you share how you instantiate langfuse within your lambda function? Especially when the lambda is hot this should not be an issue

**Comment by marcklingen** [comment]
Which SDK version do you use, please add this to the issue. Is this python or JS? Please share more context, happy to try to help here.

**Comment by marcklingen** [comment]
I'll close this issue as stale. Feel free to comment whenever you have time. This is not an issue that we observe across teams that use Langfuse, thus, I'd like to help figure this out together
