### ISSUE TITLE
bug: Disabling authentication when locally deploying brings me to a broken login screen

### ISSUE THREAD

**Issue by alanmun** [langfuse/langfuse#3260]
### Describe the bug

When I disable authentication, I get a broken login screen. I still get redirected to the login page, but the form popup with the email, password, and signup button are all gone. Nothing to interact with.

### To reproduce

In docker-compose.yml, I add to the server service's environment variables:
`      - AUTH_DISABLE_USERNAME_PASSWORD=true`

`docker compose up -d`

Visit localhost:3000

it will redirect to the login screen, except the little sign in modal in the center is gone. There is just a lighter toned rounded rectangle, with no elements inside. There is nothing to interact with on the screen.

### SDK and container versions

I am using the most recent version (On the same day of creating this issue, I ran git clone on this repository)

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
That's expected, from the docs:

> Email/password authentication is enabled by default. Users can sign up and log in using their email and password. To disable email/password authentication, set AUTH_DISABLE_USERNAME_PASSWORD=true.

What kind of behavior were you going for? Langfuse cannot be used without authentication at all (i'll make this more clear in the sentence in the docs mentioned above). You could set a default user via the init env vars.

**Comment by alanmun** [comment]
@marcklingen Thanks for adding more to the docs, that is what I thought, that a default root user is made and that you'd have one account for all real users to log in with. Something like that

**Comment by marcklingen** [comment]
> @marcklingen Thanks for adding more to the docs, that is what I thought, that a default root user is made and that you'd have one account for all real users to log in with. Something like that

ok, then it's best to use the init envs to make this work

**Comment by marcklingen** [comment]
docs change: https://github.com/langfuse/langfuse-docs/commit/cc1e4b03186c27a8aaac088335cfa90d35827f10
