### ISSUE TITLE
bug: Self hosted container crashes due to random CPU spikes

### ISSUE THREAD

**Issue by reza-mohideen** [langfuse/langfuse#3262]
### Describe the bug

We are seeing huge CPU and load spikes, which causes the entire application to crash and the api to be unavailable.
<img width="857" alt="Screenshot 2024-09-06 at 4 06 27 PM" src="https://github.com/user-attachments/assets/37404f10-3fdf-4ee0-b95c-e4dc875de6d8">
<img width="319" alt="Screenshot 2024-09-06 at 4 06 36 PM" src="https://github.com/user-attachments/assets/570b8030-b39c-4424-bda0-1839cd3f207f">

Even with load distributed across 2 containers we are seeing the same spike:
<img width="841" alt="Screenshot 2024-09-06 at 6 41 18 PM" src="https://github.com/user-attachments/assets/9a9bb9ae-f94d-4796-9bb4-d1f4a3437ce4">

### To reproduce

We do at least 1 request every 5-10 second to our langfuse server. We are running 1 container with 3.75 CPU and 15GB of Memory.  We have a total trace count of: 774,917.

We use langchain to make our llm calls.
```
llm = AzureChatOpenAI(
        deployment_name="nocd-gpt4o",
        openai_api_version="2024-05-01-preview",
        openai_api_key=os.getenv("AZURE_APIM_OPENAI_GPT4O_KEY"),
        azure_endpoint=os.getenv("AZURE_APIM_OPENAI_GPT4O_HOST"),
        model="gpt-4o",
        cache=False
    )

trace = langfuse.trace(
  name=request.project_name,
  user_id=request.user,
  tags=tags,
  metadata=request.metadata if request.metadata else {},
  version=request.version if request.version else "1",
  session_id=session_id,
  input=formatted_prompt,
 )

langfuse_handler = trace.get_langchain_handler()

resp = llm.invoke(formatted_prompt, config={"callbacks": [langfuse_handler]})

trace.update(output=resp)
```

### SDK and container versions

container version: 2.78.0
python sdk version: 2.47.0

### Are you interested to contribute a fix for this bug?

Yes

**Comment by maxdeichmann** [comment]
@reza-mohideen, thanks for opening the issue. This is very interesting. I have a few follow up questions:

- Do you have a special usage pattern? How many traces do you ingest per minute?
- Can you share a higher granularity of CPU? Id be interested if the CPU is that high all the time or during some CPU intensive operations
- Do you have large Inputs / Outputs for traces and do you tokenise + calculate cost in langfuse? We use tiktoken for tokenization which is quite CPU heavy. ([Docs](https://langfuse.com/docs/model-usage-and-cost))

**Comment by marcklingen** [comment]
@reza-mohideen any additional input here would be super helpful as we do not observe this issue in our own environments. would love to help resolve this or otherwise close the issue
