### ISSUE TITLE
bug: not able to bypass SSL validation for self-signed certification

### ISSUE THREAD

**Issue by jaiswalvineet** [langfuse/langfuse#3287]
### Describe the bug

so I am using langfuse langfuse==2.45.0 on GKE UAT, and we have self sign certificate there and final self hosted server URL for me is https://IP:3000, once we want to consume it on Langfuse decorator side, where its pulling host URL from env file, we don't have any provision to bypass SSL certificate validation and getting this error 

2024-09-10 08:49:46 - httpcore.connection - DEBUG - start_tls.failed exception=ConnectError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))

Ideally, we should have some key to bypass certification validation for lower environment like we have LANGFUSE_CSP_ENFORCE_HTTPS or verify=Flase, in case of requests. 

Can anyone please let me know if there are any technique  to bypass this certification change ?

### To reproduce

just host langfuse on a self-signed certificate secure connection and try to consume it via decorator   

### Are you interested to contribute a fix for this bug?

Yes

**Comment by hassiebp** [comment]
Hi @jaiswalvineet - thanks for raising this! Please use a custom httpx client with [SSL settings appropriate for your use-case](https://www.python-httpx.org/advanced/ssl/#ssl-configuration-on-client-instances) and pass that client to the [Langfuse constructor](https://langfuse.com/docs/sdk/python/decorators#configure-the-langfuse-client).
