### ISSUE TITLE
bug: Information in traces are not completely logged until a new call comes in AWS Lambda

### ISSUE THREAD

**Issue by nitskoh** [langfuse/langfuse#3292]
### Describe the bug

I am running Langchain Agents using AWS Lambda and monitoring using Langfuse

When I call the lambda function, everything is logged on Langfuse trace automatically **EXCEPT**
- the trace name, 
- user_id, 
- session_id, 
- output and 
- metadata

All five data appears for the previous trace **ONLY**  if a new lambda call comes again . 

If the new call does not come in minutes,  **the 5 data for the previous traces never appears**

It seems to me that the thread does not completely close even with using `langfuse_handler.flush()` and only closes when another call is made

View code below

### To reproduce

aws lamdba ( Docker Image)
Langchain
Self-hosted Langfuse version v2.78.0

```
@observe()
@log_time
def run_agent(data, org_id, session_id):
  #  add agent nodes and edges code definition
   langfuse_handler = langfuse_context.get_current_langchain_handler()

    langfuse_context.update_current_trace(
        name="name_of_trace",
        session_id=session_id,
        user_id=org_id,
        metadata={"model_name": 'model'},
        input=data,
    )

    final_state = graph.invoke(
        {"task": f"{data}"},
        config={"configurable": {"thread_id": "1"}, "callbacks": [langfuse_handler]},
    )

    results = final_state["messages"][-1].content
    langfuse_handler.flush()
    
    return results
```

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks for sharing! i have heard from some teams who found a good way to make this work on lambdas, let's keep this issue to add docs on what's the best practice here

**Comment by kanavvikara** [comment]
I am also facing same problem, @marcklingen whats the workaround for it?

**Comment by diaztunjano** [comment]
> thanks for sharing! i have heard from some teams who found a good way to make this work on lambdas, let's keep this issue to add docs on what's the best practice here

Would love to read about best practices on lambdas! I am facing a similar problem

**Comment by nitskoh** [comment]
Hey @marcklingen 

Wanted to follow up on what potential solutions for this
