### ISSUE TITLE
bug: token counts are not correct when the the context limit exceeds and model throws an exception

### ISSUE THREAD

**Issue by manishSan** [langfuse/langfuse#3294]
### Describe the bug

The trace UI screen shows an incorrect token count in case the bedrock service throws an exception for exceeding model context.

The input values get replaced by "\<truncated due to size exceeding limit\>" text and the UI only counts the token for the replaced text instead of the original text. 
See the attached screenshot.

![Screenshot 2024-09-10 at 10 33 37 AM](https://github.com/user-attachments/assets/5f417680-ed88-4643-9a08-db9dcae79158)

### To reproduce

Here are the steps

- Use Anthropic LLMs with AWS bedrock, this has a 200k context length.
- Make an LLM call with a Context length exceeding 200K.
- Observe the trace, check the input field, and then input tokens.
- The token always shows `8`, the token count of the replaced text.

### SDK and container versions

Langfuse version - v2.74.0
SDK version -2.45.0

### Are you interested to contribute a fix for this bug?

Yes

**Comment by marcklingen** [comment]
how did you integrate with the bedrock client? you could potentially fix this by reporting the exact token counts like this: https://langfuse.com/docs/sdk/python/decorators#log-any-llm-call

Thereby they are not inferred by langfuse but rather captured at the source (api response).

**Comment by marcklingen** [comment]
Hi @manishSan, can you provide more context here? Would love to help debug/fix/solve this

**Comment by marcklingen** [comment]
Closing this issue for now. Please follow up if you can provide more context. I would love to take a deeper look into this.

**Comment by deyancodez** [comment]
@marcklingen @manishSan i am facing a similar issue and was wondering if the limit can be tweaked for the payload to be recieved at server side
