### ISSUE TITLE
bug: Column doesn't disappear upon unselecting it in Langfuse UI

### ISSUE THREAD

**Issue by lucaordronneau** [langfuse/langfuse#3309]
### Describe the bug

In the Langfuse UI, when selecting and then unselecting a Score column name, the corresponding column does not disappear as expected. This appears to be caused by a string character ".", making it impossible to remove the column.

See on images (Evaluation-1.1 and Evaluation-1.2), selected and unselected but still on the table.
<img width="889" alt="image" src="https://github.com/user-attachments/assets/e71cd999-4c7e-4c33-ab33-6b64df86fd78">
<img width="878" alt="image" src="https://github.com/user-attachments/assets/8a62cad1-97dc-424f-81aa-45bcca28d1d8">

### To reproduce

Run an experiment with a score name with a "." in it.

### Are you interested to contribute a fix for this bug?

No

**Comment by marliessophie** [comment]
Hey @lucaordronneau we've fixed the issue in [this pull request](https://github.com/langfuse/langfuse/pull/3793), thanks for reporting 🙌
