### ISSUE TITLE
bug(datasets): run-level scores incorrect if they are associated with observations and not just traces

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#3310]
### Discussed in https://github.com/orgs/langfuse/discussions/3307

<div type='discussions-op-text'>

<sup>Originally posted by **MaxYaz** September 11, 2024</sup>
Hi!
I have a Dataset with two items in it. After I run an evaluation I can see scores for every item:
![Screenshot 2024-09-11 at 11 43 51](https://github.com/user-attachments/assets/d9545322-bc4b-494e-9645-e045cb10dcca)
But the problem is the aggregated metric for a dataset run is not being displayed:
![Screenshot 2024-09-11 at 11 45 50](https://github.com/user-attachments/assets/01a190c3-bbdf-44bd-98d4-4e52220604e2)
Any ideas why this can be the case?</div>

**Comment by MaxYaz** [comment]
@marcklingen Hi!
Issues can be closed. I created a new dataset and everything worked out. Guess I got affected by LangFuse auto update. LangFuse version should be pinned :)

**Comment by marcklingen** [comment]
> @marcklingen Hi! Issues can be closed. I created a new dataset and everything worked out. Guess I got affected by LangFuse auto update. LangFuse version should be pinned :)

ok awesome, thanks for sharing!
