### ISSUE TITLE
bug: Unable to Update Trace in Second AWS Lambda Using Custom Trace Id

### ISSUE THREAD

**Issue by diaztunjano** [langfuse/langfuse#3322]
### Issue: Unable to Update Trace in Second AWS Lambda Using Langfuse SDK

**Context**:  
I am developing a WhatsApp chatbot using AWS Lambda functions and the Langfuse Python Low-Level SDK to trace interactions. Here's a brief overview of the architecture:

1. **First Lambda**:  
   - Creates a trace with relevant user information:
     ```python
     trace = langfuse.trace(
                 name=trace_name,
                 session_id=session_id,
                 user_id=user_id,
                 input=context.user_message,
                 id=custom_trace_id
             )
     ```
   - This trace logs OpenAI API calls and displays correctly in the dashboard.
   - Emits an event (with `custom_trace_id`) to trigger the second Lambda.

2. **Second Lambda**:  
   - Sends the reply message to the user and receives a `whatsapp_reply_id`.
   - Attempts to update the trace (with `custom_trace_id`) to add the `reply_message` and `whatsapp_reply_id` as metadata:
     ```python
     langfuse.trace(
         id=trace_id,
         output=reply_message,
         metadata={"whatsapp_reply_id": whatsapp_reply_id},
     )
     ```

**Problem**:  
The trace is not updated in the second Lambda, despite calling `langfuse_context.flush()` before both Lambdas finish execution. 

**Debugging Details**:  
- I have enabled `Langfuse(debug=True)` in the second Lambda. The relevant logs are:

**Log 1**:
```python
[DEBUG] 2024-09-12T01:35:52.806Z fca08116-8d75-562e-a709-de4acad66314 Creating trace id='wamid.HBgLNTY5NjMxODYxNjMVAgASGBQzQUI1NkQ0N0IwQzg5NjE2QjVBNQA=_ask_to_edit_first_movement' timestamp=datetime.datetime(2024, 9, 12, 1, 35, 52, 806607, tzinfo=datetime.timezone.utc) output='Hola Dave, ...' metadata={'whatsapp_reply_id': 'wamid.HBgLNTY5NjMxODYxNjMVAgARGBI2QTkyNTM5OTE3RTM4MTZDNzIA'}
```

**Log 2**:
```python
[DEBUG] 2024-09-12T01:35:52.806Z fca08116-8d75-562e-a709-de4acad66314 Applying deterministic sampling to trace_id: wamid.HBgLNTY5NjMxODYxNjMVAgASGBQzQUI1NkQ0N0IwQzg5NjE2QjVBNQA=_ask_to_edit_first_movement with rate 1.0
```

**Expected Outcome**:  
The trace should be updated in the second Lambda, displaying the `reply_message` and `whatsapp_reply_id` as metadata.

**Current Outcome**:  
The trace is not being updated in the second Lambda, and no error is returned.

### To Reproduce

1. **Create the First Lambda**:
   - In the first AWS Lambda function, create a trace using the Langfuse SDK:
     ```python
     trace = langfuse.trace(
         name=trace_name,
         session_id=session_id,
         user_id=user_id,
         input=context.user_message,
         id=custom_trace_id
     )
     ```
   - Log some information (e.g., API calls to an LLM) to the trace.
   - Emit an event containing the `custom_trace_id` to trigger a second Lambda function.

2. **Create the Second Lambda**:
   - In the second AWS Lambda function, simulate sending a reply message to the user and receiving a `whatsapp_reply_id`.
   - Attempt to update the trace from the first Lambda using the `trace_id`:
     ```python
     langfuse.trace(
         id=trace_id,
         output=reply_message,
         metadata={"whatsapp_reply_id": whatsapp_reply_id},
     )
     ```
   - Ensure that `langfuse_context.flush()` is called before the Lambda completes execution.

### Additional information

Here is the code snippet for the second lambda:

```python
langfuse = Langfuse(debug=True)

def handler(event: SQSEvent, context: LambdaContext) -> Dict[str, Any]:
    for record in event["Records"]:
        try:
            message_body = json.loads(record["body"])

            user_phone_number = message_body["detail"]["data"]["user_phone_number"]
            user_message_id = message_body["detail"]["data"]["user_message_id"]
            outgoing_message = message_body["detail"]["data"]["outgoing_message"]
            whatsapp_business_id = message_body["detail"]["data"][
                "whatsapp_business_id"
            ]
            trace_id = message_body["detail"]["data"].get("trace_id", "")
            create_metadata_movement_with_user_message_id = message_body["detail"][
                "data"
            ].get("create_metadata_movement_with_user_message_id", "")

            logger.info(
                f"Event info received: user_phone_number: {user_phone_number}, user_message_id: {user_message_id}, outgoing_message: {outgoing_message}, whatsapp_business_id: {whatsapp_business_id}, trace_id: {trace_id}, create_metadata_movement_with_user_message_id: {create_metadata_movement_with_user_message_id}"
            )

            reply_message_id = send_whatsapp_reply_message(
                user_phone_number,
                whatsapp_business_id,
                user_message_id,
                outgoing_message,
            )

            logger.info(f"Message sent. Reply message id: {reply_message_id}")

            if reply_message_id:
                output = outgoing_message.get("text", {}).get(
                    "body"
                ) or outgoing_message.get("interactive", {})

                logger.info(f"Updating trace {trace_id} with output {output}")

                langfuse.trace(
                    id=trace_id,
                    output=output,
                    metadata={"reply_message_id": reply_message_id},
                )

               
                langfuse_context.flush()

            return create_response(200, "Processing complete")

        except Exception as e:
            logger.error(f"Error processing message: {e}")

            langfuse.trace(
                id=trace_id,
                name="ERROR: SEND_REPLY_MESSAGE",
                metadata={"error": str(e)},
            )

            langfuse_context.flush()

            return create_response(500, "Error processing message")

    return create_response(200, "No records processed")
```

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Sorry for the slow response here<br><br>Thanks for the elaborate bug report, this is super helpful to understand the issue here.

> The trace is not updated in the second Lambda, despite calling `langfuse_context.flush()` before both Lambdas finish execution.

To confirm, all changes that you want to make (metadata/output) in the second lambda are not reflected in the trace?<br>---

Did you try whether logging traces from your second lambda works in general? Your implementation looks good and distributed tracing by passing trace_id from one function to another function is totally supported across Langfuse integrations.

As a next step, I'd like to rule out that this is not a general problem of the tracing setup in your second lambda as I suspect this issue is unrelated to the distributed nature of your traces.

**Comment by marcklingen** [comment]
@diaztunjano did you resolve this issue? happy to help in case this is still a problem

**Comment by marcklingen** [comment]
Gentle ping as I'd love to either help fix or close this issue

**Comment by diaztunjano** [comment]
Im sorry for the late response Marc. 

My main concern was that the user_id and session_id were not being saved properly and that the metadata was not being updated. I managed to get it working properly by performing more updates to the trace in different steps of the process. Also, my logic got a bit more complicated so now the trace_id is going through 3 lambdas (instead of 2 as presented in the issue) and this seems to save correctly the information.

**Comment by marcklingen** [comment]
Ok awesome, thanks for confirming that this works now
