### ISSUE TITLE
bug: ChatOCIGenAI model name not captured by python langchain integration

### ISSUE THREAD

**Issue by octadion** [langfuse/langfuse#3323]
### Describe the bug

I am using ChatOCIGenAI from Langchain with model IDs: cohere.command-r-plus, cohere.command-r-16k, and meta.llama-3-70b-instruct. The model IDs are prefixed with the provider's name.

Here is my code:
```
elif provider_lower == "oci":
    print("using oci")
    return ChatOCIGenAI(
        model_id=model_name,
        service_endpoint=other_fields.get('service_endpoint'),
        compartment_id=other_fields.get('compartment_id'),
        model_kwargs={"temperature":temperature}
    )
```

When I run the code with ChatOCIGenAI, the trace is saved, but I encounter a warning Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name. Please create an issue so we can fix your integration: https://github.com/langfuse/langfuse/issues/new/choose. In my tracking, the model name does not appear to be saved.

### To reproduce

```
from langchain_community.chat_models.oci_generative_ai import ChatOCIGenAI

chat = ChatOCIGenAI(
    model_id="meta.llama-3-70b-instruct", # example, or cohere.command-r-plus or cohere.command-r-16k
    service_endpoint=service_endpoint,
    compartment_id=compartment_id,
)
response = chat.invoke("query", temperature=0.7)
print(response.content)
```

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks for reporting this!

**Comment by hassiebp** [comment]
Thanks for reporting this @octadion! We have just released improvements to model name parsing for Langchain. Could you please upgrade to Langfuse Python SDK version >=2.51.1 and try again? 🙏🏾

**Comment by octadion** [comment]
Thanks for the update @hassiebp 
I tried upgrading to langfuse version >=2.51.1, but I am still seeing the following warning:
![image](https://github.com/user-attachments/assets/0af8f4ff-d817-460f-9871-84be42787011)

After checking my Langfuse setup, I noticed that the new changes for model name parsing don't seem to be applied yet. (cohere)
![image](https://github.com/user-attachments/assets/4e9e88b7-76fd-4511-ae65-f30bbef64ed3)

Additionally, I encountered a small validation issue related to the TraceBody schema:
![image](https://github.com/user-attachments/assets/6e2a188b-1ff7-4c5f-8749-7ded5be33fb9)

This occurs when userId is {} instead of None. In the previous version (2.48.1), this error didn’t happen because the userId was set to None by default. It seems like there was a change in how userId is being handled in the new version.

For now, I've patched it by manually ensuring that userId is set to a valid string or None, but I wanted to bring this to your attention as it may be affecting others upgrading as well.

Let me know if there's any additional information I can provide

**Comment by hassiebp** [comment]
@octadion Thanks for following up on this, could you please try again with patch 2.51.2?

As for your validation issue, how exactly did the `userId` ended up being `{}` in the first place? Could you kindly share a trace ID for me to have a closer look?

**Comment by octadion** [comment]
Thank you @hassiebp . After updating the parsing model to 2.51.2, the integration of the Cohere model with LangChain is now successfully stored.
![image](https://github.com/user-attachments/assets/587a062b-9354-4224-8a0c-0f9d6ddd5605)

Regarding the user_id error, I’ve set it up like this in the LangChain-Langfuse integration:
```
from langfuse.callback import CallbackHandler
langfuse_handler = CallbackHandler(
    public_key=langfuse_public_key,
    secret_key=langfuse_secret_key,
    host=langfuse_baseurl,
    user_id=bot.id
)
print("Langfuse public key:", langfuse_public_key)
print("Langfuse secret:", langfuse_secret_key)
print("Langfuse host:", langfuse_baseurl)
print("User ID:", bot.id)
trace_id = langfuse_handler.trace.id
print("Trace ID:", trace_id)
```
Based on the print output, there are no issues, and the user ID is recorded in the tracer, though there’s still a validation error.
![image](https://github.com/user-attachments/assets/c971de33-8a2a-47ae-8ac6-2b0c89bee13c)

**Comment by hassiebp** [comment]
Great to hear the model parsing now works!

As for the second issue, could you please share a full trace ID for which you encounter the error?

**Comment by hassiebp** [comment]
Closing this as stale. Please reopen if issue persists.
