### ISSUE TITLE
feat: openai o1-preview and o1-mini support across playground and tracing (cost tracking)

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#3340]
### Discussed in https://github.com/orgs/langfuse/discussions/3338

<div type='discussions-op-text'>

<sup>Originally posted by **juan-abia** September 13, 2024</sup>
### Describe the feature or potential improvement

Add this new models to langfuse default models. Reasoning tokens are not available trough the API, but we do get the number of tokens used (see image)
![image](https://github.com/user-attachments/assets/bf1cf34d-032d-4e36-9326-c38db99e3640)

### Additional information

_No response_</div>

**Comment by juan-abia** [comment]
I have no idea of what I'm doing, but adding the model to cost tracking would be just this PR?
https://github.com/langfuse/langfuse/pull/3341

**Comment by hassiebp** [comment]
Thanks a lot @juan-abia - we have merged #3343 to provide o1 support. We have to drop manual tokenisation for cases where no token counts as provided, as the output string alone tokenized does not reflect the total output token count for reasoning models, where the reasoning tokens from the intermediate steps count towards to total output token count.
