### ISSUE TITLE
bug: Unknown argument `refresh_token_expires_in` with Github connection. 

### ISSUE THREAD

**Issue by manzan46** [langfuse/langfuse#3355]
### Describe the bug

👋 I'm trying with the self hosted langfuse to setup Github authentication but run into an issue. 

```
'Unknown argument `refresh_token_expires_in`. Available options are marked with ?.\n' +
' at An (/app/node_modules/.pnpm/@prisma+client@5.17.0_prisma@5.17.0/node_modules/@prisma/client/runtime/library.js:114:7526)\n' +
' at _n.handleRequestError (/app/node_modules/.pnpm/@prisma+client@5.17.0_prisma@5.17.0/node_modules/@prisma/client/runtime/library.js:121:7392)\n' +
' at _n.handleAndLogRequestError (/app/node_modules/.pnpm/@prisma+client@5.17.0_prisma@5.17.0/node_modules/@prisma/client/runtime/library.js:121:7057)\n' +
' at _n.request (/app/node_modules/.pnpm/@prisma+client@5.17.0_prisma@5.17.0/node_modules/@prisma/client/runtime/library.js:121:6741)\n' +
' at async l (/app/node_modules/.pnpm/@prisma+client@5.17.0_prisma@5.17.0/node_modules/@prisma/client/runtime/library.js:130:9355)',
name: 'PrismaClientValidationError'
}
```

```
Unknown argument `refresh_token_expires_in`. Available options are marked with ?. PrismaClientValidationError:
Invalid `prisma.account.create()` invocation:
```

the documentation of NextAuth mention it https://next-auth.js.org/providers/github 

> GitHub returns a field on Account called refresh_token_expires_in which is a number. See their [docs](https://docs.github.com/en/developers/apps/building-github-apps/refreshing-user-to-server-access-tokens#response). Remember to add this field to your database schema, in case if you are using an [Adapter](https://authjs.dev/getting-started/database).

I can indeed not see it in [the schema](https://github.com/langfuse/langfuse/blob/main/packages/shared/prisma/schema.prisma#L36) but I'm surprised to be first one to encounter this issue so might something on my side 🙃 

### To reproduce

Install from `image: ghcr.io/langfuse/langfuse:2` (similar behavior with latest tag, `ghcr.io/langfuse/langfuse:sha-6ffec33`)

Use github env var to be able to login with github and then try to login.

### SDK and container versions

 `image: ghcr.io/langfuse/langfuse:2` (similar behavior with latest tag, `ghcr.io/langfuse/langfuse:sha-6ffec33`)

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Thanks for sharing! I cannot replicate this on cloud.langfuse.com (lot's of people there use github auth). Can you try whether you can sign in there with your account?

**Comment by marcklingen** [comment]
Seems like a common issue that occurs for some people and that is fixed in the next major version of nextauth (not released yet). I'll add this field to the schema, no real downside if it increases compatibility for some.

**Comment by manzan46** [comment]
> Thanks for sharing! I cannot replicate this on cloud.langfuse.com (lot's of people there use github auth). Can you try whether you can sign in there with your github account?

Yes no issue at all on `cloud.langfuse.com` and indeed did think that many use Github even on self hosted version and could not find much similar issue, that why I'm unsure if it does not come from how we configure the client on Github side or an option we forgot. 

> Seems like a common issue that occurs for some people and that is fixed in the next major version of nextauth (not released yet). I'll add this field to the schema, no real downside if it increases compatibility for some.

Thanks for looking into it!

**Comment by marcklingen** [comment]
PR open, will be fixed in next release
