### ISSUE TITLE
bug: Prompt variable shows in edit but not in display

### ISSUE THREAD

**Issue by alexrosen** [langfuse/langfuse#3359]
### Describe the bug

A handlebar variable name shows when creating and editing a prompt. When viewing the prompt the display shows "No variables".

### To reproduce

Create a prompt with a variable. Confirm that the variable name shows in edit mode. Click "Create prompt" to save.

View the new prompt. Confirm that the Variables section says "No variables".

### SDK and container versions

N/A

### Additional information

![Screenshot 2024-09-14 100713](https://github.com/user-attachments/assets/98ce5027-d4bd-4727-8ff3-91cdbcbff610)
![Screenshot 2024-09-14 100757](https://github.com/user-attachments/assets/adc9771c-29df-49b8-aa69-e11ba78c9a85)

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment]
Thanks for your report @alexrosen - I've opened a PR with a fix, to be released soon after it is merged 👍🏾
