### ISSUE TITLE
bug: Wrong redirect after successful sign up when using NEXT_PUBLIC_BASE_PATH

### ISSUE THREAD

**Issue by rors41** [langfuse/langfuse#3434]
### Describe the bug

Successful sign up redirects to "/" instead of value set in NEXT_PUBLIC_BASE_PATH [sign-up.tsx](https://github.com/langfuse/langfuse/blob/932913cd76cda129736acc103bcf752aa27b3bed/web/src/pages/auth/sign-up.tsx#L73).

### To reproduce

Build dockerfile from production branch with NEXT_PUBLIC_BASE_PATH parameter set.
Sign up with a new user.

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks for reporting this
