### ISSUE TITLE
bug: Scores don't show up in the langfuse dashboard

### ISSUE THREAD

**Issue by ajram23** [langfuse/langfuse#3451]
### Describe the bug

If you goto the dashboard and switch to a month (in my case), you will find that the scores is empty. See screenshot below
<img width="1405" alt="Screenshot 2024-09-23 at 9 40 57 AM" src="https://github.com/user-attachments/assets/1da79cd4-ac04-438d-8bd5-392dce31d7d9">
However if you go to score you will find scores from those dates 
<img width="1643" alt="Screenshot 2024-09-23 at 9 41 19 AM" src="https://github.com/user-attachments/assets/e9791a59-27ef-4db3-8e10-26f8c1e2e12b">

### To reproduce

See above

### SDK and container versions

Running on langfuse.com

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks for creating this issue, we will have a look!

**Comment by ajram23** [comment]
> thanks for creating this issue, we will have a look!

FYI, Not sure if I am making a mistake, not seeing tags in traces/dashboard either. Here is my code:         ```
langfuse_handler = CallbackHandler(
            secret_key=os.getenv('LANGFUSE_SECRET_KEY'),
            public_key=os.getenv('LANGFUSE_PUBLIC_KEY'),
            host=os.getenv('LANGFUSE_HOST'),
            user_id=email,
            release=os.getenv('APP_VERSION'),
            tags=["ingest", Config.APP_ENV],
            session_id=session_id
        )
``` I can create a separate issue if its a bug.

**Comment by marliessophie** [comment]
Hey, thanks for reporting the issue. I had a quick look and it seems your scores are not coming up on the dashboard as the traces they are referencing have been deleted. The dashboard only pulls scores with existing reference objects. We'll add a note stating this to the info icon next to the Scores 'No data' label in this empty state, to better explain this 👍  

> FYI, Not sure if I am making a mistake, not seeing tags in traces/dashboard either
We currently don't have a chart for tags on the dashboard. However, you may filter for tags, I have included a screenshot below to demonstrate the filter view. 

Please let me know in case of more questions!  

<img width="1238" alt="Screenshot 2024-09-23 at 16 43 52" src="https://github.com/user-attachments/assets/61a12b99-3e02-462d-aa24-5a2ca057789b">

**Comment by ajram23** [comment]
@marliessophie thank you for the quick turn around. Sorry I am missing something, 1. I haven't deleted any traces on langfuse 2. If they are deleted why show them in scores but not in the dashboard? 3. I am aware of how to filter the tags. My issue is that they aren't showing up even in the trace - they used to. See code attach above. Perhaps I am making a rookie mistake - very possible.

**Comment by ajram23** [comment]
@marliessophie I was able to debug the issue further, looks like the run_id or trace_id submitted is wrong. I need to figure out what the trace_id for the langchain invoke run is. Do you have a recommended way to do?

**Comment by ajram23** [comment]
Closing this issue. Turned out to be an issue of run_ids. Documentation could be clearer but not a bug. If someone else runs into this issue, use the same ID that you can get from langchain after an invoke and use it when you send the scores.

**Comment by marcklingen** [comment]
Thanks for sharing. I've just updated the docs: [https://langfuse.com/docs/integrations/langchain/tracing#predefined-trace-id--add-evaluation-or-user-feedback-score](https://langfuse.com/docs/integrations/langchain/tracing#predefined-trace-id--add-evaluation-or-user-feedback-score)
