### ISSUE TITLE
bug: app use SDK falls over after 408 from Langfuse

### ISSUE THREAD

**Issue by jonnyforsterMSG** [langfuse/langfuse#3456]
### Describe the bug

A langchain app that uses Langfuse for monitoring and prompt management via the sdk seems to fall over and stop responding if the downstream hosted langfuse server responds with a 408. 

Our apps including langfuse are hosted in AKS and langfuse has a postgres DB in Azure. We belive the db is under spec'd and this is causing us problems so we are going to add more power to see if it improves the situation. However the langchain app that uses langfuse should not need to killed and recreated in the cluster because a dependency has failed. The only error I get it 'Received 408 error by Langfuse server, not retrying:' which I'm assuming comes from the SDK? The app then falls over and I have to kill it and recreate. This error should be handled more gracefully.

I'm using langfuse in two places, as the callback

langfuse_handler = CallbackHandler(
        os.getenv('LANGFUSE_PUBLIC_KEY'),
        os.getenv('LANGFUSE_SECRET_KEY'),
        os.getenv('LANGFUSE_HOST'),
        metadata={
            "call_id": call_id, 
            "langserve_version": version("langserve"),
            "langchain_version": version("langchain_core"),
            "langchain_openai_version": version("langchain_openai"),
            "endpoint": endpoint_name,
            "useragent": user_agent
        },
        session_id=session_id,
        trace_name=f"{endpoint_name}_{call_id}",
        timeout=60
    )

langfuse_handler.auth_check()
    config = RunnableConfig(callbacks=[langfuse_handler])
    summary_chain = base_chain.with_config(config)
    return summary_chain.invoke(transcript)`

and for prompt management

prompt_manager = Langfuse(
          public_key=os.getenv('LANGFUSE_PUBLIC_KEY'),
          secret_key=os.getenv('LANGFUSE_SECRET_KEY'),
          host=os.getenv('LANGFUSE_HOST'),
          timeout=60
      )

assert prompt_manager.auth_check()
langfuse_prompt = prompt_manager.get_prompt(
        prompt_name,
        fallback=fallback_prompt
    )
prompt = PromptTemplate.from_template(langfuse_prompt.get_langchain_prompt())
return prompt, langfuse_prompt.config

### To reproduce

Underpower your hosted langfuse app db and send some traffic to it in the form of telemetry and prompt retrieval. Wait for the overwelmed server to error and the calling langchian app will stop responding. Haven't ried outside of AKS. Sending ~1k traces a day

### SDK and container versions

v 2.39.1 will upgrade to latest version now in case it helps

### Additional information

I get zero logs in AKS for from the langfuse container, is there a way to turn this on?

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment]
Thanks a lot for reporting this, @jonnyforsterMSG ! Indeed the client that is running Langchain should handle this more gracefully. I am curious on why exactly the container crashes (out of memory?), were you able to diagnose anything with that regard?

As a next step, it would be helpful if you could share the debug logs for the crashing container when adding `debug=True` to the CallbackHandler instantiation.

**Comment by hassiebp** [comment]
Closing this as stale. Please reopen if issue persists.

**Comment by jonnyforsterMSG** [comment]
Sorry for the delay I turned on debug=true but I can't share the results as it is littered with PII. I couln't find anything immediately obvious from the logs either, but can check again if there's anything you specifically want me to look at. 

Yes I think the container crashes becuase it's out of memory. The cluster couldn't scale anymore and the allocation was constantly increasing. I've been running tracemalloc to take a constant snapshots and can see that the biggest memory drain is Python\Python312\Lib\threading.py. It gets bigger with every request so I'm pretty sure that's my culprit

I'm using FastApi and langchain in the client and it should be all async (below examples). The only other bit of code is where the chain is setup which retrieves the prompt from langfuse. Is there something I need to configure in the callback and\or the get_prompt call to make sure I'm not holding onto resources or creating excessive threads?

`@app.post(f"/{ENDPOINT}")
async def summarise_call_transcript(request: Request, body: SummaryRequestBody):
    """
    Summarise the call transcript using the provided details.

    Args:
        request (Request): The HTTP request object.
        body (SummaryRequestBody): The body of the request containing call details.

    Returns:
        dict: The summary of the transcript.

    Raises:
        HTTPException: If an error occurs during processing.
    """
    try:
        return await create_summary(
            call_id=body.input.callId,
            transcript=body.input.transcript,
            session_id=body.input.sessionId,
            base_chain=get_base_chain(),
            endpoint_name=ENDPOINT,
            user_agent=request.headers.get("user-agent")
        )
    except Exception as exception:
        print(traceback.format_exc())
        raise HTTPException(status_code=500, detail="An error has occurred") from exception
    finally:
        snapshot = tracemalloc.take_snapshot()
        top_stats = snapshot.statistics('lineno')

        print("[ Top 10 ]")
        for stat in top_stats[:10]:
            print(stat)`

`async def create_summary(
        call_id: str,
        transcript: str,
        session_id: str,
        base_chain: Any,
        endpoint_name: str,
        user_agent: str
) -> Any:
    """
    Create a summary with the given transcript and required LLM parameters.

    Args:
        call_id (str): The identifier of the call.
        transcript (str): The conversation that occurred on the call.
        session_id (str): An identifier to tie traces together.
        base_chain (Any): The base chain.
        endpoint_name (str): The API endpoint that was invoked to trigger this process.
        user_agent (str): The HTTP user agent header.

    Returns:
        Any: The summary of the transcript.
    """
    langfuse_handler = CallbackHandler(
        os.getenv('LANGFUSE_PUBLIC_KEY'),
        os.getenv('LANGFUSE_SECRET_KEY'),
        os.getenv('LANGFUSE_HOST'),
        metadata={
            "call_id": call_id,
            "langfuse_version": version("langfuse"),
            "langchain_version": version("langchain_core"),
            "langchain_openai_version": version("langchain_openai"),
            "endpoint": endpoint_name,
            "user_agent": user_agent
        },
        session_id=session_id,
        trace_name=f"{endpoint_name}_{call_id}",
        timeout=60,
    )
    if not langfuse_handler.auth_check():
        raise ValueError("Authentication with Langfuse failed.")

    config = RunnableConfig(callbacks=[langfuse_handler])
    summary_chain = base_chain.with_config(config)
    return await summary_chain.ainvoke(transcript)`

**Comment by hassiebp** [comment]
@jonnyforsterMSG The issue is likely that you are not reusing your `CallbackHandler` instance but reinstantiating it on every `create_summary` call. This sets up a new Langfuse client each time with their own background threads, leading ultimately to your OOM error.

Could you please refactor your code to instantiate `CallbackHandler` only once?

**Comment by jonnyforsterMSG** [comment]
This has fixed my problem thank you
