### ISSUE TITLE
bug: there's no DATABASE_PORT env var

### ISSUE THREAD

**Issue by guidev** [langfuse/langfuse#3457]
### Describe the bug

It would be nice to have a `DATABASE_PORT` env var for self-hosting https://langfuse.com/docs/deployment/self-host

This way we could use a custom DB port

### To reproduce

https://github.com/langfuse/langfuse/blob/5f94ca8e82a5f744c894058bb89d4c38c4b05d8f/web/entrypoint.sh#L7

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks for raising this. Is it an option for you to just include the port in DATABASE_HOST as most teams use the default port?

**Comment by marcklingen** [comment]
Closing this as this can be achieved via DATABASE_HOST, please add a comment in case this does not solve the issue for you
