### ISSUE TITLE
bug: Inconsistent tracing with @observe and asyncio

### ISSUE THREAD

**Issue by gsouf** [langfuse/langfuse#3471]
### Describe the bug

With the python SDK. My top function is wrapped with `@observe()`. Inside there are many calls to gpt completion api via `AsyncAzureOpenAI` from `langfuse.openai`. 

When these calls are run sequentially, langfuse works well and produces consistent results. However when they are parallelized, langfuse seems to result in somehow inconsistent results. For the same input, langfuse dashboard will report different traces where some calls seem to be missing - **and that's not due to gpt resulting in different generation** .

There might be a problem with langfuse and `AsyncAzureOpenAI`.

Is there something obvious here? Some practice I might have missed?

As it's not a priority for us I haven't taken time to investigate further. If that's not an obvious issue to debug, I'll provide further details here

### To reproduce

Given the following files:

- **test.py**
```python
from dotenv import load_dotenv
from langfuse.decorators import observe
from langfuse.openai import AsyncOpenAI
import asyncio

load_dotenv()

client = AsyncOpenAI()

# Example async function that takes a letter as input
async def call_async_function(number):
    res = await client.chat.completions.create(
        model="gpt-4o-mini",
        max_tokens=100,
        messages=[
            {"role": "user", "content": f"Write this number in letters: '{number}'"}
        ],
    )

    return res.choices[0].message.content

@observe()
async def story():
    # starts generation async
    tasks = [call_async_function(letter) for letter in range(10)]

    # await for all
    results = await asyncio.gather(*tasks)

    # show results
    for result in results:
        print(result)

@observe()
async def main():
    await story()

# Run the main function using asyncio
if __name__ == "__main__":
    asyncio.run(main())
```
- **.env**
```
LANGFUSE_SECRET_KEY=""
LANGFUSE_PUBLIC_KEY=""
LANGFUSE_HOST=""
OPENAI_API_KEY=""
```
- **requirements.txt**
```
langfuse
openai
python-dotenv
```

- install dependencies
- fill .env
- run test.py
- observe traces broken in langfuse

When I run this script I get the following output:

```
Zero
One
Two
The number '3' in letters is "three."
Four
Five
Six.
Seven
Eight
Nine
```

In langfuse dashboard I see the following traces:
![image](https://github.com/user-attachments/assets/4a155dbb-7eb3-4cba-960c-0c996c690f9e)

When I open the first the generation trace for the prompt "Write this number in letters: '0'":

![image](https://github.com/user-attachments/assets/28af8c06-9e6c-4b6d-b543-0ae6764cf25e)

As you can see there are few problems:
- only 6 "Generation" when I actual had 10 calls. 
- All calls have 0 generation tokens, but the output of the script shows that it  
- the trace for the call "Write this number in letters: '0'" has no output
 

### Working example:

I modified the "main" function to sleep for 1 second before returning and it will work:

```
@observe()
async def main():
    await story()
    await asyncio.sleep(1)
```

![image](https://github.com/user-attachments/assets/15cdf33c-6010-4be8-a254-3b82ef5deb63)

### SDK and container versions

pip: langfuse==2.49.0

### Are you interested to contribute a fix for this bug?

Yes

**Comment by hassiebp** [comment]
Thanks for your report @gsouf! Could you kindly share a minimum example for which you encountered the inconsistencies?

**Comment by gsouf** [comment]
@hassiebp Actually nothing special to do to reproduce the issue, just use the asyncClient within asyncio and tracing will be broken. I updated the ticket description and provided steps to replicate, as well as a workaround with sleeping before returning

**Comment by marcklingen** [comment]
@hassiebp can you have a look into this one again?

**Comment by hassiebp** [comment]
Hi @gsouf - please make sure to flush the events to Langfuse after the execution. Your adjusted example here works well for me: 

```python
from dotenv import load_dotenv
from langfuse.decorators import observe
from langfuse.openai import openai, AsyncOpenAI
import asyncio

load_dotenv()

client = AsyncOpenAI()


# Example async function that takes a letter as input
async def call_async_function(number):
    res = await client.chat.completions.create(
        model="gpt-4o-mini",
        max_tokens=100,
        messages=[
            {"role": "user", "content": f"Write this number in letters: '{number}'"}
        ],
    )

    return res.choices[0].message.content


@observe()
async def story():
    # starts generation async
    tasks = [call_async_function(letter) for letter in range(10)]

    # await for all
    results = await asyncio.gather(*tasks)

    # show results
    for result in results:
        print(result)


@observe()
async def main():
    await story()


# Run the main function using asyncio
if __name__ == "__main__":
    asyncio.run(main())

    openai.flush_langfuse()
```

**Comment by gsouf** [comment]
@hassiebp thanks! As running operation asynchronously might be something user might want to often, may I recommend flush operation in case of an async context is something easier to discover in the langfuse documentation?

**Comment by hassiebp** [comment]
Whether async or not, when running in short-lived environments, a final flush ensures queued events are delivered properly. <br><br>What do you mean exactly by 'work by itself'? What would be the possible experience from your perspective?

**Comment by gsouf** [comment]
@hassiebp I was in the impression that it works well when not using sync context and that some mechanism were used to make sure the script will not leave before it's saved 
Also it's not mentioned in the doc that flushing is necessary, so that was just an assumption that we could somehow have it to work without flushing in async environment too

**Comment by hassiebp** [comment]
You are right, I'm sure you have carefully read the docs and if it didn't became clear, we have to do a better job documenting. Thanks for the feedback!

Flushing is always necessary in short-lived environments to guarantee event delivery to Langfuse servers, irrespective of sync vs async.

In any case, great to see your issue resolved!
