### ISSUE TITLE
bug: ERROR:langfuse:API error occurred:

### ISSUE THREAD

**Issue by brosand** [langfuse/langfuse#3490]
### Describe the bug

When trying to use langfuse with the langchain integration, I get this bug:

```
ERROR:langfuse:API error occurred: Unexpected error occurred. Please check your request and contact support: https://langfuse.com/support.
```

### To reproduce

I setup the process like this
```
import os
from langchain_azure_chat_models import AzureChatOpenAI
from langfuse.callback import CallbackHandler

# Set up LangFuse CallbackHandler with API keys and host
langfuse_handler = CallbackHandler(
    public_key=os.getenv("LANGFUSE_PUBLIC_KEY"),
    secret_key=os.getenv("LANGFUSE_PRIVATE_KEY"),
    host=os.getenv("LANGFUSE_HOST"),
)

# Initialize the Azure OpenAI language model with the callback handler
llm = AzureChatOpenAI(
    temperature=0,
    deployment_name="your-azure-deployment-name",
    openai_api_version="2024-05-01-preview",
    openai_api_type="azure",
    azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
    openai_api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    callbacks=[langfuse_handler],
)

# Example usage of the LLM
async def get_response():
    response = await llm.ainvoke("Hello, how are you?")
    return response.content
```

### SDK and container versions

langchain==0.2.16
langchain-community==0.2.17
langchain-core==0.2.41
langchain-openai==0.1.25
langchain-text-splitters==0.2.4
langfuse==2.51.1
langsmith==0.1.128

### Additional information

Self-hosted, kubernetes

### Are you interested to contribute a fix for this bug?

No

**Comment by brosand** [comment]
followup -- seems to be related to #1456

**Comment by hassiebp** [comment]
@brosand Could you please upgrade langchain and move to the recommended `from langchain_openai import AzureChatOpenAI` and try again?

https://python.langchain.com/docs/integrations/chat/azure_chat_openai/

**Comment by hassiebp** [comment]
Closing this as stale. Please reopen if issue persists.
