### ISSUE TITLE
bug: favicon not affected by NEXT_PUBLIC_BASE_PATH

### ISSUE THREAD

**Issue by emfomy** [langfuse/langfuse#3495]
### Describe the bug

With `NEXT_PUBLIC_BASE_PATH=/langfuse` set, the favicon link is `href="/favicon-32x32.png"`, not `href="/langfuse/favicon-32x32.png"`

### To reproduce

Follows https://langfuse.com/docs/deployment/self-host#custom-base-path

* Set `NEXT_PUBLIC_BASE_PATH=/langfuse`
* Rebuild docker image
* Open website
* Check favicon in html head section

### SDK and container versions

v2.81.0

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Fixed it, will be included in next release
