### ISSUE TITLE
docs: add intent classification example notebook to the Cookbook/docs

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#3498]
## Context

Langfuse helps to track issues with LLM applications via evaluation scores:[ https://langfuse.com/docs/scores](https://langfuse.com/docs/scores) 

Often it is helpful to classify different user intents in LLM Applications (e.g. Q&A chatbots) to understand for which user intents the issues are prevalent. Currently many developers who want to do this lack good instructions and an example that they can follow as this is not documented yet.

## Goal

Add Notebook to the Langfuse cookbook in the documentation which demonstrates how to run intent classification outside of Langfuse to label the data

## Idea

1. Fetch data via langfuse sdk: fetch_traces
2. Run intent classification/clustering library on data
3. Add the intent label back to langfuse as a tag via the sdk

**Comment by marcklingen** [comment]
Sure, looking forward to the contribution on this as this will be very useful for many teams who do not have an intent classification pipeline yet

**Comment by thompsgj** [comment]
@marcklingen Hello, I've completed an initial version of the notebook for review.  Happy to make any changes.  

One question I had... Should I add an entry for this notebook in the `_routes.json`?

**Comment by marcklingen** [comment]
thank you, I'll try to review this asap. I can add _routes, no worries

**Comment by marcklingen** [comment]
fyi, this just made it to the main docs

https://langfuse.com/docs/analytics/example-intent-classification
