### ISSUE TITLE
feat: Add ability to add a note to a Langfuse API key

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#3500]
## Goal

When having many api keys, it is helpful to add a note to each api key in order to remember which key maps to which use case. This helps to delete them later on.

## Suggested change

- Add editable field that writes onChange in the [APIKeyList](https://github.com/langfuse/langfuse/blob/main/web/src/features/public-api/components/ApiKeyList.tsx).
- [Note](https://github.com/langfuse/langfuse/blob/800b2136b9ee43c688659e2a8de3b4fae109ab1b/packages/shared/prisma/schema.prisma#L142) already exists in the db schema is not used until now.
- Probably needs update trpc route that is only used for note updates.

## Discussed in https://github.com/orgs/langfuse/discussions/2642

<sup>Originally posted by **agibralter** July 16, 2024</sup>

> It would be helpful to be able to label or name different API keys (e.g. for different application environments). Right now, the only label is the date created and the public key itself which is not very user-friendly.

**Comment by faresbouzayen** [comment]
Hi @marcklingen! I’m interested in working on adding a note feature for the Langfuse API keys.

Proposed Changes:
Editable Field: Add an editable field in the APIKeyList to input notes for each key.
Database Integration: Utilize the existing note field in the database schema.
Update TRPC Route: Ensure the TRPC route is updated to handle note changes.
This will definitely help in managing multiple API keys better! I’ll start digging into it and let you know if I have questions. Thanks!

**Comment by marcklingen** [comment]
Sure, please open a PR once this is ready

**Comment by Atharva1723** [comment]
Can I work on this issue?

**Comment by marcklingen** [comment]
Sure, open for contributions on this @Atharva1723

**Comment by marcklingen** [comment]
completed here: https://github.com/langfuse/langfuse/pull/4686
