### ISSUE TITLE
feat: variable width of main menu on non-mobile screens

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#3501]
Currently the main menu is always visible on larger screens and moved to a drawer on smaller screens.

As many views in Langfuse benefit from horizontal space, it'd make sense to make the menu collapsible on larger screens to reduce it's width. The icons of the different product features should still be visible.

[This](https://ui.shadcn.com/examples/mail) is a good example and uses shadcn/ui which is already used across Langfuse including Resizable

https://github.com/user-attachments/assets/c20872a6-38f6-46ed-abf6-1e5a9f174208

All of the core logic for this is currently in [layouts.tsx](https://github.com/langfuse/langfuse/blob/main/web/src/components/layouts/layout.tsx). Please note that the available menu items are dynamically created based on routes (this should not change). Also, langfuse currently has a seconday menu item level which would be nice to keep

**Comment by marcklingen** [comment]
@Sahil-Sinha-11 I'll update the issue with more context later today!

**Comment by marcklingen** [comment]
Updated the issue description with more details on this. The goal here is to have a narrow-width option on large screens which does not fully hide the menu (see video in issue description)

**Comment by marctorsoc** [comment]
Hi @Sahil-Sinha-11 , thanks for willing to help. You look like real FE (not like me 😄 ), so I don't think you will, but if I can help at all, let me know and we can share / split the work. I really would like this feature to be implemented :)

**Comment by faresbouzayen** [comment]
Hey @marcklingen! I’m excited to take on the task of implementing a collapsible main menu for larger screens.

Plan:
Collapsible Menu: Implement a narrow-width option that retains visibility of icons for product features.
Dynamic Menu Items: Ensure the menu items dynamically generated based on routes remain intact.
Secondary Menu: Keep the secondary menu items as part of the design.
Let’s enhance the layout and make the most of the horizontal space! I’ll dive into the layouts.tsx file and keep you posted on my progress. Thanks!

**Comment by marcklingen** [comment]
Quick research

- this seems good: https://github.com/salimi-my/shadcn-ui-sidebar
- Apparently there’s an official version coming very soon from shadcn/ui acc to his x posts

**Comment by marcklingen** [comment]
shadcn/ui sidebar is released: https://ui.shadcn.com/docs/components/sidebar

WIP PR: #3837
