### ISSUE TITLE
Mask / redact PII from traces logged to langfuse

### ISSUE THREAD

**Issue by hassiebp** [langfuse/langfuse#3518]
### Discussed in https://github.com/orgs/langfuse/discussions/3402

<div type='discussions-op-text'>

<sup>Originally posted by **marcklingen** September 18, 2024</sup>
### Describe the feature or potential improvement

In todays community session, the idea came up multiple times to redact PII and other sensitive information from traces.

I'd suggest to add a callback on the integration level which can be optionally used to remove sensitive data before it is logged to Langfuse.

### Additional information

Potential DX (low-level sdk, extends to other integrations)

```python
import re

langfuse = Langfuse(
    # redact emails
    mask=lambda input: re.sub(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', '[REDACTED]', input)
)
```

Probably a util is necessary here to apply the mask to more complex (size/objects) inputs/outputs without performance issues.</div>

**Comment by ajram23** [comment]
+1

**Comment by marcklingen** [comment]
I'd add that if the whole update operation was available as context, this masking could also be used to disable logging of I/O for some observations alltogether

**Comment by pexxi** [comment]
This feature would be greatly appreciated on the JS SDK in our company!

**Comment by Spinachboul** [comment]
@marcklingen  Can we also use lazy masking approach in this case? I believe when the function detects the presence of sensitive information in the log, only then it will apply the masking which will improve performance and cosume less memory!!

**Comment by marcklingen** [comment]
I think it could be cool to defer applying the mask to the background thread that actually batches and exports the events to the langfuse api, that's a good idea. Not sure if necessary in a v1 version of this though

**Comment by Spinachboul** [comment]
@marcklingen Why dont in the v1 version , we keep the simplicity and mask the data as soon as it gets logged, and in the later versions we can try deferring the mask application to the background!!

**Comment by marcklingen** [comment]
Sounds good to me, happy to support a contribution to this!

**Comment by Spinachboul** [comment]
@marcklingen Can I be assigned to work on this issue??

**Comment by marcklingen** [comment]
sure, are you interested in JS, Python or both? Can you share your suggested implementation as a rough spec before starting to implement it?

**Comment by someshfengde** [comment]
Hi @marcklingen  can you please assign this issue to me. I'd like to work on python's side implementation. 

I'm thinking about using [microsoft/presidio](https://github.com/microsoft/presidio) package for detecting PII information. It works better compared to simple re search. workflow for package. 

![image](https://github.com/user-attachments/assets/3d352886-74aa-431f-b2b9-9f5749bde63c)

I might still need some help in clarifying how can I integrate this with langfuse. Before I've worked mostly with LLM integrations and have personally used langfuse in few of my projects :)

**Comment by marcklingen** [comment]
Sounds good, I think the important thing here is that the hook in the SDK accepts any lambda and we do not force the use of a specific library assuming that different use cases require different libraries/implementations. regex is just a very simple -dependency example.

**Comment by marcklingen** [comment]
I'd look into the python sdk implementation, langfuse-python sdk. All integrations re-use the core langfuse client

**Comment by ajram23** [comment]
Only thing about regex is that it is very brittle. IMHO, Brittle doesn't work for PII.

**Comment by marcklingen** [comment]
agree, i don't think that regex is the solution here, I just meant that the implementation should expose the full trace/observation event and expect a lambda as a mask which can either be simple (e.g. regex or mask out all content for observations with name "secret") or complex (use a custom classifier or something like presidio)

**Comment by yassineselmi** [comment]
I think integrating with Presidio or LLMGuard Scanners is a good idea. But the fact that we can pass any callable function as "pre-processing" will be great feature.

+1

**Comment by someshfengde** [comment]
one thing I'm afraid of that it'll add some latency in storing some responses. But most of traces will be small still there will be some impact. 

Underlying issue in presidio; https://github.com/microsoft/presidio/issues/1461

**Comment by epeters3** [comment]
+1 for allowing an arbitrary lambda. We would love to use something like this to replace image data URLs in our traces with metadata about the image instead. The images themselves can be a few MBs in size and cause trace spans to become not visible in Langfuse, due to size.

**Comment by ajram23** [comment]
@

> one thing I'm afraid of that it'll add some latency in storing some responses. But most of traces will be small still there will be some impact.
> 
> Underlying issue in presidio; [microsoft/presidio#1461](https://github.com/microsoft/presidio/issues/1461)

Looks like this is only for big files. Am I mistaken?

**Comment by shawnzhu** [comment]
I made https://github.com/langfuse/langfuse-python/pull/967 for the python SDK. it's very simple and will cover input/output. comments are appriciated!

**Comment by someshfengde** [comment]
> @
> 
> > one thing I'm afraid of that it'll add some latency in storing some responses. But most of traces will be small still there will be some impact.
> > Underlying issue in presidio; [microsoft/presidio#1461](https://github.com/microsoft/presidio/issues/1461)
> 
> Looks like this is only for big files. Am I mistaken?

yes it's for big files only

**Comment by hassiebp** [comment]
Passing a custom masking function has been released, please check out our docs, try it out and let us know your feedback! 🙏🏾 

- [Docs](https://langfuse.com/docs/tracing-features/masking)
- [Python SDK release](https://github.com/langfuse/langfuse-python/releases/tag/v2.53.0)
- [JS SDK release](https://github.com/langfuse/langfuse-js/releases/tag/v3.28.0)

**Comment by david-heward-unmind** [comment]
Is there something that could help with encrypting/decrypting the chat transcript at the field level in the database?

**Comment by marcklingen** [comment]
> Is there something that could help with encrypting/decrypting the chat transcript at the field level in the database?

We do currently explore application level encryption with some larger teams that might require it for their security guidelines. If you are interested, please reach out marc at langfuse com

Details on this here: https://langfuse.com/docs/deployment/self-host#application-level-encryption

**Comment by toxfox69** [comment]
This is something I've been building specifically for this use case — a PII interceptor that sits between agent execution and Langfuse trace emission.

The approach: classify PII using on-device ML before the SDK logs anything, replace actual values with typed placeholders (`[PII_SSN_a1b2c3]`, `[PII_MEDICAL_3d4e5f]`), and store an encrypted vault for authorized de-tokenization. Trace structure is fully preserved for debugging — only the sensitive values are tokenized. Nothing leaves the customer's infrastructure.

I built this as a Langfuse-compatible callback wrapper — it hooks into the trace emission pipeline at the SDK level, so it works transparently with existing instrumentation.

Demo is live at https://the-service.live/scrub if anyone wants to see the classification in action (paste any text, see what gets flagged and replaced).

Happy to share the integration code for the Langfuse SDK wrapper if that's useful for this issue. The scrub + de-tokenize pattern seems like a clean fit for the callback-based approach @marcklingen suggested.

**Comment by MuthulakshmiRK** [comment]
Hey, saw your discussion around masking PII in traces.

I’ve been experimenting with a small API that detects and masks emails/phones before logging (works on nested JSON too).

Would be curious how you're handling this currently — happy to share what I built if useful.
