### ISSUE TITLE
bug: model latency is using K as unit

### ISSUE THREAD

**Issue by gyliu513** [langfuse/langfuse#353]
### Describe the bug

The latency for the model should be ms but not k

### To reproduce

login to langfuse.com with view-only account

<img width="1340" alt="Screenshot 2023-10-12 at 11 29 17 AM" src="https://github.com/langfuse/langfuse/assets/4461983/b4c31912-0e48-4705-a1a4-8d749e92c116">

**Comment by gyliu513** [comment]
good, it works, thanks @maxdeichmann 

@maxdeichmann can you explain abi for `50th Percentile`, `90th Percentile`? Thanks

**Comment by maxdeichmann** [comment]
> good, it works, thanks @maxdeichmann
> 
> @maxdeichmann can you explain abi for `50th Percentile`, `90th Percentile`? Thanks

Awesome! What do you mean with 'abi'? The percentiles are calculated using `percentile_disc`, see: https://www.postgresql.org/docs/9.4/functions-aggregate.html

**Comment by gyliu513** [comment]
@maxdeichmann good to know, thanks.

My bad, it is not `abi`, I was originally meaning `a bit` :)

**Comment by maxdeichmann** [comment]
> @maxdeichmann good to know, thanks.
> 
> My bad, it is not `abi`, I was originally meaning `a bit` :)

Haha ok, you're welcome :) If you want to have further explanations, let me know.
