### ISSUE TITLE
bug: DEBUG:langfuse:~0 items in the Langfuse queue

### ISSUE THREAD

**Issue by ajram23** [langfuse/langfuse#3539]
### Describe the bug

Unwanted logging from Langfuse floods the log file/terminal. Doesn't happen every time but when it does, it's unstoppable. It suggests that it depends on the code path. I don't even have logging level as debug (have it as INFO)

### To reproduce

Run the application you have with langfuse libraries.

### SDK and container versions

langfuse python 2.51.0

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks for raising this, this should only be logged if the logging level is DEBUG

**Comment by hassiebp** [comment]
Hi @ajram23 - what exactly do you mean by it is depending on the code path? Have you found a way to reproduce this reliably? 🤔

**Comment by ajram23** [comment]
@hassiebp seems to be happening reliability in my app this morning. Happy to show it to you!

**Comment by hassiebp** [comment]
This seems to be an issue most likely with your local setup @ajram . Could you please 

* try to find all occurrences of `debug` in your codebase to rule out any instantiation with `debug=True`
* make sure the `LANGFUSE_DEBUG` environment variable is not set
* manually mute the langfuse logger via 

\`\`\`python

import logging 

logger = logging.getLogger('langfuse')

logger.disabled = True

```
```

**Comment by ajram23** [comment]
@hassiebp thanks! Let me double check and get back to you!

**Comment by ajram23** [comment]
@hassiebp you were right, I messed up - rookie error! Sincere apologies! Closing this!

**Comment by hassiebp** [comment]
No worries, AJ - happy to help and to have this resolved! 🙏🏾🎉
