### ISSUE TITLE
bug: ValidationError: str type expected for userId in TraceBody

### ISSUE THREAD

**Issue by spacepirate0001** [langfuse/langfuse#3565]
### Describe the bug

When updating a trace using the Langfuse client, I'm encountering a validation error for the `userId` field in `TraceBody`. The error suggests that a string type is expected, but it seems the value being passed is of a different type.

```
ERROR:langfuse:1 validation error for TraceBody
userId
str type expected (type=type_error.str)
Traceback (most recent call last):
File "c:\Users\hayth\vsc_workstation\Carbon.Cloud.nl2sql.venv\Lib\site-packages\langfuse\client.py", line 2887, in update
request = TraceBody(**trace_body)
^^^^^^^^^^^^^^^^^^^^^^^
File "c:\Users\hayth\vsc_workstation\Carbon.Cloud.nl2sql.venv\Lib\site-packages\pydantic\v1\main.py", line 341, in init
raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for TraceBody
userId
str type expected (type=type_error.str)
```

### To reproduce

```
# Create a RunnableConfig
            runnable_conf = RunnableConfig(
                max_concurrency=MAX_CONCURRENCY,
                run_name=str(run_uuid),
                run_id=str(run_uuid),
                callbacks=[langfuse_handler],
                tags=[f"model={query.model}", f"platform={os.environ.get('PLATFORM')}"]
            )
# Define the runnable chain
            runnable_chain = RunnableSequence(similar_prompt | llm | parser)
            
# Invoke the runnable chain to generate the SQL query
            response = runnable_chain.invoke(
                {"natural_language_query": query.query, "schema": schema_string},
                config=runnable_conf
            )
```

### SDK and container versions

SDK langfuse==2.51.2
Container image v2.81.2

### Additional information

**Expected Behavior**
The `userId` field should either accept non-string types and convert them to strings internally, or provide clearer error messages about the expected type.

**Actual Behavior**
The update operation fails with a validation error, stating that a string type is expected for `userId`.

**Additional Context**
This error occurs even when the `userId` is not explicitly set in the code, suggesting it might be an issue with how default values are handled or how the `TraceBody` is constructed.

**Possible Solutions**
1. Automatically convert non-string `userId` values to strings
2. Provide more detailed error messages about the type and value causing the issue
3. Allow `None` or other types for `userId` if appropriate

### Are you interested to contribute a fix for this bug?

No

Any assistance or clarification on how to properly set the `userId` when updating a trace would be greatly appreciated.

**Comment by hassiebp** [comment]
Thanks for raising this, @spacepirate0001 ! Do you see this exception raised when invoking the chain? I do not see an `update` operation that you mentioned, nor an explicit setting of `userId` 🤔

**Comment by spacepirate0001** [comment]
@hassiebp the issue happens `on_chain_end` in `langfuse/callback/langchain.py` L#890  `_update_trace_and_remove_state` somewhere here:

```
        """Update the trace with the output of the current run. Called at every finish callback event."""
        chain_trace_updates = self.trace_updates.pop(run_id, {})

        if (
            parent_run_id
            is None  # If we are at the root of the langchain execution -> reached the end of the root
            and self.trace is not None  # We do have a trace available
            and self.trace.id
            == str(run_id)  # The trace was generated by langchain and not by the user
        ):
            self.trace = self.trace.update(
                output=output, **chain_trace_updates, **kwargs
            )
```

**Comment by zoltan-fedor** [comment]
Same here.
I had to pin our `langfuse` client at `2.50.3`, as `2.51.3` was throwing this error.

**Comment by hassiebp** [comment]
Thanks for raising this, PR with a fix is up to be merged and released soon 👍🏾

**Comment by zoltan-fedor** [comment]
Thanks, `v2.51.4` has fixed it for me.
