### ISSUE TITLE
bug: Inconsistency in token count between sdk and ui

### ISSUE THREAD

**Issue by saiprasath21** [langfuse/langfuse#3582]
### Describe the bug

<img width="1468" alt="Screenshot 2024-10-04 at 5 01 34 PM" src="https://github.com/user-attachments/assets/a0a77a6c-d0cc-42af-ac92-20d8e3207a1a">
<img width="671" alt="Screenshot 2024-10-04 at 5 02 11 PM" src="https://github.com/user-attachments/assets/21246c18-87c3-4905-a577-0b1df91b20ff">

I'm trying to get the token usage at the end of a RAG chain and store it in my DB. 

The token count gets correctly reflected in the UI, but when trying to access it through the sdk it's wrong. I've attached the corresponding images. 

### To reproduce

`
        lf_client.flush()
        observations = lf_client.get_trace(
            id=lf.langfuse_context.get_current_trace_id()
        ).observations
        for obs in observations:
            if obs.type in "GENERATION":
                print(obs.usage)
`

### Additional information

If I add a 0.5 sec sleep between the flush and get_trace, the values are consistent. Is there a lag between flush and things getting uploaded to the right DB?

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment]
@saiprasath21 Thanks for raising this! After delivering the events to the Langfuse server via `flush`, events are queued on the backend for processing which might take a few moments. The succeeding `flush` reflects that events are acknowledged by LF servers, but not yet finally processed. CC @maxdeichmann

**Comment by saiprasath21** [comment]
Is there a way to find out how long to wait before I end my process after flushing?

**Comment by hassiebp** [comment]
There is no way for that at the moment unfortunately. Probabilistically, it should only take a few seconds. If you rely on strong guarantees for your application, please open a feature request for that on our discussions board 👍🏾
