### ISSUE TITLE
bug: OpenAI beta.chat.completions.parse fails for openai >= 1.50.0

### ISSUE THREAD

**Issue by hassiebp** [langfuse/langfuse#3635]
### Describe the bug

Since OpenAI Python SDK release 1.50 (https://github.com/openai/openai-python/releases/tag/v1.50.0) , generations related to structured output parsing are not logged to Langfuse. 

### To reproduce

Install OpenAI Python SDK version >=1.50. 

Run: 

```python
    from typing import List
    from langfuse.openai import openai
    from pydantic import BaseModel

    class CalendarEvent(BaseModel):
        name: str
        date: str
        participants: List[str]

    openai.beta.chat.completions.parse(
        model="gpt-4o-2024-08-06",
        messages=[
            {"role": "system", "content": "Extract the event information."},
            {
                "role": "user",
                "content": "Alice and Bob are going to a science fair on Friday.",
            },
        ],
        response_format=CalendarEvent,
    )

    openai.flush_langfuse()
```

### Are you interested to contribute a fix for this bug?

Yes

**Comment by lshalon** [comment]
Perhaps we can also add a test around this?

**Comment by hassiebp** [comment]
@lshalon - a fix has been [released here](https://github.com/langfuse/langfuse-python/releases/tag/v2.51.5), could you please upgrade and try again? 🙏🏾
