### ISSUE TITLE
bug: Not able to sign up on local docker

### ISSUE THREAD

**Issue by chethan-chavan** [langfuse/langfuse#3639]
### Describe the bug

Unable to signup with local docker (localhost:3000)

### To reproduce

# Clone the Langfuse repository
git clone https://github.com/langfuse/langfuse.git
cd langfuse
 
# Start the server and database
docker compose up

browser login to : http://localhost:3000/auth/sign-up
<img width="1504" alt="Screenshot 2024-10-08 at 2 39 07 PM" src="https://github.com/user-attachments/assets/63180428-49a9-423a-806f-94047f21371f">

### Are you interested to contribute a fix for this bug?

No

**Comment by Steffen911** [comment]
Hey @chethan-chavan ,
Thank you for your report. We are currently investigating this issue and can confirm that we see the same thing. We assume that it's due to a next.js update that we released in 2.83.0. We'll roll this back and create a new patch release once we confirm the fix.

**Comment by marcklingen** [comment]
also reported here:
https://github.com/orgs/langfuse/discussions/3637
https://github.com/orgs/langfuse/discussions/3641

**Comment by marcklingen** [comment]
hotfix: https://github.com/langfuse/langfuse/pull/3640

released: https://github.com/langfuse/langfuse/releases/tag/v2.83.1

**Comment by marcklingen** [comment]
docker builds need roughly 1h to be available, you can check the github action status to track this

**Comment by thanga-v2** [comment]
wow, thanks for the timely help.

**Comment by marcklingen** [comment]
sure, sorry for the inconvenience of a broken build here

**Comment by thanga-v2** [comment]
No worries. Thank you for your timely attention and help.
