### ISSUE TITLE
bug: `shutdownAsync` is not reachable from the `observeOpenAI`'s return Proxy

### ISSUE THREAD

**Issue by mifopen** [langfuse/langfuse#3642]
### Describe the bug

I guess it should be possible to use `shutdownAsync` and not only `flushAsync` that is exposed.

### To reproduce

```ts
const client = observeOpenAI(...);
client.shutdownAsync(); // <-- not available()
```

### Are you interested to contribute a fix for this bug?

Yes

**Comment by hassiebp** [comment]
@mifopen Thanks for raising this, agree that `shutdownAsync` has to be exposed. As I saw you'd be open to contribute on this, feel free to open a PR! (Implementation should be quite straightforward analogously to exposing `flushAsync`)

**Comment by hassiebp** [comment]
This has been recently released, please upgrade your SDK 🙏🏾
