### ISSUE TITLE
bug: Sign-in button not visible while setting up with docker

### ISSUE THREAD

**Issue by thanga-v2** [langfuse/langfuse#3648]
### Describe the bug

Unable to sign in
<img width="1512" alt="Screenshot 2024-10-08 at 6 59 23 PM" src="https://github.com/user-attachments/assets/d9dcf41b-dec5-4c45-90eb-b56f0af917e0">
<img width="1497" alt="Screenshot 2024-10-08 at 6 59 49 PM" src="https://github.com/user-attachments/assets/95bcfe1f-86cb-45c9-9eb5-e06b5b1bf776">

### To reproduce

Please find the atached docker logs as well.

### Are you interested to contribute a fix for this bug?

No

**Comment by thanga-v2** [comment]
Tried authProviders.credentials as true, still the button is not visible. @dosu
![Screenshot 2024-10-08 at 7 22 48 PM](https://github.com/user-attachments/assets/f18d679e-1eb3-4ee2-b7fe-a26b6aec9831)

**Comment by thanga-v2** [comment]
Tried with github still not working....

![Screenshot 2024-10-08 at 7 29 58 PM](https://github.com/user-attachments/assets/de46ad5f-584e-4e09-9ae8-49972ec7a0d9)

**Comment by thanga-v2** [comment]
Generated next_auth_secret, salt and encryption key as well. @dosu
![Screenshot 2024-10-08 at 7 57 39 PM](https://github.com/user-attachments/assets/c1103b6d-bd07-41e7-88f8-fdef56c849fc)

**Comment by thanga-v2** [comment]
already did. not working @dosu

**Comment by marcklingen** [comment]
this is fixed, please pull the latest container version

see https://github.com/langfuse/langfuse/issues/3639 for more details

**Comment by thanga-v2** [comment]
Thank you so much @marcklingen

**Comment by thanga-v2** [comment]
It is working now
![Screenshot 2024-10-09 at 11 57 11 AM](https://github.com/user-attachments/assets/a4f7814c-3438-4d4f-ad46-f6ea19d846b1)
