### ISSUE TITLE
bug: Using "#" in trace_id prevents from viewing it

### ISSUE THREAD

**Issue by eliorc** [langfuse/langfuse#3669]
### Describe the bug

I'm reporting to Langfuse through LiteLLM, and everything works as expected.
I recently changed the naming of my traces to be `trace#0`, `trace#1` ... `trace#n` to help me see the iterative nature of my applicaiton.
After this change, I noticed that I can view the traces inside the session page, but in the trace page they appear in the list but when clicking on them I get an error.

Sessions page -> I can see the session ✅ 
Session view (after I click a specific session) -> I can see all the traces and their content ✅ 
Traces page -> I can see all the traces ✅ 
Trace view (after I click a specific trace) -> Stuck on loading and shows an error ❌ 

Screenshot:
![image](https://github.com/user-attachments/assets/8d10aa86-23b3-4a0e-8d77-0291a1d0facb)

### To reproduce

I believe the cause is the `#` in the trace name, just use `#` in the name.

### SDK and container versions

Using container with `langfuse/langfuse:2`, version 2.82.0 OSS.

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks for reporting this!

**Comment by marcklingen** [comment]
I was able to reproduce this, looking into a fix

**Comment by marcklingen** [comment]
fixed it, will be merged once ci is passed. logging off for today, you can pull container langfuse/langfuse:main if you do not want to wait for the release tomorrow (generally not recommended as :2 are the released versions
