### ISSUE TITLE
bug: `Test in playground` from generation does not populate messages

### ISSUE THREAD

**Issue by FlorDonnaSanders** [langfuse/langfuse#3671]
### Describe the bug

When pushing `Test in playground` from a generation, the messages are not auto populated in the playground (anymore?).

E.g. pushing `Test in playground` here
![image](https://github.com/user-attachments/assets/a9580099-98ad-422a-95f0-efbe6b81a3db)
Goes to
![image](https://github.com/user-attachments/assets/5882ddb8-0681-4ad8-b877-bc66939dc76d)

### To reproduce

- Go to a generation
- Press the test in playground button
- See an empty list of messages

### Additional information

Tested in both chrome and firefox.

### Are you interested to contribute a fix for this bug?

No

**Comment by FlorDonnaSanders** [comment]
FYI: Test in playground from the prompt manager does still work, only seems broken from the generation window.

**Comment by marcklingen** [comment]
Can you share an example generation from tracing that does not work? Currently generations that are not ChatML are ignored afaik

**Comment by marcklingen** [comment]
can you share the raw json?

**Comment by marcklingen** [comment]
assuming default role could cause errors, it's interesting to understand what's going on here. is this the message array that you use with openai models?

**Comment by FlorDonnaSanders** [comment]
When constructing our messages, we do add a `role: "user"` entry to the message field, but it seems that information is stripped somewhere in our pipeline (possibly somewhere in the langchain parsing), causing it to be lost before calling the OpenAI API.  
I will do some further research and fix it from our end. Good to know the test in playground functionality is otherwise working.
