### ISSUE TITLE
bug: prisma migrations failing on container startup due to error `schema is not empty`

### ISSUE THREAD

**Issue by rhighs** [langfuse/langfuse#3676]
### Describe the bug

I am trying to deploy a langfuse docker image on google cloud run and its database is running somewhere else. Starting fresh is pretty easy and yields no errors. However, if I try to perform a new deployment of the container (e.g. I want to change version) I get the following errors:

```
2024-10-09 12:47:35.939 CEST
Prisma schema loaded from packages/shared/prisma/schema.prisma
2024-10-09 12:47:36.029 CEST
Datasource "db": PostgreSQL database "appdb", schema "public" at "localhost"
2024-10-09 12:47:36.263 CEST
252 migrations found in prisma/migrations
2024-10-09 12:47:36.368 CEST
Error: P3005
2024-10-09 12:47:36.368 CEST
The database schema is not empty. Read more about how to baseline an existing production database: https://pris.ly/d/migrate-baseline
2024-10-09 12:47:36.387 CEST
Applying database migrations failed. This is mostly caused by the database being unavailable.
```

**These errors complain that**:
- The database migration has failed
- The reason for failure is likely the db not being available
    - I can tell you that is not the case, as the db is reachable and stayed up all the time

Disabling migrations at docker startup (using `LANGFUSE_AUTO_POSTGRES_MIGRATION_DISABLED=true`) seems to solve the issue, but this would expose me to bugs given by schema updates/missing fields.
     - I want to keep safe from this happening

This is a problem since it shows up a container error and it makes it exit almost immediately, now allowing me to perform a deployment without completely resetting the database (no bueno). Thank you!
  

### To reproduce

Simply perform a google cloud run deployment setting the following env vars:

```
export DATABASE_URL=""
export DIRECT_URL="<nonPoolingDbUrl>"
export NEXTAUTH_URL="<nextauthUrl>"
export NEXTAUTH_SECRET="<nextauthSecret>"
export SALT="<salt>"
export ENCRYPTION_KEY="<encryptionKey>"
export HOSTNAME="0.0.0.0"
```

### SDK and container versions

- Container image version: [langfuse:latest](https://hub.docker.com/layers/langfuse/langfuse/latest/images/sha256-1030b8d86d058aa407c95db9dab2898122566c71a9dd839893241c664dd0d5c6?context=explore)
- SDK Version: `none`

### Are you interested to contribute a fix for this bug?

No

**Comment by rhighs** [comment]
> Hello @rhighs! I'm here to help you with any bugs, questions, or contributions you have in mind. Let's work together to resolve the issue you're facing.
> 
> To resolve the database migration error (P3005) when deploying a Langfuse Docker image on Google Cloud Run, consider the following steps:
> 
> 1. **Shadow Database Configuration**: If your database user lacks the `CREATE DATABASE` permission, create a shadow database and configure the `SHADOW_DATABASE_URL`. This is often necessary for cloud databases. Refer to the [Prisma docs](https://www.prisma.io/docs/orm/prisma-migrate/understanding-prisma-migrate/shadow-database#cloud-hosted-shadow-databases-must-be-created-manually) for detailed instructions.
> 2. **Database User Permissions**: Ensure the database user has the necessary permissions for migrations. You might need to use a different user for migrations by setting the `DIRECT_URL` environment variable. For large deployments, configure the database user with long timeouts as migrations might take a while to complete.
> 3. **Environment Variables**: Double-check that all required environment variables are correctly set, especially `DATABASE_URL` and `DIRECT_URL`. You can also use `DATABASE_HOST`, `DATABASE_USERNAME`, `DATABASE_PASSWORD`, and `DATABASE_NAME` as alternatives to `DATABASE_URL`.
> 4. **Cloud SQL Permissions**: If using Google Cloud SQL, ensure the service accounts have the `Cloud SQL Client` role to avoid authorization issues. Grant this role to the service accounts ending in `@appspot.gserviceaccount.com` and `-compute@developer.gserviceaccount.com`.
> 5. **Cloud Run Configuration**: Ensure the Cloud Run service is configured to connect to the Cloud SQL instance by enabling Cloud SQL connections and selecting the created Cloud SQL instance in the dropdown.
> 
> By addressing these points, you should be able to resolve the migration error without disabling migrations [[1]](https://langfuse.com/docs/deployment/self-host)[[2]](https://langfuse.com/docs/self-host)[[3]](https://github.com/langfuse/langfuse-docs/blob/main/pages/docs/deployment/self-host.mdx).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

1. Didn't try the shadow database option. I honestly don't understand why that would be needed.
2. User has all the necessary permissions, why would it fail only the second time after a migration has been applied successufully in the past deployment.
3. No need for this.
4. Out of scope
5. Out of scope

**Comment by marcklingen** [comment]
Do you provide the same database credentials to the application via `DATABASE_URL`?

**Comment by marcklingen** [comment]
afaik setting `SHADOW_DATABASE_URL` has solved similar issues for others in the past.

However, the prisma docs mention that it is not used for the deploy command: [https://www.prisma.io/docs/orm/prisma-migrate/understanding-prisma-migrate/shadow-database](https://www.prisma.io/docs/orm/prisma-migrate/understanding-prisma-migrate/shadow-database)

**Comment by rhighs** [comment]
> deploy command

@marcklingen I honostly didn't give it a try yet, I'll let you know about this. How about "deploy command" what do you mean exactly? What discriminates this from other type of commands? )if there's any)

**Comment by maxdeichmann** [comment]
@rhighs can you check the migrations table for me? Is there anything in the logs column? Could you also give me the output from the prisma status command? https://www.prisma.io/docs/orm/reference/prisma-cli-reference#migrate-status

**Comment by rhighs** [comment]
@maxdeichmann how would you suggest running prisma status, i've containerized the app. Should i just pull a repo at the same release version and run it from there?

**Comment by rhighs** [comment]
I've managed to run the prisma status command as I said above, simply pointing to the production database. It seems indeed there are a few unapplied migrations. My langfuse instance is pointing to dockerhub tag `latest`, what would you suggest me doing?

```
255 migrations found in prisma/migrations
Following migrations have not yet been applied:
20230518191501_init
20230518193415_add_observaionts_and_traces
20230518193521_changes
20230522092340_add_metrics_and_observation_types
20230522094431_endtime_optional
20230522131516_default_timestamp
20230523082455_rename_metrics_to_gradings
20230523084523_rename_to_score
20230529140133_user_add_pw
20230530204241_auth_api_ui
20230618125818_remove_status_from_trace
20230620181114_restructure
20230622114254_new_oservations
20230623172401_observation_add_level_and_status_message
20230626095337_external_trace_id
20230705160335_add_created_updated_timestamps
20230706195819_add_completion_start_time
20230707132314_traces_project_id_index
20230707133415_user_add_email_index
20230710105741_added_indices
20230710114928_traces_add_user_id
20230710200816_scores_add_comment
20230711104810_traces_add_index
20230711110517_memberships_add_userid_index
20230711112235_fix_indices
20230717190411_users_feature_flags
20230720162550_tokens
20230720164603_migrate_tokens
20230720172051_tokens_non_null
20230721111651_drop_usage_json
20230731162154_score_value_float
20230803093326_add_release_and_version
20230809093636_remove_foreign_keys
20230809132331_add_project_id_to_observations
20230810191452_traceid_nullable_on_observations
20230810191453_project_id_not_null
20230814184705_add_viewer_membership_role
20230901155252_add_pricings_table
20230901155336_add_pricing_data
20230907204921_add_cron_jobs_table
20230907225603_projects_updated_at
20230907225604_api_keys_publishable_to_public
20230910164603_cron_add_state
20230912115644_add_trace_public_bool
20230918180320_add_indices
20230922030325_add_observation_index
20230924232619_datasets_init
20230924232620_datasets_continued
20231004005909_add_parent_observation_id_index
20231005064433_add_release_index
20231009095917_add_ondelete_cascade
20231012161041_add_events_table
20231014131841_users_add_admin_flag
20231018130032_add_per_1000_chars_pricing
20231019094815_add_additional_secret_key_column
20231021182825_user_emails_all_lowercase
20231025153548_add_headers_to_events
20231030184329_events_add_index_on_projectid
20231104004529_scores_add_index
20231104005403_fkey_indicies
20231106213824_add_openai_models
20231110012457_observation_created_at
20231110012829_observation_created_at_index
20231112095703_observations_add_unique_constraint
20231116005353_scores_unique_id_projectid
20231119171939_cron_add_job_started_at
20231119171940_bookmarked
20231129013314_invites
20231130003317_trace_session_input_output
20231204223505_add_unit_to_observations
20231223230007_cloud_config
20231223230008_accounts_add_cols_azure_ad_auth
20231230151856_add_prompt_table
20240103135918_add_pricings
20240104210051_add_model_indices
20240104210052_add_model_indices_pricing
20240105010215_add_tags_in_traces
20240105170551_index_tags_in_traces
20240106195340_drop_dataset_status
20240111152124_add_gpt_35_pricing
20240117151938_traces_remove_unique_id_external
20240117165747_add_cost_to_observations
20240118204639_add_models_table
20240118204936_add_internal_model
20240118204937_add_observations_view
20240118235424_add_index_to_models
20240119140941_add_tokenizer_id
20240119164147_make_model_params_nullable
20240119164148_add_models
20240124140443_session_composite_key
20240124164148_correct_models
20240126184148_new_models copy
20240130100110_usage_unit_nullable
20240130160110_claude_models
20240131184148_add_finetuned_and_vertex_models
20240203184148_update_pricing
20240212175433_add_audit_log_table
20240213124148_update_openai_pricing
20240214232619_prompts_add_indicies
20240215224148_update_openai_pricing
20240215234937_fix_observations_view
20240219162415_add_prompt_config
20240226165118_add_observations_index
20240226182815_add_model_index
20240226183642_add_observations_index
20240226202040_add_observations_trace_id_project_id_start_time_idx
20240226202041_add_observations_trace_id_project_id_type_start_time_idx
20240226203642_rewrite_observations_view
20240227112101_index_prompt_id_in_observations
20240228103642_observations_view_cte
20240228123642_observations_view_fix
20240304123642_traces_view
20240304123642_traces_view_improvement
20240304222519_scores_add_index
20240305095119_add_observations_index
20240305100713_traces_add_index
20240307090110_claude_model_three
20240307185543_score_add_source_nullable
20240307185544_score_add_name_index
20240307185725_backfill_score_source
20240312195727_score_source_drop_default
20240314090110_claude_model
20240325211959_remove_example_table
20240325212245_dataset_runs_add_metadata
20240326114211_dataset_run_item_bind_to_trace
20240326114337_dataset_run_item_backfill_trace_id
20240326115136_dataset_run_item_traceid_non_null
20240326115424_dataset_run_item_index_trace
20240328065738_dataset_item_input_nullable
20240404203640_dataset_item_source_trace_id
20240404210315_dataset_add_descriptions
20240404232317_dataset_items_backfill_source_trace_id
20240405124810_prompt_to_json
20240408133037_add_objects_for_evals
20240408134328_prompt_table_add_tags
20240408134330_prompt_table_add_index_to_tags
20240411134330_model_updates
20240411194142_update_job_config_status
20240411224142_update_models
20240414203636_ee_add_sso_configs
20240415235737_index_models_model_name
20240416173813_add_internal_model_index
20240417102742_metadata_on_dataset_and_dataset_item
20240419152924_posthog_integration_settings
20240420134232_posthog_integration_created_at
20240423174013_update_models
20240423192655_add_llm_api_keys
20240424150909_add_job_execution_index
20240429124411_add_prompt_version_labels
20240429194411_add_latest_prompt_tag
20240503125742_traces_add_createdat_updatedat
20240503130335_traces_index_created_at
20240503130520_traces_index_updated_at
20240508132621_scores_add_project_id
20240508132735_scores_add_projectid_index
20240508132736_scores_backfill_project_id
20240512151529_rename_memberships_to_project_memberships
20240512155020_rename_enum_membership_role_to_project_role
20240512155021_add_pricing_gpt4o
20240512155021_scores_drop_fk_on_traces_and_observations
20240512155022_scores_non_null_and_add_fk_project_id
20240513082203_scores_unique_id_and_projectid_instead_of_id_and_traceid
20240513082204_scores_unique_id_and_projectid_instead_of_id_and_traceid_index
20240513082205_observations_view_add_time_to_first_token
20240522081254_scores_add_author_user_id
20240522095738_scores_add_author_user_id_index
20240523142425_score_config_add_table
20240523142524_scores_add_config_id_idx
20240523142610_scores_add_fk_scores_config_id
20240524154058_scores_source_enum_add_annotation
20240524156058_scores_source_backfill_annotation_for_review
20240524165931_scores_source_enum_drop_review
20240524190433_job_executions_add_fk_index_config_id
20240524190434_job_executions_add_fk_index_score_id
20240524190435_job_executions_add_fk_index_trace_id
20240524190436_job_executions_index_created_at
20240528214726_add_cursor_new_columns_observations
20240528214727_add_cursor_new_columns_scores
20240528214728_add_cursor_index_01
20240528214728_add_cursor_index_02
20240528214728_add_cursor_index_03
20240528214728_add_cursor_index_04
20240528214728_add_cursor_index_05
20240528214728_add_cursor_index_06
20240528214728_add_cursor_index_07
20240528214728_add_cursor_index_08
20240528214728_add_cursor_index_09
20240528214728_add_cursor_index_10
20240528214728_add_cursor_index_11
20240528214728_add_cursor_index_12
20240528214728_add_cursor_index_13
20240528214728_add_cursor_index_14
20240528214728_add_cursor_index_15
20240528214728_add_cursor_index_16
20240528214728_add_cursor_index_17
20240528214728_add_cursor_index_18
20240603212024_dataset_items_add_index_source_trace_id
20240604133338_scores_add_index_name
20240604133339_score_data_type_add_boolean
20240606093356_drop_unused_pricings_table
20240606133011_remove_trace_fkey_datasetrunitems
20240607090858_pricings_add_latest_gemini_models
20240607212419_model_price_anthropic_via_google_vertex
20240611105521_llm_api_keys_custom_endpoints
20240611113517_backfill_manual_score_configs
20240612101858_add_index_observations_project_id_prompt_id
20240617094803_observations_remove_prompt_fk_constraint
20240618134129_add_batch_exports_table
20240618164950_drop_observations_parent_observation_id_idx
20240618164951_drop_observations_updated_at_idx
20240618164952_drop_scores_updated_at_idx
20240618164953_drop_traces_external_id_idx
20240618164954_drop_traces_release_idx
20240618164955_drop_traces_updated_at_idx
20240618164956_create_traces_project_id_timestamp_idx
20240624133412_models_add_anthropic_3_5_sonnet
20240625103957_observations_add_calculated_cost_columns
20240625103958_fix_model_match_gpt4_vision
20240703214747_models_anthropic_aws_bedrock
20240704103900_observations_view_read_from_calculated
20240704103901_scores_make_value_optional
20240705152639_traces_view_add_created_at_updated_at
20240705154048_observation_view_add_created_at_updated_at
20240710114043_score_configs_drop_empty_categories_array_for_numeric_scores
20240710114044_add_pricing_gpt4o_mini
20240718004923_datasets_tables_add_projectid_composite_key
20240718011733_dataset_runs_add_unique_dataset_id_project_id_name copy
20240718011734_dataset_runs_drop_unique_dataset_id_name
20240718011735_observation_view_add_prompt_name_and_version
20240807111358_models_add_openai_gpt_4o_2024_08_06
20240807111359_add_organizations_main_migration
20240814223824_model_fix_text_embedding_3_large
20240814233029_dataset_items_drop_fkey_on_traces_and_observations
20240815171916_add_comments
20240913095558_models_add_openai_o1_2024-09-12
20240913185822_account_add_refresh_token_expires_in
20240917183001_remove_covered_indexes_01
20240917183002_remove_covered_indexes_02
20240917183003_remove_covered_indexes_03
20240917183004_remove_covered_indexes_04
20240917183005_remove_covered_indexes_05
20240917183006_remove_covered_indexes_06
20240917183007_remove_covered_indexes_07
20240917183008_remove_covered_indexes_08
20240917183009_remove_covered_indexes_09
20240917183010_remove_covered_indexes_10
20240917183011_remove_covered_indexes_11
20240917183012_remove_covered_indexes_12
20240917183013_remove_covered_indexes_13
20240917183014_remove_covered_indexes_14
20240917183015_remove_covered_indexes_15
20240917183016_remove_covered_indexes_16
20241009042557_auth_add_created_at_for_gitlab
20241009110720_scores_add_nullable_queue_id_column
20241009113245_add_annotation_queue

To apply migrations in development run prisma migrate dev.
To apply migrations in production run prisma migrate deploy.
```

**Comment by rhighs** [comment]
About `SHADOW_DATABASE_URL`, prisma docs state that:
> The shadow database is not required in production, and is not used by production-focused commands such as prisma migrate resolve and prisma migrate deploy

Why would this be needed? How can i be sure that my langfuse container is running in production mode hence running migrations using `prisma migrate deploy`?

These are a few of the env vars I've set:
```
          { name: 'DATABASE_URL', value: poolingDbUrl },
          { name: 'DIRECT_URL', value: nonPoolingDbUrl },
          { name: 'NEXTAUTH_URL', value: nextauthUrl },
          { name: 'NEXTAUTH_SECRET', value: nextauthSecret },
          { name: 'SALT', value: salt },
          { name: 'ENCRYPTION_KEY', value: encryptionKey },
          { name: 'HOSTNAME', value: '0.0.0.0' },
          { name: 'NODE_ENV', value: 'production' }
```

**Comment by rhighs** [comment]
I managed to get the prisma command to work properly, I brutally set all migrations as applied using a simple script from the root of the langfuse project:
```bash
#!/bin/bash
for m in $(ls packages/shared/prisma/migrations); do
  prisma migrate resolve --applied $m --schema ./packages/shared/prisma/schema.prisma
done
```

some of them gave errors, so I went on fixing them manually. Particularly these were the errors I found when trying to run `prisma migrate deploy`.

**Applying migration `20240126184148_new_models copy`**

```
Error: P3018

A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 20240126184148_new_models copy

Database error code: 23505

Database error:
ERROR: duplicate key value violates unique constraint "models_pkey"
DETAIL: Key (id)=(clruwn3pc00010al7bl611c8o) already exists.

DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E23505), message: "duplicate key value violates unique constraint \"models_pkey\"", detail: Some("Key (id)=(clruwn3pc00010al7bl611c8o) already exists.", hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: Some("models_pkey"), file: Some("nbtinsert.c"), line: Some(570), routine: Some("_bt_check_unique") }
```

**Applying migration `20240718011733_dataset_runs_add_unique_dataset_id_project_id_name copy`**
```
Error: P3018

A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 20240718011733_dataset_runs_add_unique_dataset_id_project_id_name copy

Database error code: 42P07

Database error:
ERROR: relation "dataset_runs_dataset_id_project_id_name_key" already exists

DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42P07), message: "relation \"dataset_runs_dataset_id_project_id_name_key\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("index.c"), line: Some(864), routine: Some("index_create") }
```

**Comment by maxdeichmann** [comment]
@rhighs thanks a lot for trying all of this out and providing me with the outputs. I think you applied some of the migrations multiple times now, hence the two failing migrations. The first one inserts a new row into a table with a unique key constraint, the other one adds an index which already exists.

I am still not sure what happened here, given that the original error message said that migrations were found but the database schema was empty. Usually, prisma would then apply the diff to the database.

Given the setup works for now, i would close this. Please re-open if the issue appears again.

**Comment by Doctor2kUa** [comment]
There are a lot of problems with migrations. Clean install via helm.
psql "postgresql://langfuse:***@langfuse-postgresql/postgres_langfuse"   -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"
DROP SCHEMA
CREATE SCHEMA

prisma migrate deploy --schema=./packages/shared/prisma/schema.prisma
Prisma schema loaded from packages/shared/prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres_langfuse", schema "public" at "langfuse-postgresql"

295 migrations found in prisma/migrations

Applying migration `20230518191501_init`
Applying migration `20230518193415_add_observaionts_and_traces`
Applying migration `20230518193521_changes`
Applying migration `20230522092340_add_metrics_and_observation_types`
Applying migration `20230522094431_endtime_optional`
Applying migration `20230522131516_default_timestamp`
Applying migration `20230523082455_rename_metrics_to_gradings`
Applying migration `20230523084523_rename_to_score`
Applying migration `20230529140133_user_add_pw`
Applying migration `20230530204241_auth_api_ui`
Applying migration `20230618125818_remove_status_from_trace`
Applying migration `20230622114254_new_oservations`
Error: ERROR: current transaction is aborted, commands ignored until end of transaction block
   0: schema_core::commands::apply_migrations::Applying migration
           with migration_name="20230622114254_new_oservations"
             at schema-engine/core/src/commands/apply_migrations.rs:91
   1: schema_core::state::ApplyMigrations
             at schema-engine/core/src/state.rs:226

I try to use 

#!/bin/bash
for m in $(ls packages/shared/prisma/migrations); do
  prisma migrate resolve --applied $m --schema ./packages/shared/prisma/schema.prisma
done

but got errors on some files

**Comment by Doctor2kUa** [comment]
After I found some objects that block aplying some migrations I got

 prisma migrate deploy --schema=./packages/shared/prisma/schema.prisma
Prisma schema loaded from packages/shared/prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres_langfuse", schema "public" at "langfuse-postgresql"

295 migrations found in prisma/migrations

Error: P3009

migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
The `20240126184148_new_models copy` migration started at 2025-04-21 16:09:45.154896 UTC failed

I am not sure this is best way to make migrations but that is all that I can make
