### ISSUE TITLE
bug: langfuse的api文档中 Get a dataset run and its items获取数据集运行没有返回对应的分数

### ISSUE THREAD

**Issue by l19930105** [langfuse/langfuse#3713]
### Describe the bug

Get a dataset run and its items的
/api/public/datasets/{datasetName}/runs/{runName}
结果中希望返回分数

### To reproduce

![1](https://github.com/user-attachments/assets/859118ff-4fa8-435d-8ebe-ef924dc0d6bb)
![image](https://github.com/user-attachments/assets/74c59f4f-80ae-481e-ad08-51cd1c13ec06)

### Are you interested to contribute a fix for this bug?

No

**Comment by l19930105** [comment]
The API endpoint /api/public/datasets/{datasetName}/runs/{runName} does not return scores because the logic to fetch scores is not included in the query for this endpoint. To include scores in the response,

**Comment by marcklingen** [comment]
the dataset run item includes a reference to the trace. You can fetch the scores related to the trace from the scores endpoint
