### ISSUE TITLE
bug: Error occurs while running tracer on self-hosted Langfuse

### ISSUE THREAD

**Issue by laura-y7860** [langfuse/langfuse#3715]
### Describe the bug

Hoping to capture the Langflow traces using the self-hosted Langfuse.
Have upgraded langflow to the latest version, and the below error occurs when tyring to run the tracer.
![image](https://github.com/user-attachments/assets/bf73256c-de56-4fb5-8379-5c2bf16d125f)

### To reproduce

Have followed the instruction on how to self-host Langfuse from the following link: https://langfuse.com/docs/integrations/langflow

Except now I have placed the keys to .env as the instruction showed in this video: https://www.youtube.com/watch?v=SA9gGbzwNGU&ab_channel=Langflow

![image](https://github.com/user-attachments/assets/5b3fc69b-680c-491d-a3c1-2c7c90ed2c0b)

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Is langfuse accessible on localhost? Do you run all of this inside of docker compose?

**Comment by laura-y7860** [comment]
Hello @marcklingen, Thanks for your response.

Yes I can access Langfuse on localhost and have rant all of them inside of the same docker compose as the instruction.

**Comment by marcklingen** [comment]
then, you'll need to switch localhost:3000 with e.g. langfuse:3000 as this uses the docker internal networking. See this [note](https://langfuse.com/docs/deployment/self-host#troubleshooting) for more details:

> When using Docker Compose / Kubernetes, your application needs to connect to the Langfuse container at the docker internal network address that you specified, e.g. `http://langfuse:3000/` `http://langfuse.docker.internal:3000`. Learn more: [docker compose networking documentation](https://docs.docker.com/compose/how-tos/networking/), [kubernetes networking documentation](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/)

**Comment by laura-y7860** [comment]
Hello @marcklingen, Thanks for your response.

I resolved the error by including 
```
env_file:
    - .env
```
in the docker compose. 

I will close the issue now. Thanks for your help !

**Comment by marcklingen** [comment]
awesome, thanks for sharing!
