### ISSUE TITLE
bug: LANGFUSE_INIT_USER_EMAIL not lowercased when checking for existing user

### ISSUE THREAD

**Issue by uladkaminski** [langfuse/langfuse#3727]
### Describe the bug

When initializing a user with the LANGFUSE_INIT_USER_EMAIL environment variable, the application creates a user with a lowercased email. However, when checking for an existing user on subsequent application starts, it doesn't lowercase the email, potentially leading to inconsistencies in user recognition.

Expected behaviour: The application should consistently use either lowercased or case-sensitive emails when creating and checking for users to ensure proper user management.

### To reproduce

- Set the LANGFUSE_INIT_USER_EMAIL environment variable with an email containing uppercase letters (e.g., "[Test@Example.com](mailto:Test@Example.com)").
- Set the LANGFUSE_INIT_USER_PASSWORD environment variable with a valid password.
- Start the application for the first time. This will create a user with a lowercased email.
- Stop the application.
- Start the application again.
- Observe that the application fails to recognize the existing user because it's checking for the email with its original case.

### Additional information

User creation (lowercases email):
```
const user = await prisma.user.findUnique({
  where: {
    email: email.toLowerCase(),
  },
});
```

Subsequent check (doesn't lowercase email):
```
const existingUser = await prisma.user.findUnique({
  where: { email: env.LANGFUSE_INIT_USER_EMAIL },
});
```

### Are you interested to contribute a fix for this bug?

Yes

**Comment by marcklingen** [comment]
good one, thanks a lot for sharing! i will fix this right away

**Comment by marcklingen** [comment]
added a fix, merging this right now and will be included in next release
#3754 

thanks again for reporting this
