### ISSUE TITLE
bug: asking for score before reasoning in LLM-as-a-judge evals will significantly reduce reliability

### ISSUE THREAD

**Issue by nikshepsvn** [langfuse/langfuse#3760]
### Describe the bug

Not really a traditional bug, but moreso an issue with the way the response for evals is structured. By asking an LLM for score first and reason later, we are significantly hampering the reliability of the score cause the score is generated without reasoning and then the reasoning is being used to justify the score. Changing the behavior to generate reasoning and base the score off of that reasoning will improve quality since this is a more traditional CoT method. 

### To reproduce

Running any eval, you can see score is produced first and reasoning trace later.

### Are you interested to contribute a fix for this bug?

Yes

**Comment by nikshepsvn** [comment]
Will wait for someone more familiar with the codebase to confirm this behaviour, if confirmed true, I can investigate and provide a fix. This is based on seeing this JSON in the UI but want to confirm the same behaviour is valid in the underlying object generation.

**Comment by marcklingen** [comment]
good one, we should change this! @hassiebp what do you think?

**Comment by hassiebp** [comment]
@nikshepsvn Thanks a lot for raising this. We are currently using structured output to generate the eval scores, with `score` and `reasoning` as keys. 

Do I understand you correctly that having the `reasoning` key prior to the `score` key increases reliability of the `score`? Curious to learn from you here!

**Comment by nikshepsvn** [comment]
Yes, this is because if we ask for reasoning behind the score first, the reasoning being present in the context will help it more accurately predict a numerical value since now it has information to make its prediction more accurate. This roughly how CoT helps models. Asking for a score first and the prediction later will cause it to just use reasoning to justify whatever score it comes up since it can't adjust the score post generation. Thanks for verifying and fixing!

**Comment by marcklingen** [comment]
Agree, in-context reasoning here should improve eval scores instead of just producing a comment on why the eval score was most likely the right one. Thanks again for raising this!
