### ISSUE TITLE
bug: Instrumentation does not return full traces nor Model costs when using LlamaIndexInstrumentor

### ISSUE THREAD

**Issue by sqpollen** [langfuse/langfuse#3768]
### Describe the bug

We use a multi-step retrieval process using LlamaIndex in a FastAPI route as below:

```
import time

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from sentry_sdk import capture_message

from lib.constants import SIMILARITY_TOP_K
from lib.database import insert_queries
from lib.dependencies import get_dependency
from lib.response_handlers import create_error_response
from lib.retrieval import generate_source, retriever_query
from prompts.clara import generate_prompt, NO_ANSWER
from langfuse.llama_index import LlamaIndexInstrumentor

router = APIRouter()


class QueryPayload(BaseModel):
    query: str
    extended: bool = False
    stage: str = None
    type: str = None


@router.post("/retriever-stream")
async def retriever_stream(
    payload: QueryPayload,
    index=Depends(get_dependency("index")),
    llm=Depends(get_dependency("llm")),
    vector_store=Depends(get_dependency("vector_store")),
):
    instrumentor = LlamaIndexInstrumentor()
    instrumentor.start()
    try:
        start = time.time()

        if not payload.query.strip():
            return create_error_response("Empty query provided", start, {}, 400)

        query = payload.query
        extended = payload.extended
        stage = payload.stage
        type = payload.type

        if stage is not None and type is not None:
            query = f"{query}.I have {arthritis_type} and {arthritis_stage}."

       //RETRIEVER 
        retriever = index.as_retriever(
            similarity_top_k=SIMILARITY_TOP_K,
        )

        filtered_nodes = await retriever_query(retriever, query, vector_store)

        context = ""
        sources = []

        for node in filtered_nodes:
            source = generate_source(node)
            sources.append(source)
            context += node.node.text + "\n"

        if len(context) == 0:
            final_text = NO_ANSWER
            insert = insert_queries(query, final_text, [])
            if insert["error"] is not None:
                return create_error_response(insert["error"], start, {}, 500)
            return StreamingResponse(final_text, media_type="text/event-stream")

        // Generates custom prompt
        prompt = generate_prompt(
            query, context, extended, stage, type
        )

        response = llm.stream_complete(prompt)

        def response_stream():
            final_text = ""
            for text in response:
                formatted_text = text.delta
                final_text += formatted_text
                yield formatted_text
            insert = insert_queries(query, final_text, sources)
            if insert["error"] is not None:
                error = insert["error"]
                capture_message("Error saving query: {}".format(error))

        return StreamingResponse(response_stream(), media_type="text/event-stream")
    except Exception as error:
        return create_error_response(str(error), start, {}, 500)
```

The traces we are getting from Langfuse are incomplete.

Heres the retrieval traces (I don't understand why there is two)

<img width="1445" alt="image" src="https://github.com/user-attachments/assets/e707944c-bcd4-4df9-b8ba-fd2415b65e1b">

<img width="1445" alt="image" src="https://github.com/user-attachments/assets/b39507a3-5f3b-4bcb-907e-f01916dc021b">

And here is the LLM query - as you can see it is missing all observability

<img width="1445" alt="image" src="https://github.com/user-attachments/assets/e651c33d-93c9-4261-8d6e-18a4745cfcaa">

All of these traces are also captured individually so its not possible to piece them together.

How would we get this tracing properly?

### To reproduce

See above code

### SDK and container versions

langfuse==2.33.0
llama-index==0.10.58

### Are you interested to contribute a fix for this bug?

No

**Comment by sqpollen** [comment]
> To properly capture and piece together complete traces when using `LlamaIndexInstrumentor` for multi-step retrieval and query processes, you can utilize the `instrumentor.observe()` context manager to manage trace IDs and parent observation IDs. This allows you to link multiple LlamaIndex executions into a single trace or span, ensuring that the traces are complete and connected.
> 
> Here's how you can do it:
> 
> ```python
> from langfuse.decorators import langfuse_context, observe
> from langfuse.llama_index import LlamaIndexInstrumentor
> from llama_index.core import Document, VectorStoreIndex
> 
> instrumentor = LlamaIndexInstrumentor()
> 
> @observe()
> async def retriever_stream(payload, index, llm, vector_store):
>     # Get current trace ID and observation ID
>     current_trace_id = langfuse_context.get_current_trace_id()
>     current_observation_id = langfuse_context.get_current_observation_id()
> 
>     # Set IDs on the instrumentor
>     with instrumentor.observe(
>         trace_id=current_trace_id,
>         parent_observation_id=current_observation_id,
>         update_parent=False,  # Do not update the parent observation or trace, default is True
>     ):
>         # Your existing code logic here
>         # ...
> 
>         # Example of running a query
>         retriever = index.as_retriever(similarity_top_k=SIMILARITY_TOP_K)
>         filtered_nodes = await retriever_query(retriever, payload.query, vector_store)
> 
>         # Continue with your existing logic
>         # ...
> ```
> 
> By using the `observe()` decorator and setting the `trace_id` and `parent_observation_id`, you can ensure that all related operations are part of the same trace, providing a complete picture of the multi-step process. Additionally, you can use the `trace` object yielded by the context manager to attach scores and metadata, further enriching the trace data [[1]](https://langfuse.com/docs/integrations/llama-index)[[2]](https://langfuse.com/docs/integrations/llama-index/get-started).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

thanks @dosu._ that solved the issue with the full trace but the trace still isn't include the output tokens from the LLM response. See trace below

<img width="412" alt="image" src="https://github.com/user-attachments/assets/8f9a5a11-abba-47f3-9a48-9d28408e0a9e">

I noticed that the trace is also recording sensitive information from kwargs. How do we exclude kwargs from the traces?

**Comment by sqpollen** [comment]
> that solved the issue with the full trace but the trace still isn't include the output tokens from the LLM response.



> To exclude sensitive information, such as `kwargs`, from being recorded in traces, you can use the `@observe()` decorator with specific configurations. Set `capture_input` and `capture_output` to `False` to prevent capturing inputs and outputs:
> 
> ```python
> from langfuse.decorators import observe
> 
> @observe(capture_input=False, capture_output=False)
> async def retriever_stream(payload, index, llm, vector_store):
>     # Your existing code logic here
>     # ...
> ```
> 
> Additionally, you can manually update the observation with sanitized data using the `langfuse_context.update_current_observation` method:
> 
> ```python
> from langfuse.decorators import langfuse_context
> 
> @observe(capture_input=False, capture_output=False)
> async def retriever_stream(payload, index, llm, vector_store):
>     # Update the observation with sanitized data
>     langfuse_context.update_current_observation(
>         input="sanitized input",  # any serializable object
>         output="sanitized output",  # any serializable object
>     )
>     # Your existing code logic here
>     # ...
> ```
> 
> This setup will ensure that sensitive information is not included in the traces [[1]](https://langfuse.com/guides/cookbook/python_decorators)[[2]](https://langfuse.com/docs/sdk/python/decorators).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

That solved the issue with sanitising the input but the trace still doesnt include the output tokens from the LLM completion.


![image](https://github.com/user-attachments/assets/f9407e08-d3db-4d3e-b97c-38f71b45cc93)

**Comment by hassiebp** [comment]
Thanks a lot for raising this @sqpollen. This is likely related to FastApi + StreamingResponse + contextvars not working well together. [See related issue here](https://github.com/langfuse/langfuse/issues/3474#issuecomment-2414611345). We will take a look.

**Comment by hassiebp** [comment]
@sqpollen This is due to an upstream issue in the llama index package. See this feature request to track progress: https://github.com/run-llama/llama_index/issues/16721

**Comment by hassiebp** [comment]
Closing this as stale. Please let us know if you continue to encounter this issue.
