### ISSUE TITLE
bug: python sdk does not url encode run names

### ISSUE THREAD

**Issue by Dranero** [langfuse/langfuse#3776]
### Describe the bug

When querying for dataset runs with the python SDK, run names might include slashed ("/") for example when using git branch names in run names. It is not possible to query those runs with the SDK via name, because the slashes don't get url encoded and therefore result in a 404 at the webserver. However, when url encoding the slashes beforehand, I can fetch the runs, so it should be all good on the server.

Probably other strings also don't get url encoded, but I am not sure on that one. 
Thank you :)

### To reproduce

```
from urllib.parse import quote_plus
run_name = "branch/version/timestamp"
dataset_name = "first_set"

# copied from https://langfuse.com/docs/datasets/overview#run-experiment-on-a-dataset
dataset = langfuse.get_dataset(dataset_name)
for item in dataset.items:
    with item.observe_llama_index(run_name=run_name):
        index = VectorStoreIndex.from_documents([doc1, doc2])
        response = index.as_query_engine().query(item.input)
langfuse.flush()
# end copy

# returns 404
langfuse.get_dataset_run(dataset_name, run_name)
# returns dataset
langfuse.get_dataset_run(quote_plus(dataset_name), quote_plus(run_name))

```

### SDK and container versions

python sdk: 2.51.2
langfuse version: 2.81.0 (self hosted)

### Additional information

The bug might be [here](https://github.com/langfuse/langfuse-python/blob/main/langfuse/api/resources/datasets/client.py#L244)

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment]
Thanks for raising this @Dranero - we will prioritize a fix for this
