### ISSUE TITLE
feat: NextAuth SSO

### ISSUE THREAD

**Issue by p5** [langfuse/langfuse#381]
### Describe the feature you'd like to request

It would be great if Langfuse users could authenticate with Google OIDC/SAML using NextAuth rather than a username and password.  This would make it much simpler to onboard and offboard users in an organization.

Providers that would be great to support initially are:
- [Auth0](https://next-auth.js.org/providers/auth0)
- [Azure EntraID](https://next-auth.js.org/providers/azure-ad)
- [Google](https://next-auth.js.org/providers/google) - the one we're mostly interested in

But there are so many more providers available.

### Describe the solution you'd like to see

I don't know too much about NextAuth, but it seems like it should be fairly trivial to enable SSO.
I'm not sure how much you will need to change behind the scenes for user IDs to link up correctly or set permissions on each user.

NextAuth provide decent documentation, and it looks like a couple of lines of code.
https://next-auth.js.org/providers/google

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by maxdeichmann** [comment]
Hi @p5 thanks for raising this. Is this currently blocking you in adoption of Langfuse? We will discuss how we will prioritize this.

**Comment by maxdeichmann** [comment]
Thanks, understood! We will come back to this.

**Comment by p5** [comment]
That's great news!  Thank you!

Should we close this issue as complete, or do you want to leave it open until Azure and emails are added?

**Comment by marcklingen** [comment]
Let's close it as this was your core request. Getting Oauth credentials from Azure (multi-tenancy) is unreasonably complex and I'll get to magic-link auth soon as I want to add email sending capabilities for other features as well.
