### ISSUE TITLE
bug: Negative latency and TTFT values observed on Traces, Generation UI

### ISSUE THREAD

**Issue by r15-ds** [langfuse/langfuse#3819]
### Describe the bug

My purpose is to have a single entry in Traces UI and that trace_id linked to a single entry in Generation UI. However, I have been getting two entries created in Generation UI. I have found a semi-workaround to have one entry in Traces and the same trace_id linked to a single entry in Generation UI, however, it lands up capturing negative latency and TTFT. 

Currently when I try to get the generation id using "langfuse.get_observations().data[0].id", it gets the id but the TTFT and Latency fields start showing up negative time (like -5seconds). I'd like to attach some custom scores in the generation UI, however it always creates a second entry against the the same trace ID.  When I did this "langfuse.get_observations().data[0].id" it got me a single entry alright but messes up TTFT and Latency with -tive values.. Objective is to have a single row in traces having custom scores (which is happening alright) and the same trace Id showing up just once in Generations UI (having the same custom scores)

![1](https://github.com/user-attachments/assets/c78b6e92-a069-44c6-849e-053aee5b5031)

**If there is an easier/ alternate way to do this, I'm happy to use that approach.** Please note that I'm not using decorator @observe to have more control over what I capture in langfuse (as there are lot of other llm/ api calls that I would like to avoid getting tracked in langfuse)

### To reproduce

```python
from langfuse.callback import CallbackHandler
from langfuse import Langfuse
import uuid
from langchain_openai import ChatOpenAI
from langchain.callbacks.base import BaseCallbackHandler
import httpx
import os
import streamlit as st

langfuse_trace_id = str(uuid.uuid4())    
langfuse = Langfuse(
                    secret_key= os.environ["LANGFUSE_SECRET_KEY"],
                    public_key=os.environ["LANGFUSE_PUBLIC_KEY"],
                    httpx_client=httpx.Client(verify=False),
                    host=os.environ["LANGFUSE_HOST"],
                    )
      
langfuseHandler = CallbackHandler(
    public_key=os.environ["LANGFUSE_PUBLIC_KEY"],
    secret_key=os.environ["LANGFUSE_SECRET_KEY"],
    host=os.environ["LANGFUSE_HOST"],
    httpx_client=httpx.Client(verify=False),
)                      


class StreamHandler(BaseCallbackHandler):
    def __init__(self, container, initial_text=""):
        self.container = container
        self.text=""
    def on_llm_new_token(self, token: str, **kwargs) -> None:
        self.text+=token
stream_handler = StreamHandler(st.empty())

llm = ChatOpenAI(
    base_url= os.getenv('URL'),
    api_key = os.getenv('API_KEY'), 
    model = "",
    temperature=0.,
    http_client=httpx.Client(verify=False),
    http_async_client=httpx.AsyncClient(verify=False),
    streaming = True,
    callbacks=[stream_handler],
    stream_options = {"include_usage":True},
    stream_usage = True,
)

response = llm.invoke(promptStr, config={"callbacks": [langfuseHandler], 
                                         "run_name": "Abc",
                                         "run_id": langfuse_trace_id
                                         })

langfuse_generation_id = langfuse.get_observations().data[0].id # This line most likely causes negative latency and TTFT

# The following snippet most like is the reason for "second" entry in Generation UI. 
generation = langfuse.generation(
    id = langfuse_generation_id,
    trace_id = langfuse_trace_id,
)

#### Simplified metric for bug reproducibility 
# I am trying to get the scores captured (along with other metric like latency, token usage, TTFT) in the Generation UI for the linked trace_id. However, langfuse.score captures the score in the second entry which is certainly linked to the same trace_id but it makes it hard for a user as they'd need fiddle with 2 rows in Generation UI.

for metric, score in zip(["A", "B"], [0.1,0.2]):
      langfuse.score(
          trace_id = langfuse_trace_id,
          observation_id = generation.id,
          name = metric,
          value = score
      )
```  

### SDK and container versions

langchain==0.2.6
langfuse==2.51.3

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment]
@r15-ds Thanks a lot for raising this. Could you please simplify your example to a _minimum_ reproducible example, and clearly state what the actual output is vs your expected output? That'd help me a lot to support you on this.

**Comment by r15-ds** [comment]
Well, the above code snippet is the bare minimum thats needed to reproduce it. Not sure if I can reduce it further. The following line is the most likely reason for negative latency. 
```
langfuse.get_observations().data[0].id
```

So, any ```langfuse``` object created should be able to reproduce the issue I'm hoping

**Comment by hassiebp** [comment]
Closing this as expected behavior.
