### ISSUE TITLE
bug: sessions not showing on version 2.85 OSS

### ISSUE THREAD

**Issue by jonnyforsterMSG** [langfuse/langfuse#3822]
### Describe the bug

I'm providing a sessionId to every trace (below) and the older versions of the Langfuse portal (2.71) show these sessions in the session page but the newer versions do not. I can still see the sessionId in the traces page next to each trace but the sessions page does not have any entries

```
langfuse_handler = CallbackHandler(
    os.getenv('LANGFUSE_PUBLIC_KEY'),
    os.getenv('LANGFUSE_SECRET_KEY'),
    os.getenv('LANGFUSE_HOST'),
    metadata={
        "langfuse_version": version("langfuse"),
        "langchain_version": version("langchain_core"),
        "langchain_openai_version": version("langchain_openai"),
    },
    timeout=60,
)

async def create_summary(
        call_id: str,
        transcript: str,
        session_id: str,
        base_chain: Any,
        endpoint_name: str,
        user_agent: str
) -> Any:

    langfuse_handler.metadata.update({
        "call_id": call_id,
        "endpoint": endpoint_name,
        "user_agent": user_agent
    })
    langfuse_handler.session_id = session_id
    langfuse_handler.trace_name = f"{endpoint_name}_{call_id}"

    if not langfuse_handler.auth_check():
        raise ValueError("Authentication with Langfuse failed.")

    config = RunnableConfig(callbacks=[langfuse_handler])
    summary_chain = base_chain.with_config(config)
    return await summary_chain.ainvoke(transcript)

```

### To reproduce

Setup an instance of Langfuse on the latest version and send some telemetry with a sessionId check the sessions page to see if there are any entries

### SDK and container versions

SDK langfuse = "^2.5"

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Please follow the docs on how to set trace name and session id instead of

```
langfuse_handler.session_id = session_id
langfuse_handler.trace_name = f"{endpoint_name}_{call_id}"
```

This should work:

```
from langfuse.callback import CallbackHandler
 
langfuse_handler = CallbackHandler()
 
trace_name = "langchain_trace_name"
session_id = "random-session"
user_id = "random-user"
tags = ["random-tag-1", "random-tag-2"]
 
# Your existing Langchain code to create the chain
 
# Pass config to the chain invocation to be parsed as Langfuse trace attributes
 
chain.invoke(
    {"animal": "dog"},
    config={
        "callbacks": [langfuse_handler],
        "run_name": trace_name,
        "tags": tags,
        "metadata": {
            "langfuse_session_id": session_id,
            "langfuse_user_id": user_id,
        },
    },
)
```

Docs: [https://langfuse.com/docs/integrations/langchain/tracing#dynamic-trace-attributes-in-chain-invocation](https://langfuse.com/docs/integrations/langchain/tracing#dynamic-trace-attributes-in-chain-invocation)

You need to be on the latest sdk version as this was recently improved.

**Comment by jonnyforsterMSG** [comment]
Cheers, I've update the SDK (2.52.1) and made the changes to the config object

```
config= {
        "callbacks": [langfuse_handler],
        "metadata": {
            "langfuse_session_id": session_id,
            "call_id": call_id,
            "endpoint": endpoint_name,
            "user_agent": user_agent
        },
    }
```
and the session_id still shows next to the trace but I still don't get any sessions in the sessions page (attached screenshot). Have been using ainvoke on the chain but got the same result with invoke

![no_sessions](https://github.com/user-attachments/assets/1f11fffe-b429-4b30-b380-8278eebd065a)

**Comment by jonnyforsterMSG** [comment]
v2.85.1 OSS of the portal

**Comment by marcklingen** [comment]
can you share a link to an example trace?

**Comment by jonnyforsterMSG** [comment]
It's a self hosted version so won't be accessible from outside our network?

**Comment by marcklingen** [comment]
If self-hosted and not accessible from the outside, a screenshot of the trace would be helpful.

Is the trace within the last hour? (the session table is filtered by last hour in your screenshot)

**Comment by marcklingen** [comment]
this looks good, and these sessions do not show up on the session table even if you completely remove the time filter on the session table?

**Comment by jonnyforsterMSG** [comment]
correct, there a re no sessions in the table for these traces even when the filter is set to 'All time'

**Comment by jonnyforsterMSG** [comment]
also when I click into the session from the trace page it doesn't include that trace in it's list of associated traces

**Comment by marcklingen** [comment]
can we have a look into this together while screensharing the issue as I cannot reproduce this?

my calendar: https://cal.com/marc-kl/10

**Comment by marcklingen** [comment]
@jonnyforsterMSG I'd love to have a look together in order to fix this

**Comment by jonnyforsterMSG** [comment]
I've setup a meeting on Wednesday via your calendar @marcklingen, have you got it?

**Comment by marcklingen** [comment]
just saw it, looking forward to having a look together

**Comment by jonnyforsterMSG** [comment]
this is fixed thank you @marcklingen. For the record I was using an 'old' sessionId and because the sessions page is filtered on created date I couldn't see the session until I changed the threshold to 'all time'

**Comment by marcklingen** [comment]
sure, happy to help
