### ISSUE TITLE
bug: 'NoneType' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by nonlocalStream** [langfuse/langfuse#3834]
### Describe the bug

When using langfuse observe in python with openai, sometimes langfuse errors out and does not exit elegantly causing the caller (the main product code) to error out

This is not ideal because the observability system should cause the main system to fail

**Current behavior**
Langfuse sometimes throws NPE (we do not have a good way to repro since this is dependent on the openAI response but we are suspecting this happens when openAI response is empty)

**Expected behavior**
Langfuse should not ever error out the main application that's calling langfuse

Here's the error trace we see: 
```
File "/app/lib/machine_learning/models/gpt.py", line 565, in __async_score
    response = await self.async_client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
File "/usr/local/lib/python3.11/site-packages/langfuse/openai.py", line 602, in _wrap_async
    raise ex
  
File "/usr/local/lib/python3.11/site-packages/langfuse/openai.py", line 580, in _wrap_async
    openai_response.__dict__ if _is_openai_v1() else openai_response,
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '__dict__'
```

Reading the code in langfuse/openai https://github.com/langfuse/langfuse-python/blob/main/langfuse/openai.py#L547-L561 , `openai_response = wrapped(**arg_extractor.get_openai_args())`. We are suspecting this is because OpenAI sometimes returns empty response (we found this behavior before we integrate with langfuse) which causes `openai_response` to be None and causing the NPE.

### To reproduce

We do not have a good way to repro since this is dependent on the openAI response but we are suspecting this happens when openAI response is empty. Mainly there's a way to mock out the openAI response from langfuse side

### SDK and container versions

langfuse python sdk langfuse==2.44.1
langfuse v2.84.1 OSS

### Additional information

In the past week, we can see ~10% of observe call are failing due to this reason in our application
<img width="1269" alt="Screenshot 2024-10-18 at 3 56 32 PM" src="https://github.com/user-attachments/assets/e4f41607-6389-46e8-8e34-74f7f47aef00">

For more context, here's how we are using the langfuse observer. We use a customized wrapper but we think this is not the root cause the issue above
```

def ai_observe(
    capture_input: bool = True,
    capture_output: bool = True,
    as_type: Literal["generation"] | None = None,
) -> Callable[
    [Callable[..., Any]],
    Callable[..., Any],
]:
    def decorator(func: Callable[..., Any]) -> Callable[..., Any]:
        def sync_execute_func_with_observe(*args: Any, **kwargs: Any) -> Any:
              try:
                  return langfuse_context.observe(  # pyright: ignore[reportUnknownMemberType]
                      capture_input=capture_input,
                      capture_output=capture_output,
                      as_type=as_type,
                  )(func)(*args, **kwargs)
              except Exception as e:
                  _log_ai_observe_error(e)
                  raise
            return func(*args, **kwargs)

        async def async_execute_func_with_observe(*args: Any, **kwargs: Any) -> Any:
                try:
                    return await langfuse_context.observe(  # pyright: ignore[reportUnknownMemberType]
                        capture_input=capture_input,
                        capture_output=capture_output,
                        as_type=as_type,
                    )(func)(*args, **kwargs)
                except Exception as e:
                    _log_ai_observe_error(e)
                    raise
            return await func(*args, **kwargs)

        @wraps(func)
        def wrapper(*args: Any, **kwargs: Any) -> Any:
            if asyncio.iscoroutinefunction(func):
                return async_execute_func_with_observe(*args, **kwargs)
            return sync_execute_func_with_observe(*args, **kwargs)

        return wrapper

    return decorator
```

### Are you interested to contribute a fix for this bug?

Yes

**Comment by nonlocalStream** [comment]
@hassiebp awesome thanks for confirming @hassiebp! Is there anything I can do to help expedite the fix? Happy to contribute

**Comment by hassiebp** [comment]
Hi Chuqian - we have just released [a new version with a fix](https://github.com/langfuse/langfuse-python/releases/tag/v2.52.2), could you please upgrade and try again? 👍🏾

**Comment by nonlocalStream** [comment]
@hassiebp Thank you for the quick fix! I'm updating to the new version. Curious how you were able to reproduce the issue? I'd love to have some easier way to verify the issue gets fixed after I upgrade

**Comment by hassiebp** [comment]
@nonlocalStream - great! We have mocked a None response and made sure to handle that case gracefully. Please let us know whether the issue is fixed now on your end 👍🏾
