### ISSUE TITLE
bug: Unable to Add langfuse_prompt When Using OpenAI Structured Output

### ISSUE THREAD

**Issue by 0xcodedead** [langfuse/langfuse#3844]
### Describe the bug

Description:
When trying to add the langfuse_prompt parameter to the OpenAI structured output, it results in an error and prevents the trace and prompt linking from working correctly in the WebUI.

Steps to Reproduce:
Attempt to use langfuse_prompt as shown below:
`
from openai import AsyncOpenAI

client = AsyncOpenAI()

prompt_template = langfuse.get_prompt('foo')

chat_completion = client.beta.chat.completions
response = await chat_completion.parse(
    langfuse_prompt=prompt_template,
    **kwargs
)
`
Alternatively, add langfuse_prompt to the kwargs.

Error message: 
`AsyncCompletions.parse() got an unexpected keyword argument 'langfuse_prompt'`

### To reproduce

from openai import AsyncOpenAI

client = AsyncOpenAI()

prompt_template = langfuse.get_prompt('foo')

chat_completion = client.beta.chat.completions
response = await chat_completion.parse(
    langfuse_prompt=prompt_template,
    **kwargs
)

### SDK and container versions

[[package]]
name = "langfuse"
version = "2.43.3"
description = "A client library for accessing langfuse"
optional = false
python-versions = "<4.0,>=3.8.1"
files = [
    {file = "langfuse-2.43.3-py3-none-any.whl", hash = "sha256:62a368009dd26f698905321a52929ab4e75996a871f41db2892beb5257ab69d2"},
    {file = "langfuse-2.43.3.tar.gz", hash = "sha256:046d872d0d0053d02816d5e5a610be0e4ae7ebb69e65d979111fc522be965691"},
]

### Are you interested to contribute a fix for this bug?

No

**Comment by kikwho** [comment]
I have the same issue and would really appreciate if you guys have a look at this!

All the other langfuse custom args defined in the OpenAiArgsExtractor don't work in the client.beta.* as well. Please fix this. OP's problem is NOT AsyncOpenAI specific, the same thing happens with the normal langfuse OpenAI client.


These args don't work in the client.beta.* :
```
 OpenAiArgsExtractor(
	name=None,
	metadata=None,
	trace_id=None,
	session_id=None,
	user_id=None,
	tags=None,
	parent_observation_id=None,
	langfuse_prompt=None,
	**kwargs
)
```

**Comment by kikwho** [comment]
@0xcodedead Looks like this issue got fixed in version v2.51.5, see #3635

Then try again, report your results pls.

**Comment by hassiebp** [comment]
@kikwho Could you please bump your openai version to >1.50 and try again?
@0xcodedead Could you please change your import to `from langfuse.openai import AsyncOpenAI`?

**Comment by hassiebp** [comment]
Closing this as stale. Please reopen if issue persists.
