### ISSUE TITLE
bug: add user that have an account to the progect

### ISSUE THREAD

**Issue by kobrinartem** [langfuse/langfuse#387]
### Describe the bug

I can not add user to the project it say that:

User must already have an account
User does not exist or already has access to this project

### To reproduce

If user already use the platform I can not add him to my project

**Comment by marcklingen** [comment]
Thanks for reporting this bug @kobrinartem. I see many projects being shared with other users right now on our managed service.

To clarify, the users you are trying to add to the project already created an account with the same email address? Happy to get this fixed quickly

**Comment by kobrinartem** [comment]
I have tested with both: users that already have the account and users that don't have

**Comment by marcklingen** [comment]
Ok thanks for confirming, this is currently the expected behavior. In #395 I'm currently adding email outbound, then adding invites of non-users makes sense as Langfuse can let them know that they are invited to a project

**Comment by marcklingen** [comment]
Create #412 for this new feature, thanks for raising this
