### ISSUE TITLE
bug: panic when getting langchain handler outside of the trace

### ISSUE THREAD

**Issue by imaxmelnyk** [langfuse/langfuse#3888]
### Describe the bug

This is not safe, encounter it in my tests where api key is not set:
https://github.com/langfuse/langfuse-python/blob/main/langfuse/decorators/langfuse_decorator.py#L632

### To reproduce
Do not set any env vars and run the following:
```
@observe
def something():
  langfuse_context.get_current_langchain_handler()
```

### Are you interested to contribute a fix for this bug?

Yes

**Comment by imaxmelnyk** [comment]
@dosu moreover, this code later checks for an empty observation, but it can never happen (because it fails if there is no observation in context):
https://github.com/langfuse/langfuse-python/blob/main/langfuse/decorators/langfuse_decorator.py#L634

**Comment by hassiebp** [comment]
@imaxmelnyk Thanks for raising this! What is the exact error message you are seeing, an `IndexError`? That line should fail if you are outside a decorated context, no matter whether api keys are set or not.
