### ISSUE TITLE
feat: OpenAI Support

### ISSUE THREAD

**Issue by gyliu513** [langfuse/langfuse#389]
### Describe the feature you'd like to request

If I was not using LangChain, LangFlow etc but just OpenAI python script, langfuse will not able to collect the mtrics.

### Describe the solution you'd like to see

Support OpenAI as well

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
Hi @gyliu513, 

The Langfuse Python SDK can be used to integrate with any Python-based LLM application.

For OpenAI specifically, you can use the drop-in replacement of the SDK (just added in `langfuse==1.1.2`) to track all OpenAI requests automatically in Langfuse. All async properties of the SDK remain.

```diff
- import openai
+ from langfuse.openai import openai
```

See [docs](https://langfuse.com/docs/integrations/openai) for more details and an end to end example.
