### ISSUE TITLE
bug: @observe auto updating trace name by function name

### ISSUE THREAD

**Issue by lilytttt** [langfuse/langfuse#3909]
### Describe the bug

Whenever I call functions with `@observe()` , the trace name will be auto updated to be the function name. 

### To reproduce

```
@observe()
async def analyst(query, **kwargs):
    pass
```

```
res await analyst(query='hihi', langfuse_observation_id='xxxxx')
```

### SDK and container versions

langfuse==2.51.2

### Are you interested to contribute a fix for this bug?

No

**Comment by lilytttt** [comment]
> Hey @lilytttt! I'm here to help you with any bugs, questions, or contributions. Let's work together to solve the issue you're facing while we wait for a human maintainer.
> 
> The behavior you're experiencing, where the trace name automatically updates to the function name when using the `@observe()` decorator, is the default behavior in Langfuse version 2.51.2. The decorator captures the function name as part of the trace by default [[1]](https://langfuse.com/docs/sdk/python/decorators).
> 
> If you want to customize the trace name, you can use the `langfuse_context.update_current_trace()` method within the decorated function to set a custom trace name. Here's an example:
> 
> ```python
> from langfuse.decorators import langfuse_context, observe
> 
> @observe()
> async def analyst(query, **kwargs):
>     # Set a custom trace name
>     langfuse_context.update_current_trace(name="Custom Trace Name")
>     pass
> 
> # Usage
> res = await analyst(query='hihi', langfuse_observation_id='xxxxx')
> ```
> 
> This allows you to override the default behavior and set a trace name of your choice [[1]](https://langfuse.com/docs/sdk/python/decorators)[[2]](https://langfuse.com/docs/sdk/python/example).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

**Comment by hassiebp** [comment]
@lilytttt Thanks for reporting - this is expected behavior. If you'd like to override the trace name, please use `langfuse_context.update_current_trace(name='custom_name')`

**Comment by lilytttt** [comment]
> @lilytttt Thanks for reporting - this is expected behavior. If you'd like to override the trace name, please use `langfuse_context.update_current_trace(name='custom_name')`

@hassiebp Is there any plan that we can add any param so that we can choose not automatically update the name?

It is not so easy to update trace name in each functions if I have several layers in my application.
I would prefer we can set the trace name only once.

**Comment by hassiebp** [comment]
I'm not sure I can follow - setting `langfuse_context.update_current_trace(name='custom_name')` anywhere in the execution context should be sufficient to update the trace name. If not, this would be a bug. 

So you should be able to call that method anywhere within any nested function execution once and the trace name should be updated accordingly.

**Comment by lilytttt** [comment]
> I'm not sure I can follow - setting `langfuse_context.update_current_trace(name='custom_name')` anywhere in the execution context should be sufficient to update the trace name. If not, this would be a bug.
> 
> So you should be able to call that method anywhere within any nested function execution once and the trace name should be updated accordingly.

@hassiebp Yes, totally understood. But it makes the things difficult if I need to add this line of code for each function.

**Comment by hassiebp** [comment]
You would not have to do that for each decorated function, but only *once* per trace. So to change the trace name created from executing your top-most decorated function, only one trace update call should suffice.

**Comment by lilytttt** [comment]
> You would not have to do that for each decorated function, but only _once_ per trace. So to change the trace name created from executing your top-most decorated function, only one trace update call should suffice.

@hassiebp But for the code below, the final trace name I got is function_2 not "Custom Trace Name" I update. How can I change that?

```
from langfuse.decorators import langfuse_context, observe
@observe()
async def function_2(query, **kwargs):
    # another chain for some tasks
    pass

@observe()
async def analyst(query, **kwargs):
    # Set a custom trace name
    langfuse_context.update_current_trace(name="Custom Trace Name")
    # some langchain / ... usecase
    await function_2(query = '', langfuse_observation_id=langfuse_context.get_current_trace_id())

# Usage
res = await analyst(query='hihi')
```

**Comment by hassiebp** [comment]
@lilytttt I cannot reproduce that with the latest `langfuse-python` version: 

![CleanShot 2024-11-04 at 14 16 45](https://github.com/user-attachments/assets/2a323fef-bdfd-416d-9de1-3249681d92d9)
