### ISSUE TITLE
Installation on Azure postgres fails when MD5 function disabled

### ISSUE THREAD

**Issue by chrnzt** [langfuse/langfuse#3915]
### Describe the bug

Migrations are failing on Azure Database for PostgreSQL Flexible Server  with the error below :

```
Migration name: 20240807111359_add_organizations_main_migration
Database error code: XX000
Database error:
ERROR: could not compute MD5 hash: disabled for FIPS
```

Calling the postgres md5 function produces the same error :
```
SELECT MD5('PostgreSQL MD5');
ERROR:  could not compute MD5 hash: disabled for FIPS
```
This error appears to be caused by :
> Support for MD5 is disabled in favor of [SCRAM authentication](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-connect-scram) authentication for new PostgreSQL 14+ new server deployments.
(https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/release-notes#release-september-2024)

The prisma migration scripts should not use FIPS non compliant functions like md5.

### To reproduce

Migration from version 2.55 to version 2.85.1 with newly deployed Azure Postgres Flexible 16.4

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Thanks for sharing!

The use of MD5 here is not related to security; it simply combines various sources of randomness to create a unique ID for a row, making it generally unrelated to FIPS: [https://github.com/langfuse/langfuse/blob/10d5975e261ac75a9a81950870031dc0abbcda3e/packages/shared/prisma/migrations/20240807111359_add_organizations_main_migration/migration.sql#L66](https://github.com/langfuse/langfuse/blob/10d5975e261ac75a9a81950870031dc0abbcda3e/packages/shared/prisma/migrations/20240807111359_add_organizations_main_migration/migration.sql#L66)

According to [this thread](https://github.com/FusionAuth/fusionauth-issues/issues/2891), Azure potentially reverted disabling MD5 on newer deployments. Can you verify this?

**Comment by marcklingen** [comment]
@chrnzt did reenabling MD5 (either manually or by Azure reverting this change) fix this for you?

**Comment by marcklingen** [comment]
Was this resolved? I'd appreciate any update as we either would need to accommodate this or we can close this issue

**Comment by chrnzt** [comment]
Hello
md5 has been reeanabled on the new Azure Postgre deployments and patched on already deployed instances.
However, it would be nice if future prisma migrations used a different function in case the disabling is present in later versions of Postgre.
