### ISSUE TITLE
bug: Duplicate Observation

### ISSUE THREAD

**Issue by anantgupta129** [langfuse/langfuse#3921]
### Describe the bug

getting duplicate observation when using openai
![image](https://github.com/user-attachments/assets/2dc070bd-6996-4965-84a0-0e8efddc20e3)

### To reproduce

```python
def _get_client(self, reuse: bool = False) -> openai.AzureOpenAI:
        if reuse:
            return self._client
        else:
            return openai.AzureOpenAI(api_version=self.api_version)

@observe(as_type="generation", capture_input=False, capture_output=False)
    def _complete(self, messages: Sequence[ChatMessage], **kwargs) -> ChatCompletion:
        client = self._get_client()
        message_dict = to_openai_message_dicts(messages)
        params = self._get_model_kwargs(**kwargs)

        response = client.chat.completions.create(messages=message_dict, stream=False, **params)
        openai_message = response.choices[0].message
        message_gen = from_openai_message(openai_message)

        langfuse_context.update_current_observation(
            model=response.model,  # self.model_name,
            model_parameters=params,
            input=message_dict,
            output=message_gen.content,
            usage={
                "input": response.usage.prompt_tokens,
                "output": response.usage.completion_tokens,
                "total": response.usage.total_tokens,
            },
        )
        return ChatCompletion(
            message=message_gen, id=response.id, usage=response.usage.model_dump()
        )
```

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment]
Hi @anantgupta129 - are you using the Langfuse openai integration for your openai call? 

```pyton
from langfuse.openai import openai
```

If so, you can drop the `as_type=generation` on your decorated function, as Langfuse will take care to classify the executions as a generation under the hood already.

**Comment by anantgupta129** [comment]
@hassiebp  i am using openai directly, i did not want to use `langfuse.openai` because of other LLM integration like custom llm deployment or anthropic or any other

**Comment by hassiebp** [comment]
Hmm the generation name `OpenAI-generation` is only set by the Langfuse OpenAI integration. Either somewhere else in your app the openai client monkey patch is applied by importing `from langfuse.openai import openai`, or you have a third party package that uses the langfuse openai integration. 

Could you please try this in your module:

`from openai import openai

print(openai.langfuse_public_key)`

If that attribute exists, there must be the langfuse openai integration activated somewhere.

**Comment by anantgupta129** [comment]
@hassiebp got it, langfuse openai is indeed imported in app for Async streaming responses. As `langfuse_context` does not work with async streaming apis. 

Is there any way u ca. Update the context with trace or observation I'd?  Like `langfuse_context.update_trace_from_id` instead of up`date_current_trace`

**Comment by hassiebp** [comment]
You can use this workaround

```python
from langfuse import Langfuse

langfuse = Langfuse()
trace_id = 'your_trace_id_to_update`

langfuse.trace(id=trace_id, user_id='my_user_id, ...)
```
