### ISSUE TITLE
bug: Test in playground doesn't bring up context

### ISSUE THREAD

**Issue by ajram23** [langfuse/langfuse#3931]
### Describe the bug

Not sure if this is expected behavior or a bug. When I click test in background in a trace it just takes me to the playground and expects me to fill out stuff. Instead it has all the relevant info including prompt, input, access to tools/output. All of these should be loaded in context

### To reproduce

Open a trace with OpenAI call go to generator, click test in playground.

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment]
Hi @ajram23 - this is probably due to a parsing issue when jumping from generation messages to the playground. Could you please share the observation ID for which you see the jump fail? You can find it in the URL path

**Comment by ajram23** [comment]
@hassiebp Here you go aaac4226-fd48-4a6b-8c5e-9a75d177f4c6.

**Comment by ajram23** [comment]
@hassiebp Also do you folks support function calling in the playground? if not linking to openAI's playground would be very useful.

**Comment by hassiebp** [comment]
Hi AJ, the playground does not support tool call messages currently that breaks the message parsing for you generation. Thus, a playground with empty messages is shown. We have the following Github discussion here to track progress on the feature request: https://github.com/orgs/langfuse/discussions/3166

**Comment by hassiebp** [comment]
Closing this as underlying issue is the missing tool call support in playground. Please follow progress on that here:  https://github.com/orgs/langfuse/discussions/3166
