### ISSUE TITLE
bug: 100% memory and CPU consumption when setting up the dev environment

### ISSUE THREAD

**Issue by faresbouzayen** [langfuse/langfuse#3932]
### Describe the bug

I expect the dev env to be working reasonably

### To reproduce

setup the dev env

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Closing this issue for now as I cannot reproduce this, please share more details on your setup if you still encounter these problems

**Comment by okaeiz** [comment]
I am also experiencing this issue.
