### ISSUE TITLE
bug: no token counts on llamaindex chat and stream_chat

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#3952]
### Describe the bug

@voortwis reported this:

> I ran into an issue (maybe related to my way of using):
> i use llamaindex with ollama and and the LLamaIndexInstrumentor (i know, still in beta):
> .complete(..) gives token counts.
> .chat(..) does not - nor does the stream_chat().

### To reproduce

```
from langfuse.llama_index import LlamaIndexInstrumentor

import os
os.environ["LANGFUSE_HOST"] = "https://endpoint/"
os.environ["LANGFUSE_PUBLIC_KEY"] = "pk-"
os.environ["LANGFUSE_SECRET_KEY"] = "sk-"

instrumentor = LlamaIndexInstrumentor(
    # public_key="pk-",
    # secret_key="sk-",
    # host="https://endpoint/",
    flush_at=1)
instrumentor.start()
```

```
from llama_index.llms.ollama import Ollama

llm = Ollama(base_url="https://endpoint/", 
             # model="llama3.1:latest", 
             model="granite3-moe:latest", 
             request_timeout=120.0) # 2 minutes
```

Testcode:

```
from llama_index.core.llms import ChatMessage

# Flush doesn't make any difference

# YES token count
resp = llm.complete("Who is Kendrick?")
print(resp)
instrumentor.flush()

messages = [
    ChatMessage(role="system", content="You are Kendrick."),
    ChatMessage(role="user", content="Write a verse."),
]

# No token count (streaming either)
response = llm.chat(messages)
print(response)

with instrumentor.observe(trace_id='llm-chat', session_id="with-token-counts", user_id='my-user'):
    response = llm.chat(messages)
    print(response)
instrumentor.flush()

with instrumentor.observe(trace_id='llm-chat-stream', session_id="with-token-counts", user_id='my-user'):
    response = llm.stream_chat(messages)
    for r in response:
        print(r.delta, end="")
    
instrumentor.flush()
```

### Are you interested to contribute a fix for this bug?

No

**Comment by voortwis** [comment]
to make sure I am @ the latest version, this is at the top of my notebook. - after which i restarted.

```
%pip install --update llama-index-llms-ollama
%pip install --update llama-index-embeddings-ollama

%pip install --update langfuse 
%pip install --update llama_index

%pip install --update ipywidgets
```
the streaming version does not log any tokens (or response), even when wrapped with instrumentor.observe(...): . Maybe there is a solution for that too although not that important for now.

**Comment by hassiebp** [comment]
@voortwis Thanks for sharing this! 
- Are you running a self hosted setup?If yes, could you please share a screenshot of the generation missing the token usage. If not, you can simply paste a trace URL here.
- There was a similar issue with OpenAI yesterday, [see docs here](https://langfuse.com/docs/integrations/llama-index/get-started#streamed-openai-responses-and-token-usage) on how to capture token usage for streamed OpenAI calls. Is there a way to force Llama models to return token usage as well similar as with OpenAI?

**Comment by voortwis** [comment]
@hassiebp Thank you for looking into this - issue fixed, see below.

I self host on k8s.
for reference on ollama: https://github.com/ollama/ollama/blob/main/docs/api.md#chat-request-streaming
i returns the tokenusage in the last streaming response when streaming

with version: v2.53.2
![image](https://github.com/user-attachments/assets/6699cbf4-7bb1-49d7-a17d-98bc1bbbfe73)

with version: v2.53.3
![image](https://github.com/user-attachments/assets/6231c040-cac8-40d9-b628-c892ce074de4)


and in the console it also shows a message (this was a good sign before i looked in the langfuse frontend): Trace ID is not set. Creating generation client with new trace id.

**Comment by hassiebp** [comment]
Thanks @voortwis ! Are your traces complete though / do you see additional traces? The warning message you described should not occur 🤔

**Comment by voortwis** [comment]
the traces are complete. no extra parts.

**Comment by hassiebp** [comment]
Perfect, closing this issue now 👍
