### ISSUE TITLE
feat: Support HuggingFacePipeline as the LLM model

### ISSUE THREAD

**Issue by yueming-zhang** [langfuse/langfuse#397]
### Describe the feature you'd like to request

I am using HuggingFacePipeline as shown below. It works fine with LangChain, and also able to log trace to Langfuse. However, the logged trace missing the actual Prompt. The root cause is in the screenshot as the model_name is not available causing exception. Then the self.runs[] won't contain the run_id, causing missing prompt later. Could you advise how to passing in model_name in this scenario?

generate_text = transformers.pipeline(
    model=self.model, 
    tokenizer=self.tokenizer,
    return_full_text=True,  # langchain expects the full text
    task='text-generation',
    # we pass model parameters here too
    stopping_criteria=self.stopping_criteria,  # without this model rambles during chat
    temperature=0.1,  # 'randomness' of outputs, 0.0 is the min and 1.0 the max
    max_new_tokens=512,  # max number of tokens to generate in the output
    repetition_penalty=1.1  # without this output begins repeating
)    

llm =  HuggingFacePipeline(pipeline=generate_text, model_kwargs = {"model_name" :'Llama-2-13b'})
chain = ConversationalRetrievalChain.from_llm(llm, vector_store.as_retriever())
<img width="652" alt="image" src="https://github.com/langfuse/langfuse/assets/36120718/93168779-9ce8-4f84-8929-8522e0def9c2">

### Describe the solution you'd like to see

Using a default model_name if not provided. This will work for HuggingFacePipeline and other LLM.

Or provide an example of how to use HuggingFacePipeline.

### Additional information

I can't find the callback.py file in the repo. I can provide a PR if you let me know where is the callback.py.

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by maxdeichmann** [comment]
@yueming-zhang thanks for raising this! Unfortunately we ran into this issue quite sometimes as Langchain has the model info in different parts of the kwargs dependent on the chain that is executed.
Here is the file we are talking about: https://github.com/langfuse/langfuse-python/blob/main/langfuse/callback.py#L498
Here is a test class where you can add the HuggingFacePipeline and see where it breaks: https://github.com/langfuse/langfuse-python/blob/main/tests/test_langchain.py

It would be awesome if you could provide a PR that solves the issue :)

**Comment by yueming-zhang** [comment]
I have a fix on my local by using <unknown> as the model name if the real name can't be determined. Could you grant me permission to create PR on the langfuse-python repo?

**Comment by marcklingen** [comment]
@yueming-zhang we'd love to merge this for other users, can you create a PR with your changes? happy to support on this

**Comment by maxdeichmann** [comment]
@yueming-zhang  thanks for reporting this issue. As of [release 2.11.0](https://github.com/langfuse/langfuse-python/releases/tag/v2.11.0), this issue was resolved. Feel free to re-open this issue if this appears again.
