### ISSUE TITLE
bug: UI / Traces page / Select all checkbox looking half on Firefox

### ISSUE THREAD

**Issue by abdullah-retorio** [langfuse/langfuse#4024]
### Describe the bug

Langfuse version: 2.87.0

Where: Tracing / Traces page

Browser: Firefox

Definition: Select all checkbox, which is used for selecting all traces and located on the left top, is looking 
 half. Check screenshot

![b](https://github.com/user-attachments/assets/bfac4f65-765f-493a-bdde-0d98d489ace8)

### To reproduce

Langfuse version: 2.87.0

Where: Tracing / Traces page

Browser: Firefox

Definition: Select all checkbox, which is used for selecting all traces and located on the left top, is looking 
 half. Check screenshot

![b](https://github.com/user-attachments/assets/bfac4f65-765f-493a-bdde-0d98d489ace8)

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Thanks for sharing, can reproduce this on Firefox

**Comment by marcklingen** [comment]
this was quick, thank you @marliessophie

**Comment by abdullah-retorio** [comment]
Thank you for your quick reaction @marliessophie @marcklingen
