### ISSUE TITLE
feat: Create Support for gemini models in playground

### ISSUE THREAD

**Issue by hassiebp** [langfuse/langfuse#4028]
### Discussed in https://github.com/orgs/langfuse/discussions/4019

<div type='discussions-op-text'>

<sup>Originally posted by **anuraj-suman** November  3, 2024</sup>
### Describe the feature or potential improvement

Currently we do not support Gemini models in playground in langfuse.
Please support this

### Additional information

_No response_</div>

**Comment by hongkongkiwi** [comment]
Yes please, this would be really excellent.

It is the cheapest model by far for for multimodal processing and so I imagine it's in quite widespread use.

It is already supported in Langsmith the other advanced product, so hopefully it's not too much work to port it over.

**Comment by hassiebp** [comment]
We have just shipped Google Vertex AI support for playground and evals 👍🏾  Feel free to give it a spin and let us know your feedback! 🙏🏾 

https://langfuse.com/changelog/2024-11-28-google-vertex-ai-support-playground-evals
