### ISSUE TITLE
bug: Cost Reporting Stuck at $0 for AWS Bedrock Claude Pipeline Traces

### ISSUE THREAD

**Issue by maycszz** [langfuse/langfuse#4072]
### Describe the bug

I've integrated Langfuse tracing with my AWS Bedrock Claude Pipeline, and while token usage is accurately logged and tabulated (as seen in the UI), the reported cost remains at $0 regardless of the number of tokens used. I expected the cost to reflect usage, based on the number of tokens sent.

**Expected Behavior:**
The cost for AWS Claude models should reflect the usage, dynamically updating based on the tokens sent.

**Actual Behavior:**
The cost consistently shows $0 despite active token usage being reported accurately.

This is only happening for AWS Claude Models (Haiku, Sonnet, etc..) and the issue is with the total cost calculation.

![Screenshot 2024-11-06 at 12 49 26 PM](https://github.com/user-attachments/assets/fd4dea13-bf62-4db6-87f3-450cebcbaa93)

### To reproduce

I retrieved usage tokens from AWS's claude pipelines

Example usage retrieved from AWS Claude API: `{'inputTokens': 9758, 'outputTokens': 45, 'totalTokens': 9803}`

After retrieving it, i send the trace to langfuse with the following code:
```
       trace = self.langfuse.trace(
            name=f"pipeline_trace:{__name__}",
            input=body,
            user_id=user["email"],
            metadata={"user_name": user["name"], "user_id": user["id"]},
            session_id=body["chat_id"],
        )
        generation = trace.generation(
            name=body["chat_id"],
            model=body["model"],
            input=body["messages"],
            metadata={"interface": "open-webui"},
        )

        self.chat_generations[body["chat_id"]] = generation
        print(trace.get_trace_url())

        generation = self.chat_generations[body["chat_id"]]
        user_message = get_last_user_message(body["messages"])
        modified_usage = {"input": usage.get("inputTokens"), "output": usage.get("outputTokens"), "total": usage.get("totalTokens"), "unit": "TOKENS"}
 
        generated_message = get_last_assistant_message(body["messages"])
        generation.end(
            output=generated_message,
            usage=modified_usage,
            metadata={"interface": "open-webui"},
        )

```

Example of the usage dict sent to langfuse: `{'input': 9758, 'output': 45, 'total': 9803, 'unit': 'TOKENS'}`

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Thanks for sharing, have you tried to set up a model definition to map token counts to costs?<br>Docs: [https://langfuse.com/docs/model-usage-and-cost](https://langfuse.com/docs/model-usage-and-cost)

**Comment by maycszz** [comment]
Hi @marcklingen,

Thank you for your response. I’ve set up a model definition to map token counts to costs, as shown in this screenshot: ![Screenshot 2024-11-12 at 12 03 37 PM](https://github.com/user-attachments/assets/ffa1efce-d740-40ec-85fe-e46e9756b902)

However, costs for the Claude and Gemini models are still not computed automatically and remain at $0. Currently, I have to manually calculate the cost by multiplying the token count (from the provider API) by the price per 1K tokens, then send it as a trace to Langfuse for the cost to appear.

Is there a way to provide just the token count and have Langfuse automatically calculate the cost in its UI? This would also simplify handling price updates.

Thanks in advance!

**Comment by marcklingen** [comment]
Can you share an example trace (public link) how it is reported by openwebui directly? Like before you have updated it? Usually this should not be necessary.

**Comment by marcklingen** [comment]
Were you able to resolve this? You can add custom model prices in Langfuse to make Langfuse do the token x price calculation for you (see docs page included above). I'll close this issue for now, please let me know in case this still does not work for you, happy to help
