### ISSUE TITLE
bug: Custom model cost tracking broken

### ISSUE THREAD

**Issue by akvachan** [langfuse/langfuse#4073]
### Describe the bug

I am using LiteLLM proxy server with custom configured model names and costs. In Langfuse, I utilize normal OpenAI integration like so:

```
import os
import httpx
from langfuse.openai import OpenAI
from dotenv import load_dotenv

http_client = httpx.Client(verify="./cacert.pem")

load_dotenv('.env')


client = OpenAI(http_client = http_client)

messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Write a text message to book a table at a restaurant"},
]

response = client.chat.completions.create(
    model="azure.gpt-4o-mini",
    messages=messages
)

print(response.choices[0].message.content)
```

Please notice the line  `model="azure.gpt-4o-mini"`

In order for Langfuse to correctly infer the model, I create a corresponding entry (manually) in Langfuse instance:

<img width="1462" alt="image" src="https://github.com/user-attachments/assets/afc8cfb7-95d0-422c-830a-40008d8577d4">

When I execute the code above, I get following generation:

<img width="1503" alt="image" src="https://github.com/user-attachments/assets/eecaa685-f7cb-4883-a0e2-3b51214d5be8">

And here is the trace:

<img width="1501" alt="image" src="https://github.com/user-attachments/assets/e89ab4ef-658d-4369-ad18-deaf1f0eb0af">

It look like my added model simply gets ignored. Can you tell me why? Is this (potential) bug or am I doing something wrong here?

PS: I already read [this](https://langfuse.com/docs/model-usage-and-cost#ingest) documentation

### To reproduce

You will need to install simple LiteLLM proxy: https://docs.litellm.ai/docs/proxy/quick_start

### Are you interested to contribute a fix for this bug?

No

**Comment by akvachan** [comment]
I am currently using the latest Langfuse:

Here are my other dependencies, in the local setup, if this helps.

<img width="453" alt="image" src="https://github.com/user-attachments/assets/8bb83ee8-53f1-4bee-8cb0-e411a4edab23">

**Comment by hassiebp** [comment]
Thanks for your report @akvachan ! Could you please provide a trace ID / generation ID for which you see this mismatch (you can get it from the URL path).

Also, could you please enable langfuse debug mode in your LiteLLM app by setting `LANGFUSE_DEBUG="True"` in your environment?

I assume that at some point the model name is swapped to gpt-4o-mini rather than with the azure prefix. We need to find out where exactly now :)

**Comment by hassiebp** [comment]
Hi @akvachan , this is working as expected. We match the name of the actual model used that is returned by the LLM provider for cost tracking. 

Could you please create a separate issue with an repro example for the observe decorator + LiteLLM issue you mentioned?
