### ISSUE TITLE
bug: Traces collection from the Vercel AI SDK doesn’t work when the app is deployed on Vercel

### ISSUE THREAD

**Issue by apshenichniy** [langfuse/langfuse#4082]
### Describe the bug

I forked an [example project](https://github.com/langfuse/langfuse-vercel-ai-nextjs-example) and updated the dependencies. It works when running locally, but there are no traces when the app is deployed on Vercel.

### To reproduce

[Repo](https://github.com/apshenichniy/langfuse-vercel-ai-nextjs-example)

### SDK and container versions

`"ai": "latest",
  "langfuse-vercel": "^3.29.1",
`

### Are you interested to contribute a fix for this bug?

No

**Comment by apshenichniy** [comment]
> The issue you're experiencing with traces collection from the Vercel AI SDK not working when deployed on Vercel might be related to Vercel’s OpenTelemetry Collector, which is only available on Pro and Enterprise Plans. This is a known limitation mentioned in the documentation [[1]](https://langfuse.com/docs/integrations/vercel-ai-sdk).

It is deployed on the Pro plan.

**Comment by hassiebp** [comment]
Hi @apshenichniy - could you please verify that environment variables are set correctly in your vercel project? If yes, could you please enable debug logs and share the outputs: 

```typescript
new LangfuseExporter({ debug: true });
```

**Comment by hassiebp** [comment]
Closing this as stale.
