### ISSUE TITLE
bug(sdk-pythong):Dependencies -> Langfuse SDK,  Package, and Safety

### ISSUE THREAD

**Issue by nthanapaisal** [langfuse/langfuse#4088]
### Describe the bug

Hi,

My application needs these 3 libraries (Langfuse SDK,  Package, and Safety). However, It seems there is conflict when I tried to build a package 

Langfuse 2.52.0 depends on Packaging<25.0 and >=23.2 
Safety 2.3.5 depends on Packaging<22.0 and >=21.0 

Any recommendation on which Langfuse SDK version to use to solve this conflict?

Thanks

### To reproduce

pip-compile requirements.in

```
Langfuse
Packaging
Safety
```

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment]
Hi @nthanapaisal - since Langfuse is depending on a newer version of `packaging`, could you try upgrading your requested Safety package version to a release matching the packaging dependency range?

**Comment by hassiebp** [comment]
Closing this as stale.
