### ISSUE TITLE
bug: gpt-4o-latest doesnt work

### ISSUE THREAD

**Issue by jjamgmv** [langfuse/langfuse#4112]
### Describe the bug

The cost of gpt-4o-latest price is 0

### To reproduce

The cost of gpt-4o-latest price is 0

### Are you interested to contribute a fix for this bug?

No

**Comment by r00dY** [comment]
I confirm. I literally came here to report the same bug just to see it's already added.

**Comment by r00dY** [comment]
@hassiebp what do you mean by that? `chatgpt-4o-latest` is neither the same as `gpt-4o-2024-08-06` nor `gpt-4o`

**Comment by hassiebp** [comment]
We have just merged cost tracking support for `chatgpt-4o-latest` 👍🏾 Please let us know if you notice anything out of the order.
