### ISSUE TITLE
feat: invite new users to a project that do not have an account yet

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#412]
### Describe the feature you'd like to request

As mentioned by @kobrinartem in #387, it would be useful to invite users to Langfuse by adding them to a project, even if they do not have an account yet. This is currently not suported.

### Describe the solution you'd like to see

- Email notification with invite, email service is pending merge in #395 
- Pending account state, users needs to be able to sign up and instantly have access to the projects
- Pending state on member list in project (user has not joined yet)

### Contribute

- [X] Yes, I can implement this and raise a PR

<sub>[LFC-217](https://linear.app/langfuse/issue/LFC-217/feat-invite-new-users-to-a-project-that-do-not-have-an-account-yet)</sub>

**Comment by 18feb06** [comment]
@marcklingen Can I work on it?

**Comment by marcklingen** [comment]
@18feb06 generally yes, but I'd suggest to collaborate on a spec/design in this issue first before starting to implement it as there are many ways to do this (user flow, database model, implementation of notifications)

**Comment by 18feb06** [comment]
Ok... Can you give me any suggestion.

**Comment by 18feb06** [comment]
> ### Describe the feature you'd like to request
> As mentioned by @kobrinartem in #387, it would be useful to invite users to Langfuse by adding them to a project, even if they do not have an account yet. This is currently not suported.
> 
> ### Describe the solution you'd like to see
> * Email notification with invite, email service is pending merge in [Add magic-link auth #395](https://github.com/langfuse/langfuse/pull/395)
> * Pending account state, users needs to be able to sign up and instantly have access to the projects
> * Pending state on member list in project (user has not joined yet)
> 
> ### Additional information
> _No response_
> 
> ### Contribute
> * [x]  Yes, I can implement this and raise a PR
> 
> [LFC-217](https://linear.app/langfuse/issue/LFC-217/feat-invite-new-users-to-a-project-that-do-not-have-an-account-yet)


As you mentioned above to create a membership with pending state, but how can we create a membership wihtout userId (As user has not been signed up and there is no user).
