### ISSUE TITLE
feat(openai-integration): Support `n` modelParam and track n-choices as array in output

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#4199]
### Discussed in https://github.com/orgs/langfuse/discussions/4197

<div type='discussions-op-text'>

<sup>Originally posted by **ngamolsky** November 12, 2024</sup>
Currently, when using the [`n` parameter](https://platform.openai.com/docs/api-reference/chat/create#chat-create-n) in openai completions, this parameter is not visible anywhere in the trace, and we only see the first choice output.

It should be supported in two places:

1. At the top of the trace detail where we see the other generation params (see screenshot)
2. In the output.

This is especially important when capturing generation traces as datasets, as if you are using the n parameter you likely want all the outputs in your dataset.

Im sure there are several ways of implementing the second piece, in terms of using a list of outputs or splitting out different generations (probably less correct).

Related discussions:
https://github.com/BerriAI/litellm/issues/4964

<img width="1476" alt="image" src="https://github.com/user-attachments/assets/40742671-07af-4c52-b04f-5714acaeab82">
</div>

**Comment by ngamolsky** [comment]
Do we think it's better to have a list of of completions as the output which results in something like this

<img width="1462" alt="Screenshot 2024-11-12 at 2 13 41 PM" src="https://github.com/user-attachments/assets/af5c079f-e4a7-43a9-ac5b-53e0c8af20ad">


Or do we want to concatenate the responses in the code to get a single output with something like:

<img width="1537" alt="image" src="https://github.com/user-attachments/assets/522ada0a-ed63-4256-8b31-5d3028ec23e9">
@marcklingen

**Comment by ngamolsky** [comment]
Probably the best option is a change in the frontend which can add a little info section above the responses to note that they are from the n choices param

**Comment by marcklingen** [comment]
On the SDK level, I would probably opt for
Output = { choices: [..] }

initially this is then rendered in the default json view component in the ui, this could then be improved in the future but doesn’t need to happen right away

**Comment by ngamolsky** [comment]
Great PR opened!\

**Comment by marcklingen** [comment]
thank you, we will have a look

**Comment by hassiebp** [comment]
PR is merged and released already 👍🏾
