### ISSUE TITLE
feat: (optionally) fail health check if database unavailable

### ISSUE THREAD

**Issue by tomi-bigpi** [langfuse/langfuse#4200]
### Describe the bug

Continuing from discussion https://github.com/orgs/langfuse/discussions/4179

Currently, the health check API endpoints return 200 / OK even when there are database connectivity issues. This makes it impossible to leverage the health endpoints as they are normally used in Kubernetes to terminate an unhealthy pod.

(The reason in the discussion for the current behavior was due to a cluster going down due to temporary database issues when the health check failed. However, this seems like a misconfiguration of the deployed stack since not reflecting database status in the health endpoint defeats the purpose and could be avoided in Kubernetes with a higher failureThreshold for example)

### To reproduce

* Configure an incorrect database password
* Hit the health APIs http://localhost:3000/api/public/health

Note the 200 - OK status.

### Additional information

@marcklingen suggested the following in the discussion:

> I think it would be a good idea to allow this as an optional flag, for example, curl http://localhost:3000/api/public/health?failIfDbUnavailable=true.

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks @tomi-bigpi
