### ISSUE TITLE
bug: AttributeError: 'generator' object has no attribute 'choices'

### ISSUE THREAD

**Issue by weibinke** [langfuse/langfuse#422]
### Describe the bug

I am using OpenAI with Langfuse，following https://langfuse.com/docs/integrations/openai.

But it goes wrong when i use steam=True mode to call OpenAI completion.create, seam langfuse does not support this yet?

wrong message here:
  .venv/lib/python3.11/site-packages/langfuse/openai.py", line 75, in _get_call_details
    completion = result.choices[-1].message.content
                 ^^^^^^^^^^^^^^
AttributeError: 'generator' object has no attribute 'choices'

### To reproduce

follow https://langfuse.com/docs/integrations/openai, and call OpenAI completion.create with stream=True

**Comment by maxdeichmann** [comment]
@weibinke thanks for reporting. We know this does not work yet. Would you be interested to look into this and maybe create a PR?

**Comment by kirad1231** [comment]
@maxdeichmann  Streaming still not work, could you look into it?

**Comment by maxdeichmann** [comment]
> still not work, could you look into it?

@kirad1231 thanks for raising this. In Python repo, we do have a test for that: https://github.com/langfuse/langfuse-python/blob/7e069db65e251444398a284642392df6992a3374/tests/test_openai.py#L112-L113

Did you implement that differently on your end?
