### ISSUE TITLE
[bug] Langfuse overwriting ingested usage for gpt-4o-mini models & incorrect inferred usage for low-detail image data

### ISSUE THREAD

**Issue by LastRemote** [langfuse/langfuse#4232]
### Discussed in https://github.com/orgs/langfuse/discussions/4231

<div type='discussions-op-text'>

<sup>Originally posted by **LastRemote** November 14, 2024</sup>
I am using Langfuse low-level Python SDK to track my gpt-4o-models usage. I use a generation to track model i/o, TTFT and usage information. I found two issues here:

1. Langfuse returns incorrect usage if I set "detail": "low" according to [OpenAI vision guide](https://platform.openai.com/docs/guides/vision#low-or-high-fidelity-image-understanding). The model returns `'usage': {'completion_tokens': 120, 'prompt_tokens': 5683, 'total_tokens': 5803}`, but I got `15,631 → 120 (∑ 15,751)` from Langfuse.

2. Even if I send the usage to Langfuse client, Langfuse still prefers its inferred usage, which is not intended according to [Langfuse documentation](https://langfuse.com/docs/model-usage-and-cost). I tried to update the model (in the generation) to something else, and it tracked the usage data correctly. I am attaching a screenshot of my experiments below:
<img width="649" alt="Screenshot 2024-11-14 at 20 25 16" src="https://github.com/user-attachments/assets/5111b455-7ab1-4ffb-9429-5e479daea600">

I am using a self-hosted Langfuse (v2.81.0 OSS) for these experiments. I hope it helps.
</div>

**Comment by marcklingen** [comment]
let's first discuss this within the discussion thread, I think I can help you there already, closing this for now
