### ISSUE TITLE
bug: Wrong cost summary in bookmark Session and Users

### ISSUE THREAD

**Issue by kglapiakbng** [langfuse/langfuse#4249]
### Describe the bug

I discover that in langfuse UI (in official https://cloud.langfuse.com/ site) Total Cost is wrong in bookmarks: "Sessions" and "Users". 

First bookmark Users:
For the same time peroid I have different values of "Total cost" for same user in Dashboard and in bookmark Users - approx 2 times. 

Also in Bookmark Sessions Total cost is about 2 times higher that in Dashboard.

Probably its some aggregation or calculation issue in UI of this bookmarks. 
I attach screenshots

![bookmark-user](https://github.com/user-attachments/assets/58e9f014-5bf9-4aea-a52e-82f1b084ac04)
![dashboard](https://github.com/user-attachments/assets/afc41609-f01b-4208-9fb7-157eafb39127)
![dashbord-user](https://github.com/user-attachments/assets/fda76094-9bb0-4a9c-addb-f1a67d6b6e67)
![sessions](https://github.com/user-attachments/assets/5e2a3dfe-6679-43cd-9d36-5297975d24f1)

### To reproduce

Bug is in UI on official site https://cloud.langfuse.com.
My user is: k.glapiak@brandnewgalaxy.com

### Are you interested to contribute a fix for this bug?

No

**Comment by Steffen911** [comment]
Hey @kglapiakbng,
Thank you for the report and apologies for the delay. Updating the information and reading from Clickhouse was an ongoing project on our Cloud instance for the past weeks. I checked your project and validated that the dashboard numbers and the session and user numbers match for 24h, 7d, and 30d. Hence, I'd expect that the numbers are correct going forward.

As this seems resolved from my side, I'll go ahead and close the issue. Please reopen if you see any other discrepancies.
