### ISSUE TITLE
bug: no sidebar for scores

### ISSUE THREAD

**Issue by christos-bsq** [langfuse/langfuse#4290]
### Describe the bug

The **Show/Hide Columns** menu has no sidebar for "Scores"

As a result 
1. The UI element is very long
2. If the project has many scores, some don't appear on the page

_Langfuse v2.90.1_

### To reproduce

0. have project with many scores (or zoom in a lot)
1. go to the `/traces` page
2. go the the `Show/Hide` columns --> `Scrores`
  - There is no sidebar
  - No way to see all the scores, assuming they are many
  - if zook

### Additional information

Screenshot with **100% Zoom: `28` scores**
![image](https://github.com/user-attachments/assets/8ffa9b9c-e4c7-45ac-b8fa-719345476365)

Screenshot with **90% Zoom: `30` scores**
![image](https://github.com/user-attachments/assets/d19d40d5-e40c-432f-aeb9-a58397e2fab7)

_Plus, the way the scores are ordered kept changing while I was trying to take screenshots for this bug report._

### Are you interested to contribute a fix for this bug?

No

**Comment by marliessophie** [comment]
Hey @christos-bsq thank you for reporting this! I fixed this in [4569](https://github.com/langfuse/langfuse/pull/4569), which should be included in our next release
