### ISSUE TITLE
feat: Increase character limit of comments in Langfuse

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#4297]
### Discussed in https://github.com/orgs/langfuse/discussions/4280

<div type='discussions-op-text'>

<sup>Originally posted by **jannikmaierhoefer** November 18, 2024</sup>
### Describe the feature or potential improvement

The current limit is 500 characters.

### Additional information

_No response_</div>

**Comment by marcklingen** [comment]
2 pages in characters, this seems to be a reasonable estimate to me

```
A typical 2-page document contains approximately:
	•	500-600 words per page (1,000-1,200 total words)
	•	3,000-3,600 characters with spaces per page (6,000-7,200 total characters)
	•	2,500-3,000 characters without spaces per page (5,000-6,000 total characters)
Note: These are estimates for standard formatting:
	•	12pt font
	•	Double-spaced
	•	1-inch margins
	•	Times New Roman or similar font
	•	Letter/A4 size paper
The exact count will vary based on formatting, font choice, margin size, and spacing.
```

**Comment by marliessophie** [comment]
This has been addressed in https://github.com/langfuse/langfuse/pull/4577
