### ISSUE TITLE
bug: auth errors not logged in Python SDK

### ISSUE THREAD

**Issue by gyliu513** [langfuse/langfuse#430]
### Describe the bug

If I set a wrong public key for langfuse and run openai following https://langfuse.com/docs/integrations/openai#chat-completion, the openai call can still be succeed but there is no trace/generation info due to I was not able to connect to langfuse.

### To reproduce

The langfuse should fail fast if the pub key or secret key is not right

**Comment by maxdeichmann** [comment]
@gyliu513 thanks for submitting this! Did you see unauthenticated error logs in the console? We do not want to add latencies to the SDK, hence it is not possible to authenticate in advance with the server.

**Comment by gyliu513** [comment]
> @gyliu513 thanks for submitting this! Did you see unauthenticated error logs in the console?

No error in the console, and everything runs good, but just no trace/generation in the langfuse UI. I think this behavior is not good for customers, like I have run some apps with LLMs, and it cost me some money, but finally I found the key is not right and no data was captured by langfuse, I will not able to do any analytics. Compared with cost and latency, I prefer reduce some cost ;-)

**Comment by maxdeichmann** [comment]
Thanks! Did you have any specific logging setup in your application or run everything on a given log level? Exceptions are logged as warning and should print to your console.

**Comment by gyliu513** [comment]
No, I was just using the openai example in the langfuse documentation, and also using my own docker compose langfuse with default config. I was wondering can we add a simple ping API just to detect if langfuse server can be connected or not?

**Comment by gyliu513** [comment]
this is because for openai integration, we need to finish the openai call first, and then create the generations, the case here is openai call succeeded, but langfuse api call failed, thus no analytics from langfuse UI.

**Comment by maxdeichmann** [comment]
> this is because for openai integration, we need to finish the openai call first, and then create the generations, the case here is openai call succeeded, but langfuse api call failed, thus no analytics from langfuse UI.

i think a ping API would be a bit verbose. It is strange that you did not see any error logs. Usually, they should appear. Would you be fine with logs showing up in case auth fails?

**Comment by gyliu513** [comment]
> i think a ping API would be a bit verbose. It is strange that you did not see any error logs. Usually, they should appear. Would you be fine with logs showing up in case auth fails?

Yes, that make sense, thanks @maxdeichmann

**Comment by maxdeichmann** [comment]
The Python SDK as of version 1.2.1 has prints auth errors to the console: https://github.com/langfuse/langfuse-python/releases
