### ISSUE TITLE
bug: Trace Tree Inaccurate in Langfuse using LangfuseExport Vercel AI SDK

### ISSUE THREAD

**Issue by leo-paz** [langfuse/langfuse#4302]
## Example 1
![image](https://github.com/user-attachments/assets/bedbaab2-a532-4968-b14c-25fd3bfb3de6)
In the above screenshots the structure of the span tree is completely off based on which calls were made first. Additionally, the names of the SPAN elements never include the `functionId` I specify in `experimental_telemetry`.

Maybe I'm misunderstanding how this works but for some reason the very last call I make to `streamText` in my workflow is what is used for the trace name. But, the span representing my last call is actually here:
![image](https://github.com/user-attachments/assets/2d54164c-dae5-4711-a1a9-d4e19b461122)
The bottom `generateObject` calls in the first picture should actually all be placed under `queryKnowledgeGraph`

The metadata on the trace call is also coming from my last generateObject SPAN. Not sure if this is an issue on the AI SDK telemetry implementation but it would be nice to have my functionId names in the `generateObject` and `streamText` spans. As well as the tree structure

## Example 2
![image](https://github.com/user-attachments/assets/ffc9acc9-3442-4a18-ba43-79b57aaae554)
These 3 `generateObject` calls happen in the same place in the code but in a `while` loop - the top most one is the last call that gets placed in the proper `queryKnowledgeGraph` parent where the bottom two should be placed.

In this example, the traceName is actually coming from the `functionId` set on these three `generateObject` calls.

Any help would be much appreciated as I want these to be in order before creating our evaluation set. I assume something about the timing of how parents are created is off.

### To reproduce

The initial `streamText` with the `queryKnowledgeGraph` tool call are here:
![image](https://github.com/user-attachments/assets/641a97bc-ad9a-4f36-b27b-92df6580a9ab)
All the subsequent `generateObject` and `streamText` calls all happen in how this tool is handled.

Happy to provide more code if needed.

### SDK and container versions

`ai: 3.4.33`
`langfuse-vercel: 3.29.1`

### Are you interested to contribute a fix for this bug?

Yes

**Comment by hassiebp** [comment]
Thanks a lot for raising this @leo-paz - we will take a look!

**Comment by hassiebp** [comment]
@leo-paz we have just released better support to group multiple Vercel AI SDK executions under one trace. Please upgrade langfuse-vercel [to latest](https://github.com/langfuse/langfuse-js/releases/tag/v3.30.4) and check out [our docs here for more detail](https://langfuse.com/docs/integrations/vercel-ai-sdk#group-multiple-executions-in-one-trace).

If you see further issues with respect to nesting hierarchies, these are likely on the level of the ai-sdk telemetry. Could you please provide a minimum repro example in that case?

**Comment by hassiebp** [comment]
Closing this. Please let us know if you continue to encounter this issue.
