### ISSUE TITLE
bug: Enable debug model for openai integration

### ISSUE THREAD

**Issue by gyliu513** [langfuse/langfuse#431]
### Describe the bug

The integration with langfuse and openai cannot enable langfuse debug model cause the langfuse was initiated hard-coded without debug parameter at https://github.com/langfuse/langfuse-python/blob/main/langfuse/openai.py#L41

### To reproduce

just run openai integration, no debug log

**Comment by maxdeichmann** [comment]
@gyliu513 it is now possible to set the debug mode via the environment variable `LANGFUSE_DEBUG`: https://github.com/langfuse/langfuse-python/pull/156/files

**Comment by gyliu513** [comment]
Thanks @maxdeichmann for the quick response!
