### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Subhraj07** [langfuse/langfuse#434]
### Describe the bug

Readme has incorrect docker-compose command

Current Command
```
# Clone repository
git clone https://github.com/langfuse/langfuse.git
cd langfuse

# Run server and database
docker compose up -d
```

### To reproduce

After following the Installation steps Anyone can reproduce the issue

### Additional information

docker-compose up -d could fix the issue

**Comment by marcklingen** [comment]
Since compose v2, `docker compose` is the recommended command-line syntax ([source](https://docs.docker.com/compose/migrate/#docker-compose-vs-docker-compose)).
