### ISSUE TITLE
bug: When updating to the latest SDK the application breaks on self-hosted langfuse

### ISSUE THREAD

**Issue by mhattingpete** [langfuse/langfuse#4354]
### Describe the bug

When we updating the SDK to the latest version I get the following error when running my application:

Error processing multimodal event: status_code: 404, body: <!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><meta name="next-head-count" content="2"/><link rel="preload" href="/_next/static/css/1156154c1d065d8c.css" as="style"/><link rel="stylesheet" href="/_next/static/css/1156154c1d065d8c.css" data-n-g=""/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills-42372ed130431b0a.js"></script><script src="/_next/static/chunks/webpack-fafe7122277f5772.js" defer=""></script><script src="/_next/static/chunks/framework-d2dcb18632b956b2.js" defer=""></script><script src="/_next/static/chunks/main-84cace7572b555e1.js" defer=""></script><script src="/_next/static/chunks/pages/_app-fa6683830cdf76d5.js" defer=""></script><script src="/_next/static/chunks/pages/_error-a6b891bf0b43bbee.js" defer=""></script><script src="/_next/static/6JpvmybkvxPF3AgZExXWv/_buildManifest.js" defer=""></script><script src="/_next/static/6JpvmybkvxPF3AgZExXWv/_ssgManifest.js" defer=""></script></head><body><div id="__next"><script>!function(){try{var d=document.documentElement,c=d.classList;c.remove('light','dark');var e=localStorage.getItem('theme');if('system'===e||(!e&&true)){var t='(prefers-color-scheme: dark)',m=window.matchMedia(t);if(m.media!==t||m.matches){d.style.colorScheme = 'dark';c.add('dark')}else{d.style.colorScheme = 'light';c.add('light')}}else if(e){c.add(e|| '')}if(e==='light'||e==='dark')d.style.colorScheme=e}catch(e){}}()</script><div class="flex min-h-full flex-1 flex-col justify-center py-12 sm:px-6 lg:px-8" data-sentry-component="Spinner" data-sentry-source-file="spinner.tsx"><div class="sm:mx-auto sm:w-full sm:max-w-md"><img src="/icon.svg" width="42" height="42" alt="Langfuse Icon" class="mx-auto motion-safe:animate-spin" data-sentry-component="LangfuseIcon" data-sentry-source-file="LangfuseLogo.tsx"/><h2 class="mt-5 text-center text-2xl font-bold leading-9 tracking-tight text-primary">Loading ...</h2></div></div></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"statusCode":404}},"page":"/_error","query":{},"buildId":"6JpvmybkvxPF3AgZExXWv","nextExport":true,"isFallback":false,"gip":true,"locale":"en","locales":["en"],"defaultLocale":"en","scriptLoader":[]}</script></body></html>

### To reproduce

Update the SDK to v. 2.54.1
Run a langchain application such as:
```python
from src.utils.models.load import model_gpt4o
from langchain_core.prompts.chat import (
    ChatPromptTemplate,
)
import os

from dotenv import load_dotenv
from langchain_core.runnables.config import RunnableConfig
from langfuse.callback import CallbackHandler


# Load env vars
load_dotenv()


version = os.environ.get("VERSION")
env = os.environ.get("ENV")
user_id = f"{os.environ.get('USER_ID')}_{env}_{version}"

langfuse_handler = CallbackHandler(
    secret_key=os.environ.get("LANGFUSE_SECRET_KEY"),
    public_key=os.environ.get("LANGFUSE_PUBLIC_KEY"),
    host=os.environ.get("LANGFUSE_HOST"),
    user_id=user_id,
    version=version,
    metadata={"env": env},
)

config = RunnableConfig(callbacks=[langfuse_handler])

prompt = ChatPromptTemplate.from_messages(
        [
            ("system", "You are an expert in information extraction by analyzing images."),
            ("user", [{"text": "{input}"}, {"image_url": {"url": "{image_data}"}}]),
        ]
    )

chain = prompt | model_gpt4o

chain.with_config(config).invoke({"input": "Extract the text from the image", "image_data": f"data:image/jpeg;base64,{base64_encoded_image}"})
```
### SDK and container versions

SDK: 2.54.1
Container: 2.89.0

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment]
Hi @mhattingpete - thanks for reporting this! We have added multimodal support in our latest SDK releases. If your Langfuse platform container is not up to date, the endpoints the SDK is trying to reach are not available. Please upgrade your Langfuse platform image.

In any case, this error should be logged only and not break your application. In the UI, you should see an error message for where the multimodal asset was placed in input / output / metadata. Is that correct?

**Comment by mhattingpete** [comment]
Hi @hassiebp. Thanks for getting back to me. I would have thought that a breaking change in the SDK would require a major version update.

**Comment by anonymousmaharaj** [comment]
When I send image to my LLM via Openwebui Pipeline I got error in langfuse filter
`text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).`
I use `v2.92.0` langfuse version

**Comment by alexyoung23jj** [comment]
@hassiebp which version of the langfuse platform container is needed to support multimodal logs? We are on v2, do we need to be on v3 for these endpoints to work?

**Comment by hassiebp** [comment]
@alexyoung23jj Yes, you'll need V3 to self host Langfuse with multimodal support

**Comment by alexyoung23jj** [comment]
@hassiebp Gotcha. Is there a way I can make a multimodal llm call and have the outputs be logged with langfuse without needing to do that upgrade? I don't actually need to see the pdf inputs in the langfuse instance but I'd like to have the output recorded.

**Comment by jnanasrijave3** [comment]
@hassiebp https://github.com/langfuse/langfuse/issues/5061 created new issue here.
