### ISSUE TITLE
bug(sdk-python): sdk should force a flush from the internal queue to the server at exit 

### ISSUE THREAD

**Issue by glesperance** [langfuse/langfuse#4392]
### Describe the bug

Python task-manager currently triggers `.join()` at process exit.[1]
This however doesn't wait for the requests to be all sent to langfuse and risks loosing data. 

### To reproduce

Create a bunch of request via threadpool, then exit the process. Some requests will be lost.

### SDK and container versions

[[package]]
name = "langfuse"
version = "2.54.1"

### Additional information

PR https://github.com/langfuse/langfuse-python/pull/1006 fixes this by calling shutdown instead of flush.

### Are you interested to contribute a fix for this bug?

Yes

**Comment by hassiebp** [comment]
Thanks a lot for your contribution @glesperance !
