### ISSUE TITLE
feat(ui): support rendering audio in vLLM multi-modal format

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#4406]
vLLM multi-modal format, please! 

Here is an example from the [vLLM docs](https://docs.vllm.ai/en/v0.6.0/getting_started/examples/openai_audio_api_client.html):
```
{
    "type": "audio_url",
    "audio_url": {
        "url": audio_url
    },
}
```

It would also be great to add support for .ogg and .oga audios.

_Originally posted by @recursingfeynman in https://github.com/langfuse/langfuse/discussions/3004#discussioncomment-11352979_

**Comment by hassiebp** [comment]
@recursingfeynman - thanks for bringing up vLLM multimodal support in Langfuse! This should be already supported if you pass your media asset as a base64 data URI - have you tried that? If the messages are traced in the trace / generation input the upload handling should be automatic.

From the vLLM docs: 

```python
# Use base64 encoded audio in the payload
def encode_audio_base64_from_url(audio_url: str) -> str:
    """Encode an audio retrieved from a remote url to base64 format."""

    with requests.get(audio_url) as response:
        response.raise_for_status()
        result = base64.b64encode(response.content).decode('utf-8')

    return result


audio_base64 = encode_audio_base64_from_url(audio_url=audio_url)
chat_completion_from_base64 = client.chat.completions.create(
    messages=[{
        "role":
        "user",
        "content": [
            {
                "type": "text",
                "text": "What's in this audio?"
            },
            {
                "type": "audio_url",
                "audio_url": {
                    # Any format supported by librosa is supported
                    "url": f"data:audio/ogg;base64,{audio_base64}"
                },
            },
        ],
    }],
    model=model,
    max_tokens=64,
)

result = chat_completion_from_base64.choices[0].message.content
print(f"Chat completion output:{result}")
```

**Comment by recursingfeynman** [comment]
> If the messages are traced in the trace / generation input the upload handling should be automatic.

Hi! Thank you for your feedback. Unfortunately, .ogg files currently not supported in self-hosted Langfuse (v2.92.0, SDK 2.55.0).
```
Error processing multimodal event: status_code: 400, body: {'message': 'Invalid request data', 'error': [{'received': 'audio/ogg', 'code': 'invalid_enum_value', 'options': ['image/png', 'image/jpeg', 'image/jpg', 'image/webp', 'audio/mpeg', 'audio/mp3', 'audio/wav', 'text/plain', 'application/pdf'], 'path': ['contentType'], 'message': 'Invalid content type. Only supporting image/png, image/jpeg, image/jpg, image/webp, audio/mpeg, audio/mp3, audio/wav, text/plain, application/pdf'}]}
```

With Langfuse Cloud i have some success with that, but it looks different from the [preview](https://langfuse.com/docs/tracing-features/multi-modality) demonstrated in documentation. ![image](https://github.com/user-attachments/assets/fe24b7c0-2598-4a0e-8ee4-e2dee91a91ca)

**Comment by recursingfeynman** [comment]
@hassiebp Thank you! I will keep an eye on the updates. Although support for audio URLs is not a crucial feature for me, it could be beneficial for others who find it important to handle such cases. As I can see, the format described in the issue description is not handled for audio URLs, although it works for images. Could you please clarify why the issue was closed as "not planned"?

**Comment by hassiebp** [comment]
@recursingfeynman For my understanding, to you mean rendering an audio player for audio URLs on a remote host or a base64 data URI passed as `audio_url` as described in the VLLM docs? The latter should be already supported (on cloud and on V3 preview for self hosters)

**Comment by mrdrprofuroboros** [comment]
@hassiebp 
+1 here, also using .ogg audios and would like to have them as audio previews rather than file attachments
