### ISSUE TITLE
bug: Empty output with Vercel AI SDK

### ISSUE THREAD

**Issue by dzshch** [langfuse/langfuse#4408]
### Describe the bug

The `LangfuseExporter` in the `langfuse-vercel` library does not correctly parse the output when the span contains the `ai.response.object` attribute. It currently only supports attributes like`ai.result.text`, `ai.toolCall.result`, etc., causing the output field to be null in traces.

Expected behavior: The output field should include the value of `ai.response.object` when available.
Actual behavior: The output field in the Langfuse trace is null, despite the `ai.response.object` attribute being populated with valid data.

### To reproduce

Setup LangfuseExporter from langfuse-vercel and use latest Vercel "ai" package

const sdk = new NodeSDK({
  traceExporter: new LangfuseExporter({
    secretKey: import.meta.env.MAIN_VITE_LANGFUSE_SECRET_KEY,
    publicKey: import.meta.env.MAIN_VITE_LANGFUSE_PUBLIC_KEY,
    baseUrl: import.meta.env.MAIN_VITE_LANGFUSE_HOST,
    debug: true
  }),
  instrumentations: [getNodeAutoInstrumentations()]
})

### Additional information

The issue occurs in the parseOutput method:
parseOutput(span) {
  const attributes = span.attributes;
  return "ai.result.text" in attributes
    ? attributes["ai.result.text"]
    : "ai.toolCall.result" in attributes
    ? attributes["ai.toolCall.result"]
    : "ai.result.object" in attributes
    ? attributes["ai.result.object"]
    : "ai.result.toolCalls" in attributes
    ? attributes["ai.result.toolCalls"]
    : undefined;
}

Changes in Vercel AI response:
https://github.com/vercel/ai/commit/dad775f494157502eb5c30a49c57b8f206f127dc

### Are you interested to contribute a fix for this bug?

Yes

**Comment by nikshepsvn** [comment]
+1

**Comment by nikshepsvn** [comment]
still broken for me on 3.31.0 (https://discord.com/channels/1111061815649124414/1111063198989307964/1311103926963277874)

https://us.cloud.langfuse.com/project/cm26ovono008hix0jpuljhdgx/traces/b0c758f75642555efc77bc3519b65d67?timestamp=2024-11-27T08%3A59%3A54.549Z

**Comment by hassiebp** [comment]
Hey Nikshep, could you please share the exact versions you are on? `generateObject` traces correctly for me on `ai@4.0.6`: 
https://cloud.langfuse.com/project/clsajidd7000011ohtpd9xm1w/traces/018243e4-1340-4868-b1af-5ac19efd3fcf
