### ISSUE TITLE
bug: Falsy output values get tracked as null when using Python SDK

### ISSUE THREAD

**Issue by tux-type** [langfuse/langfuse#4439]
### Describe the bug

Falsy output values (`False`, `0`, etc.) get tracked as `null` in the Langfuse interface. So, when a function returns a false value this is what appears under the span:

![image](https://github.com/user-attachments/assets/3b0d9d0a-64b7-4220-b7a7-74d602995b48)

### To reproduce

```Python
from langfuse.decorators import observe

@observe(capture_output=True)
def ask_question_false(question: str) -> bool:
    return False


@observe(capture_output=True)
def ask_question_0(question: str) -> int:
    return 0

ask_question_false("Is Lyon the capital of France?")
ask_question_0("Is Lyon the capital of France?")
```

### SDK and container versions

Using Python SDK: langfuse-python v2.54.1

### Are you interested to contribute a fix for this bug?

Yes

**Comment by marcklingen** [comment]
thanks for sharing!

**Comment by marcklingen** [comment]
@hassiebp please review https://github.com/langfuse/langfuse-python/pull/1010

**Comment by hassiebp** [comment]
Merged, thanks a lot for your contribution, @tux-type ! 🙏🏾
