### ISSUE TITLE
bug(langfuse-vercel): AI generated output/responses not getting traced to langfuse

### ISSUE THREAD

**Issue by jagzmz** [langfuse/langfuse#4443]
### Describe the bug

`vercel/ai` updated their telemetry event signatures in this PR https://github.com/vercel/ai/pull/2872/files.
![image](https://github.com/user-attachments/assets/4fc9617e-4d23-4fed-be54-7ea5f91b19c9)

As you can see above, it changed the names for events like, `ai.result.text`, `ai.result.toolCalls`.

This change affects the `langfuse-vercel` package https://npmjs.com/package/langfuse-vercel, which emits the tracing to the langfuse cloud.

## Proposed Solution

I want to propose the following fix to the `langfuse-vercel` package which will allow the functionality to work as expected. Unfortunately I wasn't able to locate this package under the langfuse Github Organisation in order to create a PR. 

```diff
diff --git a/node_modules/langfuse-vercel/lib/index.cjs.js b/node_modules/langfuse-vercel/lib/index.cjs.js
index 4e5f788..29b3d7f 100644
--- a/node_modules/langfuse-vercel/lib/index.cjs.js
+++ b/node_modules/langfuse-vercel/lib/index.cjs.js
@@ -192,7 +192,7 @@ class LangfuseExporter {
   }
   parseOutput(span) {
     const attributes = span.attributes;
-    return "ai.result.text" in attributes ? attributes["ai.result.text"] : "ai.toolCall.result" in attributes ? attributes["ai.toolCall.result"] : "ai.result.object" in attributes ? attributes["ai.result.object"] : "ai.result.toolCalls" in attributes ? attributes["ai.result.toolCalls"] : undefined;
+    return "ai.response.text" in attributes ? attributes["ai.response.text"] : "ai.toolCall.result" in attributes ? attributes["ai.toolCall.result"] : "ai.response.object" in attributes ? attributes["ai.response.object"] : "ai.response.toolCalls" in attributes ? attributes["ai.response.toolCalls"] : undefined;
   }
   parseTraceId(spans) {
     return spans.map(span => this.parseSpanMetadata(span)["langfuseTraceId"]).find(id => Boolean(id))?.toString();
diff --git a/node_modules/langfuse-vercel/lib/index.mjs b/node_modules/langfuse-vercel/lib/index.mjs
index 6e808de..3ea1b03 100644
--- a/node_modules/langfuse-vercel/lib/index.mjs
+++ b/node_modules/langfuse-vercel/lib/index.mjs
@@ -190,7 +190,7 @@ class LangfuseExporter {
   }
   parseOutput(span) {
     const attributes = span.attributes;
-    return "ai.result.text" in attributes ? attributes["ai.result.text"] : "ai.toolCall.result" in attributes ? attributes["ai.toolCall.result"] : "ai.result.object" in attributes ? attributes["ai.result.object"] : "ai.result.toolCalls" in attributes ? attributes["ai.result.toolCalls"] : undefined;
+    return "ai.response.text" in attributes ? attributes["ai.response.text"] : "ai.toolCall.result" in attributes ? attributes["ai.toolCall.result"] : "ai.response.object" in attributes ? attributes["ai.response.object"] : "ai.response.toolCalls" in attributes ? attributes["ai.response.toolCalls"] : undefined;
   }
   parseTraceId(spans) {
     return spans.map(span => this.parseSpanMetadata(span)["langfuseTraceId"]).find(id => Boolean(id))?.toString();
```

## Temporary Fix
You can use the above snippet and create a patch file to be used with `npx patch-package` to make it work as expected.

### To reproduce

1. Follow the telemetry setup steps from https://langfuse.com/docs/integrations/vercel-ai-sdk
2. Try any kind of generation using the vercel ai sdk with `experimental_telemetry.isEnabled: true`
3. Check the tracing on the Langfuse Cloud, the output should be `null`

### SDK and container versions

langfuse-vercel@3.30.4

### Are you interested to contribute a fix for this bug?

Yes

**Comment by marcklingen** [comment]
thanks for sharing this! please find the implementation here: https://github.com/langfuse/langfuse-js/blob/main/langfuse-vercel/src/LangfuseExporter.ts

Are you interested in contributing this change via a PR?

**Comment by jagzmz** [comment]
Yes @marcklingen , will submit a PR for this

**Comment by marcklingen** [comment]
thanks, we will review asap

**Comment by jagzmz** [comment]
@marcklingen @hassiebp Here's the PR: https://github.com/langfuse/langfuse-js/pull/470

**Comment by hassiebp** [comment]
Thanks a lot for you contribution @jagzmz ! We applied your diff and shipped it in [our latest release](https://github.com/langfuse/langfuse-js/releases/tag/v3.31.0)! 🙏🏾
