### ISSUE TITLE
feat(python-sdk): disabled=true flag to disable Langfuse tracking in some environments

### ISSUE THREAD

**Issue by Rasmnev** [langfuse/langfuse#448]
### Describe the feature you'd like to request

I'm using langfuse tracing for my development but I want to disable the tracing of an llm based application, but for production I will not be using the tracing . I would like to keep the same code for the requests to openai regardless of having the keys setup or not.

### Describe the solution you'd like to see

When doing the import 
```python
from langfuse.openai import openai
```
instead of throwing an error maybe it could just send a warning that tracing won't work and skip the requests to langufuse.

### Additional information

I've tried a conditional import like this 

```python
try:
    from langfuse.openai import openai
except ValueError:
    logging.info("Could not import langfuse.openai, using regular openai.")
    import openai
```

but this breaks my code because when I call completion there are unexpected arguments name and trace_id
```python
openai.ChatCompletion.create(
                engine=model,
                messages=messages,
                max_tokens=maxTokens,
                temperature=temperature,
                name=name,
                trace_id=trace,
            )
```

I also tried creating dummy keys before importing and that will work, but will polut the logs with lots of Unauthorized errors.

### Contribute

- [X] Yes, I can implement this and raise a PR

**Comment by maxdeichmann** [comment]
@Rasmnev could you share why you do not want to use langfuse in production?

**Comment by Rasmnev** [comment]
@maxdeichmann I don't have control over that. I'm helping a client with an application that uses openai api and using Langfuse locally (self hosted) to help me in the development.
To use it in production would require authorization from the client and guarantee data security which I have no bandwidth to do at this time. In the future I may  push to use it in production as well, which is why I would like to have everything setup already

**Comment by maxdeichmann** [comment]
@Rasmnev what i could envision is having a property for the langfuse sdk called 'disabled'. When set to true, it wont do any network requests. Is this something you could look into? We are currently very busy and not sure when we will get to this.

**Comment by Rasmnev** [comment]
Sure I can work on it in the next few weeks.

**Comment by maxdeichmann** [comment]
> Sure I can work on it in the next few weeks.

Awesome. I think it could work the following way:
- Lanfguse object takes an additional parameter called `debug`
- This parameter is passed on to `TaskManager`
- In `TaskManager`, there is a function called `add_task`. Within that, only add the task to the queue if debug is False, otherwise log a message alongside the event.

**Comment by Rasmnev** [comment]
Shouldn't it be a different parameter? I think it is better to have a new parameter to control this behaviour and let debug only control logging level. Besides debug is passed to `TaskManager` but not stored, it only changes the log level.
I was thinking of creating a new parameter `LANGFUSE_TRACING_ENABLED` that would control that behaviour. If it is set to False not tasks are added and a debug message is logged.

**Comment by maxdeichmann** [comment]
> Shouldn't it be a different parameter? I think it is better to have a new parameter to control this behaviour and let debug only control logging level. Besides debug is passed to `TaskManager` but not stored, it only changes the log level. I was thinking of creating a new parameter `LANGFUSE_TRACING_ENABLED` that would control that behaviour. If it is set to False not tasks are added and a debug message is logged.

Yes, you are right. tracing_enabled sounds good and LANGFUSE_TRACING_ENABLED can be set via an env variable.

**Comment by marcklingen** [comment]
Suggestion
- disabled flag on core Langfuse constructor: `Langfuse(disabled=True)`
- alternatively, configurable via `LANGFUSE_DISABLED` environment variable
- for openai integration, alternatively configurable via `openai.langfuse_disabled=True` option
- tests required for this as it touches core functionality

Happy to support PRs on this @Rasmnev!

**Comment by marcklingen** [comment]
I'd suggest to just fix this via https://github.com/langfuse/langfuse/issues/448 (if no keys are set, Langfuse is disabled by default)
