### ISSUE TITLE
feat: Improve observation tree UI

### ISSUE THREAD

**Issue by gyliu513** [langfuse/langfuse#451]
### Describe the feature you'd like to request

there is no color to help customer identify if the trace is good or not.

### Describe the solution you'd like to see

Especially for some error traces, it is better to use red to highlight that.

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by maxdeichmann** [comment]
@gyliu513 thanks for raising this. We already thought about UI improvements last week within the team. I will add this to the list.

**Comment by gyliu513** [comment]
Thanks @maxdeichmann !

**Comment by Steenbuck** [comment]
Hey, 
another Idea to improve readability of the trace tree would to add some colours and to increase the intendation size (if there is enough space of course).
Maybe sth. like:
![langfuse_trace_UI](https://github.com/langfuse/langfuse/assets/46788032/931382fe-2aec-4302-aea6-c79beed14190)

**Comment by marcklingen** [comment]
Agree that the tree representation could be improved with e.g. colors.

Followed @Steenbuck suggestion as a quick improvement: #489

**Comment by marcklingen** [comment]
@gyliu513 if you use the `status` flag, you'll see colored warnings and errors

Example
![Screenshot 2023-11-15 at 15 27 25@2x](https://github.com/langfuse/langfuse/assets/2834609/a856f3e8-0b02-4b9d-b8c4-3055a3121018)

Anything else you'd suggest to color to make the trace more useful?

**Comment by gyliu513** [comment]
<img width="1259" alt="Screenshot 2023-11-15 at 11 42 01 AM" src="https://github.com/langfuse/langfuse/assets/4461983/23038a57-33bc-4ebf-8aa2-1c5e202b34b4">

<img width="1353" alt="Screenshot 2023-11-15 at 11 43 58 AM" src="https://github.com/langfuse/langfuse/assets/4461983/e1cc2838-2f4a-4542-8977-f295a3cb8863">

@marcklingen looks much better, what do you think the above? I get it from llmonitor.com and https://smith.langchain.com/ :)

**Comment by marcklingen** [comment]
Agree, prioritizing UI right now, expect improvements on this!

**Comment by marcklingen** [comment]
@matthieudelaro suggested fold/unfold in #488
