### ISSUE TITLE
bug: OpenAI gpt-4o-2024-11-20 token pricing is missing

### ISSUE THREAD

**Issue by pwnywiz** [langfuse/langfuse#4523]
### Describe the bug

Looks like the pricing of the latest gpt-4o-2024-11-20 model of OpenAI is missing, resulting in 0.0$ cost usage in the UI.

### To reproduce

Run any generation by using OpenAI's "gpt-4o-2024-11-20" model.

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment]
Thanks for raising this @pwnywiz - we have a [WIP PR](https://github.com/langfuse/langfuse/pull/4536) to add this model price (and other general improvements to model cost tracking) that will be merged and released soon/
