### ISSUE TITLE
feat: OWNER of project can reassign ownership

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#457]
### Describe the feature you'd like to request

User with owner role of project can make another user owner of a project

### Describe the solution you'd like to see

Transfer ownership dialog in project settings (include in danger zone)
- Only accessible by current owner
- Warn user that this will cause themselves to lose ownership

### Additional information

- Only one person can be owner
- It needs to be transactional, one user needs to be owner even if the tx fails
- Only show the dialog to the current owner, use `useHasAccess()` hook
- In the TRPC route, make sure to check if user is owner of the project with `throwIfNoAccess`

### Contribute

- [ ] Yes, I can implement this and raise a PR

<sub>[LFC-218](https://linear.app/langfuse/issue/LFC-218/feat-owner-of-project-can-reassign-ownership)</sub>

**Comment by Bl4ckEnd** [comment]
Also as a user I would expect that admins can also change the roles of others (except owner) and that you can also change an admin to a member and vice versa as owner.
Thanks for creating the issue!

**Comment by 18feb06** [comment]
I want to try this

**Comment by DIWAKARKASHYAP** [comment]
@18feb06 I apologize; I'm working on this, and regrettably, I forgot to mention it here.
