### ISSUE TITLE
bug: OpenAI python wrapper: chat completion parameter `metadata` collides with langfuse wrapper parameter

### ISSUE THREAD

**Issue by parmsib** [langfuse/langfuse#4574]
### Describe the bug

We are looking to make use of the OpenAI [Model Distillation](https://platform.openai.com/docs/guides/distillation) feature.

This entails using the Chat Completions's [`store`](https://platform.openai.com/docs/api-reference/chat/create#chat-create-store) field, which makes OpenAI store the resulting input/output pairs as training data for future fine-tuning.
When using the `store` field, an __optional [`metadata`](https://platform.openai.com/docs/api-reference/chat/create#chat-create-metadata) field is used to pass information about the completion__ to be stored alongside the data pair.

__Langfuse's Python OpenAI client library's wrapper already uses the `metadata` parameter for its own purposes__, meaning the metadata never reaches OpenAI. This makes it so stored completions don't get their metadata, and thus can't be filtered or organized for fine-tuning.

We can see that the metadata gets added to the trace in Langfuse but it does not get added to the OpenAI Chat Completion, which can be seen for your account at https://platform.openai.com/chat-completions

### To reproduce

This sends the metadata to OpenAI.
(does not use langfuse)
```
from openai import OpenAI

client = OpenAI()
response = client.chat.completions.create(
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "What is human life expectancy in the United States?"},
    ],
    model="gpt-4o-mini",
    metadata={"test": "test"},
    store=True,
)
```

This does not send the metadata to OpenAI (but does send it to langfuse)
(does use langfuse)
```
from langfuse.openai import OpenAI

client = OpenAI()

response = client.chat.completions.create(
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "What is human life expectancy in the United States?"},
    ],
    model="gpt-4o-mini",
    metadata={"test": "test"},
    store=True,
)
```

### SDK and container versions

python package `langfuse` is at version `v2.55.0`
`openai` is at version `v1.25.2`.

We do not use self-hosting.

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment]
Thanks for raising this, @parmsib ! Linked a PR to pass `metadata` to OpenAI if model distillation feature is used
