### ISSUE TITLE
bug: Python SDK calls to get_prompt are not using a default timeout and connections aren't closed.

### ISSUE THREAD

**Issue by kenny-phoenixteam** [langfuse/langfuse#4579]
### Describe the bug

Calling get_prompt creates a TCP connection that doesn't get closed. 

### To reproduce

Initialize Langfuse client with just public key, secret key, host. (default httpx client and timeout - actually becomes 0 timeout).
Start calling get_prompt in a loop and look at the the tcp connections rise in a CLOSE-WAIT state.

Sample code:
```
def __init__(self):
        # Initialize Langfuse client with environment variables
        self.langfuse_client = self._initialize_langfuse_client()

    @staticmethod
    def _initialize_langfuse_client():
        LANGFUSE_SECRET_KEY = os.getenv("LANGFUSE_SECRET_KEY")
        LANGFUSE_PUBLIC_KEY = os.getenv("LANGFUSE_PUBLIC_KEY")
        LANGFUSE_HOST = os.getenv("LANGFUSE_HOST")

        if not all([LANGFUSE_SECRET_KEY, LANGFUSE_PUBLIC_KEY, LANGFUSE_HOST]):
            raise EnvironmentError("Missing required Langfuse environment variables.")

        return Langfuse(
            public_key=LANGFUSE_PUBLIC_KEY,
            secret_key=LANGFUSE_SECRET_KEY,
            host=LANGFUSE_HOST,
        )

    def fetch_langfuse_prompt(self, prompt_name: str, **variables) -> tuple:
        """
        Fetches the specified prompt content from Langfuse API using the Langfuse SDK.

        Args:
            prompt_name (str): The name of the prompt to retrieve.

        Returns:
            tuple: A tuple containing the raw prompt object and the compiled prompt content.

        Raises:
            ValueError: If the prompt content is empty or not found.
            LangfuseError: If there is an issue with the Langfuse SDK call.
        """
        try:
            prompt = self.langfuse_client.get_prompt(prompt_name, label="latest")
        except Exception as e:
            self._log.error("Error retrieving prompt '%s': %s", prompt_name, e)
            raise Exception(f"Failed to retrieve prompt '{prompt_name}': {e}")

        if prompt:
            try:
                compiled_prompt = prompt.compile(**variables)
                return prompt, compiled_prompt
            except KeyError as e:
                raise ValueError(f"Missing variable for prompt '{prompt_name}': {e}")
        else:
            raise ValueError(f"Prompt '{prompt_name}' content is empty or not found.")
```

### SDK and container versions

Python 2.55.0

### Additional information

The timeout parameter gets mishandled in a few places. The docstrings also don't match the code. Ultimately, if a timeout is not passed in, the default becomes None. 
Although response.json() is called, it doesn't seem to close the connection from the client.
On a related note, the cache ttl doesn't default either.

### Are you interested to contribute a fix for this bug?

Yes

**Comment by hassiebp** [comment]
@kenny-phoenixteam Thanks for raising this! The probable root cause is that you are re-instantiating a Langfuse client on each prompt request rather than reusing an existing client. Prompt caching is bound to a client instance and on each client init a new HTTPX client that is in turn trying to negotiate a new TCP connection for each prompt fetch.

Could you please try refactoring your code such that the Langfuse client instance is reused? 

> look at the the tcp connections rise in a CLOSE-WAIT state.
Could you please share how you tracked this? Connections should not remain in CLOSE WAIT state irrespective of the above.

**Comment by kenny-phoenixteam** [comment]
I refactored to reuse the Langfuse client instance and confirmed the connection count remains steady. I'm not a fan of singletons in almost all scenarios, but I understand your choice. How will we know if the Langfuse client is health/unhealthy? If the client in unhealthy, what steps do we take to ensure proper shutdown so we can replace the instance?

Not sure that it matters because you've implied that Langfuse client should be a singleton, but here are the details for the high number of CLOSE-WAIT state tcp connections:

> > look at the the tcp connections rise in a CLOSE-WAIT state.
> 
> Could you please share how you tracked this? Connections should not remain in CLOSE WAIT state irrespective of the above.

cat /proc/net/tcp

I believe the close-wait happens because the timeout ultimately becomes None if both the default httpx client and timeout are used, and the Langfuse client isn't designed to cleanup connections when used on a per-instance basis, hence sockets aren't cleaned up. Below are the details for how we end up with indefinite timeout and close-wait sockets:


Timeout doesn't get passed into creation of FernLangfuse, but the httpx client (default, with 20 second timeout) does:

within Langfuse init:
```
 self.httpx_client = httpx_client or httpx.Client(timeout=timeout)

self.client = FernLangfuse(
            base_url=self.base_url,
            username=public_key,
            password=secret_key,
            x_langfuse_sdk_name="python",
            x_langfuse_sdk_version=version,
            x_langfuse_public_key=public_key,
            httpx_client=self.httpx_client,
        )
 ```
 
 Within FernLangfuse init:
 ```       
#timeout : typing.Optional[float]
#        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is # #used, in which case this default is not enforced.        

 _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else None
        )
```

Note that _default_timeout becomes None.

This is where things become problematic, still in FernLangfuse init:
```
self._client_wrapper = SyncClientWrapper(
            base_url=base_url,
            x_langfuse_sdk_name=x_langfuse_sdk_name,
            x_langfuse_sdk_version=x_langfuse_sdk_version,
            x_langfuse_public_key=x_langfuse_public_key,
            username=username,
            password=password,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(
                timeout=_defaulted_timeout, follow_redirects=follow_redirects
            )
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
        )
```
httpx_client is fine, it was passed in.
timeout in SyncClientWrapper is now None, because _default_timeout is None.
SyncClientWrapper has an httpx client with a 20 second timeout, and a timeout variable of None.

SyncClientWrapper init:
```
 super().__init__(
            x_langfuse_sdk_name=x_langfuse_sdk_name,
            x_langfuse_sdk_version=x_langfuse_sdk_version,
            x_langfuse_public_key=x_langfuse_public_key,
            username=username,
            password=password,
            base_url=base_url,
            timeout=timeout, #None
        )
        self.httpx_client = HttpClient(
            httpx_client=httpx_client,
            base_headers=self.get_headers(),
            base_timeout=self.get_timeout(), #None
            base_url=self.get_base_url(),
        )
```

Let's jump over to the get_prompt method, where the default fetch_timeout_seconds is None, and we don't pass in:

```
 return self._fetch_prompt_and_update_cache(
                    name,
                    version=version,
                    label=label,
                    ttl_seconds=cache_ttl_seconds,
                    max_retries=bounded_max_retries,
                    fetch_timeout_seconds=fetch_timeout_seconds, #None
                )

def fetch_prompts():
                return self.client.prompts.get(
                    self._url_encode(name),
                    version=version,
                    label=label,
                    request_options={
                        "timeout_in_seconds": fetch_timeout_seconds,
                    }
                    if fetch_timeout_seconds is not None
                    else None,
                )

            prompt_response = fetch_prompts()
```
Note that request_options is None at this point.

self.client.prompts is a simple wrapper for SyncClientWrapper, which has a default httpx client with default timeout of 20 seconds. SyncClientWrapper's base, BaseClientWrapper, has a timeout of None.

Within PromptsClient.get():
```
_response = self._client_wrapper.httpx_client.request(
            f"api/public/v2/prompts/{jsonable_encoder(prompt_name)}",
            method="GET",
            params={"version": version, "label": label},
            request_options=request_options, #This is None
        )
``` 
Within HttpClient.request, with request_options of None. timeout becomes None:
```
 timeout = (
            request_options.get("timeout_in_seconds")
            if request_options is not None
            and request_options.get("timeout_in_seconds") is not None
            else self.base_timeout
        )
```
request_options is None and self.base_timeout is None.  base_timeout got set to None when we created SyncClientWrapper.

Finally the call to the python httpx client. Note that timeout is passed in, which is None:

```
response = self.httpx_client.request(
            method=method,
            url=urllib.parse.urljoin(f"{base_url}/", path),
            headers=jsonable_encoder(
                remove_none_from_dict(
                    {
                        **self.base_headers,
                        **(headers if headers is not None else {}),
                        **(
                            request_options.get("additional_headers", {}) or {}
                            if request_options is not None
                            else {}
                        ),
                    }
                )
            ),
            params=encode_query(
                jsonable_encoder(
                    remove_none_from_dict(
                        remove_omit_from_dict(
                            {
                                **(params if params is not None else {}),
                                **(
                                    request_options.get(
                                        "additional_query_parameters", {}
                                    )
                                    or {}
                                    if request_options is not None
                                    else {}
                                ),
                            },
                            omit,
                        )
                    )
                )
            ),
            json=json_body,
            data=data_body,
            content=content,
            files=convert_file_dict_to_httpx_tuples(remove_none_from_dict(files))
            if files is not None
            else None,
            timeout=timeout, #None
        )
```

Timeout of None with httpx means disable timeouts. Indefinite.

I'm assuming at this point the Langfuse client was getting garbage collected and so the underlying socket remains open.

Hope this was all accurate and that I didn't misinterpret anything. Even using the same singleton instance, the timeout is None.

Best fix IMO is adding timeout to init of FernLangfuse. Multiple options though.:

self.client = FernLangfuse(
            base_url=self.base_url,
            username=public_key,
            password=secret_key,
            x_langfuse_sdk_name="python",
            x_langfuse_sdk_version=version,
            x_langfuse_public_key=public_key,
            httpx_client=self.httpx_client,
            timeout = timeout #NEW LINE
        )

**Comment by hassiebp** [comment]
Hi Kenny - first of all, thank you for the excellent write up and the detailed debugging process you conducted! 🙏🏾

You are right that the timeout on Langfuse client init should be passed down correctly to all clients. I have opened a PR with your suggested fix. 

> I'm not a fan of singletons in almost all scenarios, but I understand your choice. How will we know if the Langfuse client is healthy/unhealthy? If the client in unhealthy, what steps do we take to ensure proper shutdown so we can replace the instance?

The Langfuse client is designed to be self-healing when it enters error states (exceptions thrown in event handling, failed network requests etc.). If you encounter unrecoverable exceptions, you may attempt a clean shutdown by calling `client.shutdown()` and create a new instance. If that happens though, please raise a Github issue here as that should not happen. 

Furthermore, we have plans to drop the singleton requirement on the Langfuse client and refactor the underlying TaskManager (that manages the background threads) and the HTTPX client (that inherently manages TCP connection reuse as we discussed here) to be singletons such that all singleton management will be abstracted for the dev using our SDK. No timeline on this yet though.
