### ISSUE TITLE
bug: missing error log and early exit if CLICKHOUSE_ env is missing in 3.0.0, currently cause 500 error during upgrade

### ISSUE THREAD

**Issue by azdolinski** [langfuse/langfuse#4583]
### Describe the bug

[+] Running 1/0
 ✔ Container langfuse  Created                                                                                                         0.0s
Attaching to langfuse
langfuse  | Script executed successfully.
langfuse  | Prisma schema loaded from packages/shared/prisma/schema.prisma
langfuse  | Datasource "db": PostgreSQL database "<hidden>", schema "public" at "<hidden>"
langfuse  |
langfuse  | 271 migrations found in prisma/migrations
langfuse  |
langfuse  |
langfuse  | No pending migrations to apply.
langfuse  | Info: CLICKHOUSE_URL not configured, skipping migration.
langfuse  |   ▲ Next.js 14.2.15
langfuse  |   - Local:        http://langfuse:3000
langfuse  |   - Network:      http://172.18.0.2:3000
langfuse  |
langfuse  |  ✓ Starting...
langfuse  | Running init scripts...
langfuse  | ❌ Invalid environment variables: {
langfuse  |   CLICKHOUSE_URL: [ 'Required' ],
langfuse  |   CLICKHOUSE_USER: [ 'Required' ],
langfuse  |   CLICKHOUSE_PASSWORD: [ 'Required' ]
langfuse  | }
**langfuse  | Failed to prepare server Error: An error occurred while loading instrumentation hook: Invalid environment variables
langfuse  |     at h (/app/web/.next/server/chunks/8863.js:1:35062)
langfuse  |     at /app/web/.next/server/chunks/8863.js:1:35242
langfuse  |     at a (/app/web/.next/server/chunks/8863.js:1:35550)
langfuse  |     at 680846 (/app/web/.next/server/chunks/846.js:1:477)
langfuse  |     at t (/app/web/.next/server/webpack-runtime.js:1:485)
langfuse  |     at 162168 (/app/web/.next/server/chunks/2168.js:1:167602)
langfuse  |     at Function.t (/app/web/.next/server/webpack-runtime.js:1:485)
langfuse  |     at async Module.s (/app/web/.next/server/instrumentation.js:1:2681)
langfuse  |     at async NextNodeServer.prepareImpl (/app/node_modules/.pnpm/next@14.2.15_@babel+core@7.24.3_@opentelemetry+api@1.9.0_@playwright+test@1.47.2_babel-plugin_kbpuz46h3a5badhs6fmvawrksq/node_modules/next/dist/server/next-server.js:473:17)**
langfuse  |  ✓ Ready in 541ms
langfuse  | ❌ Invalid environment variables: {
langfuse  |   CLICKHOUSE_URL: [ 'Required' ],
langfuse  |   CLICKHOUSE_USER: [ 'Required' ],
langfuse  |   CLICKHOUSE_PASSWORD: [ 'Required' ]
langfuse  | }

### To reproduce

Upgrade from v2.92.0  -> 3.0.0-rc.3

services:
  langfuse:
    hostname: langfuse
    container_name: langfuse
    restart: always
-   image: langfuse/langfuse:latest              # [current 2024-12-04] latest: Langfuse v2.92.0 OSS
+  image: langfuse/langfuse:3.0.0-rc.3

### SDK and container versions

v2.92.0 OSS

### Additional information

    environment:
      #DATABASE_URL: postgresql://<hidden>:<hidden>@<hidden>:5432/<hidden>
      DATABASE_HOST: <hidden>
      DATABASE_USERNAME: <hidden>
      DATABASE_PASSWORD: <hidden>
      DATABASE_NAME: langfuse
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: <hidden>
      SALT: <hidden>
      ENCRYPTION_KEY: <hidden>
    # NEXTAUTH_SECRET> openssl rand -base64 32
    # SALT> openssl rand -base64 32
    # ENCRYPTION_KEY> openssl rand -hex 32

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Hi @azdolinski

This is expected as Langfuse v3 introduces Clickhouse as a more scalable data store for tracing data.

Learn more about this here: https://langfuse.com/docs/deployment/v3/overview

We will publish a detailed upgrade video in addition to this [guide](https://langfuse.com/docs/deployment/v3/migrate-v2-to-v3) to help upgrading from v2 to v3.

Happy to help in case you have any questions or feedback!

**Comment by azdolinski** [comment]
@marcklingen 
I wanted to bring to your attention that there's an uncaught error exception in the code. 
Please consider addressing this by adding an exception handler, which could include a reference to the relevant documentation or an informative message. 
Many users will likely encounter the same issue when version 3 becomes GA, so there's still time to address it. 
Introducing a new element to the whole setup is not obvious.

**Comment by marcklingen** [comment]
Fair point, we should throw instantly in the entrypoint here with a better error message and exit the process to make sure that data on v2 is not corrupted. Thanks for the hint!

**Comment by marcklingen** [comment]
@Steffen911 do you agree?

**Comment by Steffen911** [comment]
@azdolinski Could you clarify what you would expect in this case? The error message clearly state which environment variables are missing a value and all of them are documented in our [V3 self-hosting guide](https://langfuse.com/docs/deployment/v3/overview#environment-variables).

Our [migration guide](https://langfuse.com/docs/deployment/v3/migrate-v2-to-v3#2-start-new-langfuse-containers) for v2 to v3 also states that environment variables for new storage components must be configured before attempting an upgrade.

Regarding data consistency @marcklingen: If the environment variables are missing, we're not performing any additional action, but exit early within the code as soon as we try to load the web server or worker. Do you see any situation where a data corruption might happen?

**Comment by marcklingen** [comment]
The Postgres migrations here are applied before checking for the clickhouse connection if I understand the logs correctly.

**Comment by Steffen911** [comment]
Correct, but unless we add `DELETE` statements into migrations this should not cause any issues. I don't see a situation in our current setup and codebase where this could cause problems.

**Comment by azdolinski** [comment]
@Steffen911  @marcklingen 

It is great that you're displaying messages indicating the required new environments. 

However (**problem is that docker is still running**):
If `CLICKHOUSE_URL`, `CLICKHOUSE_USER`, and `CLICKHOUSE_PASSWORD` are undefined (assume that can be only during upgrade or fresh installation), please display a message such as:  
_"From version V3, Langfuse requires integration with ClickHouse. For more details, please refer to our documentation and migration v2-v3 guide: http://our.docs..."_. If the system is running with logging set to the debug level, then you should display a code trace.

It is essential to exit with a status of >=`1` (-> stop docker) because these parameters/env are mandatory for the proper functioning of the system. Keeping the system running and returning a 500 error from the web service perspective does not make sense.

Many industry guidelines suggest failing fast and visibly when required dependencies or configurations are absent. This approach aligns with the **"fail fast" principle**, providing some advantages from a technical perspective:
- the frontend load balancer will clearly identify the service as down
- if any monitoring is in place, it will surely trigger an alarm
- during the testing and development phase within a CI/CD process, it will be easier to identify and address the problem
- although not technical, it is important to increase user trust by ensuring the system does not operate partially or with incorrect configurations, and it provides administrators with a clear notice when they attempt to bring the service up again (as it could be coused ie. after `watchtower` auto upgrade process in the night).

PS. Keep running and displaying a code trace to the user can cause frustration and a desire 💡to contact support (which probably you dont whant as it cost time and💰). A better option is a brief note and a referral to the documentation (user click link.. search error message/code-id.. and got answer). 
Trace is for developers… efforts should be made to ensure that the trace is only visible when debug level mode is enabled. Any error or warning generating this type of output in operational mode should be addressed by developers and hidden by an exception (my opinion - you may disagree… and I'll understand your objection 😉- I know it is difficulte and time consuming).

**Comment by Steffen911** [comment]
Hi @azdolinski ,
Feedback heard, thank you! We're adding an early check via https://github.com/langfuse/langfuse/pull/4595 that clearly indicates that required variables are missing (In that case with a focus on CLICKHOUSE_URL as a proxy for the migration) and refer to the documentation. If you feel that this wouldn't have achieved the desired effect during your upgrade, please let me know 🙂

**Comment by azdolinski** [comment]
@Steffen911 

Perfect.

P.S. Just a small idea/suggestion from my experience: 
It's often more effective to refer users to the main page, domain, or a search engine rather than a specific documentation page. Documentation systems can change over time, and migrating to another platform might lead to broken links. It's better to direct users to a reliable search page rather than risk a 404 message, which could add to their frustration (especially if they're already frustrated by a system issue). 

Additionally, this approach educates users to visit that location for troubleshooting and encourages them to "Read The **Full** Manual." 😉

Thank you!

**Comment by marcklingen** [comment]
Thanks for the hint! We currently take the path of not breaking documentation links by always backfilling redirects when moving docs pages<br><br>example (next.config.mjs): [https://github.com/langfuse/langfuse-docs/commit/43604a6a0f49e4e0247721d9fb9914b39ca99ba1#diff-18c049b08c4a0f5ab451c598aeb2c4848bb9d7877b51ca3e5effb94a225814d2](https://github.com/langfuse/langfuse-docs/commit/43604a6a0f49e4e0247721d9fb9914b39ca99ba1#diff-18c049b08c4a0f5ab451c598aeb2c4848bb9d7877b51ca3e5effb94a225814d2)
