### ISSUE TITLE
bug: Missing cached token pricing column from models

### ISSUE THREAD

**Issue by pwnywiz** [langfuse/langfuse#4590]
### Describe the bug

Models like GPT-4o have introduced a new -reduced- pricing based on cached tokens.
That kind of information is available in their metadata response, specifically in `cache_read`:

```
usage_metadata: {
    input_tokens: 62394
    total_tokens: 62608
    output_tokens: 214
    input_token_details: {
    audio: 0
    cache_read: 60024
  }
  output_token_details: {
    audio: 0
    reasoning: 0
  }
}
```

Each trace should take into account the number of tokens cached and use the cached pricing for the proper calculation of the total cost.

### To reproduce

Use OpenAI GPT-4o model with static prompts over 1024 token size length and compare the price based on their pricing and the actual output of Langfuse. Langfuse will output the pricing based on the fixed full token price.

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment]
Thanks for raising this, @pwnywiz - we have open PRs to support this. I have linked the relevant Python SDK related one here for you to track progress on this.

**Comment by kesh-model-ml** [comment]
Just wondering if you could share a bit more about how Langfuse calculates cached vs. uncached token counts and costs?

Source of truth: Are the n_cached_context_tokens_total / n_context_tokens_total values pulled directly from OpenAI’s Usage API? Or does Langfuse infer cache hits internally (e.g. by matching repeated prompts)?
Price mapping: When estimating costs, do you apply a fixed 50% discount on input tokens for cached hits? Or are you using the cached token counts that OpenAI already returns (which include partial cache hits), and mapping those back to generations?
We’re trying to understand the underlying logic so we can trust the accuracy of the token & cost estimates across traces.

**Comment by hassiebp** [comment]
[https://github.com/orgs/langfuse/discussions/4417#discussioncomment-13001886](https://github.com/orgs/langfuse/discussions/4417#discussioncomment-13001886)

**Comment by kesh-model-ml** [comment]
Is it possible to have the breakdown of the costs in the UI and db as well as it will be good for us to reconcile this with the costs we see in our OpenAI usage dash?

ideal breakdown -> input-uncached / input-cached/ output

currently I only see input /output cost/token breakdown. We're using Langfuse version - v3.53.0

<img width="259" alt="Image" src="https://github.com/user-attachments/assets/83f97625-8367-449d-af5b-430fefc5e489" />
<img width="281" alt="Image" src="https://github.com/user-attachments/assets/b5a14ac1-df13-4c96-b765-5955ac08ca09" />
