### ISSUE TITLE
bug: clickhouse setup in docker-compse broken?

### ISSUE THREAD

**Issue by foragerr** [langfuse/langfuse#4600]
### Describe the bug

I'm attempting to `docker compose up` from the [head of main](https://github.com/langfuse/langfuse/blob/83c01bb4446835407b806dc101bdee53bdff7da9/docker-compose.yml) and there are a few different issues.

1. langfuse-web service is missing clickhouse environment variables, so it tries to connect to localhost rather than the clickhouse container
2. On fixing that, langfuse-web connects to clickhouse and fails when it tries to run migrations. First clickhouse complains that it cant find zookeeper.

```
langfuse-web-1     | error: failed to open database, "clickhouse://clickhouse:9000?username=clickhouse&password=clickhouse&database=default&x-multi-statement=true&x-cluster-name=default&x-migrations-table-engine=ReplicatedMergeTree": code: 139, message: There is no Zookeeper configuration in server config in line 0:
langfuse-web-1     | 			CREATE TABLE schema_migrations ON CLUSTER default (
langfuse-web-1     | 				version    Int64,
langfuse-web-1     | 				dirty      UInt8,
langfuse-web-1     | 				sequence   UInt64
langfuse-web-1     | 			) Engine=ReplicatedMergeTree ORDER BY sequence
langfuse-web-1     | Applying clickhouse migrations failed. This is mostly caused by the database being unavailable.
```

I enabled Clickhouse Keeper following this [post](https://www.markhneedham.com/blog/2023/12/13/clickhouse-s3queue-no-zookeeper-configuration/), when then leads to the next error.

3. Something about macros not being supported?

```
langfuse-web-1     | error: failed to open database, "clickhouse://clickhouse:9000?username=clickhouse&password=clickhouse&database=default&x-multi-statement=true&x-cluster-name=default&x-migrations-table-engine=ReplicatedMergeTree": code: 139, message: There was an error on [localhost:9000]: Code: 139. DB::Exception: No macro 'shard' in config while processing substitutions in '/clickhouse/tables/{uuid}/{shard}' at '27' or macro is not supported here. (NO_ELEMENTS_IN_CONFIG) (version 24.11.1.2557 (official build)) in line 0:
langfuse-web-1     | 			CREATE TABLE schema_migrations ON CLUSTER default (
langfuse-web-1     | 				version    Int64,
langfuse-web-1     | 				dirty      UInt8,
langfuse-web-1     | 				sequence   UInt64
langfuse-web-1     | 			) Engine=ReplicatedMergeTree ORDER BY sequence
langfuse-web-1     | Applying clickhouse migrations failed. This is mostly caused by the database being unavailable.
```

I'm guessing some sort of clickhouse config or init is getting skipped via the `docker compose up` path?

### To reproduce

checkout main, `docker compose up`

### Are you interested to contribute a fix for this bug?

No

**Comment by foragerr** [comment]
ok, found this: https://github.com/langfuse/langfuse/pull/4287/files
The env var I was missing is: `CLICKHOUSE_MIGRATION_CLUSTER_DISABLED="true"`

I think this resolves my last remaining error.


However docker-compose is still missing clickhouse config for langfuse-web, so I'll leave this issue open.

**Comment by Steffen911** [comment]
Hey @foragerr ,
Actually, those shouldn't be missing as we define an anchor (`&langfuse-worker-env`) in the worker env and read from that anchor for the web container env (`<<: *langfuse-worker-env`). It's just a way to avoid redundant declarations between the containers.

Your first error message also indicates that the correct Clickhouse instance is being accessed and it's just the wrong flag causing issues. In newer images the variable should be called CLICKHOUSE_CLUSTER_ENABLED and needs `false` for docker-compose environments. Can you ensure that you have the latest image for Langfuse? That may explain the dicrepancy.

Closing this as it's working for you and because the docker-compose is in its intended state.
