### ISSUE TITLE
bug: Serialization is broken for AWS Bedrock Image blocks

### ISSUE THREAD

**Issue by ShitizZip** [langfuse/langfuse#4631]
### Describe the bug

When adding image data to a AWS Bedrock Converse message, the block looks like

```json
            "image": {
                "format": formats[image_data["type"]],
                "source": {"bytes": image_data["content"]}
            }
```

which throws a serialization error with message
```
DEBUG:langfuse:received response: {"message":"Invalid request data","errors":["Expected object, received string"]}
```

My guess is this is due to `source` actually being a dict for Bedrock. Reference: https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_ImageSource.html

### To reproduce

Upload images to a Converse operation using boto3

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment]
@ShitizZip Thanks for raising this! Could you please share a full minimum repro example that specifies the image_data dict as well? Also, are you on the latest Langfuse Python SDK version?
