### ISSUE TITLE
bug: Optional but ask to put name in new experiment

### ISSUE THREAD

**Issue by kamonspecial** [langfuse/langfuse#4633]
### Describe the bug

In "New experiment", when I put any character in the experiment name field and delete it, although it is optional, we see an error message with "Please enter a name."
![image](https://github.com/user-attachments/assets/31843736-c1dc-4870-8561-b1107d8f4609)

### To reproduce

Just put char and delete in the Experiment name field.

### Are you interested to contribute a fix for this bug?

No

**Comment by marliessophie** [comment]
Hi @kamonspecial, thanks for reporting this glitch! We have fixed it in https://github.com/langfuse/langfuse/pull/4659, should be included in the next release :)
