### ISSUE TITLE
bug: serialization of images is broken

### ISSUE THREAD

**Issue by david1542** [langfuse/langfuse#4635]
### Describe the bug

Hi everyone,

I'm using LangGraph to build a multi-agent workflow. One of my agents uses a tool that returns an image.
When that tool is invoked, langfuse tries to serialize the image with the `EventSerializer` in `langfuse/serializer.py`. This causes the following error:
```
    return obj.decode("utf-8")
           ^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

Is there a way to tell langfuse to not serialize that tool output?

### To reproduce

Try to return an image from a tool (array of bytes).

### SDK and container versions

I'm using langfuse==2.53.1

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment]
Thanks for raising this @david1542 ! [Fixed in this commit](https://github.com/langfuse/langfuse-python/commit/6d3c5b19cd87fe61b7f18105b012592ff42b6456) by adding a fallback on decode exception.
