### ISSUE TITLE
bug: v2 to v3 migration tasks stuck on pending

### ISSUE THREAD

**Issue by samling** [langfuse/langfuse#4662]
### Describe the bug

I run a self-hosted instance of Langfuse on Kubernetes. On the announcement of the release of v3, I followed the migration guide by doing the following with my deployment:
- Created a cloud-hosted Clickhouse database
- Created an S3 bucket and configured an appropriate IAM policy
- Updated image tag from `2` to `3`
- Configured appropriate environment variables for Clickhouse, S3 and an existing Valkey instance (pointing to an unused db number)

Initially I had omitted the env var for configuring SSL migrations for Clickhouse, causing the migrations to fail. After fixing that, the Langfuse pod started without error and I could verify tables were created in Clickhouse. However, migrations were stuck pending, with no errors in the logs for Langfuse.

Subsequent attempts to retrigger migrations have failed including dropping tables in Clickhouse (which get recreated) and removing the migration rows in Postgres (which haven't been recreated...oops).

If I log a trace, I can see the object appear in S3, but nothing gets logged to the UI nor appears in Clickhouse.

![Screenshot 2024-12-09 160203](https://github.com/user-attachments/assets/d539f6ee-72d3-41c9-b48a-4c5d1f7b4f7f)

### To reproduce

See above steps to reproduce on an existing v2 instance.

### Are you interested to contribute a fix for this bug?

No

**Comment by Steffen911** [comment]
Hey @samling,
Thank you for your report.

Can you ensure that the langfuse-worker container is up and running? Do you see any logs for it? Per our [troubleshooting guide](https://langfuse.com/self-hosting/troubleshooting#missing-events-after-post-apipublicingestion) this behaviour usually indicates an offline worker.

**Comment by samling** [comment]
@Steffen911 Thanks for the quick reply. Indeed I was missing the worker container, I was using my own manifests instead of the helm chart. After switching to the helm chart (and restoring the background_migrations table contents with the queries below) and restarting the worker pod, everything went perfectly smoothly. Thanks again!

- https://github.com/langfuse/langfuse/tree/main/packages/shared/prisma/migrations/20241024121500_add_generations_cost_backfill_background_migration
- https://github.com/langfuse/langfuse/tree/main/packages/shared/prisma/migrations/20241024173000_add_traces_pg_to_ch_background_migration
- https://github.com/langfuse/langfuse/tree/main/packages/shared/prisma/migrations/20241024173700_add_observations_pg_to_ch_background_migration
- https://github.com/langfuse/langfuse/tree/main/packages/shared/prisma/migrations/20241024173800_add_scores_pg_to_ch_background_migration
