### ISSUE TITLE
bug: Update OpenAI SDK in v1

### ISSUE THREAD

**Issue by gyliu513** [langfuse/langfuse#467]
### Describe the bug

Check https://github.com/openai/openai-python/blob/main/README.md for detail.

```
You tried to access openai.Completion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
```

### To reproduce

upgrade openai and run with langfuse, will get error

**Comment by maxdeichmann** [comment]
@gyliu513 thanks for raising the issue. We will look into this as soon as possible

**Comment by gyliu513** [comment]
Thanks @maxdeichmann , this seems duplicate with #450, let me close this one, and we can focus on https://github.com/langfuse/langfuse/issues/450
