### ISSUE TITLE
bug(python): `handler.get_trace_url()` does not work

### ISSUE THREAD

**Issue by ajndkr** [langfuse/langfuse#468]
### Describe the bug

I am unable to fetch the trace url.

### To reproduce

Code from docs: https://langfuse.com/docs/integrations/langchain/python

```
# Initialize Langfuse handler
from langfuse.callback import CallbackHandler
handler = CallbackHandler(PUBLIC_KEY, SECRET_KEY)
 
# Setup Langchain
from langchain.chains import LLMChain
...
chain = LLMChain(llm=llm, prompt=prompt, callbacks=[handler])
 
# Add Langfuse handler as callback
chain.run(input="<user_input", callbacks=[handler])
```

after `chain.run`, i run the following:

```
handler.get_trace_url()
```

and I get the following error:

```
'FintoLangfuse' object has no attribute '_environment'
```

### Additional information

os: mac 14.0
python: 3.11
langfuse: 1.1.11

**Comment by maxdeichmann** [comment]
@ajndkr thanks for raising this. I fixed this issue in version `1.1.12`. Please re-open if the issue persists.
