### ISSUE TITLE
bug: langfuse db cpu full due to one query

### ISSUE THREAD

**Issue by elvis-cai** [langfuse/langfuse#4692]
### Describe the bug

we are using GCP Cloud SQL, and we found db cpu easily to be 100%, and from the analysis, it's due to one query 
```
SELECT percentile_disc($4) within group (order by "duration") as "percentile50Duration", percentile_disc($5) within group (order by "duration") as "percentile90Duration", percentile_disc($6) within group (order by "duration") as "percentile95Duration", percentile_disc($7) within group (order by "duration") as "percentile99Duration", t."name" as "traceName" FROM traces_view t WHERE t."timestamp" > $1::timestamp with time zone at time zone $8 AND t."timestamp" < $2::timestamp with time zone at time zone $9 AND t."project_id" = $3 GROUP BY t."name" ORDER BY percentile_disc(0.95) within group (order by "duration") DESC NULLS LAST
``` 

morel likely `ORDER BY percentile_disc(0.95) within group (order by "duration")` 

This clause forces PostgreSQL to sort 35 million rows (35,077,351 actual rows) based on the 95th percentile of "duration". Sorting this massive dataset is time-consuming and memory-intensive.

![image](https://github.com/user-attachments/assets/eb55e0c6-e5b6-4a43-8ade-8017ea12d917)

![image](https://github.com/user-attachments/assets/6ec3251c-3a63-46c4-a1ed-41e174bf9ddf)

just wondering is there any way to make some adjustment to make it so db io heavily, thx

### To reproduce

it will run by default when open the dashboard and we noticed trace latency is quite slow 
<img width="1972" alt="image" src="https://github.com/user-attachments/assets/49443724-74ce-4440-8f78-da8dc42509bb" />

### SDK and container versions

version: v2.78.0 OSS

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
This was a common problem as performing these kinds of queries in postgres are costly.

That's why Langfuse v3 shifted to Clickhouse which offers way higher performance for dashboard queries. Have a look here: https://langfuse.com/changelog/2024-12-09-Langfuse-v3-stable-release

**Comment by marcklingen** [comment]
alternatively you can set `LANGFUSE_DISABLE_EXPENSIVE_POSTGRES_QUERIES="true"` as a short term fix which will disable the dashboard charts which are costly

**Comment by elvis-cai** [comment]
Thanks @marcklingen, congrats on v3 stable recently, we will have a plan  on the v3 upgrade definitely, for the short term, as you suggested, we will check `LANGFUSE_DISABLE_EXPENSIVE_POSTGRES_QUERIES` params here, appreciate your quick help.

**Comment by marcklingen** [comment]
Sounds good. Glad that this helps
