### ISSUE TITLE
bug: Passing metadata to OpenAI when model distillation feat is used breaks when response_format is also set

### ISSUE THREAD

**Issue by jsundh** [langfuse/langfuse#4699]
### Describe the bug

This is a follow-up to #4574.

When `store=True` is set in the Langfuse OpenAI wrapper, that now triggers copying the `metadata` parameter to the one sent to the OpenAI client - fixed in https://github.com/langfuse/langfuse-python/pull/1031.

However, OpenAI only supports string values for its metadata key-value pairs and Langfuse adds the `response_format` parameter to its metadata here (if set): https://github.com/langfuse/langfuse-python/blob/ea75cc6ff7a47a094461a058f737b2387c4f254b/langfuse/openai.py#L153

That will then be forwarded to OpenAI as well and since that is an object and not a string, the request to OpenAI will fail with a 400 error if `response_format` is set with `store=True`:
```
openai.BadRequestError: Error code: 400 - {'error': {'message': "Invalid type for 'metadata.response_format': expected a string, but got an object instead.", 'type': 'invalid_request_error', 'param': 'metadata.response_format', 'code': 'invalid_type'}}
```

### To reproduce

Minimal reproduction in Python:

```python
# Assuming environment variables have been set
from langfuse.openai import OpenAI

client = OpenAI()
client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Output a simple JSON object",
        },
    ],
    model="gpt-4o-mini",
    store=True,
    response_format={"type": "json_object"},  # Works without this line
)
```

### SDK and container versions

Reproduced using `langfuse-python` version 2.56.2.

### Additional information

For our use case, it would be fine to explicitly exclude `response_format` from the metadata passed to OpenAI and keep it as is in the Langfuse metadata.

As for the "Yes" answer below to the question about contributing a fix, it is more of a "Yes, if necessary". In this case, it would probably be much quicker if you have time to fix it?

### Are you interested to contribute a fix for this bug?

Yes

**Comment by hassiebp** [comment]
Thanks for raising this @jsundh! Linked a PR to fix this issue.
