### ISSUE TITLE
Time to first token is displayed incorrectly in the observation screen

### ISSUE THREAD

**Issue by joshfp** [langfuse/langfuse#4703]
In the following screenshot, it can be seen that the "time to first token" is displayed as 18m 44s, which is incorrect.
![Screenshot 2024-12-12 at 10 31 02](https://github.com/user-attachments/assets/65892173-16ef-449b-9d29-da2c1f6c28f3)
When checking the observation object programmatically, the `time_to_first_token` is 1124 (milliseconds). I believe the frontend is mistakenly assuming that the value of 1124 is in seconds, which results in the 18m 44s display.

**Comment by marcklingen** [comment]
thanks for sharing, Max is currently investigating and fixing this issue. This was a fallout from v3, thanks for spotting

**Comment by maxdeichmann** [comment]
Sorry for the delay. We fixed the issue here: https://github.com/langfuse/langfuse/commit/ba750a2d551ed220100bf7fa949f27809e0db7c0
