### ISSUE TITLE
bug: Account creation fails when SSO provider returns unexpected fields

### ISSUE THREAD

**Issue by tovarisch-ildar** [langfuse/langfuse#4705]
### Describe the bug

We are encountering an issue with Langfuse when using ADFS as an SSO provider. The setup includes configuring Langfuse via AUTH_CUSTOM_* environment variables. The problem arises because the ADFS response contains an unexpected field (resource) that we cannot remove or modify.

While the user is created correctly, the account linking step fails, causing the entire sign-in process to break.

### To reproduce

Set up ADFS as an SSO provider.
Configure Langfuse with the following Docker command:

docker run --name langfuse \
-e DATABASE_URL='mypostgress' \
-e NEXTAUTH_URL='myurl' \
-e NEXTAUTH_SECRET=mysecret \
-e SALT=mysalt \
-e LANGFUSE_AUTO_POSTGRES_MIGRATION_DISABLED=false \
-e LANGFUSE_LOG_LEVEL=trace \
-e ENCRYPTION_KEY=key \
-e AUTH_CUSTOM_CLIENT_ID=client-id \
-e AUTH_CUSTOM_CLIENT_SECRET=secret \
-e AUTH_CUSTOM_ISSUER='issuer' \
-e AUTH_CUSTOM_NAME='SSO' \
-e AUTH_CUSTOM_ALLOW_ACCOUNT_LINKING=true \
-p 3030:3000 \
-a STDOUT \
langfuse/langfuse:2.93

Attempt to sign in via the configured ADFS SSO provider.

### SDK and container versions

langfuse:2.93

### Additional information

A similar issue was addressed in this issue: https://github.com/orgs/langfuse/discussions/2165. I aim to implement a more universal solution by cleaning up unnecessary fields before linkAccount. Is it okay that I created a separate issue for the upcoming PR?

### Are you interested to contribute a fix for this bug?

Yes

**Comment by marcklingen** [comment]
Fixed in #4728
