### ISSUE TITLE
bug: Wrong redirect after deleting project/organization when NEXT_PUBLIC_BASE_PATH is set

### ISSUE THREAD

**Issue by rors41** [langfuse/langfuse#4706]
### Describe the bug

When NEXT_PUBLIC_BASE_PATH is set, redirects after organization or project deletion redirect to root instead of NEXT_PUBLIC_BASE_PATH.

https://github.com/langfuse/langfuse/blob/d88902316b542ad2f3a311f86ab9d7324e777918/web/src/features/organizations/components/DeleteOrganizationButton.tsx#L66
https://github.com/langfuse/langfuse/blob/d88902316b542ad2f3a311f86ab9d7324e777918/web/src/features/projects/components/DeleteProjectButton.tsx#L64

### To reproduce

Delete project/organization when NEXT_PUBLIC_BASE_PATH is set

### SDK and container versions

container: 2.88.0

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
thanks for sharing! I will have a look soon
