### ISSUE TITLE
bug: Media URLs in Langfuse v3 web UI Are Inaccessible in Self-Hosted Setup

### ISSUE THREAD

**Issue by eloko7** [langfuse/langfuse#4717]
### Describe the bug

When using Langfuse v3 in a self-hosted Docker environment, media files (e.g., images from multimodal generation) are uploaded successfully to Minio. However, the URLs generated by the UI to access these files use the internal LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT (e.g., http://minio:9000), which is not resolvable externally. This results in broken images in the web UI.
<img width="1350" alt="Screenshot 2024-12-13 at 11 57 50" src="https://github.com/user-attachments/assets/f1f28891-c7bc-4196-8949-e2f099ac16a6" />

### To reproduce

1. Set up Langfuse v3 with the default Docker Compose configuration.
2. Run a multimodal generation with 
3. Open Trace/Generation in Web UI  (outside the Docker network).
4. Click on the Media Image Icon and attempt to open the URL

**Expected Behavior**:
The web UI should generate publicly accessible URLs for media files (e.g., http://localhost:9090/media/...), allowing them to load properly.

**Actual Behavior**:
The URLs generated use the internal endpoint (e.g., http://minio:9000/media/...), which cannot be resolved externally, leading to broken links in the UI.

### SDK and container versions

v2.93.6

### Additional information

Discussion: [Add Separate Environment Variable for Public S3 Endpoint in Self-Hosted Setup](https://github.com/orgs/langfuse/discussions/4716)

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment]
Please see thread on corresponding discussion - setup works as intended. https://github.com/orgs/langfuse/discussions/4716#discussioncomment-11556514
