### ISSUE TITLE
bug: 'LangfuseMedia' export missing

### ISSUE THREAD

**Issue by felixgabler** [langfuse/langfuse#4721]
### Describe the bug

Once we upgrade the JavaScript SDK from 3.31.1 to anything newer, it does not run the Nuxt development server anymore and we get this error message:

The requested module 'langfuse-core' does not provide an export named 'LangfuseMedia'

### To reproduce

Set up a fresh Nuxt project, install Langfuse and the Nuxt dev command should start showing `ERROR [worker reload] [worker init] /web/apps/web/.nuxt/dev/index.mjs failed`

### SDK and container versions

e.g., 3.31.3

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment]
Hi Felix, could you please share a minimal example how you are using Langfuse in your Nuxt app?

**Comment by felixgabler** [comment]
> Hi Felix, could you please share a minimal example how you are using Langfuse in your Nuxt app?

Yes, absolutely, here is the relevant code from `server/api/test-function.post.ts`

```typescript
export default defineLazyEventHandler(() => {
    const langfuse = getLangfuse();

    return defineEventHandler(async (event: H3Event) => {
        ...

        const trace = langfuse.trace({
            name: 'test-trace',
            userId,
            input,
        });

        ...

        trace.update({ output });

        await langfuse.shutdownAsync();
    });
});

function getLangfuse(): Langfuse {
    try {
        const {
            langfuseSecretKey,
            public: { langfuseBaseurl, langfusePublicKey },
        } = useRuntimeConfig();
        if (isNullable(langfuseBaseurl) || langfuseBaseurl === '') {
            throw new Error('Missing Langfuse base url');
        } else if (isNullable(langfusePublicKey) || langfusePublicKey === '') {
            throw new Error('Missing Langfuse public key');
        } else if (isNullable(langfuseSecretKey) || langfuseSecretKey === '') {
            throw new Error('Missing Langfuse secret key');
        }
        const langfuse = new Langfuse({
            secretKey: langfuseSecretKey,
            publicKey: langfusePublicKey,
            baseUrl: langfuseBaseurl,
        });
        langfuse.on('error', (error) => {
            Sentry.captureException(error);
            console.error(error);
        });
        return langfuse;
    } catch (error) {
        Sentry.captureException(error);
        throw error;
    }
}
```

**Comment by hassiebp** [comment]
Hey Felix, I cannot reproduce this: 

![CleanShot 2024-12-16 at 11 10 32@2x](https://github.com/user-attachments/assets/1cd77008-96bd-47ae-a229-ff1a27c2711a)

Could you please try reinstalling your project and make sure no older Langfuse version is required anywhere in your project?

**Comment by felixgabler** [comment]
Hey @hassiebp, seems like it works now with the latest version (https://github.com/langfuse/langfuse-js/pull/479/files)! Cheers!!
