### ISSUE TITLE
bug: LLMs-as-a-judge (Error: Selected model is not supported for evaluations. Test tool call failed.)

### ISSUE THREAD

**Issue by tobias-gp** [langfuse/langfuse#4747]
### Describe the bug

In the cloud version, I am receiving this error when creating an evaluator from a template (regardless which model I choose). 

Thanks a lot for this great piece of software! :) 

<img width="750" alt="grafik" src="https://github.com/user-attachments/assets/ffa7dc6b-cd15-4002-a848-abed01381fe6" />

### To reproduce

Follow the configuration from the screenshot

### Are you interested to contribute a fix for this bug?

No

**Comment by tobias-gp** [comment]
I just figured out that my API key had expired. Sorry!

**Comment by marliessophie** [comment]
Hi @tobias-gp, no worries, thanks for reporting regardless. We should improve the error message to actionably inform you that your key expired!
