### ISSUE TITLE
feat: Improvement of callback handler in LCEL (customization & readability)

### ISSUE THREAD

**Issue by Steenbuck** [langfuse/langfuse#481]
### Describe the feature you'd like to request

When using the the callback handler in Langchains LCEL `chain.invoke(input, config={"callbacks":[handler]})` on a simple chain like 
```
      chain = (
        {"context": vectorstore.as_retriever(), "question": RunnablePassthrough()}
        | prompt_template
        | llm
        )
```
 the captured trace is quite messy. 
![grafik](https://github.com/langfuse/langfuse/assets/46788032/5013ae26-920f-4a28-b139-eed286c54a9d)

I like to rename the whole trace (as "runnable Sequence" is quite generic and is not helping differentiate different tasks of my LLM. 
Drilling down and looking at the first span a second "problem" arises. As the first `span` can be described as the RAG, i like to see it right away (indicated with a customizable name). 
Also there appears the complete useless `Runnable Passthrough` distracting me from seeing the relevant information. Same hold true (at least for now) for the `RunnableParallel`-Span. 
So all in all I think a little customization opportunities for me and/or preconfiguration from your side would be appreciated a lot :) 

### Describe the solution you'd like to see

Idealy I wish for more controll over the creation of spans at chain definition. 
Sth. like:
```
chain = (
        {"context": vectorstore.as_retriever(), "question": RunnablePassthrough(),"callback_options":{"span_name":"rag", "show_elements"[1,0]}} # "show_elements" maybe as a list of elements to show The RAG consist of 2 Spans (VectorStoreRetriever & RunnablePassthrough) but I'm just interested in the first
        | prompt_template
        | llm 
        )
```
While writing though I'm not sure if this makes sense to implement it like this. 
Since I think the callback handler should a very simple form of hooking up langfuse to your langchain projekt maybe it should stay as simple as it is and I'm just missing better support to integrate my own traces to each step in the chain. Or  I need to write my own callback handler which I try to avoid so far. 

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
Hi @Steenbuck, had a deeper look but did not comment right away.
- Agree that being able to the name for each element of the trace when using LCEL would be nice. 
- Being able to add custom spans/events to a trace generated is super valuable but there is no clear route to implement it with a nice DX. Open for suggestions

**Comment by maxdeichmann** [comment]
@Steenbuck we are able to configure names by using LCEL by now. Here is an example:

```
 from langchain_community.vectorstores import FAISS
    from langchain_core.output_parsers import StrOutputParser
    from langchain_core.runnables import RunnablePassthrough
    from langchain_openai import OpenAIEmbeddings

    model = ChatOpenAI(temperature=0)

    template = """Answer the question based only on the following context:
    {context}

    Question: {question}
    """
    prompt = ChatPromptTemplate.from_template(template)

    loader = TextLoader("./static/state_of_the_union.txt", encoding="utf8")

    documents = loader.load()
    text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
    texts = text_splitter.split_documents(documents)

    embeddings = OpenAIEmbeddings(openai_api_key=os.environ.get("OPENAI_API_KEY"))
    docsearch = Chroma.from_documents(texts, embeddings)

    retriever = docsearch.as_retriever()

    retrieval_chain = (
        {
            "context": retriever.with_config(run_name="Docs"),
            "question": RunnablePassthrough(),
        }
        | prompt
        | model.with_config(run_name="my_llm")
        | StrOutputParser()
    )

    retrieval_chain.invoke(
        "What did the president say about Ketanji Brown Jackson?",
        config={
            "callbacks": [CallbackHandler(debug=False)],
        },
    )

```
This leads to the following trace in Langfuse:

![image](https://github.com/langfuse/langfuse/assets/17686849/e420478f-cca8-41be-8064-b2084773afe9)
