### ISSUE TITLE
feat: updates scores via public API

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#483]
### Describe the feature you'd like to request

Currently, scores can only be created through the API. I suggest making them updateable via the API.

### Describe the solution you'd like to see

Optional id on score body; upserts on id

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by EIrwin** [comment]
@marcklingen Thank you for adding this, we noticed there was the ability to update through the UI and can see the call, however the REST API itself doesn't support this.

**Comment by 18feb06** [comment]
attempt #483

**Comment by marcklingen** [comment]
@EIrwin added in #500
