### ISSUE TITLE
bug: AttributeError: 'NoneType' object has no attribute 'get

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#4834]
### Discussed in https://github.com/orgs/langfuse/discussions/4832

<div type='discussions-op-text'>

<sup>Originally posted by **sagorbrur** December 25, 2024</sup>
Hi,
I am getting this issue while integrating langfuse with __langgraph__. But the trace is coming rightly in the dashboard.
Here is the details
```bash
langfuse==2.56.2
langgraph==0.2.52
langchain-core==0.3.19
```
The error details:

```json
{
    "message": "'NoneType' object has no attribute 'get'\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.12/site-packages/langfuse/callback/langchain.py\", line 302, in __generate_trace_and_parent\n    class_name = self.get_langchain_run_name(serialized, **kwargs)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/langfuse/callback/langchain.py\", line 169, in get_langchain_run_name\n    return serialized.get(\"name\", serialized.get(\"id\", [\"<unknown>\"])[-1])\n           ^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'get'",
    "level": "ERROR",
    "name": "langfuse",
    "timestamp": "2024-12-25T04:55:53.060356+00:00"
}
```</div>

**Comment by marcklingen** [comment]
@sagorbrur can you share more details on how to reproeducr this? Which kind of node do you use here within langgraph?

**Comment by sagorbrur** [comment]
Hi @marcklingen ,
We are using different nodes as different llm agent. each node contains tools and router functions. 
Here is an example of the node graph.
![test_1 json](https://github.com/user-attachments/assets/a3a660b8-8090-432d-9085-09ee6ec0c613)

We have prepared a graph builder which build graph based on nodes llm and tool information.

We integrated langfuse as a callbackhandler.

```py
from langfuse.callback import CallbackHandler

langfuse_handler = CallbackHandler()
chat_config = {
        "configurable": {"thread_id": id},
        "callbacks": [langfuse_handler]
    }

async for event in graph.astream_events(
            {"messages": inputs}, version="v1", config=chat_config
        ):

```

By the way, while getting the above error we are getting this error also. Although this is different I am guessing.

```json
{"message": "run not found\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.12/site-packages/langfuse/callback/langchain.py\", line 441, in on_chain_end\n    raise Exception(\"run not found\")\nException: run not found", "level": "ERROR", "name": "langfuse", "pid": 235, "job_id": "AJ_74xQp2Dei6Cw", "timestamp": "2024-12-25T04:55:53.062254+00:00"}
```

**Comment by hassiebp** [comment]
@sagorbrur - this should be already fixed on the latest Python SDK version - please upgrade and try again 🙏🏾

**Comment by sagorbrur** [comment]
Hi @hassiebp ,
I am upgrading the version to langfuse 2.57.1 and will let you know if it works. 
thank you.

**Comment by sagorbrur** [comment]
Hi @hassiebp , @marcklingen ,
After upgrading to 2.57.1 version the problem was solved. 
Thank you so much.

**Comment by sagorbrur** [comment]
Hi @hassiebp ,
Just to confirm, the below problem also get solved by upgrading the version. Right?
Although this problem not originated frequently. 

```bash
{"message": "run not found\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.12/site-packages/langfuse/callback/langchain.py\", line 441, in on_chain_end\n    raise Exception(\"run not found\")\nException: run not found", "level": "ERROR", "name": "langfuse", "pid": 235, "job_id": "AJ_74xQp2Dei6Cw", "timestamp": "2024-12-25T04:55:53.062254+00:00"}
```

**Comment by marcklingen** [comment]
Great. Please open a new issue in case this happens on the latest version
