### ISSUE TITLE
feat: In the Trace Detail view: Fold / Unfold part of the tree view 

### ISSUE THREAD

**Issue by matthieudelaro** [langfuse/langfuse#488]
### Describe the feature you'd like to request

In this view, in this example
![grafik](https://github.com/langfuse/langfuse/assets/2452725/be95da5f-8266-4c68-b279-4c65094a0253)

I would like to have a button which fold/unfold the content of the AgentExecutor (and any other observation).

### Describe the solution you'd like to see

The solution could be a small arrow like in VS Code, to fold/unfold an object:
![grafik](https://github.com/langfuse/langfuse/assets/2452725/1d7a021b-072b-458c-9382-56da035bee49)

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by maxdeichmann** [comment]
@matthieudelaro thanks for the suggestion. Which data do you usually search for in the metadata?

**Comment by marcklingen** [comment]
Tracking UI suggestions in #451
