### ISSUE TITLE
feat: allow database credentials as separate environment variables

### ISSUE THREAD

**Issue by p5** [langfuse/langfuse#492]
### Describe the feature you'd like to request

We are self-hosting Langfuse in AWS, and it would be good if we were able to define the database credentials as separate environment variables so we can directly link to the managed AWS Secrets Manager credentials without having to create the string ourselves.  
This provides the benefits of us being able to automatically rotate the secrets, and the Langfuse ECS task would pick up on the changes without any manual intervention.

### Describe the solution you'd like to see

The following environment variables could be optional, along with the DATABASE_URL variable that's implemented already:
- DATABASE_HOST
- DATABASE_USERNAME
- DATABASE_PASSWORD

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
@p5 to confirm, there is no way to merge the individual environment variables on AWS?

**Comment by p5** [comment]
> @p5 to confirm, there is no way to merge the individual environment variables on AWS?

Not that I am aware of.  We would like to implement the approach for securely sharing variables from [this document](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/secrets-envvar-secrets-manager.html), with AWS-managed database credentials (to avoid the need for manual processes creating users) but there doesn't seem to be a way to do so.

This is in no way a blocker or should be considered a high priority, but would be a nice change to make it easier to automate the setup of Langfuse.

**Comment by marcklingen** [comment]
Sounds good, thanks for the context. Will mark this as low priority for now. Happy about contributions on this as I see the added benefit

**Comment by marcklingen** [comment]
@p5, fyi, @Strernd  just went ahead and contributed this. Will publish it as a new version in a minute. Hope this helps to rotate your secrets more often
