### ISSUE TITLE
feat: delete single trace

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#501]
### Describe the feature you'd like to request

Delete a single trace

### Describe the solution you'd like to see

- action on tables
- action on single trace view

### Additional information

While usually this is not necessary, there are various reasons why it can be useful to delete a single trace.

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by MushroomLamp** [comment]
To provide some additional context: I am using Langfuse with Flowise, as a tool to help debug my flows. sometimes there can be many iterations and it could be useful to be able to delete traces that are just used for debugging, to make it easier to see future traces
