### ISSUE TITLE
feat: Add Okta

### ISSUE THREAD

**Issue by chaseWillden** [langfuse/langfuse#507]
### Describe the feature you'd like to request

Our company uses Okta and next.js includes an okta provider, so this request is to add Okta as an auth provider

### Describe the solution you'd like to see

A signin with Okta button

### Additional information

Here's the PR: https://github.com/langfuse/langfuse/pull/506 

### Contribute

- [X] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
Thanks for the PR #506
