### ISSUE TITLE
feat: Display the name of the project in the header of the dashboard

### ISSUE THREAD

**Issue by matthieudelaro** [langfuse/langfuse#519]
### Describe the feature you'd like to request

<img width="653" alt="grafik" src="https://github.com/langfuse/langfuse/assets/2452725/b3f8fec0-6e3b-474f-b634-b8c5c217af84">

Since one of the project is chosen by default when we open the web UI, the user might be looking at the wrong dashboard without realizing it. Especially if the sidebar is closed, which is the case in small windows.

### Describe the solution you'd like to see

Replace `Traces` with `Traces of project GreatProjectName` 

### Contribute

- [X] Yes, I can implement this and raise a PR

**Comment by matthieudelaro** [comment]
Update about cloud langfuse:
There is a trace which just appeared in less than a minutes, as expected.
Older traces, since the last one which worked, are still missing from the dashboard.

There should be several other traces between those two once:
<img width="328" alt="grafik" src="https://github.com/langfuse/langfuse/assets/2452725/0917a175-d04d-4ffe-b426-c51e2cfbda40">

**Comment by marcklingen** [comment]
Great, thanks for the idea @matthieudelaro, thanks for the implementation @18feb06!
