### ISSUE TITLE
feat: healthcheck endpoint

### ISSUE THREAD

**Issue by p5** [langfuse/langfuse#526]
### Describe the feature you'd like to request

It would be good if there was an API endpoint that confirmed connectivity to the database so that we can perform health checks on the running containers.  This will help with uptime when self-hosting the services.

### Describe the solution you'd like to see

A `/ping` or `/healthcheck` endpoint that runs some dummy query on the database and calls any other requirement.
If the connectivity is good, and the container can access whatever it needs to, return a 200 OK.  If not, return a 500 Internal Server Error.

### Additional information

Redash has implemented a simple `/ping` endpoint that returns "pong" with a 200 OK.  This at least lets the load balancer (in AWS' case, the target group health checks) that the API is running.
https://redash.io/help/open-source/setup#Health-Check-for-Installation

If there is already an endpoint I have missed, it would be great if you could point me to the documentation.

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
Agree, @p5, this already exists but is not included in the OpenAPI spec yet. I'll add it right away

- [health.ts](https://github.com/langfuse/langfuse/blob/main/src/pages/api/public/health.ts) covers API uptime and database connection
- Example: https://cloud.langfuse.com/api/public/health
- Used for https://status.langfuse.com

**Comment by marcklingen** [comment]
It's now included in the openapi spec and also in the api reference (although it is still a bit ugly)
https://langfuse.com/docs/api-reference#tag/Health

**Comment by p5** [comment]
Thanks!  Just implemented that endpoint in our AWS environment and works perfectly

**Comment by marcklingen** [comment]
@p5 Quick update, as this is now an official feature I changed the error code to 503 instead of 500 to be more specific

Updated public docs and openapi spec accordingly (currently deploying, live in a minute): https://langfuse.com/docs/deployment/self-host
