### ISSUE TITLE
bug: I cannot remove myself from a project (as admin), but remove button is still being shown

### ISSUE THREAD

**Issue by 18feb06** [langfuse/langfuse#529]
### Describe the bug

I cannot delete myself from a project (as admin), but delete button is still being shown

### To reproduce

1. Create an admin for project.
2. Log in with your admin account.
3. Go to settings.
4. In "Project Members" table, you will see a delete icon on yourself although you cannot delete your self.

### Additional information

[Screencast from 11-20-2023 04:02:00 AM.webm](https://github.com/langfuse/langfuse/assets/88766161/28fce69c-d5bc-4452-a4ec-bf1be28a12fc)

**Comment by marcklingen** [comment]
Thanks for reporting, fixed in #530
