### ISSUE TITLE
bug: with langchain 0.0.339 and langfuse 1.7.4 generation call is not working

### ISSUE THREAD

**Issue by mohade09** [langfuse/langfuse#548]
### Describe the bug

Getting this error for model name amazon_bedrock : 
below is the model definition:
 claude_llm = Bedrock(model_id="anthropic.claude-v2", client=bedrock_runtime, model_kwargs={'max_tokens_to_sample':200})

i am getting this error from langfuse: 
model_name = self.extract_second_part(self.extract_model_id("model_id", serialized["repr"]))
KeyError: 'repr'

### To reproduce

Getting this error for model name amazon_bedrock : 
below is the model definition:
 claude_llm = Bedrock(model_id="anthropic.claude-v2", client=bedrock_runtime, model_kwargs={'max_tokens_to_sample':200})

i am getting this error from langfuse: 
model_name = self.extract_second_part(self.extract_model_id("model_id", serialized["repr"]))
KeyError: 'repr'

**Comment by maxdeichmann** [comment]
@mohade09 thanks for the issue. Are you running on the latest Python SDK version? Which langchain version are you using?

**Comment by mohade09** [comment]
The code is running in aws lambda python 3.11 and langchain : 0.0.339

**Comment by maxdeichmann** [comment]
> The code is running in aws lambda python 3.11 and langchain : 0.0.339 Here is my setup : with langchain 0.0.339 and langfuse 1.7.4

thanks, will try to reproduce this.

**Comment by mohade09** [comment]
I tried an older version 1.1.14 where the code was soemthing like this it is working 👍 on a very old version of langfuse
```
def extract_model_id(text):
                    match = re.search(r"model_id='(.*?)'", text)
                    if match:
                        return match.group(1)
                    return None

                def extract_second_part(text):
                    return text.split(".")[-1]

                model_name = extract_second_part(extract_model_id(serialize
```

**Comment by maxdeichmann** [comment]
> I tried an older version 1.1.14 where the code was soemthing like this it is working 👍 on a very old version of langfuse
> 
> ```
> def extract_model_id(text):
>                     match = re.search(r"model_id='(.*?)'", text)
>                     if match:
>                         return match.group(1)
>                     return None
> 
>                 def extract_second_part(text):
>                     return text.split(".")[-1]
> 
>                 model_name = extract_second_part(extract_model_id(serialize
> ```

Looks like we broke something when adding features for bedrock. I will look into this.

**Comment by maxdeichmann** [comment]
@mohade09 Can you check out this fix? I hope this resolves it. https://github.com/langfuse/langfuse-python/releases/tag/v1.7.5
