### ISSUE TITLE
feat: costs on traces, generations, and user tables

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#550]
### Describe the feature you'd like to request

Currently, costs are visible on the dashboard and when viewing a single trace.
Costs need to be visible on all tables to easily find expensive traces/generations.

### Describe the solution you'd like to see

On traces, generations, user table:
- Costs column
- Filter by costs

### Additional information

We should wait for @maxdeichmann to merge the simplification of the tokenization and price tracking features. This will make building this so much simpler.

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
Let's wait for @maxdeichmann to merge the changes regarding cost calculation. There will be too many changes impacting this issue.

**Comment by 18feb06** [comment]
ok

**Comment by marcklingen** [comment]
Cost on generations in #725
