### ISSUE TITLE
bug: Documentation on startTime, endTime of python API

### ISSUE THREAD

**Issue by minkooseo** [langfuse/langfuse#555]
### Describe the bug

At https://langfuse.com/docs/sdk/python, startTime and endTime types should be datetime.datetime. It's not Date.

```
In [1]: from datetime import datetime

In [2]: datetime.now()
Out[2]: datetime.datetime(2023, 11, 23, 20, 48, 33, 826396)

In [3]: type(datetime.now())
Out[3]: datetime.datetime

In [4]: datetime.now().date()
Out[4]: datetime.date(2023, 11, 23)

In [5]: type(datetime.now().date())
Out[5]: datetime.date
```

### To reproduce

NA

**Comment by marcklingen** [comment]
Thanks for the hint @minkooseo, fixed it: https://github.com/langfuse/langfuse-docs/commit/a6cb2229c9da5f6c49aa6dca6aa50efef5ec952f
