### ISSUE TITLE
feat: bookmarking of traces

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#568]
### Describe the feature you'd like to request

When browsing through many traces, being able to bookmark them for later is helpful

## UI
![Gmail star](https://github.com/langfuse/langfuse/assets/2834609/e013a7de-a96a-479a-98a4-08190b8665ab)
Clickable star
- on /traces
- on /traces/:traceid

Filter on /traces table

## Implementation
- DB schema, trace table, bookmarked, bool
- trpc route to change bookmark status of trace, invalidate trace afterwards to reload
- Component for clickable star
   - state from higher-level component as the trace table and the single trace page already loaded the trace
   - Uses trpc mutation to change star of a trace
 - New edit access to traces, I'd grant this for members, admins, owners, not for viewers

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by 18feb06** [comment]
@marcklingen Can I work on it?

**Comment by marcklingen** [comment]
@18feb06 thanks for asking, this is already work in progress, PR coming soon

**Comment by 18feb06** [comment]
ok
