### ISSUE TITLE
feat: multi-select actions on trace table, starting with trace deletion

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#572]
### Describe the feature you'd like to request

- Some actions should be performed on multiple traces, e.g. deleting traces

### Describe the solution you'd like to see

Generalized solution for row actions
1. Row selection of shadcn/ui table: https://ui.shadcn.com/docs/components/data-table#row-selection
2. Action buttons in table menu bar when rows are selected, delete trace as first supported action

Hypothetical table from shadcn/ui docs
![Table](https://github.com/langfuse/langfuse/assets/2834609/ce00af37-06f0-40c8-99b2-dba4aff4a1fa)

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by gokuljs** [comment]
@marcklingen Which section of the UI is this supposed to appear in?

**Comment by 18feb06** [comment]
@gokuljs I am currently working on it. I apologize that i did not mentioned that here.

**Comment by gokuljs** [comment]
oh okay

**Comment by 18feb06** [comment]
no problem 😊
