### ISSUE TITLE
feat: rename project

### ISSUE THREAD

**Issue by maxdeichmann** [langfuse/langfuse#577]
### Describe the feature you'd like to request

- Users should be able to rename projects in the UI of the `/project/[projectId]/settings` page. 
- Add a settings box similar to the image below, to allow users to update the project name

### Describe the solution you'd like to see

- Implementation
   -  Add the UI using shadcn + tailwind
   - Create a trpc route to update the project name
   - Check for permissions before updating. Add a `project:update` permission and assign it to owners and admins. They should be able to rename.

Current settings page
![image](https://github.com/langfuse/langfuse/assets/17686849/2121aa2f-bea2-4dd7-a83c-ae793ee42132)

Added project section
![image](https://github.com/langfuse/langfuse/assets/17686849/ba81cadb-6dd8-4f4c-aca6-24e22b102195)

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by gokuljs** [comment]
@marcklingen can you assign me this

**Comment by marcklingen** [comment]
@gokuljs this is already work in progress, no need for duplicated effort here
