### ISSUE TITLE
feat: Support for CallbackManagerForChainRun

### ISSUE THREAD

**Issue by yvesloy** [langfuse/langfuse#587]
### Describe the feature you'd like to request

I am trying to debug the HypotheticalDocumentEmbedder in langchain, but when passing the CallbackHandler, I get this error: 

ValidationError: 1 validation error for HypotheticalDocumentEmbedder
run_manager
  instance of CallbackManagerForChainRun expected (type=type_error.arbitrary_type; expected_arbitrary_type=CallbackManagerForChainRun)

### Describe the solution you'd like to see

I would like to have support for the HypotheticalDocumentEmbedder to be used with langfuse. 

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
Thanks for reporting @yvesloy!

**Comment by yvesloy** [comment]
False alarm from my side. I could make it work with the default `CallbackHandler`

**Comment by marcklingen** [comment]
Glad it works @yvesloy, feel free to create new issues if you run into any other edge cases
