### ISSUE TITLE
feat: Make pricing configurable

### ISSUE THREAD

**Issue by krille90** [langfuse/langfuse#595]
### Describe the feature you'd like to request

Hey, we are currently looking into using langfuse and managed to deploy it on-premise.
It's a beautiful tool, however all our models show 0$ usage, as we use custom models, although they still run on azure.
it would be nice to make it easy to configure the pricing for custom models, i.e. add a row to the pricing table (or update pricings manually if it changes.)

### Describe the solution you'd like to see

Add a new menu for pricing, showing the current pricing, make it editable.
Additionally, add a function to add a row.

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
Agree @krille90, definitely something we want to support with the project. Currently @maxdeichmann is building a new abstraction for token usage and model pricing. We're considering how to best support custom pricing structures

**Comment by juan-abia** [comment]
Hi! Just wanted to ask, how is this feature going? is there a PR for it already?

**Comment by dvelho** [comment]
HI! 
Same request here. Waiting for OpenAI model  "ada v2" -> $0.0001 / 1K tokens
We also need to calculate when we use just the embeddings models :)

**Comment by marcklingen** [comment]
Hi all, with the v2 release, tokenization and pricing can now be configured and also ingested via the API. See [changelog post](https://langfuse.com/changelog/2024-01-29-custom-model-prices) for full details on this change. This should address your needs, let me know if you have any feedback/ideas.
