### ISSUE TITLE
feat: When envs are not set correctly, SDKs should log an error instead of throwing an exception

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#598]

**Comment by gokuljs** [comment]
i will pick this up

**Comment by marcklingen** [comment]
Thanks @gokuljs! Let me know if you have any questions when making changes to the two sdks

**Comment by Ritish134** [comment]
@marcklingen May you please clarify on which files changes are to be done?

**Comment by gokuljs** [comment]
Hey Marcklingen, I'll kick things off this coming Saturday. Been really swamped with other stuff lately. If it doesn't get rolling, I'll be sure to get it done by my Sunday.

**Comment by shashankshet** [comment]
Hello @marcklingen ,

I updated the python-sdk to handle when envs are not set. Please let me know your suggestions on this fix

https://github.com/langfuse/langfuse-python/pull/299
