### ISSUE TITLE
feat: Well-Designed Email Template for Project Invitations

### ISSUE THREAD

**Issue by 18feb06** [langfuse/langfuse#600]
### Describe the feature you'd like to request

Well-Designed Email Template for Project Invitations with with right color scheme.

### Describe the solution you'd like to see

Well-Designed Email Template for Project Invitations with with right color scheme.

### Contribute

- [X] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
Hi @18feb06, this is a great addition to yesterdays contribution (#574)
Which library do you plan to use for the templating? WOuld love to make a good decision to use it across all transactional emails going forward

**Comment by 18feb06** [comment]
@marcklingen  I will use [React Email](https://react.email/)
