### ISSUE TITLE
feat: do not require optional fields in python client

### ISSUE THREAD

**Issue by backmask** [langfuse/langfuse#635]
### Describe the feature you'd like to request

Several optional fields in generated types are marked as mandatory. In order to pass typechecks (e.g. with mypy), it makes trace creation not as slick as it could be.

For instance:
```
CreateSpan(
    name=name,
    input=input,
    id=None,
    traceId=None,
    startTime=None,
    metadata=None,
    output=None,
    level=None,
    statusMessage=None,
    parentObservationId=None,
    version=None,
    endTime=None
)
```

Whereas it would ideally be:
```
CreateSpan(
    name=name,
    input=input
)
```

### Describe the solution you'd like to see

A solution was recently released in fern: https://github.com/fern-api/fern-python/pull/329
Adding the option `require_optional_fields = False` in the script that generates types should solve the issue.

### Contribute

- [X] Yes, I can implement this and raise a PR

**Comment by maxdeichmann** [comment]
@backmask thanks for raising this! I just deployed the change: https://github.com/langfuse/langfuse-python/releases/tag/v1.13.0
