### ISSUE TITLE
bug: Langchain callback openai model "gpt-3.5-turbo-instruct" does not track token usage

### ISSUE THREAD

**Issue by GMartin-dev** [langfuse/langfuse#648]
### Describe the bug

If you use gpt model name "gpt-3.5-turbo-instruct" using OpenAI() trace is missing token usage.

### To reproduce

Use OpenAI() with model_name = "gpt-3.5-turbo-instruct" as llm for chain or runnables.

Will Work
```
kwargs["model_name"] = "gpt-3.5-turbo-0301"
llm = OpenAI(**kwargs)
```
![image](https://github.com/langfuse/langfuse/assets/1821407/d77e3985-c67d-48ee-a9a0-143178daf9bf)

Will FAIL
```
kwargs["model_name"] = "gpt-3.5-turbo-instruct"
llm = OpenAI(**kwargs)
```
![image](https://github.com/langfuse/langfuse/assets/1821407/27f16056-81f0-485b-8fff-8dbd5eb6ae3d)

**Comment by 18feb06** [comment]
This is because pricing data is not updated with langchain.

**Comment by marcklingen** [comment]
the v2 release includes this model and the option to set custom model prices, this should solve this issue: https://github.com/langfuse/langfuse/releases/tag/v2.0.0 

Hope this helps, feel free to reopen if it does not work for you.
