### ISSUE TITLE
bug: Langchain callback TextGen() llm fails to get traced

### ISSUE THREAD

**Issue by GMartin-dev** [langfuse/langfuse#649]
### Describe the bug

If you use TextGen() as your llm it fails to get traced and you can see error in logs. The

### To reproduce

Will Work

```
kwargs["model_name"] = "gpt-3.5-turbo-0301"
llm = OpenAI(**kwargs)
```
![image](https://github.com/langfuse/langfuse/assets/1821407/3cd8bf02-0fb4-4543-b97b-284ee803a0ac)

Will fail
```
model_url = <local/network textgen server url>
llm = TextGen(model_url=model_url, **kwargs)
```
![image](https://github.com/langfuse/langfuse/assets/1821407/b356bd7c-1353-425a-8f07-009f44fc48f3)

Error
```
Traceback (most recent call last):
  File "langfuse/callback.py", line 522, in __on_llm_action
    model_name = kwargs["invocation_params"]["model_name"]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'model_name'
run not found
Traceback (most recent call last):
  File "langfuse/callback.py", line 593, in on_llm_end
    raise Exception("run not found")
Exception: run not found
```

**Comment by maxdeichmann** [comment]
@GMartin-dev, thanks for reporting this issue. As of [release 2.11.0](https://github.com/langfuse/langfuse-python/releases/tag/v2.11.0), this issue was resolved. Feel free to re-open this issue if this appears again.
