### ISSUE TITLE
bug: Langfuse client returns incorrect trace url

### ISSUE THREAD

**Issue by HugoMichard** [langfuse/langfuse#650]
### Describe the bug

When getting a trace url with `get_trace_url` from a `Langfuse` instance or a `StatefulClient` instance, an incorrect string is returned with the following format: `http://localhost:3000/trace/{trace_id}` such as `http://localhost:3000/trace/6049a0f9-fca9-4396-8b58-354625fbe9e4`.

This is incorrect and leads to a 404. Correct URL should be with the following format `http://localhost:3000/project/{project_id}/traces/{trace_id}` such as `http://localhost:3000/project/clptuavc20001de8t989k6q52/traces/6049a0f9-fca9-4396-8b58-354625fbe9e4`.

### To reproduce

Here is a base example to reproduce the bug using LangChain with the `CallbackHandler` 

```python
from langfuse.callback import CallbackHandler
from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate
from hl.ai.corneille.common.vllm.vllm_inference import vLLMInference


PUBLIC_KEY = ...
SECRET_KEY = ...
HOST = ...

llm = ...

handler = CallbackHandler(PUBLIC_KEY, SECRET_KEY, host=HOST)
chain = LLMChain(llm=llm, prompt=PromptTemplate.from_template("{question}"))

print(chain({'question': 'Hello World'}, callbacks=[handler]))
print(handler.get_trace_url())
```

**Comment by marcklingen** [comment]
Thanks for reporting this. Does this lead to a 404 in your setup?

The route is meant to redirect which worked when I just tested it: https://github.com/langfuse/langfuse/blob/main/src/pages/trace/%5BtraceId%5D.tsx
