### ISSUE TITLE
bug: application error message on dashboard 

### ISSUE THREAD

**Issue by HugoMichard** [langfuse/langfuse#653]
### Describe the bug

With local and self-hosted deployments, the dashboard tab only shows the following error:
 `Application error: a client-side exception has occurred (see the browser console for more information).`

All other tabs work perfectly fine.

On the dashboard tab, I have in my console:
![image](https://github.com/langfuse/langfuse/assets/15155145/ff29ae12-16b0-4cf9-ab82-1c2aa108c0c0)

(zoomed in)
![image](https://github.com/langfuse/langfuse/assets/15155145/bcfde046-ad98-4079-9176-41aa30d336ff)

### To reproduce

I followed steps described in https://langfuse.com/docs/deployment/local#start. When visiting `http://localhost:3000/`, after creating a new user, I just go to the dashboard tab.

**Comment by 18feb06** [comment]
@HugoMichard I tried to reproduce but it is working fine.

**Comment by 18feb06** [comment]
I think you should pull latest changes from github repo and docker by rfollwoing steps given in following link:
https://langfuse.com/docs/deployment/local#upgrade

**Comment by maxdeichmann** [comment]
@HugoMichard thanks for reporting! Are you running 1.14? (https://github.com/langfuse/langfuse/pkgs/container/langfuse)

**Comment by marcklingen** [comment]
I know this error, toReversed is unsupported in older browsers ([caniuse](https://caniuse.com/mdn-javascript_builtins_array_toreversed))
Polyfills are still missing in NextJs (which is used for the Langfuse frontend), issue is tracked here: https://github.com/vercel/next.js/issues/58242
In the meantime, installing the latest browser update should fix this issue for you @HugoMichard

**Comment by marcklingen** [comment]
`toReversed` is unsupported by older browsers ([caniuse](https://caniuse.com/mdn-javascript_builtins_array_toreversed))
Polyfills are still missing in NextJs (which is used for the Langfuse frontend), issue is tracked here: https://github.com/vercel/next.js/issues/58242
In the meantime, installing the latest browser update should fix this issue for you @HugoMichard

**Comment by marcklingen** [comment]
This problem persisted as no fix was added upstream. I've just added the polyfills to Langsfuse which increases compatibility with older browsers a lot.

Release: [v1.24.1](https://github.com/langfuse/langfuse/releases/tag/v1.24.1)
