### ISSUE TITLE
bug: `pip install langfuse` doesn't install dependencies

### ISSUE THREAD

**Issue by alexcannan** [langfuse/langfuse#676]
### Describe the bug

`pip install langfuse` on a fresh env does not install required dependencies.

### To reproduce

Occuring on version `langfuse=1.13.2`
```
python3 -m venv env
source env/bin/activate
python3 -m pip install langfuse
python3 -c "from langfuse import Langfuse"
```
You should receive something like `ModuleNotFoundError: No module named 'requests'`. If you install requests, it falls back to `ModuleNotFoundError: No module named 'langchain'`, and so on.

**Comment by marcklingen** [comment]
Thanks for reporting, we'll release a fix asap

**Comment by maxdeichmann** [comment]
@alexcannan we fixed this in the newest release: https://github.com/langfuse/langfuse-python/releases/tag/v1.13.3. feel free to re-open if the issue persists.

**Comment by alexcannan** [comment]
The issue persists for the `requests` package, you get the following traceback on a fresh venv with only `pip install langfuse`
```
(env) alex@hq3 ~> python3 -c "from langfuse import Langfuse"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/alex/env/lib/python3.10/site-packages/langfuse/__init__.py", line 1, in <module>
    from .client import Langfuse
  File "/home/alex/env/lib/python3.10/site-packages/langfuse/client.py", line 44, in <module>
    from langfuse.request import LangfuseClient
  File "/home/alex/env/lib/python3.10/site-packages/langfuse/request.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by maxdeichmann** [comment]
@alexcannan sorry for this. I fixed this here: https://github.com/langfuse/langfuse-python/releases/tag/v1.13.4
