### ISSUE TITLE
feat: using same trace id across multiple systems

### ISSUE THREAD

**Issue by surki** [langfuse/langfuse#685]
### Describe the feature you'd like to request

We have a chat bot interaction use that can be handled across multiple systems over multiple minutes (imagine: slack thread, user interactions we want to track it in a single trace). The trace id is persisted outside, fetched/passed as part of request context on the entry.

I am trying to use langfuse for this with something like this (python sdk):

Is this the correct way to use the sdk? or something else I should be doing?

```
langfuse = Langfuse(debug=True)
langfuse.auth_check()

def get_trace_id():
    # This mocks getting it from somewhere outside
    global uuid_from_external
    return uuid_from_external

def intent_detect():
    trace_id = get_trace_id()
    client = StatefulClient(langfuse.client, trace_id, StateType.TRACE, trace_id, langfuse.task_manager)

    intent = client.span(CreateSpan(name = "intent", input = "Hello"))
    intent.generation(CreateGeneration(name="rephrase", input = "Hello"))
    intent.generation(CreateGeneration(name="detect", input = "Hello"))

def user_output():    
    trace_id = get_trace_id()
    client = StatefulClient(langfuse.client, trace_id, StateType.TRACE, trace_id, langfuse.task_manager)

    kb = client.span(CreateSpan(name = "knowledge", input = "Hello"))
    kb.generation(CreateGeneration(name = "embedding", input = "Hello"))
    kb.event(CreateEvent(name = "vector-db-search"))
    kb.generation(CreateGeneration(name = "summary"))

    client.generation(CreateEvent(name = "user-output", output = "How can I help you"))


def first_interaction():
    intent_detect()
    user_output()

def second_interaction():
    intent_detect()
    user_output()


# Handled in machine1
first_interaction()

time.sleep(5)

# Sometime later, handled in machine2
second_interaction()
```

### Describe the solution you'd like to see

Would like to see support for using existing trace_id in the langfuse client rather than taking StatefulClient if possible.

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
@surki There are multiple ways to do this using the Langfuse SDKs depending on your needs. I'd suggest the following:

langfuse.trace upserts on id, it is safe to call multiple times. Use this wherever you want to add observations to the trace.
```python
trace_id=get_trace_id()
trace = langfuse.trace(CreateTrace(id=trace_id))
```

Hope this helps
