### ISSUE TITLE
feat: Prompt Template Management

### ISSUE THREAD

**Issue by Manonandan** [langfuse/langfuse#691]
### Describe the feature you'd like to request

As of now in langfuse we get traces, generations, user info, feedback (scores), etc.
It would be great to have a feature like prompt template manager. 

### Describe the solution you'd like to see

Prompt management may contain 
1. Prompt Create, Read, Edit, Delete.
2. The update of the prompt should be the next version.
3. Choose which version of the prompt to use in which place.
4. View the Hierarchy of the prompts.
```
p1.0.0
    p1.1.0
         p1.1.1
    p1.2.0
p2.0.0
p3.0.0
```

It would be better if Integration with langchain's PromptTemplate

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
Hi @Manonandan, thanks for raising this. This is actually a roadmap item to add to Langfuse. No timeline on this yet though. Let's keep this issue to track and collect thoughts on this

**Comment by marcklingen** [comment]
Prompt mamagement v1 was included in https://github.com/langfuse/langfuse/releases/tag/v1.25.0
Feel free to share feedback if you have any! Closing this for now, more improvements to come to prompt management soon
