### ISSUE TITLE
feat(js-sdk): Allow omitting keys when initialising Langfuse

### ISSUE THREAD

**Issue by flxwu** [langfuse/langfuse#710]
### Describe the feature you'd like to request

Allow initialising using:

```js
const langfuse = new Langfuse(); 
```

### Describe the solution you'd like to see

If secretKey/publicKey are not specified, the sdk will attempt to read `process.env.LANGFUSE_PUBLIC_KEY` and `process.env.LANGFUSE_SECRET_KEY`.

Equivalent to https://langfuse.com/docs/sdk/python#initialize-client

### Contribute

- [X] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
I agree, this would be a valuable addition. We can use the `getEnv` utility function to ensure compatibility across different environments. (tests highly encouraged)
