### ISSUE TITLE
feat(ui): Show hostname on settings

### ISSUE THREAD

**Issue by flxwu** [langfuse/langfuse#712]
### Describe the feature you'd like to request

While watching a friend set up Langfuse, they wondered what region they signed up in (as they weren't sure anymore).

Instinctively, they looked in the settings section. (i then pointed that it'd probably also be shown in the url - but showing it more visually wouldn't hurt)

### Describe the solution you'd like to see

In the user settings, display the region / baseUrl you are in.

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
Agree that displaying the project's hostname in the settings is a great idea. Currently, it is only shown when generating the API keys, which is not an ideal location since the keys are only displayed once.

**Comment by khareyash05** [comment]
Hi @marcklingen Kindly review my PR.Thanks
