### ISSUE TITLE
feat: Dashboards for Experimentation / Versioning

### ISSUE THREAD

**Issue by flxwu** [langfuse/langfuse#713]
[Note: This is still a very vague idea in my head. Will need proper Feature Analysis and Technical Design before proceeding]

### Describe the feature you'd like to request

**User Journey:** I am making changes to my app and want to see how my app's LLM usage reacts to these changes"

https://github.com/langfuse/langfuse/issues/691 is somewhat related, although it is only a subset imo. Prompts are just one small piece of a larger puzzle that you can modify / tweak:

* LLM parameters
* Overall LLM setup / architecture
* Functions
* Pricing
* ...

## SDK

```
langfuse.trace({
   ...
   version: 'v0'
})
```

## UI
* On Dashboard Charts, group by Version
* On all tables, allow sorting/filtering by version

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
Already available (APIs and SDKs): [https://langfuse.com/docs/experimentation](https://langfuse.com/docs/experimentation).

Good idea to add charts or a summary table to the dashboard to shows the impact of new versions/releases on metrics (scores, latency, average cost) + total volume on each version.

**Comment by flxwu** [comment]
oh nice! didn't know this existed, should've done a quick docs search i guess 🙈 thanks!

**Comment by marcklingen** [comment]
Charts/tables for experimentation purposes will be part of https://github.com/langfuse/langfuse/discussions/1011. Closing this issue for now.
