### ISSUE TITLE
Invalid discriminator value. Expected 'trace-create' | 'observation-create' | 'observation-update' | 'score-create'bug: 

### ISSUE THREAD

**Issue by dove-young** [langfuse/langfuse#716]
### Describe the bug

langfuse python SDK always generate errors like

```
langfuse.request.APIErrors: [Langfuse] Invalid request data (400): [
  {
    "code": "invalid_union_discriminator",
    "options": [
      "trace-create",
      "observation-create",
      "observation-update",
      "score-create"
    ],
    "path": [
      "type"
    ],
    "message": "Invalid discriminator value. Expected 'trace-create' | 'observation-create' | 'observation-update' | 'score-create'"
  }
]
```

langfuse sdk version `2.0.1`
langfuse image `ghcr.io/langfuse/langfuse:latest`
containers

```
88f83e89481b   ghcr.io/langfuse/langfuse:latest           "docker-entrypoint.s…"   4 days ago   Up 3 hours             0.0.0.0:3000->3000/tcp                             langfuse-langfuse-server-1
db9374a51e2b   postgres                                   "docker-entrypoint.s…"   4 days ago   Up 3 hours             0.0.0.0:5432->5432/tcp                             langfuse-db-1
```

### To reproduce

run the python code as described in https://langfuse.com/docs/sdk/python#initialize-client

```python
from langfuse import Langfuse
import os
from dotenv import load_dotenv

load_dotenv(override=True)

langfuse_host = os.getenv("LANGFUSE_HOST", None)
langfuse_secret_key = os.getenv("LANGFUSE_SECRET_KEY", None)
langfuse_public_key = os.getenv("LANGFUSE_PUBLIC_KEY", None)

from langfuse import Langfuse
 
langfuse = Langfuse(
    debug=False,
    public_key = langfuse_public_key,
    secret_key = langfuse_secret_key,
    host = langfuse_host
)

trace = langfuse.trace(name = "llm-feature")

trace = langfuse.trace(
    name = "docs-retrieval",
    user_id = "user__935d7d1d-8625-4ef4-8651-544613e7bd22",
    metadata = {
        "env": "production",
        "email": "user@langfuse.com",
    }
)

# create span, sets start_time
span = trace.span(
    name="embedding-search",
    metadata={"database": "pinecone"},
    input = {'query': 'This document entails the OKR goals for ACME'},
)
 
# function, mocked
# retrieved_documents = retrieveDoc()
retrieved_documents = {"response": "[{'name': 'OKR Engineering', 'content': 'The engineering department defined the following OKR goals...'},{'name': 'OKR Marketing', 'content': 'The marketing department defined the following OKR goals...'}]"}
 
# update span and sets end_time
span.end(
    output=retrieved_documents
);
```

**Comment by maxdeichmann** [comment]
@dove-young looking into this. Thanks for reporting

**Comment by maxdeichmann** [comment]
> @dove-young looking into this. Thanks for reporting

@dove-young can you fetch the latest docker version of the server and try again?

**Comment by dove-young** [comment]
Good. re-pull the latest image solves this problem. the image digest is 

`sha256:93492dc1dfc27848897a59b075b810dea0eb2a61b747bba4aa571957e545ad90`

**Comment by marcklingen** [comment]
Perfect. Thanks for confirming

**Comment by davegildea** [comment]
> Good. re-pull the latest image solves this problem. the image digest is
> 
> `sha256:93492dc1dfc27848897a59b075b810dea0eb2a61b747bba4aa571957e545ad90`

What version is working for you ?

**Comment by maxdeichmann** [comment]
Also, you can GET the health endpoint to verify the container version: https://langfuse.com/docs/api-reference#tag/Health

This endpoint returns the GH release number: https://github.com/langfuse/langfuse/releases

**Comment by marcklingen** [comment]
Since @davegildea and Chris (from Discord) still have this issue on the latest langfuse release and SDK, I tried to quickly reproduce it but was unable to. Can you help with a colab that reproduces the problem?

My code: https://colab.research.google.com/drive/1i3vdywoUq7ZN54CP3uLn1HsSkLaWGHdC#scrollTo=Q-UxiIqKyNqh
The trace: https://cloud.langfuse.com/trace/f7d1b48f-712b-4e47-936e-5b935b40e345

**Comment by davegildea** [comment]
@maxdeichmann @marcklingen thank you both for your help, we have pulled the docker container listed above 
``` 
sha256:93492dc1dfc27848897a59b075b810dea0eb2a61b747bba4aa571957e545ad90 
```
and its now working for us

Thanks
Dave

**Comment by marcklingen** [comment]
Perfect, @davegildea, thanks for confirming that it works with the latest production version
