### ISSUE TITLE
bug: LangChain callback handler fails to upload data

### ISSUE THREAD

**Issue by HugoMichard** [langfuse/langfuse#717]
### Describe the bug

When using the `CallbackHandler` for LangChain, I am getting the following error 
```
Giving up execute_task_with_backoff(...) after 3 tries (langfuse.request.APIErrors: [Langfuse] Invalid request data (400): [
  {
    "code": "invalid_union_discriminator",
    "options": [
      "trace-create",
      "observation-create",
      "observation-update",
      "score-create"
    ],
    "path": [
      "type"
    ],
    "message": "Invalid discriminator value. Expected 'trace-create' | 'observation-create' | 'observation-update' | 'score-create'"
  }
], Invalid request data (400): [
  {
    "code": "invalid_union_discriminator",
    "options": [
      "trace-create",
      "observation-create",
      "observation-update",
      "score-create"
    ],
    "path": [
      "type"
    ],
    "message": "Invalid discriminator value. Expected 'trace-create' | 'observation-create' | 'observation-update' | 'score-create'"
  }
])
ERROR:backoff:Giving up execute_task_with_backoff(...) after 3 tries (langfuse.request.APIErrors: [Langfuse] Invalid request data (400): [
  {
    "code": "invalid_union_discriminator",
    "options": [
      "trace-create",
      "observation-create",
      "observation-update",
      "score-create"
    ],
    "path": [
      "type"
    ],
    "message": "Invalid discriminator value. Expected 'trace-create' | 'observation-create' | 'observation-update' | 'score-create'"
  }
], Invalid request data (400): [
  {
    "code": "invalid_union_discriminator",
    "options": [
      "trace-create",
      "observation-create",
      "observation-update",
      "score-create"
    ],
    "path": [
      "type"
    ],
    "message": "Invalid discriminator value. Expected 'trace-create' | 'observation-create' | 'observation-update' | 'score-create'"
  }
])
ERROR:langfuse:error uploading: [Langfuse] Invalid request data (400): [
  {
    "code": "invalid_union_discriminator",
    "options": [
      "trace-create",
      "observation-create",
      "observation-update",
      "score-create"
    ],
    "path": [
      "type"
    ],
    "message": "Invalid discriminator value. Expected 'trace-create' | 'observation-create' | 'observation-update' | 'score-create'"
  }
], Invalid request data (400): [
  {
    "code": "invalid_union_discriminator",
    "options": [
      "trace-create",
      "observation-create",
      "observation-update",
      "score-create"
    ],
    "path": [
      "type"
    ],
    "message": "Invalid discriminator value. Expected 'trace-create' | 'observation-create' | 'observation-update' | 'score-create'"
  }
]
Traceback (most recent call last):
  File "/home/hugo/code/corneille/.venv/lib/python3.8/site-packages/langfuse/task_manager.py", line 140, in upload
    self._upload_batch(batch)
  File "/home/hugo/code/corneille/.venv/lib/python3.8/site-packages/langfuse/task_manager.py", line 167, in _upload_batch
    execute_task_with_backoff(batch)
  File "/home/hugo/code/corneille/.venv/lib/python3.8/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/home/hugo/code/corneille/.venv/lib/python3.8/site-packages/langfuse/task_manager.py", line 165, in execute_task_with_backoff
    return self._client.batch_post(gzip=False, batch=batch, metadata=metadata)
  File "/home/hugo/code/corneille/.venv/lib/python3.8/site-packages/langfuse/request.py", line 53, in batch_post
    return self._process_response(
  File "/home/hugo/code/corneille/.venv/lib/python3.8/site-packages/langfuse/request.py", line 100, in _process_response
    raise APIErrors(
langfuse.request.APIErrors: [Langfuse] Invalid request data (400): [
  {
    "code": "invalid_union_discriminator",
    "options": [
      "trace-create",
      "observation-create",
      "observation-update",
      "score-create"
    ],
    "path": [
      "type"
    ],
    "message": "Invalid discriminator value. Expected 'trace-create' | 'observation-create' | 'observation-update' | 'score-create'"
  }
], Invalid request data (400): [
  {
    "code": "invalid_union_discriminator",
    "options": [
      "trace-create",
      "observation-create",
      "observation-update",
      "score-create"
    ],
    "path": [
      "type"
    ],
    "message": "Invalid discriminator value. Expected 'trace-create' | 'observation-create' | 'observation-update' | 'score-create'"
  }
]
```

An empty trace gets uploaded to my langfuse instance
![image](https://github.com/langfuse/langfuse/assets/15155145/50b5a34e-2d1f-429b-b651-6bc44c3a655f)

This seems to be a regression introduced in `2.0.1` as I do not have the error when pinning down my SDK version to `1.14.0`.

### To reproduce

Here is a minimal script to reproduce the error. I currently am using the [local machine deployment](https://langfuse.com/docs/deployment/local). I have tried getting the deployment to the latest version (`1.19.0`) but am still running into the issue.

```python
from langfuse.callback import CallbackHandler
from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate

PUBLIC_KEY = ...
SECRET_KEY = ...
llm = ...

handler = CallbackHandler(PUBLIC_KEY, SECRET_KEY, host="http://localhost:3000")
chain = LLMChain(llm=llm, prompt=PromptTemplate.from_template("{question}"))

print(chain({'question': 'hello world'}, callbacks=[handler]))

print(handler.get_trace_url())
print(handler.langfuse.get_trace_url())
```

### Additional information

With the reproduction code, I surprisingly got the trace URLs printed before the error described.

**Comment by marcklingen** [comment]
Happy to help debug

Are you sure that you are on the latest version of the Langfuse container?

Does this lead to an exception or is an error logged?


For context: traceurl is available  immediately as it does not depend on an api response. While the events are sent asynchronously in batches to the api, ids are generated by the sdk in order to use them downstream in applications without any delay

**Comment by jaindees** [comment]
I am also getting similar error while trying to update user_id, session_id or trace name later by taking control of the trace_id from the langchain handler. It throws following error. These scenarios were working with 1.14 version but breaking with 2.0.1. Also, server docker image is pointing to most latest image 1.19.3. Can you please help or provide guidance as how to set user_id, session_id, metadata and trace name fields through CallbackHandler for Langchain integration?

Giving up execute_task_with_backoff(...) after 3 tries (langfuse.request.APIErrors: [Langfuse] Error processing events (500): Internal Server Error)
ERROR:backoff:Giving up execute_task_with_backoff(...) after 3 tries (langfuse.request.APIErrors: [Langfuse] Error processing events (500): Internal Server Error)
ERROR:langfuse:error uploading: [Langfuse] Error processing events (500): Internal Server Error
Traceback (most recent call last):
  File "D:\DEV\PythonWorkspaces\genai\Lib\site-packages\langfuse\task_manager.py", line 140, in upload
    self._upload_batch(batch)
  File "D:\DEV\PythonWorkspaces\genai\Lib\site-packages\langfuse\task_manager.py", line 167, in _upload_batch
    execute_task_with_backoff(batch)
  File "D:\DEV\PythonWorkspaces\genai\Lib\site-packages\backoff\_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DEV\PythonWorkspaces\genai\Lib\site-packages\langfuse\task_manager.py", line 165, in execute_task_with_backoff
    return self._client.batch_post(gzip=False, batch=batch, metadata=metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DEV\PythonWorkspaces\genai\Lib\site-packages\langfuse\request.py", line 53, in batch_post
    return self._process_response(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DEV\PythonWorkspaces\genai\Lib\site-packages\langfuse\request.py", line 100, in _process_response
    raise APIErrors(
langfuse.request.APIErrors: [Langfuse] Error processing events (500): Internal Server Error

**Comment by marcklingen** [comment]
Thanks for the details.

To pinpoint the problem, would it be an options for you to quickly test if you get the same errors when using Langfuse cloud? Thereby we get backend logs + rule out any self-hosting configuration issues. 

(You can use a free account)

**Comment by jaindees** [comment]
Thanks Marc for prompt response. The above example works but later when I try to get hold of same trace.id and try to fire another langfuse.trace() request with additional parameters like input, output, metadata etc. it errors out on our server but seems to work on langfuse cloud. Not sure what is missing. Got this from server log if this could help to figure out what is going wrong here.

handling single event df8e4211-59d7-446c-8fc3-7fb7610849b1 {
  "id": "df8e4211-59d7-446c-8fc3-7fb7610849b1",
  "timestamp": "2023-12-20T10:31:22.447347+00:00",
  "type": "trace-create",
  "body": {
    "id": "f34659e1-ea0c-4627-bc1d-f1897c459674",
    "name": "LangChain-Update-Trace",
    "sessionId": "session-5678",
    "userId": "user-5678",
    "release": "1.0.0"
  }
}
Trying to create trace, project  clq6oi45x000jxnnr84atg5su , body: {
  id: 'f34659e1-ea0c-4627-bc1d-f1897c459674',
  name: 'LangChain-Update-Trace',
  sessionId: 'session-5678',
  userId: 'user-5678',
  release: '1.0.0'
}
prisma:error
Invalid `prisma.trace.upsert()` invocation:


Unique constraint failed on the fields: (`id`)
retrying processing events 1
handling single event df8e4211-59d7-446c-8fc3-7fb7610849b1 {
  "id": "df8e4211-59d7-446c-8fc3-7fb7610849b1",
  "timestamp": "2023-12-20T10:31:22.447347+00:00",
  "type": "trace-create",
  "body": {
    "id": "f34659e1-ea0c-4627-bc1d-f1897c459674",
    "name": "LangChain-Update-Trace",
    "sessionId": "session-5678",
    "userId": "user-5678",
    "release": "1.0.0"
  }
}
Trying to create trace, project  clq6oi45x000jxnnr84atg5su , body: {
  id: 'f34659e1-ea0c-4627-bc1d-f1897c459674',
  name: 'LangChain-Update-Trace',
  sessionId: 'session-5678',
  userId: 'user-5678',
  release: '1.0.0'
}
prisma:error
Invalid `prisma.trace.upsert()` invocation:


Unique constraint failed on the fields: (`id`)
retrying processing events 2
handling single event df8e4211-59d7-446c-8fc3-7fb7610849b1 {
  "id": "df8e4211-59d7-446c-8fc3-7fb7610849b1",
  "timestamp": "2023-12-20T10:31:22.447347+00:00",
  "type": "trace-create",
  "body": {
    "id": "f34659e1-ea0c-4627-bc1d-f1897c459674",
    "name": "LangChain-Update-Trace",
    "sessionId": "session-5678",
    "userId": "user-5678",
    "release": "1.0.0"
  }
}
Trying to create trace, project  clq6oi45x000jxnnr84atg5su , body: {
  id: 'f34659e1-ea0c-4627-bc1d-f1897c459674',
  name: 'LangChain-Update-Trace',
  sessionId: 'session-5678',
  userId: 'user-5678',
  release: '1.0.0'
}
prisma:error
Invalid `prisma.trace.upsert()` invocation:


Unique constraint failed on the fields: (`id`)
retrying processing events 3
Error handling event: PrismaClientKnownRequestError:
Invalid `prisma.trace.upsert()` invocation:


Unique constraint failed on the fields: (`id`)
    at si.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:125:6817)
    at si.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:125:6151)
    at si.request (/app/node_modules/@prisma/client/runtime/library.js:125:5859)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:130:10025)
    at async v.process (/app/.next/server/chunks/5811.js:37:3852)
    at async w (/app/.next/server/chunks/5811.js:1:2807)
    at async BackOff.request (/app/.next/server/chunks/5811.js:1:1893) {
  code: 'P2002',
  clientVersion: '5.7.0',
  meta: { modelName: 'Trace', target: [ 'id' ] }
}

**Comment by maxdeichmann** [comment]
> it errors out on our server but seems to work on langfuse cloud.

Are you 100% sure that you have the latest docker container? Sometimes, Docker does some caching. The docker version and the one we run hosted are identical. Different behavior is not expected here.

**Comment by maxdeichmann** [comment]
> "options": [
>       "trace-create",
>       "observation-create",
>       "observation-update",
>       "score-create"
>     ],

@HugoMichard thanks for reporting. The options in the error messages are from earlier versions before `1.19.0`. Can you double check that you run the latest server version? Docker sometimes does some caching.

**Comment by HugoMichard** [comment]
> > "options": [
> > "trace-create",
> > "observation-create",
> > "observation-update",
> > "score-create"
> > ],
> 
> @HugoMichard thanks for reporting. The options in the error messages are from earlier versions before `1.19.0`. Can you double check that you run the latest server version? Docker sometimes does some caching.

I am currently running with version `1.19.1`. To make sure that I am running that version, I directly checked out on [commit `e6662a9`](https://github.com/langfuse/langfuse/commit/e6662a9b187275b7aa15ccfe7389bac006420113), then did `docker compose rm -f` followed by `docker compose up --force-recreate --build` to launch the containers while trying to avoid Docker caching.

Am I missing something ?

**Comment by HugoMichard** [comment]
Here are the logs on the server 
```
langfuse-langfuse-server-1  | Prisma schema loaded from prisma/schema.prisma
langfuse-langfuse-server-1  | Datasource "db": PostgreSQL database "postgres", schema "public" at "db:5432"
langfuse-langfuse-server-1  | 
langfuse-langfuse-server-1  | 68 migrations found in prisma/migrations
langfuse-langfuse-server-1  | 
langfuse-langfuse-server-1  | 
langfuse-langfuse-server-1  | No pending migrations to apply.
langfuse-langfuse-server-1  |    ▲ Next.js 14.0.3
langfuse-langfuse-server-1  |    - Local:        
langfuse-langfuse-server-1  |    - Network:   
langfuse-langfuse-server-1  | 
langfuse-langfuse-server-1  |  ✓ Ready in 721ms
langfuse-langfuse-server-1  | handling ingestion event [
langfuse-langfuse-server-1  |   {
langfuse-langfuse-server-1  |     "id": "43fdd1a5-0270-4eb5-a00f-393744c25c96",
langfuse-langfuse-server-1  |     "timestamp": "2023-12-20T14:06:26.814447+00:00",
langfuse-langfuse-server-1  |     "type": "trace-create",
langfuse-langfuse-server-1  |     "body": {
langfuse-langfuse-server-1  |       "id": "d1277b4e-4ef2-4ca1-b2f2-1158cd282845",
langfuse-langfuse-server-1  |       "name": "LLMChain",
langfuse-langfuse-server-1  |       "metadata": {}
langfuse-langfuse-server-1  |     }
langfuse-langfuse-server-1  |   }
langfuse-langfuse-server-1  | ]
langfuse-langfuse-server-1  | handling single event 43fdd1a5-0270-4eb5-a00f-393744c25c96 {
langfuse-langfuse-server-1  |   "id": "43fdd1a5-0270-4eb5-a00f-393744c25c96",
langfuse-langfuse-server-1  |   "timestamp": "2023-12-20T14:06:26.814447+00:00",
langfuse-langfuse-server-1  |   "type": "trace-create",
langfuse-langfuse-server-1  |   "body": {
langfuse-langfuse-server-1  |     "id": "d1277b4e-4ef2-4ca1-b2f2-1158cd282845",
langfuse-langfuse-server-1  |     "name": "LLMChain",
langfuse-langfuse-server-1  |     "metadata": {}
langfuse-langfuse-server-1  |   }
langfuse-langfuse-server-1  | }
langfuse-langfuse-server-1  | Trying to create trace, project  clptuavc20001de8t989k6q52 , body: {
langfuse-langfuse-server-1  |   id: 'd1277b4e-4ef2-4ca1-b2f2-1158cd282845',
langfuse-langfuse-server-1  |   name: 'LLMChain',
langfuse-langfuse-server-1  |   metadata: {}
langfuse-langfuse-server-1  | }
langfuse-langfuse-server-1  | handling ingestion event [
langfuse-langfuse-server-1  |   {
langfuse-langfuse-server-1  |     "id": "43fdd1a5-0270-4eb5-a00f-393744c25c96",
langfuse-langfuse-server-1  |     "timestamp": "2023-12-20T14:06:26.814447+00:00",
langfuse-langfuse-server-1  |     "type": "trace-create",
langfuse-langfuse-server-1  |     "body": {
langfuse-langfuse-server-1  |       "id": "d1277b4e-4ef2-4ca1-b2f2-1158cd282845",
langfuse-langfuse-server-1  |       "name": "LLMChain",
langfuse-langfuse-server-1  |       "metadata": {}
langfuse-langfuse-server-1  |     }
langfuse-langfuse-server-1  |   }
langfuse-langfuse-server-1  | ]
langfuse-langfuse-server-1  | handling single event 43fdd1a5-0270-4eb5-a00f-393744c25c96 {
langfuse-langfuse-server-1  |   "id": "43fdd1a5-0270-4eb5-a00f-393744c25c96",
langfuse-langfuse-server-1  |   "timestamp": "2023-12-20T14:06:26.814447+00:00",
langfuse-langfuse-server-1  |   "type": "trace-create",
langfuse-langfuse-server-1  |   "body": {
langfuse-langfuse-server-1  |     "id": "d1277b4e-4ef2-4ca1-b2f2-1158cd282845",
langfuse-langfuse-server-1  |     "name": "LLMChain",
langfuse-langfuse-server-1  |     "metadata": {}
langfuse-langfuse-server-1  |   }
langfuse-langfuse-server-1  | }
langfuse-langfuse-server-1  | Trying to create trace, project  clptuavc20001de8t989k6q52 , body: {
langfuse-langfuse-server-1  |   id: 'd1277b4e-4ef2-4ca1-b2f2-1158cd282845',
langfuse-langfuse-server-1  |   name: 'LLMChain',
langfuse-langfuse-server-1  |   metadata: {}
langfuse-langfuse-server-1  | }
langfuse-langfuse-server-1  | handling ingestion event [
langfuse-langfuse-server-1  |   {
langfuse-langfuse-server-1  |     "id": "43fdd1a5-0270-4eb5-a00f-393744c25c96",
langfuse-langfuse-server-1  |     "timestamp": "2023-12-20T14:06:26.814447+00:00",
langfuse-langfuse-server-1  |     "type": "trace-create",
langfuse-langfuse-server-1  |     "body": {
langfuse-langfuse-server-1  |       "id": "d1277b4e-4ef2-4ca1-b2f2-1158cd282845",
langfuse-langfuse-server-1  |       "name": "LLMChain",
langfuse-langfuse-server-1  |       "metadata": {}
langfuse-langfuse-server-1  |     }
langfuse-langfuse-server-1  |   }
langfuse-langfuse-server-1  | ]
langfuse-langfuse-server-1  | handling single event 43fdd1a5-0270-4eb5-a00f-393744c25c96 {
langfuse-langfuse-server-1  |   "id": "43fdd1a5-0270-4eb5-a00f-393744c25c96",
langfuse-langfuse-server-1  |   "timestamp": "2023-12-20T14:06:26.814447+00:00",
langfuse-langfuse-server-1  |   "type": "trace-create",
langfuse-langfuse-server-1  |   "body": {
langfuse-langfuse-server-1  |     "id": "d1277b4e-4ef2-4ca1-b2f2-1158cd282845",
langfuse-langfuse-server-1  |     "name": "LLMChain",
langfuse-langfuse-server-1  |     "metadata": {}
langfuse-langfuse-server-1  |   }
langfuse-langfuse-server-1  | }
langfuse-langfuse-server-1  | Trying to create trace, project  clptuavc20001de8t989k6q52 , body: {
langfuse-langfuse-server-1  |   id: 'd1277b4e-4ef2-4ca1-b2f2-1158cd282845',
langfuse-langfuse-server-1  |   name: 'LLMChain',
langfuse-langfuse-server-1  |   metadata: {}
langfuse-langfuse-server-1  | }
```

**Comment by jaindees** [comment]
@marcklingen , @maxdeichmann , Just to let you know we got this fixed in our environment by dropping the database and recreating a fresh one. Our docker image was the latest one. After creating a new database, it started working like a charm.

_**Quick few questions though._**
1. Lagnchain agents do not log all the functions (function calling feature of OpenAI) passed as part of a LLM call. Do we have some sample as how to make this work or any plan to bring this feature in future releases?
2. Any specific reason to not to support update trace? That is what I was trying in my earlier examples since earlier input/output at trace level were not getting reflected but seems it is supported now. Seems update trace works in the same way create trace works, just pass the original trace_id for any updates using langfuse.trace() api. Am I correct?
3. Any plans to update cost part for other models like google's Palm2, Claude, Cohere etc.
4. When can we expect some data compliance like SOC2, ISO27001 etc.?

BTW, I really love the tool and it is great way to capture the data and get entire observability to a LLM application. Thanks for building it and making it available to the community. Appreciate all your efforts :)

**Comment by maxdeichmann** [comment]
> > > "options": [
> > > "trace-create",
> > > "observation-create",
> > > "observation-update",
> > > "score-create"
> > > ],
> > 
> > 
> > @HugoMichard thanks for reporting. The options in the error messages are from earlier versions before `1.19.0`. Can you double check that you run the latest server version? Docker sometimes does some caching.
> 
> I am currently running with version `1.19.1`. To make sure that I am running that version, I directly checked out on [commit `e6662a9`](https://github.com/langfuse/langfuse/commit/e6662a9b187275b7aa15ccfe7389bac006420113), then did `docker compose rm -f` followed by `docker compose up --force-recreate --build` to launch the containers while trying to avoid Docker caching.
> 
> Am I missing something ?

According to this [article](https://www.baeldung.com/ops/docker-compose-latest-image), you have to execute `docker-compose pull` to fetch the latest containers. I tested it locally and it worked for me. I will add that to our docs for future reference.

**Comment by maxdeichmann** [comment]
> @marcklingen , @maxdeichmann , Just to let you know we got this fixed in our environment by dropping the database and recreating a fresh one. Our docker image was the latest one. After creating a new database, it started working like a charm.
> 
> **_Quick few questions though:-_**
> 
> 1. Lagnchain agents do not log all the functions (function calling feature of OpenAI) passed as part of a LLM call. Do we have some sample as how to make this work or any plan to bring this feature in future releases?
> 2. Any specific reason to not to support update trace? That is what I was trying in my earlier examples since earlier input/output at trace level were not getting reflected but seems it is supported now. Seems update trace works in the same way create trace works, just pass the original trace_id for any updates using langfuse.trace() api. Am I correct?
> 3. Any plans to update cost part for other models like google's Palm2, Claude, Cohere etc.
> 4. When can we expect some data compliance like SOC2, ISO27001 etc.?
> 
> BTW, I really love the tool and it is great way to capture the data and get entire observability to a LLM application. Thanks for building it and making it available to the community. Appreciate all your efforts :)

Sorry that you had to drop the db. I am still not sure what caused your issue. To answer your questions:

1. langchain agent function call: i will look into this.
2. updating traces is possible with the newest Python SDK: https://langfuse.com/docs/sdk/python#traces. Under the hood, it does exactly what you said
3. Cost: we know we lack support here. This has very high priority on our end.
4. We are currently working on compliance. See here: https://langfuse.com/docs/data-security-privacy#compliance. Feel free to reach out to [security@langfuse.com](mailto:security@langfuse.com) with specific questions on that topic.

**Comment by jaindees** [comment]
Thank @maxdeichmann for your prompt responses. Appreciated!!!

**Comment by HugoMichard** [comment]
that worked for me, thank you very much @maxdeichmann for your help ! :pray:

**Comment by maxdeichmann** [comment]
Your welcome, both of you :)
