### ISSUE TITLE
feat: support middle click on all buttons

### ISSUE THREAD

**Issue by backmask** [langfuse/langfuse#744]
### Describe the feature you'd like to request

I'd like to be able to open multiple traces in new tabs. This currently works well with the side-menu. I think all links in tables are not working.

### Describe the solution you'd like to see

Links that change the router path should support a middle mouse click to open that link in a new tab
For instance: opening a trace in the trace explorer

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
Such a good one, thanks for the feedback 🙏 Will prioritize this

**Comment by marcklingen** [comment]
@backmask the change is included in https://github.com/langfuse/langfuse/releases/tag/v1.23.0
(the Docker image is still being built rn)
