### ISSUE TITLE
feat: Design the SideBar's scrollbar

### ISSUE THREAD

**Issue by khareyash05** [langfuse/langfuse#751]
### Describe the feature you'd like to request

The current scrollbar looks dull. A stylised scrollbar will look great

### Describe the solution you'd like to see

A Next styled scrollbar

### Contribute

- [X] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
@khareyash05 I'm not sure what you are referring to. To keep it simple I'd rather not apply custom css to the scrollbars and keep the   default look on each device/OS.

**Comment by khareyash05** [comment]
@marcklingen I am referring to the sidebar's scrollbar. I agree with you.
