### ISSUE TITLE
bug: Redundant span with callback on Langchain model

### ISSUE THREAD

**Issue by YuvalBergerP** [langfuse/langfuse#761]
### Describe the bug

I am using Langfuse v2.2.1 and Langchain v0.0.345.
I'm not using a chain, but only using Langchain to wrap the model calls, using the Langfuse callback on the model wrapper. It generates the traces, but in a weird structure: Each model call creates two children, a span an a generation. the span includes the input but not the output, and all other data also included in the generation. The generation is not under the span, but a sibling to it.
The behavior also reproduces if I uses `generate` instead of `invoke`. Putting the callback on the `generate` method also reproduced the same result, and putting it on the `invoke` method produced an empty trace.

### To reproduce

```
langfuse = Langfuse(
    sdk_integration=SDKIntegrationTypes.LANGCHAIN,
)
trace = langfuse.trace(
    id=str(uuid.uuid4()),
    name="GenAI Request",
)
if trace:
    handler = trace.get_langchain_handler()
    if handler:
        callbacks = [handler]
        model = ChatOpenAI(
            max_retries=3,
            timeout=10,
            callbacks=callbacks,
        )
        b = model.invoke(
            [ChatMessage(content="hello", role="user")],
        )
        langfuse.flush()
```

### Additional information

<img width="1369" alt="image" src="https://github.com/langfuse/langfuse/assets/98692944/c04ce9ca-4198-49e8-8503-9c7d84805c80">
<img width="1368" alt="image" src="https://github.com/langfuse/langfuse/assets/98692944/627a2468-6b11-4292-bb46-6b5552f30f9e">

**Comment by maxdeichmann** [comment]
@YuvalBergerP thanks for raising this and for sharing the code snippet. I was able to re-produce this. We will provide a fix for this and let you know here.

**Comment by maxdeichmann** [comment]
@YuvalBergerP i just shipped a fix for this: https://github.com/langfuse/langfuse-python/releases/tag/v2.6.4

Please re-open the issue if you come across again.
