### ISSUE TITLE
bug: generation time is 0s when using `trace.generation` after calling `generation.end()`

### ISSUE THREAD

**Issue by nilsreichardt** [langfuse/langfuse#779]
### Describe the bug

<img width="697" alt="image" src="https://github.com/langfuse/langfuse/assets/24459435/c5a0a8c3-69ea-4d10-a2df-c25f499af19b">

You can in this screenshot that the time for the "usage-playground" generation is -0.00s. This happens, when you call `trace.generation()` after calling `generation.end()`.

### To reproduce

Use this code sample:

```ts
import Langfuse from "langfuse";
import OpenAI from "openai";
import { ChatCompletionMessageParam } from "openai/resources";

async function main() {
  const openai = new OpenAI({
    apiKey: process.env.OPENAI_KEY!,
  });

  const langfuse = new Langfuse({
    publicKey: process.env.LANGFUSE_PUBLIC_KEY!,
    secretKey: process.env.LANGFUSE_SECRET_KEY!,
  });

  const input = "What is Langfuse?";
  const messages: Array<ChatCompletionMessageParam> = [
    {
      role: "system",
      content: "Be a helpful assistant.",
    },
    {
      role: "user",
      content: input,
    },
  ];
  const model = "gpt-3.5-turbo-1106";

  const trace = langfuse.trace({
    name: "playground",
  });
  const generation = trace.generation({
    name: `usage-playground`,
    model: model,
    completionStartTime: new Date(),
    input: input,
  });

  const chatCompletion = await openai.chat.completions.create({
    messages: messages,
    model: model,
  });

  generation.end({
    output: chatCompletion,
  });

  // This is causing the bug:
  trace.generation({
    id: generation.id,
    metadata: {
      tokensPerCard: -1,
    },
  });
  
// This works as expected:
//   generation.end({
//     metadata: {
//       tokensPerCard: -1,
//     },
//   });

  console.log(JSON.stringify(chatCompletion, null, 2));
  await langfuse.shutdownAsync();
}

// eslint-disable-next-line @typescript-eslint/no-floating-promises
main();
```

### Additional information

JS SDK: `v2.0.2`
Discord thread: https://discord.com/channels/1111061815649124414/1111063352593088633/1187541559583977603

**Comment by flxwu** [comment]
Calling `trace.generation({id: generation.id})` after `generation.end` will overwrite the generation object. I think this is working as intended, such that you're able to reset / update the parameters of the generation as you like.

Thus I'm wondering, why would you use 

```
trace.generation({
    id: generation.id,
    metadata: {
      tokensPerCard: -1,
    },
  });
```

instead of 

```
generation.end({
     metadata: {
       tokensPerCard: -1,
     },
   });
```

?

@nilsreichardt btw - i believe your example here is different from the code you reported on discord 🤔

**Comment by flxwu** [comment]
@nilsreichardt btw; i believe this code is different from the one you reported on discord, as you're not using `trace.generation({ id: generation.id })` after `generation.end()` in your discord code 🤔

**Comment by nilsreichardt** [comment]
In my code, I made a change to ensure that the `generation` object is accessible even after parsing the response from calling GPT. This fixed the issue I was experiencing. Thanks to @flxwu for the help ❤️

@Langfuse team, feel free to close this ticket.
