### ISSUE TITLE
feat: Add API to return version of self-hosted Langfuse deployment

### ISSUE THREAD

**Issue by jmaness** [langfuse/langfuse#787]
### Describe the feature you'd like to request

To help investigate issues, knowing the specific version of Langfuse deployed in an environment would be useful. 

### Describe the solution you'd like to see

One possible solution could be an API that returns the Langfuse version string. For example `GET /version` could return `1.25.0`.

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
Great idea @jmaness, thanks. I've just added the current version to the response of /api/public/health. See API reference for details. This will be in the next release later today

**Comment by marcklingen** [comment]
Included in https://github.com/langfuse/langfuse/releases/tag/v1.26.0
