### ISSUE TITLE
bug: "Exception: Run not found, see docs what to do in this case."

### ISSUE THREAD

**Issue by lbatteau** [langfuse/langfuse#808]
### Describe the bug

We are using Langfuse integrated with Langchain in a production FastAPI application. Up until now we were recreating the chains for each request, but when we stopped doing this, we started to see a lot of the following errors in our logs:

```
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/langfuse/callback.py", line 393, in on_chain_end
    raise Exception("run not found")
Exception: run not found
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/langfuse/callback.py", line 236, in on_chain_start
    self.runs[run_id] = self.runs[parent_run_id].span(
KeyError
UUID('fc8e2cc9-2f3c-47a7-9cea-76ffa21c217a')
```

```
Traceback (most recent call last):
            self.log.debug(
                f"on retriever start: run_id: {run_id} parent_run_id: {parent_run_id}"
            )
            if parent_run_id is None or parent_run_id not in self.runs:
                raise Exception("parent run not found")
Exception
parent run not found
```

Is it possible that the Langfuse CallbackHandler is not suitable for async? 

> Advanced if you use a sync CallbackHandler while using an async method to run your LLM / Chain / Tool / Agent, it will still work. However, under the hood, it will be called with [run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor) which can cause issues if your CallbackHandler is not thread-safe.

See https://python.langchain.com/docs/modules/callbacks/async_callbacks

### To reproduce

Unfortunately we cannot share proprietary code, but this is how we create the CallbackHandler:

```python
def get_langfuse_callback() -> CallbackHandler | None:
    return (
        CallbackHandler(
            host=settings.langfuse.host,
            public_key=settings.langfuse.public_key,
            secret_key=settings.langfuse.secret_key,
        )
        if settings.langfuse
        else None
    )
```

And this is how it gets called:

```python
result = await self._chain.acall(
                {
                    "question": question,
                    "prompt_instruction": prompt_instruction,
                    "chat_history": [
                        (question_answer.question, question_answer.answer) for question_answer in chat_history[-10:]
                    ],
                },
                callbacks=[self._langfuse_callback] if self._langfuse_callback else [],
            )
```

### Additional information

The exception mentions the docs. We've searched high and low but can't find anything relevant.

**Comment by lbatteau** [comment]
We have to disable Langfuse in production as it is crashing the evaluations, please prioritize!

**Comment by skywateryang** [comment]
@marcklingen 
We are suffering from same issue when calling API parallelly using ThreadPoolExecutor or langchain.batch

**Comment by bowheadadmin** [comment]
If it helps, the bug is specially noticeable if you execute multiple async calls with a callback handler in a loop

**Comment by marcklingen** [comment]
async/batch is currently not officially supported: https://langfuse.com/docs/integrations/langchain/tracing#supported-langchain-interfaces

This is work-in-progress, we'll add support for this soon!

**Comment by lbatteau** [comment]
What happened to

> This is work-in-progress, we'll add support for this soon!

??

**Comment by marcklingen** [comment]
@lbatteau meant to reference this release as it includes slight changes for async/batch: https://github.com/langfuse/langfuse-python/releases/tag/v2.22.0

Let me know if this works now as expected!

**Comment by lbatteau** [comment]
Great, going to try it out!
