### ISSUE TITLE
feat: Implement CallbackHandler for Llamaindex

### ISSUE THREAD

**Issue by spreeni** [langfuse/langfuse#819]
### Describe the feature you'd like to request

I would like to use Langfuse with [Llamaindex](https://github.com/run-llama/llama_index) to track my LLM interactions. I would like to use a similar callback handler to the langchain one.

### Describe the solution you'd like to see

A callback handler adjusted for the Llamaindex interface would be nice. As the library builds onto langchain, the interface is not super different.

[Code for the interface of a Lllamaindex callback handler](https://github.com/run-llama/llama_index/blob/main/llama_index/callbacks/base_handler.py)

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
Hi @spreeni, agree that this would be useful. I'm already in touch with the llamaindex team to discuss the details and stability of the interfaces. Let's continue the discussion here as we clean up the GitHub issues to contain prioritized features only (on which we can collaborate as PRs): https://github.com/langfuse/langfuse/discussions/828
