### ISSUE TITLE
bug: token_usage error for gemini-pro in LangChain

### ISSUE THREAD

**Issue by SathinduGA** [langfuse/langfuse#822]
### Describe the bug

When integrating with LangChain and using gemini-pro model, there is an error saying `KeyError: 'token_usage'`

![Screenshot 2024-01-05 at 3 12 33 PM](https://github.com/langfuse/langfuse/assets/11785398/98cb8b89-5a5f-4bd2-a073-3d8846322333)

### To reproduce

Install `langchain` and `langfuse` python SDKs and follow  [this](https://python.langchain.com/docs/integrations/chat/google_generative_ai) LangChain tutorial to use Google Gemini Pro models with LangChain.

```
from langchain_google_genai import ChatGoogleGenerativeAI
from langfuse.callback import CallbackHandler

handler = CallbackHandler()
model = ChatGoogleGenerativeAI(model="gemini-pro", convert_system_message_to_human=True, callbacks=[handler])
model(
    [
        SystemMessage(content="Answer only yes or no."),
        HumanMessage(content="Is apple a fruit?"),
    ]
)
```

**Comment by maxdeichmann** [comment]
@SathinduGA, thanks for reporting this issue. As of [release 2.11.0](https://github.com/langfuse/langfuse-python/releases/tag/v2.11.0), this issue was resolved. Feel free to re-open this issue if this appears again.
