### ISSUE TITLE
bug:(docs): Erroneous Alerts on Signing up to updates on Langfuse  

### ISSUE THREAD

**Issue by khareyash05** [langfuse/langfuse#835]
### Describe the bug

Bug - On subscribing for updates on the website. It works fine the first time but on typing the same email shows 
UI - The alert doesnt seem a good way to show this, one can also generate a Dialog Box for showing the same message
![Screenshot from 2024-01-07 22-43-30](https://github.com/langfuse/langfuse/assets/60147732/5fce19bd-940b-4058-988d-491ffc4bd9f0)

### To reproduce

Subscribe to updates again with same email

### Additional information

I would like to work on this

**Comment by marcklingen** [comment]
The API for now returned an error if a user was already subscribed. In your case this happened as there were two API requests sent right after another. I've just fixed it to not error when the contact already exists. Thanks for reporting!
