### ISSUE TITLE
bug: costs are not tracked with gpt-35-turbo-1106 in  azure openai

### ISSUE THREAD

**Issue by langgg0511** [langfuse/langfuse#848]
### Describe the bug

![image](https://github.com/langfuse/langfuse/assets/38091079/64dccf98-95ae-4877-a88f-d1ffa3518b72)

### To reproduce

trace.generation(model="gpt-35-turbo-1106")

**Comment by maxdeichmann** [comment]
@langgg0511 wait for updates on cost. We will make things much easier there in the next days.

**Comment by marcklingen** [comment]
This was fixed in Langfuse v2.0.0
