### ISSUE TITLE
feat(UI): Open trace in new tab

### ISSUE THREAD

**Issue by lkNGAT** [langfuse/langfuse#851]
### Describe the feature you'd like to request
I would like to be able to open traces in a new tab while keeping a filter selection.
Sometimes I want to filter for a comination of score and value and look into a trace. 

### Describe the solution you'd like to see
Right clicking on the trace id and providing the option to "Open in a new tab".

### Additional information
No response

### Contribute
No response

**Comment by marcklingen** [comment]
This works as expected:

https://github.com/langfuse/langfuse/assets/2834609/57b57311-9c1f-4a16-bbe9-38ababf093e0

Closing for now, happy to help debug if you can share more details
