### ISSUE TITLE
bug: generation fails silently if there are iterables in the model_parameters dictionary

### ISSUE THREAD

**Issue by norton120** [langfuse/langfuse#865]
### Describe the bug

Just upgraded to Python sdk 2.6.0, and certain generations have been sporadically absent from our traces. 
After quite a bit of digging, it looks like the presence of iterables in `model_parameters` causes the generation to fail silently. 

### To reproduce

```
generation = trace.generation(
                    name="vllm_completion",
                    ...
                    model_parameters={'temperature': 0.0, 'max_tokens': 264, "stop": ['\nUser','\nuser']})

assert generation is None 

generation = trace.generation(
                    name="vllm_completion",
                    ...
                    model_parameters={'temperature': 0.0, 'max_tokens': 264, "stop": '\nuser'})

assert generation is not None

```

The newlines do not seem to make a difference - any iterable for any key in `model_parameters` appears to have the same effect.

**Comment by maxdeichmann** [comment]
All changes merged and deployed.
