### ISSUE TITLE
bug: Allow opening links in new tab

### ISSUE THREAD

**Issue by ricklamers** [langfuse/langfuse#877]
### Describe the bug

![Screenshot 2024-01-14 at 10 10 54 AM](https://github.com/langfuse/langfuse/assets/1309307/9f573cb6-4b07-45c9-b8e7-c99d05bc4798)

Unable to open links like these in new tabs

### To reproduce

Try clicking a link

**Comment by maxdeichmann** [comment]
@ricklamers when i click 'command' while clicking a link, it opens up in a new tab, otherwise it opens up in the same tab. I think this is expected behavior. If this does not work for you, feel free to re-open the issue.

**Comment by ricklamers** [comment]
I tried that (hold Command, click), doesn't work. Don't see a version in the UI but build ID: ieGfpTysxPFaGCIa28hyN
