### ISSUE TITLE
bug: Filtering on metadata keys for Generation doesn't work

### ISSUE THREAD

**Issue by bryan-agicap** [langfuse/langfuse#910]
### Describe the bug

In Tracing > Generation table

Filtering on metadata keys for generation doesn't work. 

It filters on the metadata keys from the traces instead.

### To reproduce

Here in this first image I don't have any filters applied. So it displays every generations correctly. As you can see I have some report_generation with a "language" metadata key
![chrome_ooCR94GMA5](https://github.com/langfuse/langfuse/assets/145330610/d297c986-7952-4b80-96d1-d51d3cd8afed)

But then if we filter the metadata key "language" contains "FR", it actually doesn't display the report_generation with the metadata key. It seems to display the audio_transcription that have a trace with metadata language key "FR".
![chrome_b5V71G2QCJ](https://github.com/langfuse/langfuse/assets/145330610/c534ad9d-c34f-49a4-b4d0-ab381f483e46)

### Additional information

A workaround for now seems to apply the metadata in both the traces and the generations.

**Comment by maxdeichmann** [comment]
@bryan-agicap thanks for raising this! Just fixed the issue here: https://github.com/langfuse/langfuse/pull/911

Expect this to be live in the next 20 min.

**Comment by bryan-agicap** [comment]
⚡ 🙏 thanks!
