### ISSUE TITLE
bug: Score creation access denied

### ISSUE THREAD

**Issue by bryan-agicap** [langfuse/langfuse#914]
### Describe the bug

Getting 'Access denied for score creation' when trying to create a score from langfuse python SDK.
I can successfully create a trace, generation or span from my server, but cannot create a score. (verified auth)

### To reproduce

os.environ["LANGFUSE_HOST"] = settings.langfuse.host
os.environ["LANGFUSE_PUBLIC_KEY"] = settings.langfuse.public_key
os.environ["LANGFUSE_SECRET_KEY"] = settings.langfuse.secret_key

langfuse = Langfuse()

langfuse.score(
    trace_id=payload.event.item.ts,
    name="reaction_added",
    comment=None,
    value=score,
)

### Additional information

The event sent to my langfuse server is the following (appearing in my logs)
![image](https://github.com/langfuse/langfuse/assets/145330610/9cc7b076-5992-44e3-b1dd-31b26241ef30)

in the function `checkApiAccessScope()`
there is this resource.type case
```

    case "score":
      const scoreCheck =
        (await prisma.score.count({
          where: {
            id: resource.id,
            trace: { projectId },
          },
        })) === 1;
      if (!scoreCheck)
        console.log("score check", scoreCheck, resource.id, projectId);
      return scoreCheck;
    default:
      return false;
```
      
Could it be that the event type name changed from score to score-create ?

**Comment by maxdeichmann** [comment]
Hi @bryan-agicap, thanks for raising this. Are you sure, that the trace exists already on our backend when you submit a score? In this case we could also have a denied access.

**Comment by bryan-agicap** [comment]
After double checking, you are actually right. I was not receiving the correct id and the trace was not existing.
Thank for your help to debug this!
