### ISSUE TITLE
bug: (python sdk) missing dependency `python-dateutil`

### ISSUE THREAD

**Issue by CNSeniorious000** [langfuse/langfuse#960]
### Describe the bug

![image](https://github.com/langfuse/langfuse/assets/74518716/bf5975d1-58df-4b82-b2d4-13566839ecba)

```
/langfuse/task_manager.py", line 11, in <module>

from dateutil.tz import tzutc

ModuleNotFoundError: No module named 'dateutil'
```

### To reproduce

in `Dockerfile`, simply `pip install langfuse` and init it in a `main.py`

### Additional information

In [#227](https://github.com/langfuse/langfuse-python/commit/84c3dceadfce07c0b02cdbcefe412137ea0f096a#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L13), you removed `python-dateutil`.

I think `v2.7.1` should be yanked.

**Comment by maxdeichmann** [comment]
@CNSeniorious000 thanks for raising this. I just confirmed the bug, and yanked the release. I will provide a fix as soon as possible for this and improve testing to ensure this does not happen again.

**Comment by maxdeichmann** [comment]
@CNSeniorious000 this bug was fixed. If you upgrade your SDK, everything is fine.
